### ISSUE TITLE
Weather displayed condition improvement

### ISSUE THREAD

**Issue by victorcerutti** [home-assistant/architecture#102]
Hello,
The weather card has two way to show the current condition
One is the icon, from a list (`clear-night`, `cloudy`, …)
The other is the text condition

It uses the same attributes (`condition`), meaning that once you convert the initial text condition to the icon condition, it loses a part of the information.
For exemple, if the platform returns a drizzle condition, you have to convert it to `rainy` to display the correct icon.

A simple way to change it would be to have a new attribute for the icon condition which returns  by default the text condition. This would work with every weather platform already existing which could later be improved to return a specific condition icon if necessary

in components/weather/\_\_init__.py

```python
    @property
    def condition_icon(self):
        """Return the condition icon."""
        return self.condition
```

**Comment by fabaff** [comment]
The mapping in the `CONDITION_CLASSES` was created to have the same output (aka show the same icon) from all platforms. This allows one to change from one `weather` platform to another with minimal changes for automation as the conditions are standardized. Also, the mapping was done according the available icons from Material Design Icons.

The `sensor` weather platforms often show additional details while the `weather` platforms are focusing on showing the most common meteorological data.

From my point of view, we should keep the textual representation of the condition in the `sensor` weather platforms.

**Comment by armills** [comment]
What's the problem you're trying to solve here? Is there a specific condition you want to write an automation for that's getting lost as a more generic form? It's always possible to extend the list of supported conditions if there's a useful condition that's currently not available.

**Comment by victorcerutti** [comment]
I think I poorly explained my enhancement idea.
Having the condition icon from a list is fine
I just think the text condition could be free from being from the condition list.

Therefore, the card could display:
`Heavy snow` with a `snowy` icon
or `Light snow` with still a `snowy` icon
And not what it does today translating any of this 2 conditions to:
`snowy` text with a `snowy` icon

My proposition to duplicate create a new condition for the icon was not correct.
The `condition` property should stay as it is in regards to automation based on it.
But the text condition could be a different `condition_text` attribute.

@armills This is not a problem regarding an automation. It's just that writing the `CONDITION_CLASSES ` dict for a new weather platform made me realise we are losing some data that could be useful on a display dashboard.

**Comment by fabaff** [comment]
We should keep in mind that allowing a free text in `condition_text` would make it impossible to provide frontend translations.

We have over a dozen of possible conditions and I think that's more than enough as the difference between "shower rain and drizzle" and "heavy shower rain and drizzle" is subjective and meteorology not an exact science.

**Comment by victorcerutti** [comment]
Most weather datas come from a local source and text conditions are already in the correct langage so that wasn't really an issue.
However I understand that it doesn't add a significative value to the weather card.
