### ISSUE TITLE
Separate the configuration and data directories

### ISSUE THREAD

**Issue by bartfeenstra** [home-assistant/architecture#105]
## Summary
The current configuration directory contains much more than just configuration, such as the logs and the SQLite database. This makes it hard to distinguish between the two, and hinders efforts to work towards deployed configuration, or even read-only configuration (a potential future feature).

## Proposal & scope
Separate configuration and instance-specific data/content into different directories. This applies solely to storage targets, and does not encompass any changes in Home Assistant's behavior. For backwards compatibility with existing installations, the content storage directory can default to the configuration storage directory, if the newer, specific content storage directory does not exist. Ideally, 'throw-away' data such as logs would go to a third destination, since you wouldn't want to back those up, unlike config and data.

**Comment by ahayworth** [comment]
Would moving more things into the [.storage](https://github.com/home-assistant/home-assistant/pull/15045) directory be a potential solution for things that are data, but not configuration (and definitely not logs)?

**Comment by PRabahy** [comment]
It seems to me that there are actually 3 domains of data storage.

1. Manual configuration (configuration.yaml, secrets.yaml)
2. GUI configuration (anything that gets written when I click use the Configuration gui)
3. Logs/data (Anything that is automatically generated as a result of the configuration)

If both 1 and 2 are restored, then the system should work correctly. It should only be necessary to back up 3 if the user is worried about looking up historical events/values after restoring a backup.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
