### ISSUE TITLE
Enforce Python code to be installed through Pip

### ISSUE THREAD

**Issue by bartfeenstra** [home-assistant/architecture#106]
Currently a lot of the Python code is not installed through Pip, as they are HA extensions that need to be placed in the correct directories manually. This avoids many of the benefits a package manager like Pip offers us, such as conflict detection and automation.

## Proposal
Require all Python code to be installed through Pip. There is generally no need to have such code located in any specific directory, since Python loads code from anywhere in the current environment. For registration purposes, it's easier and more robust to have users add a module name to a registry file than to download arbitrary Python files and place them in different directories.

## Benefits & use cases
- Extensions will no longer have to be added to the code base verbatim, as Pip will pull in the relevant code automatically. This prevents third-party code from ending up in people's configuration directories.
- Extension requirements can be versioned easily, by telling HA we require `extension >= 3.2`, and Pip automatically pulling in whatever is the latest compatible release.
- Extensions can use the same mechanism to communicate HA compatibility.

**Comment by balloob** [comment]
All Home Assistant python code is installed via Pip and on a dependency per component basis, including versioning. Anything that lives outside is a custom component, which is outside of Home Assistant because it has not been contributed back or does not meet our quality standards.
