### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by puterboy** [home-assistant/architecture#1065]
Add an `resistance` sensor device_class to home assistant core and frontend (+ documentation).
Units would be: mOhms (milli), Ohms, KOhms (Kilo), MOhms (Mega)

Integrations which would benefit from this include not just resistance sensors/measurements but for example the BME680 class of sensors that include a gas sensor that measures in KOhms.

**Comment by balloob** [comment]
Please use issues instead of discussions for architecture proposals. Feature requests can go to the forums. https://community.home-assistant.io/c/feature-requests/13
