### ISSUE TITLE
Limit meteorological data to weather platforms 

### ISSUE THREAD

**Issue by fabaff** [home-assistant/architecture#107]
A long time ago I created the `weather` component. My idea was to replace/remove the weather `sensor` platforms with `weather` platforms along the way. Nowadays the weather `sensor` platforms are still around because some provide more details than the `weather` platforms. Extending the `weather` component is already covers in the arch repo.

Some `weather` platforms depend on the logic to retrieve the data from their weather `sensor` platform like `zamg` or `buienradar`. This reduced the amount of code as there was no need to duplicate it. Today, we say that such a constellation needs a component.

I would like to suggest that we stop the introduction of `sensor` platforms which are dealing with exclusively with meteorological data. They should become `weather` platforms.

This was coming up as there was a `sensor` platform for [Météo-France](https://github.com/home-assistant/home-assistant/pull/17773) introduced and now there is a PR a [`meteo_france`](https://github.com/home-assistant/home-assistant/pull/18404) weather platform pending.

After the second PR was submitted I started to look into the OpenWeatherMap integration as this was one of the first available and one that isn't backed up by a component. Setting up all `weather` platforms like the new SMHI integration would definitely improve the user experience and this was the starting point. The issue now is that at least for the OWM part would a config flow create a `weather` platform and a bunch of weather `sensor`s and those sensors would pretty much show the same data as the `weather` platform. Doesn't make much sense for me. 

My solution would be to allow which one should be setup:

![screenshot from 2018-11-19 19-08-21](https://user-images.githubusercontent.com/116184/48726075-8c390d00-ec2e-11e8-8610-85befae742f1.png)

Summary:

- No longer allow `sensor` platforms for meteorological data
- Remove the existing weather `sensor` platforms if there is config flow support or allow in some way the selection which platform to setup

**Comment by helto4real** [comment]
I agree. For specific properties from a specific weather institutes you could always allow for custom attributes like I did with the SMHI platform providing "cloudiness" as addition to the standard weather attributes. Then there is no need for sensor platforms.

**Comment by dgomes** [comment]
I agree. But one other thing bothers me: 
- The amount of boilerplate config flow code that all weather components must repeat

**Comment by balloob** [comment]
I think that config flows should be limited to the very basics. Users shouldn't pick between weather and sensors, it should just be weather. Use `configuration.yaml` for advanced sensors, if we even want to make those available.

For boilerplate, there can be a helper like we have for a discovery based config entry.

**Comment by MartinHjelmare** [comment]
We have no plans to stop adding sensor platforms for weather measurements. The weather integration is just a simplification of weather measurements to let the frontend consume it more easily.
