### ISSUE TITLE
Should turning on all device types be implicit or explicit

### ISSUE THREAD

**Issue by ioangogo** [home-assistant/architecture#108]
Currenlty `turn_on`, `turn_off`, `toggle` and other similar services implicitly assume that the users wants all of the current device types to do the action when the body is empty or when there is not entity_id, this can cause issues like [this one from reddit](https://www.reddit.com/r/homeassistant/comments/9yk23x/the_home_assistant_api_a_cautionary_tale/) or when the user forgets when testing a automation, triggering all the automations. This could get more dangerous as more sensitive things are added to home assistant. another reason is that most people discover this by accident, it is in the docs, but not in a area most people venture.

I made garage door example in the discord where something might accenendlty send a empty body to the covers service (like someone using their own alexa skill and someone else closing blinds) and there might be someone leaving the garage at the time, the garage door might close on them in this example. that example is the worst case and the only one i can think of to illustrate the problem

I feel like the service calls to all services should be explicit meaning that the user has to do something like `{"entity_id": "all"}` or some other flag in the service body meaning that accedental triggers dont happen

**Comment by balloob** [comment]
This has been implemented and the old functionality has been deprecated.
