### ISSUE TITLE
Standardised device classes for air pollutants for the sensor component

### ISSUE THREAD

**Issue by danielsjf** [home-assistant/architecture#109]
I'm proposing to add a few new standardised device classes for sensors that reflect some commonly measured pollutants for air quality measurements.

- particulate_matter for unspecified particulate matter measurements
- particulate_matter_10 for particulate matter smaller than 10 µm, a boundary often used
- particulate_matter_2.5 for particulate matter smaller than 2.5 µm, a boundary often used
- particulate_matter_01 for particulate matter smaller than 1 µm, a boundary often used
- volatile_organic_compounds
- carbon_dioxide
- carbon_monoxide

One that I'm still doubting about is to also add an `aqi` device class. This would represent the generic Air Quality Index or score that most devices have. All devices have a separate definition of these, but still it would make sense to standardise it in some way.

**The case**

There are quite a few Air Quality components already:
* https://www.home-assistant.io/components/sensor.waqi/
* https://www.home-assistant.io/components/sensor.london_air/
* https://www.home-assistant.io/components/sensor.luftdaten/
* https://www.home-assistant.io/components/sensor.foobot/
* https://www.home-assistant.io/components/sensor.airvisual/
* https://www.home-assistant.io/components/sensor.xiaomi_miio/

Many report some if not all of the pollutants mentioned above.

Also the Homekit integration tries to include some of them already. See the full list here:
https://www.home-assistant.io/components/homekit/#supported-components

These Homekit names are good examples but don't seem very standardised.

I am working myself on a [new integration](https://github.com/danielsjf/awair_component) for the Awair Air Quality monitor here and I would like to integrate these device classes immediately. I will add this component to Home Assistant soon, but I am waiting for the API to mature a bit more (it still in beta, expect it in a month or so). In the meantime I would like to get the device classes straight.

Let me know what you think.

**Comment by fabaff** [comment]
We are talking about 6-7 platforms now. I would like to suggest that we create an `air_pollutants` component like the `weather` component and profit from such an approach. This would solve the issue of the standardization of the output, simpler support for config flow and allow better UI support.

I guess that `ozone` should be added as well even if that's coming usually from weather services. `sulpher_dioxide` could be another one.

**Comment by danielsjf** [comment]
A few more (from the sensors above):
* nitrogen_oxide
* nitrogen_monoxide
* nitrogen_dioxide
* light
* noise

Some more exotic pollutants:
* radon

**Comment by fabaff** [comment]
I created an MVP for a [`air_pollutants`](https://github.com/home-assistant/home-assistant/pull/18707) component to standardize the handling of this kind of information.

**Comment by cdce8p** [comment]
In addition to just listing the current levels for specific pollutants, HomeKit does support some additional functions that might be worth taking into consideration when designing the new component:
- For air quality levels we currently do a mapping of number / density of PM2.5 particles. [homekit/utils.py -> density_to_air_quality](https://github.com/home-assistant/home-assistant/blob/9894eff732831285981d2481488896c50276d4d1/homeassistant/components/homekit/util.py#L146-L156)
- Both `CO` and `CO2` sensors support additional parameter:
  - `peak` level (at the moment the maximum, measured since start of HA -> not ideal, but less important)
  - `detected` = the value is above a threshold (!! important for HomeKit; HK alarms are based on it)
  [homekit/const -> thresholds](https://github.com/home-assistant/home-assistant/blob/b4e2f2a6efcdb593c0226b6fa73da271d6f7f872/homeassistant/components/homekit/const.py#L150-L151)
 
All values had been chosen in best knowledge, but without 100% certainty.

**Comment by fabaff** [comment]
For the AQI is also a mapping used. We could handle this like we handle the condition for the `weather` platforms. 

For dealing with thresholds, I think that we should start with CO and CO2 as they are available for HomeKit and go from there. `peak` looks like something which requires a detour for other platforms (would need the features of the `statistics` sensor).

**Comment by danielsjf** [comment]
The MVP looks good to me.

The thresholds still seem a bit vague to me? In my opinion there are many that you could use: lethal, WHO, EU,... Maybe something the user could choose from? Potentially we can add it as a value/name in the config.

How does the transfer happen from sensors to the new component? Gradually or at the release? I am certainly willing to help.

**Comment by fabaff** [comment]
> How does the transfer happen from sensors to the new component? Gradually or at the release? I am certainly willing to help.

They are migrated if one is doing the work.
