### ISSUE TITLE
How to deal with history sensors

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#11]
Definition: 2nd order components are components that take raw data available in Home Assistant and process it into new data.

We are getting more and more 2nd order components that show a statistic over a period in the history of an entity (example: [history_average](https://github.com/home-assistant/home-assistant/pull/10717) which allows calculating average value during last 2 hours)

The problem with these sensors is that their state is time based and thus they update the value on every update, which spams the state machine.

How can we solve this? One thing we can do is to set a minimal update interval to limit state updates.

But what else?

**Comment by andrey-git** [comment]
Limiting update interval for 2nd order components will make them inaccurate.
Unless they want time decay they only update when the "source" component updates, right?

**Comment by balloob** [comment]
Correct.

**Comment by grea09** [comment]
Just adding some additional issues that could benefit from a history API:

First issue: the Linky component (currently broken) uses an API that doesn’t allow real-time access to the value of the sensor. Instead all you can access is the history of the value for each half-hours as recent as the previous day. While wanting to interface with the utility meter there are only one way: do an ugly hack to present the yesterday data in function of the time. This makes impossible any correlation of data afterwards or to have correct monthly bills.

Another example of the issue: The MiFlora defices are battery powered. Each request takes a bit of energy. That is why it is adviced to have a low polling frequency. That results in poor temporal resolution in graphs and a lot of energy waste. The offical app however can access a low energy log and therefore get data with a good resolution in one request.

Repost of [this feature request](https://community.home-assistant.io/t/implement-an-elegant-way-to-populate-history-from-the-sensors-code/100995?u=grea09) as advised in Discord.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
