### ISSUE TITLE
Device to device Bindings

### ISSUE THREAD

**Issue by pbalogh77** [home-assistant/architecture#111]
The idea is to have a much simpler and usable way of setting up simple interactions between devices.
A device to device binding (d2d, for now) is a python object, which defines a usecase between a number of device platforms.
For example the "Venetian Blind controller" binding would have 2 or 4 device parameters of button devices and 1 or more device parameter of cover devices. It'd automatically raise/lower the blinds based on two buttons and tilt the blind blades based on the other two button. It could be a stateful object, e.g. it could remember/restore/count/continue its operation as needed.
Envisioned simple use cases:
- Two-button dimmer: Two buttons and a list of lights
- One or two button lights with on/off
- Venetian blinds and buttons
- Motion sensros, locks and lights

For the user interface, it could be as simple as a list of these bindings activate, adding/editing a new one would be one or more lists to populate with devices and a selection of the binding to be applied between them. E.g. you select a light that supports dimming and a button, and it offers you only the bindings which are relevant to these devices together.

**Comment by balloob** [comment]
What you're proposing is a new automation component with device and integration specific triggers instead of triggers based on events/states.

**Comment by pbalogh77** [comment]
@balloob, what I proposed was that if you have 10 switches and 10 lights, you could just 'connect' them up. And a switch and light should know how to interact. If you have (like I had in my prev. flat) 55 venetian blinds and 25 set of buttons to control them, instead of creating a separate automation for each press of each button, you could just 'connect' them up. A venetian blind and a 4 button wall switch should know how to interact. Same goes for most sensors, actuators, etc. Having this sort of templates for their interactions (device type A <-> device type B) and config options on these interactions (like what should doubleclick mean) would make building and configuring a system so much less tedious. Using Z-wave for everything and setting up direct associations gets it half done. But why can't I take a zigbee button, and a z-wave light, a z/wave sensor and a wifi actuator and still be efficient and convenient in setting it up?

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
