### ISSUE TITLE
Enable ReportState for Google Assistant

### ISSUE THREAD

**Issue by marchingphoenix** [home-assistant/architecture#112]
Google Assistant likes to be kept up to date with device states.
Can be useful to reflect changes when a device is slow to update after sending a command (looking at you MQTT)

Google's ReportState doc:
https://developers.google.com/actions/smarthome/report-state

Optional jwt helper library:
https://google-auth.readthedocs.io/en/latest/reference/google.auth.jwt.html#google.auth.jwt.Credentials

Alexa implementation:
https://github.com/home-assistant/home-assistant/pull/18114

I'm currently working on other traits in the google_assistant component. I'll likely take this on after that work completes. Let me know if anyone has any questions or comments or if someone else would like to take this up.

**Comment by marchingphoenix** [comment]
Currently working on adding `Modes` to media_players (and leaving it open for others to add to) and `CameraStream` for enabling "Show my my <camera>" support. About to open a new Arch ticket for the CameraStream though.

**Comment by ahayworth** [comment]
Gotcha - `Modes` would be interesting. I hope they release documentation on the `REMOTECONTROL` device type soon - I feel like it'd be a better home for media_player support. Looking around, `REMOTECONTROL` definitely exists and works, but it's not documented. Seems to be what the native Google Assistant<->Harmony integration uses.

`CameraStream` would be awesome. Do you know if displays (like the Home Hub, or the Lenovo Hub) will be registered as endpoints, or is it strictly chromecast-only?

As for me - I've been poking around the `REMOTECONTROL` and `SECURITYSYSTEM` device types. It'd be really great if we could somehow get access to real documentation on it, ala Nest and Harmony.

**Comment by marchingphoenix** [comment]
As far as i can tell, it'll work on smart displays natively. Those present a Chromecast target to Google Home, nothing fancy needs to be done on our end.

**Comment by balloob** [comment]
Nabu Casa is adding an endpoint for Alexa to get a token to be able to talk directly to Amazon. I am not sure if this can be done for Google too or that we have to route each state via Home Assistant Cloud. Depends on how their authentication works. Will do some research.

This is obviously a feature that we want to add. We should make sure that it's opt-in though. It's a lot of information we're sharing with the big G.

**Comment by ahayworth** [comment]
> I am not sure if this can be done for Google too or that we have to route each state via Home Assistant Cloud. Depends on how their authentication works. Will do some research.

They require that you create a JWT via a service account, and then request an OAuth access token for this API. That is sent along with a ReportState call. I'm not sure if you can lock a JWT or OAuth token down on a per-`agentUserId` basis or not.

> This is obviously a feature that we want to add. We should make sure that it's opt-in though. It's a lot of information we're sharing with the big G.
We should consider if we want to continue exposing all domains by [default](https://www.home-assistant.io/components/google_assistant/#expose_by_default) to Google, as well.

**Comment by balloob** [comment]
Yes, the defaults are pretty bad. We should fix it. Especially things like groups should not be exposed probably. Media players should be opt-in because they are not officially supported. etc

**Comment by balloob** [comment]
Implemented.

**Comment by ahayworth** [comment]
@balloob, you are wonderful. ❤️
