### ISSUE TITLE
System Health component

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#114]
People sometimes get into trouble because they misconfigure their internet, DNS or have trouble with a component. It would be great if we could offer a status page that people could see the health of their system.

By default we can test if we can reach the internet and we can let components register their own health checks, example is Z-Wave connected, Hue bridge available etc. 

We could then show a status page in configuration that will show checks for each integration and the network.

Inspired by

![image](https://user-images.githubusercontent.com/1444314/49206909-d8651980-f3b3-11e8-9453-d3ec659a7644.png)

**Comment by dgomes** [comment]
I think most people already have that, but we could make it easier to discover/configure.

<img width="392" alt="screen shot 2018-11-29 at 10 41 15" src="https://user-images.githubusercontent.com/137684/49216618-6c8aad00-f3c3-11e8-9ae1-dc2839a6125f.png">

**Comment by balloob** [comment]
I don't want users to configure it, I want integrations to configure it themselves when they are setup.

**Comment by dgomes** [comment]
can it be a new component property ?

**Comment by frenck** [comment]
The component should be able to communicate back at least some information on what is wrong.

If we are going to build this...  may I bring up something else / similar?
This was discussed before in the Discord chat, but we could handle a similar approach on security.
E.g., allowing components to warn/list possible security issues (e.g., using InfluxDB without authentication).

I know this is a little off topic, but the practical design would be very very similar.

**Comment by balloob** [comment]
I think that could fit in the same component. Security is also part of a health check.

I would expect a new component `system_health`. During setup , a component can register different checks.

```python
# Register check so system health can query on demand
async def async_setup(hass, config):
    hass.components.system_health.async_register_check(
        DOMAIN, TYPE_CONNECTION, async_check_mqtt_connected)

# Component can pro-actively report too, so user can be notified
async def on_disconnect():
    hass.components.system_health.async_notify(
        DOMAIN, TYPE_CONNECTION, status=DISCONNECTED)
```

**Comment by frenck** [comment]
I like that, especially the pro-active one could do pretty valuable things.
