### ISSUE TITLE
Standardizing events

### ISSUE THREAD

**Issue by cnrd** [home-assistant/architecture#115]
So I saw this: https://github.com/home-assistant/home-assistant/pull/17354#issuecomment-430262541 and though that it would be a good idea to have a discussion about this.

I feel like there would be benefits to standardizing events, just as we standardize components.

**Comment by rytilahti** [comment]
I'm wondering what's holding on standardizing these? Is it just that someone needs to put in the work to write definitions (and at the end, fix the existing platforms)?

**Comment by balloob** [comment]
We have an unwritten standard: components can fire their own events but the events should be prefixed by the component name. Platforms are not allowed to fire events as platforms provide entities.

**Comment by frenck** [comment]
I want to light up this discussion again.

I've seen two variants in the wild now:

1. `domain.event_name`
2. `domain_event_name`

I think we need to choose one moving forward, and stick to it.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
