### ISSUE TITLE
serial over tcp

### ISSUE THREAD

**Issue by martikainen87** [home-assistant/architecture#116]
Would be really nice to get a component/integration to connect to serial port over IP, and to be able to connect to mulitple ports. 

Usage example

* Raspberry Pi connected with a Z-wave stick and Conbee stick to get a portable Z-wave/ZigBee gateway (with a powerbank connected ofc)
* Build a clustered solution of HA using docker swarm or other cluster functions.

There is a github of someone who started to develop a function for it, but I have no idea if this is useful or not since I'm not a developer by any means. 

https://github.com/pavelrevak/ser2tcp

**Comment by MartinHjelmare** [comment]
The architecture repo is not a place for feature requests. Please use our forum section for that.
