### ISSUE TITLE
Current `water_heater` entity missing important attributes, methods

### ISSUE THREAD

**Issue by zxdavb** [home-assistant/architecture#117]
The current version of `water_heater` was https://github.com/home-assistant/home-assistant/pull/17058, and appears to have been implemented completely independently of the corresponding discussion at https://github.com/home-assistant/architecture/issues/59

This caught many of us by surprise, because the PR was started/accepted after https://github.com/home-assistant/architecture/issues/59, with no mention of it in that discussion (I think it was a Hackoberfest thing) - so the first we knew was when https://github.com/home-assistant/home-assistant/pull/17058 was accepted, and https://github.com/home-assistant/architecture/issues/59 was closed.

As it stands, the `water_heater` has no `current_temperature`, nor does it have one/off/heating as states!

Ironically, there is https://github.com/home-assistant/home-assistant/pull/19093, which would add some of this functionality, but it was been blocked pending an architectural discussion...

So here it is.  Discuss.

**Comment by zxdavb** [comment]
A proposed schema
```
icon = "mdi:thermometer-lines"

supported_features = SUPPORT_OPERATION_MODE | SUPPORT_ON_OFF | support_temperature | support_target_temp
state: [
  STATE_OFF,  # boiler not active (not using energy), current temp is irrelevant
  STATE_ON,  # boiler will act to attain/maintain target temp when required
  STATE_HEATING, # boiler is actively heating the water (assumes STATE_ON) - Optional
]

state_attributes: [
  'operation_mode': [manual, schedule, etc]
  'current_temperature', # reported by a temperature sensor
  'target_temperature', # the temperature to reach...
  'temperature_unit',  # TEMP_CELSIUS, or the other one...
  'min_temperature',  # lowest possible target temp
  'max_temperature',  # maximum possible target temp
  'precision',  #  1, 0.5 or 0.1 (PRECISION_WHOLE, HALVES, TENTHS)
]

Services: [  # some devices allow setting these parameters ahead of time
  'set_operation_mode':  { 'service_data': ['operation_mode'] }
  'set_temperature': { 'service_data': ['target_temperature'] }
  'turn_off',
  'turn_on': {}
]
```

**Comment by zxdavb** [comment]
Currently, the water_heater has a peice of code thus:
```python
    @property
    def state(self):
        """Return the current state."""
        return self.current_operation
```
...where `current_operation` is one of: 
```
STATE_ECO = 'eco'
STATE_ELECTRIC = 'electric'
STATE_PERFORMANCE = 'performance'
STATE_HIGH_DEMAND = 'high_demand'
STATE_HEAT_PUMP = 'heat_pump'
STATE_GAS = 'gas'
```

In my opinions, these are not states (they are operating modes).  `state` should really be limited to ON, OFF or HEATING.

**Comment by balloob** [comment]
Don't define state as being something independent. State in Home Assistant is just taking the most important property and exposing that as state. State is always defined as just returning a single property.

As discussed in #22, there is operation mode and operating mode. Water heater should have both, even if operation mode is not configurable.

**Comment by zxdavb** [comment]
> Don't define state as being something independent. State in Home Assistant is just taking the most important property and exposing that as state. State is always defined as just returning a single property.
> 
> As discussed in #22, there is operation mode and operating mode. Water heater should have both, even if operation mode is not configurable.

**Comment by zxdavb** [comment]
closed in error

**Comment by kloknibor** [comment]
I would like to add that I also need this added functionality to be able to add in all the functionality in my component. 

So there are different vendors that would benefit from this change.

**Comment by zxdavb** [comment]
Maybe we should wait fro the re-write of the `climate` entity, and take leadership from there?

**Comment by kloknibor** [comment]
@zxdavb how long will that take? Because if that'll take a long time I won't mind doing the work twice and prefer to just get my component working soon :)

**Comment by zxdavb** [comment]
> @zxdavb how long will that take? Because if that'll take a long time I won't mind doing the work twice and prefer to just get my component working soon :)

No idea. The answer to that question may be best asked elsewhere... https://discordapp.com/channels/330944238910963714/330990195199442944

**Comment by kloknibor** [comment]
Sine the thread is already running for months I would prefer to just implement this already and than hopefully we can use new climate device to make a new water_heater device that will have everything we need :)!

**Comment by elupus** [comment]
Just for reference: https://github.com/home-assistant/home-assistant/pull/21393

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
