### ISSUE TITLE
Homekit RGB light

### ISSUE THREAD

**Issue by SebDominguez-zz** [home-assistant/architecture#118]
So apparently I need to discuss on the "`Hassio` / `Home assistant` / `Hassos`" architecture to make my lightbulb to work correctly with `Home.app` / `HomeKit`.

Related issue: https://github.com/home-assistant/home-assistant/issues/19251

**tl;dr:** `Homekit` / `homebridge` (I don't know witch one is causing this issue) seems to not being happy when a light is setup with **both** color **and** temperature features.

Since the temperature option seems to be redundant on a color light would't be better if the temperature option is removed from color light?

**Comment by MartinHjelmare** [comment]
The issue was fixed.
