### ISSUE TITLE
rename air_pollutants platform to air_quality ?

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/architecture#122]
continuing from: https://github.com/home-assistant/home-assistant/pull/19410

please consider renaming  the Air_pollutants platform to air_quality?

Though Waqi has started out to collect data on air pollutant, wouldn't it be nicer to focus on the air_quality aspect. Waqi meaning: World Air Quality Index.

Air_quality might be a more logical place for other components and sensors that contain air-info, not necessarily concentrated on / limited to pollution, like ozone or other environmental gasses/materials

**Comment by eliseomartelli** [comment]
I like this spin on the air_pollutants component. 
The name `air_quality` feels like something that can hold a lot more platforms than `air_pollutants`.

On https://github.com/home-assistant/home-assistant/pull/19410 you can see a clear example of how this naming can be "confusing".

**Comment by balloob** [comment]
I like the positive spin of "air quality"

**Comment by fabaff** [comment]
`air_pollutants` may not be a suitable name for "marketing purposes" or commercial products but it reflects best IMHO what the component is representing at the moment. The focus is on different pollutants in the air.

**Comment by eliseomartelli** [comment]
@fabaff I think that is partly right. 
Think about it... Devices (and services) are in fact giving us Air Quality data by measuring the pollutants. 

example: http://aqicn.org

Even the Air Quality (AQI) is flawed. The greater it is, the worst the air quality is.

**Comment by fabaff** [comment]
If people think that `air_quality` is a better name for the component then change it.

**Comment by MartinHjelmare** [comment]
Sounds like we have an agreement. So then we can merge the PR (when ready) that does the rename and closes this issue.
