### ISSUE TITLE
Adding sensors and remotes to Philips Hue

### ISSUE THREAD

**Issue by marthoc** [home-assistant/architecture#128]
This is something that I’ve been looking at for a while (and @robmarkcole has implemented as a custom component that is quite popular on the community board). Last year I added support for sensors to the underlying aiohue library, now it just needs to be implemented in Home Assistant. 

I open this as an architecture issue as it will require a rethinking of how Hue works now and so I thought it best to get feedback and ideas before proceeding. 

Currently Hue has only one platform: light. But adding Hue sensors (as they are blanket referred to in the Hue API) would add binary_sensor, sensor, and events. 

First item for discussion: Hue devices currently poll in the light platform. Adding sensors would mean that we could move the actual updating to the component, one poll for all device states regardless of platform. This is not a contentious proposal, I don’t think. 

Second item: adding Hue sensors would mean that the polling interval would need to drop significantly, to say 1s or less, so that the motion sensor and remotes are actually useful. I don’t think this is really a problem from the Hue side (one request every second is not a big deal for the bridge), but I’m not sure what kind of load this adds to Home Assistant. This is a more significant issue and one that could be a deal breaker for implementing Hue sensors - if we can’t poll that often, then things like motion and remotes become pretty useless. 

Third: proposal for entities. Remotes like the Hue dimmer or tap (stateless buttons) should be represented in HASS as events, not sensors. The motion sensor should be a binary sensor. Temperature and luminance will be sensors. Batteries for the remote and motion sensor should have their own sensor rather than exist as a device state attribute of the motion/temp/luminance sensors (this is how deconz does it).

I’m happy for any feedback before starting work on the component. In my view this can proceed in staged PRs:
- first, rewrite Hue so that the component polls and then signals platforms to update
- second, rewrite the light platform to use the new component update mechanism
- third to fifth: add binary sensor, sensor, and events

**Comment by robmarkcole** [comment]
Hi @marthoc 
@yottatsa has made a lot of improvements to [the custom component](https://github.com/robmarkcole/Hue-sensors-HASS) recently and I'm sure will be able to offer some good advice here. 
On the points you raise above, I agree with your suggestions. For point 3 in particular, yes we want to break out the separate sensors (nice discussion on the forum about this), and remotes should be implemented as [remotes](https://www.home-assistant.io/components/#remote) which are stateless but fire events. 
Cheers

**Comment by yottatsa** [comment]
Polling one HTTP API endpoint every second and parse a JSON makes no load neither for HASS nor for Hue Bridge. This interval is enough for a Motion sensor.

However, I'm not sure about the remote and the feedback is mixed. One of the options would be using rules and CLIP sensors to persist the event. Unfortunately I have no remotes to play with.

> rewrite Hue so that the component polls and then signals platforms to update

I've already disabled polling for entities in the custom component, and working on implementing  proper event reactor.

> The motion sensor should be a binary sensor.

Done.

> Temperature and luminance will be sensors.

Planned.

> Batteries for the remote and motion sensor should have their own sensor rather than exist as a device state attribute of the motion/temp/luminance sensors (this is how deconz does it).

Not sure but why not.

> remotes could be implemented as remotes which are stateless but fire events

Planned.

**Comment by marthoc** [comment]
> However, I'm not sure about the remote and the feedback is mixed. One of the options would be using rules and CLIP sensors to persist the event. Unfortunately I have no remotes to play with.

I don't think I know exactly what you mean here. Given that the component polls the API it does present some difficulty with determining when there is a new event but off the top of my head I think we'd have to store the "lastupdated" attribute from the Hue sensor api object on each update, and if the new lastupdated doesn't match the previous lastupdated value, fire the event. The polling interval would mean that at MOST there would be a 1s delay from button press to automation triggering, which seems acceptable to me (though obviously not the ideal, which would be instantaneous).

> Batteries for the remote and motion sensor should have their own sensor rather than exist as a device state attribute of the motion/temp/luminance sensors (this is how deconz does it).

This I think is just a matter of practicality since many users will probably make a template sensor to break out this attribute anyway for easier tracking/automating, so why not just do that from the outset (and, if the remote won't have an entity, there won't be an entity to hold that device state attribute, so it just makes sense to represent all batteries as entities themselves).

**Comment by balloob** [comment]
We still need to poll multiple endpoints, no? One for lights, one for sensors? They can be on a different interval.

**Comment by yottatsa** [comment]
@balloob yes, we need to poll multiple endpoints. I'm now looking on how to re-design `aiohue` to provide events instead of update API. With this it could be possible to drastically simplify the code of lights and sensors.

**Comment by mvdwetering** [comment]
> > However, I'm not sure about the remote and the feedback is mixed. One of the options would be using rules and CLIP sensors to persist the event. Unfortunately I have no remotes to play with.
> 
> I don't think I know exactly what you mean here. Given that the component polls the API it does present some difficulty with determining when there is a new event but off the top of my head I think we'd have to store the "lastupdated" attribute from the Hue sensor api object on each update, and if the new lastupdated doesn't match the previous lastupdated value, fire the event. The polling interval would mean that at MOST there would be a 1s delay from button press to automation triggering, which seems acceptable to me (though obviously not the ideal, which would be instantaneous).

This also depends a bit on which events you want to forward to Home Assistant, just a generic Press or all of the events the devices generate. 
The Hue tap only has a Press event, but the Hue dimmer switch sends out multiple events in sequence. These sequences can be (1) Press, Short release or (2) Press, Hold (multiple times as long as the user holds the button), Long release. Note that in these sequences the events come _within_ a second of each other.

So if you are polling at a 1 second rate you often are going to miss the Press event in sequence 1 and 2 you often see the Short release or Hold without seeing the Press since it got overwritten.
However you can figure out that there was a Press event since you see the Short release/Hold that means there had to be a Press event before so you could generate the event yourself to have the complete sequence (but you should then also take care of the case where you did get the Press and on next poll you get the Short release/Hold to avoid duplicate Presses).

**Comment by marthoc** [comment]
@mvdwetering I think on a polling basis only the short release and long release are usable, for click and long click/hold events (inferred from short release and hold). Otherwise, as you said, you can’t reliably pick up the other events. 

And I don’t see the utility in also firing a click event along with short release event and hold events; any automation that would need to fire based on ANY button being pressed could just trigger on both short and hold events.

**Comment by mvdwetering** [comment]
> And I don’t see the utility in also firing a click event along with short release event and hold events; any automation that would need to fire based on ANY button being pressed could just trigger on both short and hold events.

That depends if you want to support behaviour that starts on a button press and ends on releasing that button. For example dimming lights while you hold a button (like default Philips Hue behaviour of the dimmer switch). 
But something like that can also be done by using a button press for start dimming and press again to stop dimming.

**Comment by EpicLPer** [comment]
I wonder how Apple's Home app does it. It'll instantly show you when a motion sensor has been triggered, are they also polling the Hub multiple times per second then?

**Comment by yottatsa** [comment]
@EpicLPer AFAIK HomeKit has an ability to push events.

**Comment by MartinHjelmare** [comment]
Hue now supports sensors and events and has a push based update model besides the polling.
