### ISSUE TITLE
Climate - Fan Direction Control

### ISSUE THREAD

**Issue by constantin-baciu** [home-assistant/architecture#129]
There are air conditioning units that allow for control of the fan direction (vertical and / or horizontal).

The unit I have is a Fujitsu Halcyon and it allows for that control via the remote AND via the app (https://play.google.com/store/apps/details?id=com.fujitsu.fglair is the one I'm using).

There is an API (still under development here: https://github.com/Mmodarre/pyfujitsu) that already gets and sets the values for the fan direction. But Home Assistant doesn't use those features as they are not supported.

I'm sure Fujitsu units are not the only ones that support this. So, it would be a great addition to Home Assistant if they were supported.

**Comment by marchingphoenix** [comment]
relates to #22 but should stand on its own.
If configured using the right services, this could also be exposed out to the voice assistants.

**Comment by jnimmo** [comment]
Is this not already covered off using the swing modes available in climate? Just needs to be implemented by the appropriate component

**Comment by constantin-baciu** [comment]
Not really. The swing mode doesn't cover setting specific positions for the louvers.

**Comment by dzungpv** [comment]
Yes it í sam e with Mistsubishi Aircon, lib here support https://github.com/SwiCago/HeatPump both vertical and horizontal but for the climate limited, i could only support 1 off them in https://github.com/SwiCago/HeatPump/tree/master/integrations/home-assistant.io

**Comment by dzungpv** [comment]
@balloob I am late for the #22  but could we support both swing mode? It is both vertical and horizontal, they and independent so could not merge to 1 "swing" mode

**Comment by constantin-baciu** [comment]
Hi guys,

Any news on this front?
I've been trying to use the py scripts from here: https://github.com/Mmodarre/pyfujitsu, but, you cannot import modules when using python_scripts. :(

Thanks!

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck

**Comment by constantin-baciu** [comment]
Hi @frenck,

Can you tell us if this type of functionality is in any of your plans?

Thanks!
