### ISSUE TITLE
Sensor - Adding services

### ISSUE THREAD

**Issue by dgomes** [home-assistant/architecture#131]
I've been told that sensor platforms should not have services. I've opened this Issue to argue otherwise.

There are currently 6 sensor platforms that register services, my PR https://github.com/home-assistant/home-assistant/pull/19718 would like to add 2 services to a new sensor platform (utility_meter).

The added services are quite generic, they provide a means to start/pause a sensor and to reset a sensor. This functionality is quite generic and could easily be made common to all sensor platforms (I actually find interest in start/pause other sensors and reset).

Why do I require these services now ? The utility_meter sensor I'm proposing is a key sensor to implement a smart meter (electricity, gas, water, heating, etc). Smart Meters are usually made out of several counters which take turns (depending on multiple factors such as time, market dynamics, etc) accumulating data. The services allow for this externalisation of logic to a different component and/or automation.

Full Context: https://github.com/home-assistant/home-assistant/pull/19718#pullrequestreview-191981477

**Comment by MartinHjelmare** [comment]
Just copying my comment about the existing 6 sensor platforms that register services:
> I can't find any valid implementations of the examples above.
>
> - The mopar sensor service sends a command to change the state of the car. Clearly against our architecture. That should be done from a switch platform or from a new mopar component.
> - dovado service that sends an sms should be done from a new dovado component.
> - The other four platforms' services are now redundant, after we implemented the general entity update service. Those services should be removed.

**Comment by MartinHjelmare** [comment]
The argument has been that sensors are read only and we shouldn't confound that by registering services under the sensor component or platforms. A service is by definition doing an action, changing the state of something.

**Comment by dgomes** [comment]
I think that is a very dogmatic view of the sensor component.

For starters, as you pointed out, you can issue an update_entity service to a sensor.

Then there is the case of sensors that just map external platforms that can be manipulated regardless of any rule. For instance, you have no control about mqtt sensors that can be manipulated using HA automations (that was the state-of-the-art before I implemented the utility_sensor, people would create a topic and several automations to update the mqtt topic in a very wasteful way)

**Comment by dgomes** [comment]
Looking into Mozilla's Web Thing API (assuming our sensors map to a property), you can have read-only and writable properties.

https://iot.mozilla.org/wot/#property-object
https://iot.mozilla.org/wot/#property-resource

**Comment by balloob** [comment]
Just make it a component if it needs services. We now have embedded platforms too, so it becomes super easy: `utility_meter/__init__.py`, `utility_meter/sensor.py`.

**Comment by balloob** [comment]
It's fine, it's the future.
