### ISSUE TITLE
weather cards use incorrect windspeed unit or state

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/architecture#132]
please see: https://github.com/home-assistant/home-assistant-polymer/issues/2482

several weather platforms use windspeed in m/s (meters per second, not mile) but show unit km/hr. This obviously is incorrect and should either be multiplied by 3,6 for km/hr, or show m/s

Open Weathermap is correct, Darksky and Buienradar are incorrect, both in Lovelace and regular Ha
![schermafbeelding 2019-01-15 om 16 23 04](https://user-images.githubusercontent.com/33354141/51194104-ae77a000-18ea-11e9-9362-15b0ef8e7feb.jpg)
![schermafbeelding 2019-01-15 om 16 23 14](https://user-images.githubusercontent.com/33354141/51194107-ae77a000-18ea-11e9-9fd3-5934a1ec2db3.jpg)

**Comment by Mariusthvdb** [comment]
And see https://github.com/home-assistant/home-assistant/issues/16793#issuecomment-454526140

**Comment by DubhAd** [comment]
And https://github.com/home-assistant/home-assistant-polymer/issues/1679

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
