### ISSUE TITLE
Processing of bounding boxes by image_processing

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/architecture#133]
Currently we don't have a nice way to handle bounding box information returned by image_processing entities. My suggestion is that a nice solution would be to have a destination output for processed images, so that a second camera is created, showing the processed image with bounding boxes drawn on it. Alternatively we standardise the way that bounding boxes are returned (e.g. [tensorflow](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/image_processing/tensorflow.py) and [facebox](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/image_processing/facebox.py) have differing approaches currently) then use some other method to process those. Be good to get input of @hunterjm @dgomes

Duplicates this issue? https://github.com/home-assistant/architecture/issues/41

**Comment by arsaboo** [comment]
`image_processing` components should allow saving processed images with bounding boxes. Users are then free to use them with `local_file` camera or in an automation. In that sense, I am closer to the current implementation in Tensorflow component. It would be great if some of the features in the TF component can be abstracted so that all `image_processing` components can use them.

**Comment by robmarkcole** [comment]
@arsaboo I am using that basic approach [here](https://www.hackster.io/robin-cole/motion-activated-image-capture-and-classification-of-birds-6ef1ce#toc-tying-it-all-together-8), with [folder_watcher](https://www.home-assistant.io/components/folder_watcher/) component to detect new saved files and display them on a local_file camera. It works but is a bit hacky.

**Comment by arsaboo** [comment]
Indeed...`save_image` should be refactored to the platform level and an event (that can be used in automations) should be fired so that all platforms can use it.

**Comment by dgomes** [comment]
save_image is a terrible IPC.
We should workout a better mechanism, else we are just killing SD cards in RPi's

I've previsouly proposed something https://github.com/home-assistant/architecture/issues/41

**Comment by robmarkcole** [comment]
Well we already let people save images, it is opt-in. I actually like your (scratched) suggestion in the other thread that the processed image (with bounding box) be displayed on a second 'sink' camera. The image then isn't saved but can be used in automations

**Comment by arsaboo** [comment]
Indeed, Pi is not the "optimal" device for image_processing. So, we should not design with Pi as our focal device. In any case, `save_image` is optional and can stay that way. 

Bounding boxes can be optional; components that don't provide bounding boxes can just save images.

**Comment by robmarkcole** [comment]
OK so we have a range of opinions, how to progress forward to action here?

**Comment by robmarkcole** [comment]
It is become clear that displaying the processed image with bounding boxes is what people want. It is in principle not necessary to actually save the image if we were instead to create a _new_ camera which displayed the image + bounding box. This would save disk usage and greatly simplify usage. Any thoughts @arsaboo @hunterjm @dgomes ?

**Comment by robmarkcole** [comment]
To update, I moved the bounding box save method to the image processing integration. I adopted the approach used by tensorflow. Now is a good time to make a decision about the sink camera idea, which I am in favour of as it will greatly simplify usage

**Comment by robmarkcole** [comment]
Update: saving of images to disk is just creating so many tedious issues, I am now leaning away from this approach. Much better to have another camera that displays the annotated image

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
