### ISSUE TITLE
Adding VOC attributes to Air Quality component

### ISSUE THREAD

**Issue by reefab** [home-assistant/architecture#136]
In the previous discussion about adding a device class for air quality monitors: #109

There is a mention to have 'volatile_organic_compounds' as an attribute but alas, it is not present in the component.

I'm currently working to migrate the foobot sensor to this air quality platform and I figured this would make sense to have it part of the generic component as many indoor air quality monitors will provide this measurement. Especially considering that many of those monitors do not have an actual CO2 sensor but derives CO2 values from their VOC sensor.

I already made a PR request adding this attribute and the corresponding property to the component: https://github.com/home-assistant/home-assistant/pull/20306 but I'm opening this issue as requested. I'll make another PR if there is an agreement.

**Comment by Jc2k** [comment]
This has come up as part of https://github.com/home-assistant/home-assistant/pull/30383. @itewk pointed out there is a discrepancy between the docs [here](https://developers.home-assistant.io/docs/en/entity_air_quality.html) (which lists VOC) and the code [here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/air_quality/__init__.py) (which doesn't).

I'd certainly support adding it to the base entity. It looks like the dyson fans already support it and both homekit integrations want to use the attribute. It looks like xiaomi_miio may have support as well, but with a different attribute name.

**Comment by ahayworth** [comment]
This would be useful for the Awair component as well, which reports a "total VOCs" measurement (but does not break them out individually). If there is consensus that `volatile_organic_compounds` should be added to the base component, I will be happy to submit a PR.
