### ISSUE TITLE
Enable auth providers to update user info upon authentication

### ISSUE THREAD

**Issue by bob1de** [home-assistant/architecture#138]
Hi,

I was first redirected from home-assistant/home-assistant to the community forums and then over to here, hence that's the third time I open an issue/thread on this topic. So don't be confused. Hopefully, this is finally the right place.

Just for reference, here are the other two:

- https://github.com/home-assistant/home-assistant/issues/20547
- https://community.home-assistant.io/t/enable-auth-providers-to-update-user-information-upon-authentication/95118

I would like to enable auth providers to update user information (such as name) upon each authentication. This makes sense for auth providers that get their information from external sources, such as the upcoming command_line auth provider (#19985).

The implementation of UserMeta would need to be changed to allow setting attributes partially, such as only name without changing is_active, for instance.

Here's a PR with a possible implementation: https://github.com/home-assistant/home-assistant/pull/20550

What do you think?

Best regards
Robert

**Comment by rohankapoorcom** [comment]
I like the general approach. It matches the common single sign on pattern where the authentication provider knows everything about the user and is responsible for updating systems that need this information. Commonly this is used when the user changes their name or their email address (possibly because they changed their name) so that it only needs to be changed in a common source and propagates outwards.

**Comment by efficiosoft** [comment]
Exactly. I'm using this with LDAP, for instance.

**Comment by efficiosoft** [comment]
Another thing that could be updated is group memberships, as soon as a API for it exists.

**Comment by efficiosoft** [comment]
I have a PR ready that I'm just filing now. We can then discuss about a possible implementation.

**Comment by balloob** [comment]
How will this work when there are two auth providers linked to a user?

**Comment by efficiosoft** [comment]
The implementation has been simplified to no longer require the auth provider to differentiate between new and existing users, unless it explicitly wants to.

**Comment by balloob** [comment]
But if 2 auth providers both have a name, logging in will override it?

Also, what if the user has changed their name?

I see your use case and I see how you can get that covered, but we need to think about the system as a whole and take all other use cases into account too.

**Comment by rohankapoorcom** [comment]
Maybe we could add something to configuration where there is an order of auth providers and the order defines the hierarchy at which they are allowed to update the metadata?

**Comment by balloob** [comment]
Maybe syncing has to be done via a component instead of adding it to the auth provider?

**Comment by efficiosoft** [comment]
> But if 2 auth providers both have a name, logging in will override it?

If two auth providers think to know a user's name, that names should be identical, or there's a misconfiguration.

> Also, what if the user has changed their name?

Could you please describe what you mean with this? If a user changes his name (we talk of the real name, not the username!), that change is known by the auth provider and propagated to HA upon next login.

> I see your use case and I see how you can get that covered, but we need to think about the system as a whole and take all other use cases into account too.

That's what I'm trying :)

**Comment by efficiosoft** [comment]
I think the implementation is now in an usable state.

1. No new method added, reworked ``async_user_meta_for_credentials()`` instead to be called both when user is created and loaded from database later. Each auth provider can decide whether he knows about a specific parameter of ``UserMeta`` (currently only real name and activity state) and change that upon authentication.

2. Sensible defaults (``name=None, is_active=True``) are used for newly created users, unless explicitly overwritten by an auth provider that claims to know better, which cleanly addresses the external auth provider case without interfering with other providers.

3. None of the existing auth providers will modify the user's activity state after user creation.

**Comment by efficiosoft** [comment]
Any chance home-assistant/home-assistant#20550 is going to be accepted? I think all qualms have been addressed by now, or are there any points I haven't thought of?

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
