### ISSUE TITLE
Additional device_class power

### ISSUE THREAD

**Issue by SukramJ** [home-assistant/architecture#140]
Hi,

i think a device_class "power" (DEVICE_CLASS_POWER = 'power') is needed for sensor devices that deliver additional metrics for current power consumption. The required unit for this is "Watt". 
Alternate name might be DEVICE_CLASS_POWERCONSUMPTION.

Homematic IP Devices like HmIP-BSM, HmIP-FSM and HmIP-FSM deliver such values.

I don't mean power status, to see if i device is powered on/off. This is already mentioned for binary_sensors.

BR
Markus

**Comment by OttoWinter** [comment]
I agree. Couple of other things to discuss too:

* The unit 'kW' (killowatts, note capitalization) should also be allowed, most household power meters use this unit. Also the power _unit_ for just w should be `W` (not `Watts`).
* We should also decide on an icon. I believe `mdi:flash` works quite well (and is used quite often already)
