### ISSUE TITLE
Disable partial custom component overlays

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#141]
We currently have the following loading order for any platform or component:

 - `custom_components/hue/light.py`
 - `homeassistant/components/hue/light.py`

This means that a user can create a partial custom component, where they only override a single platform of Home Assistant, but not the others. For example, Hue could be composed of:

 - `homeassistant/components/hue/__init__.py`
 - `homeassistant/components/hue/config_flow.py`
 - `homeassistant/components/hue/bridge.py`
 - `custom_components/hue/light.py`

This can cause the issue that the built-in component or platform evolves and now no longer offers the data structures or functions that the custom platform expects to be there.

I propose that when we load a platform, we first resolve the component and then load all platforms from the same source. This means that a custom component will now replace a built-in component instead of blend in with it.

**Comment by pvizeli** [comment]
Make absolutely sense
