### ISSUE TITLE
Optional Parameter for minimum brightness level of dimmers (light component)

### ISSUE THREAD

**Issue by SukramJ** [home-assistant/architecture#144]
Currently it is possible to set the brightness of a dimmer between 0 and 255.
The assumption is that 0 is **OFF** and the rest means **ON**.

But if you check the real world dimming the situation looks quite different.
**Example:**
I have multiple installed in my house and all behave different:
I have dimmers with 1, 2 and 4 leds connected to it. 
If I reduce the brightness to 20 all leds are on. 
If I go slowly down to 10 the dimmer works as expected, but only 3 of 4 leds are on, and not always the same led is off.
Lowering the brightness to 5 has the effect that only one led is still on.
Most of my dimmers are Homematic IP, but also my OSRAMs and Hues don't work below a brightness of 3. I checked the dimmers with a meter and they work (power output) as expected.

**My personal conclusion is:** 

- Dimming below a certain value my cause unexpected and undesired behavior of the leds
- A led that emits no visible light is off.

I'd like to have an optional config parameter for light entities to assign a minimum brightness level per dimmer.

In my case the dimmer with the 4 leds will be set to a minimum brightness of 20 and the others will be set to 10.

**Comment by Hedda** [comment]
+1 

I have Qubino Flush Dimmer (Z-Wave dimmer for flush mounting box) on almost all my ceiling light switches and in my experince is cannot go lower than 15% for LED lights even though it is by many considered the best dimmer available today, (it can however perform at a lower percentage with traditional incandescent bulbs and low-voltage halogen lamps with electronic transformer).

**Comment by Hedda** [comment]
@SukramJ Did you close this because it has been implemented now or was the suggestion denied?

**Comment by SukramJ** [comment]
It's not implemented.
After one year of no further attention i decided to close it.

**Comment by Hedda** [comment]
Would it not just be better to leave it open unless a core developer says it will never be added?

**Comment by Gamester17** [comment]
+ for re-opening and just leave this feature request open until the core developers say to close it

**Comment by dgomes** [comment]
Guys, this repository is **NOT** for feature request!

You come here when you want to discuss a change in how HA generally behaves/structured (therefore an architecture discussion). If you submit an issue here you should be able to actually implement the decision.

Personally I'm OK with this change, therefore supporting it (although my DALI system supports this feature natively, and HA is not aware of)
