### ISSUE TITLE
Idea to extend light turn_on service

### ISSUE THREAD

**Issue by zewelor** [home-assistant/architecture#145]
Hi

I want to propose some way to pass additional params via `light.turn_on` service, to lights that support more specific settings.

* Lifx is one example, which is currently handling this via custom turn on service (named [set_state](https://github.com/home-assistant/home-assistant/blob/ec57db78b505562666415210a989ecb039368106/homeassistant/components/lifx/light.py#L53)).
* Yeelight also could use this, as it supports custom `power_mode` param, currently handled by custom service [set_mode](https://github.com/home-assistant/home-assistant/blob/7429b9d87e4fba37aee6aae7eb45701522d73aaa/homeassistant/components/light/yeelight.py#L225), it only takes single param.

Now to turn on yeelight with desired power mode, you need to first call the `set_mode` service, then `turn_on` with desired settings, which might results in weird blinking, etc., depending on the parameter changed. I think it would be good for UX to be able to set it in single `turn_on` call. I understand that the `light.turn_on` service needs to be generic, so maybe it would be possible to extend it with a new field, something like, 'extra_params', which will be validated by lights that support them. The light could register the method, with custom schema validation for the extra params key.

I think doing custom services that expand `light.turn_on`, with different names might not be a great way. It duplicates the service, and there is need to use different service names to turn on different lights, when we want some custom params passed to them. Maybe a more unified approach would be nicer.

**Comment by OttoWinter** [comment]
I do not think we should extend `light.turn_on` further. It already handles _way_ to much in one command. If anything, we should be _splitting up_ the arguments into separate commands. For example the `effect` and `flash` options should IMO be separate service calls.

**Comment by zewelor** [comment]
Thanks for feedback. I can see problem with too big turn_on service. Yeelight and Lifx, both can use some kind of turn on with more params, thats why I was thinking that way. Maybe turn_on should only accept params, that can be set, without turning light on ? But then it probably differs from platform to platform ? So the best solution, for described case, would be to create custom service, like lifx does. Which can take all turn_on arguments + custom arguments, and will be specific for yeelight, instead of current set_mode ?

**Comment by frenck** [comment]
This architectural request did not gain traction. And I agree with Otto that we should not pursue this either. This can be easily solved by adding integration specific services 👍
