### ISSUE TITLE
Use kelvins as the preferred white temperature unit

### ISSUE THREAD

**Issue by amelchio** [home-assistant/architecture#146]
Home Assistant currently uses mireds as the internal representation of color temperature for white lights. I believe this has no particular reasoning other than the Hue API being the first one implemented and it uses mireds.

However, lights are always advertised with a certain kelvin range, even Hue bulbs, so this is the scale that humans know and also the one used for most other light APIs.

This means that almost all light integrations must do kelvin/mired conversions and that has resulted in numerous bugs. We have had bugs such as swapped warm/cold, division by zero and setting a temperature that is slightly (but noticeably) wrong. These kinds of bugs continue to appear in new implementations. This is because implementors expect kelvins and mireds to be related by a linear function but they are not.

Since the kelvin/mired relationship is reciprocal rather than linear, an interesting artifact is that the color temperature slider in the UI is not intuitive. For a 2000K-8000K (500-125 mireds) bulb, the expected midpoint is 5000K but the midpoint we currently use in the UI is way off at 3200K.

# Proposal

* We currently have ATTR_KELVIN as an alternative way to provide ATTR_COLOR_TEMP. I propose to reverse this relationship, making ATTR_KELVIN the primary attribute that platforms receive.
* Introduce a `kelvin` property for the color temperature of a light. If needed, we can keep `color_temp` centrally, just like `hs_color` auto-converts to `rgb_color`.
* Attributes `min_mireds`/`max_mireds` become `min_kelvin`/`max_kelvin` or maybe today we have a better way to provide these values to the frontend?
* Rename `SUPPORT_COLOR_TEMP` to `SUPPORT_KELVIN`
* Change the UI to use a kelvin scale.

If we can agree, I volunteer to implement these changes across all light platforms. It is not entirely clear to me how it would affect external stuff like mqtt?

**Comment by OttoWinter** [comment]
I 100% agree with this. The internal use of mired has always annoyed me very much (without HA I probably wouldn't even have had to learn what that scale is)

**Comment by amelchio** [comment]
I am closing this issue. It never received much discussion and though I see that it got a fair number of 👍, I have now lost the motivation to go forward with it.

**Comment by james10952001** [comment]
Perhaps we could revisit this at some point? There are some reasonable technical reasons for using the rather esoteric Mireds unit internally however the whole lighting industry uses the Kelvin scale so it would be really great the UI could be set to Kelvin instead. This is similar to C vs F for temperature, it isn't THAT difficult to learn to work with a new scale but it's a lot more convenient to be able to use the one most people are accustomed to.

**Comment by HenkRenting** [comment]
I fully agree.
Kelvin should be used instead of Mired.
I never even heard of it.. :-)

**Comment by icemanch** [comment]
Just adding to this.  Kelvin is the standard for describing light color.  People understand Kelvin.  Using mired in the UI seems unnecessarily technical.  I've worked in the lighting industry designing light fixtures and I've never heard of mired until Home Assistant.

**Comment by KapJI** [comment]
Using kelvins makes a lot of sense to me. I needed to google what mired is.

**Comment by janiversen** [comment]
👍 for the use of kelvin in the UI.

**Comment by KapJI** [comment]
Let's reopen this.

**Comment by thecode** [comment]
Another option is to let the device set the preferred unit similar to what we do in color modes.
If I have to choose one it would also be kelvin, but the optimal solution is to support both, the main problem with kelvin to mired conversion is that it is not an accurate conversion so that if the device work in kelvin and you convert to mired you get a value that when converting back will have a small offset.
