### ISSUE TITLE
Suggestion: “Zigbee” sub-forum (equivalent to the “Z-Wave” subforum) in Home Assistant Community Forum

### ISSUE THREAD

**Issue by Hedda** [home-assistant/architecture#150]
Since Home Assistant now supports native Zigbee Home Automation too (foremost via the ZHA component) I was wondering if we can please also get a dedicated “Zigbee” subforum (category)  in the Home Assistant Community Forums (preferably under the configuration category section as a sub-forum/sub-category?)? 

https://community.home-assistant.io/ => https://community.home-assistant.io/c/configuration => zigbee

My main argument for this is that more people might take notice of the native Zigbee solution for HASS that you now get with the ZHA component and its control panel and perhaps that will help make it not take as long for Zigbee to also become a first-class citizen in Home Assistant, just as Z-Wave already is today. Should that not be an acceptable request?

https://community.home-assistant.io/c/configuration => https://community.home-assistant.io/c/configuration/zwave

So a separate section dedicated to “Zigbee” and then maybe most specifically the ZHA component in Home Assistant, much as how the Z-Wave section is summed up here is in this sticky but for Zigbee:

https://community.home-assistant.io/t/about-the-z-wave-category/315

Yes I know this is not technically a core code architecture issue for Home Assistant but I think that making Zigbee into a first-class citizen is a core community issue for Home Assistant and since my previous request posted in community forum have gone completely unanswered I thought that I would rehash this issue here

https://community.home-assistant.io/t/suggestion-zigbee-sub-forum-equivalent-to-the-z-wave-subforum-here/74844

Again please excuse the cross-posting but in my defense, Zigbee deserves to be a first-class citizen in Home Assistant and in Home Assistant Community Forum.

**Comment by fabaff** [comment]
Subcategory added -> https://community.home-assistant.io/c/configuration/zigbee
