### ISSUE TITLE
Convert device tracker to EntityComponent

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant/architecture#151]
# Background
We've been talking loosely in different places about refactoring the device_tracker component to not have it merge devices. See eg:
- https://github.com/home-assistant/architecture/issues/71
- https://github.com/home-assistant/architecture/issues/72
- https://github.com/home-assistant/home-assistant/pull/19131#discussion_r247299766

This is now possible after the person component was implemented. The first PR was here:
- https://github.com/home-assistant/home-assistant/pull/20290

# Proposal

In this architecture issue I would like to follow up previous talk and propose that we go ahead with converting the device_tracker component to an EntityComponent with EntityPlatforms.

I have a draft PR ready with my proposal:
https://github.com/home-assistant/home-assistant/pull/21151

The plan for conversion is to first add support for EntityComponent in the device tracker component and convert 1 router platform and the 4 gps platforms that use config entries. Then gradually convert one platform at a time, after the groundwork has been accepted and merged. Tests will be cleaned up first and separately one PR per platform after which a PR with the corresponding platform conversion will be made.

# Questions

If we agree that we should convert to EntityComponent, there are some questions that I would like to discuss:

1. How do we need to handle the stale devices feature (and `consider_home` option)? Should it be removed or somehow kept around? If we need to keep it, how should that work?
2. Should we keep the see service around? If we keep it, do all platforms need to support it, or is it ok that only gps tracking platforms support it? FYI: There are mainly two types of platforms today, router platforms and gps tracking platforms.
3. Is it ok that we drop support for the `known_devices.yaml` config file? With lovelace the use case of this config file is gone, in my opinion.
4. Is it ok to drop support for `hide_if_away`? See point 3 for rationale.
5. Is it ok to drop support for `track_new_devices`? See point 3 for rationale. The suggestion is to always track all devices. Possibly we could add support for [entity filter](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/entityfilter.py), if we want to keep config support for what devices to track.
6. Is it ok to drop support for default group with all device tracker devices? See point 3 for rationale.
7. Is it ok to drop support for gravatar as entity picture? This could be replaced with a gravatar feature for person component instead.

Please add more questions that I have missed.

**Comment by balloob** [comment]
I want to make sure that we make it a relatively smooth transition. So we should not make changes yet without alternatives in place. Things that come to mind that we should implement first:
 - Allow uploading avatar images for persons (replaces image, gravatar)
 - Add a conditional badge to Lovelace, so people can mimic hide_if_away
 - add something to person component to replace default device tracker group

For your questions

1. We can make it part of the base device tracker entity that platforms extend. Although, that might be annoying? hmmm
2. iOS app depends on it, and I bet a bunch of custom integrations use it. We can't just drop it.
3. I agree
4. It doesn't work anymore anyway, it's a frontend concern. We might want to add conditional badges first.
5. Yep, we should drop it. 
6. yep, replace with person alternative
7. replace with avatar upload for person component.

**Comment by Landrash** [comment]
This sounds like a great plan.

Just one thought.
With the release of the Person tracking there can now be a potential Gap in coverage in asset tracking. 

This should potentially be kept in mind since there's most likely a possibility of code reuse.

This might be solved with something similar as the person component for those wanting to track their cat, car or keys. (Not related to this issue)

**Comment by balloob** [comment]
Note, person and assets are not in the same component just as why light and switch are not in the same component. Their interactions might seem very similar when looking at basic functionality, but they will grow in different directions. Person will have a user connected to it, it will link with mobile apps for easy notification etc.

**Comment by Landrash** [comment]
I understand that they are separated. just mentioning that if the device trackers gets refactored it would be preferable to keep in mind that use case.

**Comment by MwC-Trexx** [comment]
I like the entity idea, but believe this would also be very valuable for Media Devices.

So think of the following use case.  I have a new Smart TV.

So you are a "Vizio TV" entity 

It has multiple device tracker (router) entities
- WiFI MAC address
- Ethernet MAC address.

It also has multiple media player entries:
- media_player.vizio_smartcast
- media_player.vizio_smartcastdisplay
- media_player.vizio_plex

You then also have remote entities:
- remote.vizio
- remote.vizio_plex

All of these which are tied to a single physical "entity".

There also needs to be a way to clean up some of the legacy "slug" in the entity/device registries for older versions of these items above.

**Comment by MartinHjelmare** [comment]
I don't understand how this is related to the topic of this issue, converting device tracker component to use `EntityComponent` helper.

**Comment by MartinHjelmare** [comment]
Should we add restore state to base device tracker entity, or let platforms handle that?

**Comment by balloob** [comment]
Platforms should handle that.

**Comment by olbjan** [comment]
Just wanted to add some thoughts around how I believe some current functionality / logic might be impacted here:

1. Track by default
There are several network based device trackers that behave badly with regards to a possible track=true default. Google Home comes to mind as do network-based trackers that pull MAC addresses / ARP table entries. With these trackers in mind, a default of track=false right now makes more sense as they will create an abundance of entries in known_devices.yaml, most of which are probably not necessary to be tracked. The problem that comes to mind is that we either get a long list of entities we don't want or there needs to be a complicated onboarding for the platforms so the user can select which entities to create in the first place - similar to yaml include/exclude in recorder & history components.

2. Use of known_devices.yaml
While I agree it should be dropped at some point, I would like to point to installs with default track=false scenarios being a big use case for known_devices.yaml. Anyone running router mac table based trackers would get entries for every device on their network + possibly guests while they may only want to track phone mac addresses.

**Comment by balloob** [comment]
Mac addresses for any device on our network can be used for discovery and in helping tracking devices that are online/offline. So I think that each and all of them _should_ go into the device registry.

Bluetooth trackers with unstable tracking addresses, 🤷‍♂️ I dunno. Guess they can't track much to begin with. For either bluetooth or big device scans, it would be best to just have the individual configuration specify the addresses they should report on. It should not be globally managed.

**Comment by mrand** [comment]
> (5) The suggestion is to always track all devices

Would there potentially be a impacts (loading time, managing/usability, database entries or size, etc) if the number of devices gets staggeringly large?

I'm thinking of a scanner located where it might pick up devices from a bustling sidewalk corner in a city - it could easily add thousands every day, ten's of thousands over a week.

**Comment by balloob** [comment]
@MartinHjelmare can you add the pending improvements for the person component as tasks to https://github.com/orgs/home-assistant/projects/1 so we can keep an eye on it.

**Comment by kylezimmerman** [comment]
@mrand I agree, I live in an apartment building, and my `known_devices.yaml` has several hundred devices in it. I only actually track about 10 of them.

While lovelace would allow me to only display those 10 that I care about, I'd rather my history/log/database/system resources not get bloated tracking devices I don't care about. It also feels a bit creepy to track my neighbors devices without their consent.

It would be really nice to have a way to ignore/disable tracking of found devices before the deprecation of `known_devices.yaml`.

**Comment by Swamp-Ig** [comment]
I can probably update the Google Maps tracker when this is ready, so you can pencil me in for that.

**Comment by balloob** [comment]
One solution we can have for not tracking all entities from a platform is to allow disabling entity or devices. We already have this support in the entity registry, but it's not exposed. A disabled entity will not be added to Home Assistant when it is passed to `async_add_entities`. It requires a platform to only start updating entities via a callback in `async_added_to_hass`.

We could add an option to config entries to disable new devices or entities by default. I am not sure yet if this should be at entity or device level, probably device?

**Comment by mrand** [comment]
> We could add an option to config entries to disable new devices or entities by default. I am not sure yet if this should be at entity or device level, probably device?

Per device would be nice because it would give the option for maybe leaving one (more remote) active while disabling in high traffic areas.   But I don't know the architectural impact(s).  Here's a discussion where people have run into the exact problem I describe: https://old.reddit.com/r/homeassistant/comments/c695yt/i_successfully_got_room_presence_working_on_my/es8syrc/

**Comment by balloob** [comment]
Closing this issue. All different types of device tracker platforms are now able to be based around a config entry.
