### ISSUE TITLE
Add additional Cover device classes

### ISSUE THREAD

**Issue by andrewsayre** [home-assistant/architecture#153]
This is a proposal to add the following device classes to the Cover component:
* `door`: Control of a door (more generic than garage door)
* `curtain`: Control of curtains and drapes, could be for a window, wall, anything
* `awning`: Control of awnings, could be for a window, patio, anything
* `blind`: Control of window blinds
* `shutter`: Control of shutters, could be for a window, door, anything
* `shade`: Control of other types of shades, could be for window, patio, pergola, anything

We have three existing classes today `garage`, `window`, and `damper` which will remain.

This spawned out of the work to create the SmartThings cover platform, which would utilize `door`, `shade`, and `garage`.

**Comment by balloob** [comment]
So we already have 3 existing device classes: garage, window and damper.

It looks like damper was accidentally added by a PR instead of going through the right channels. Neither is "damper" a word related to cover devices, I think that we can delete that one. CC @Kane610

I think it's fine to add the proposed ones.

**Comment by balloob** [comment]
We should make sure we add them to the cover docs and what they represent.

**Comment by Kane610** [comment]
Definitely the right channels (https://github.com/home-assistant/architecture/issues/73), feel free to change it though.

**Comment by andrewsayre** [comment]
So deconz is still using `damper`.  Are we sure we want to remove it?

**Comment by Gamester17** [comment]
Would it be wrong to add "screens", as in motorized projection-screens, as another cover class?

An example is Somfy products: https://www.somfysystems.com/residential/interior/projection-screens

PS: Motorized projection-screens are sometimes also referred to as "electric projection canvas".

**Comment by Gamester17** [comment]
By the way, please excuse the bikeshedding, however, two other popular synonyms for "shades" is "blinds" and "shutters", (as in "roller blinds" and "window shutters") , and while its semantics as it is for the same word in this context I would guestimate that both the word "blinds" and the word "shutters" are more commonly used in the context of home automation than the word "shades" when referring to motorized roller blinds or motorized shutters. 

To put in context, if someone would just say; "I have a shades in my bedrum" while not already on the topic of home automation it would not make me personally think of roller blinds or window shutters but instead of either shades as in sunglasses or shade as in a shadow, at least when taken out of context, because that is how I only known people use the word "shade" . 

To back this wording argument of semantics I point out that not even people editing wikipedia have used "shade" in this context to this date:
https://en.wikipedia.org/wiki/Shade
https://en.wikipedia.org/wiki/Shutter
https://en.wikipedia.org/wiki/Blind

To back this my guestimate I argue that can google IKEA's new smart blinds; "Fyrtur" and "Kadrilj", which in all articles I could find they are always referred to as "blinds" and never as "shades".

**Comment by balloob** [comment]
I think I agree on the shade front. I would even be fine with differentiating between blinds and shutters, there is no need to be generic, "cover" is the generic name, device classes should be specific.

**Comment by andrewsayre** [comment]
I wholeheartedly agree that we should add `blind` and `shutter`.  Those are different things than a `shade`, which should remain. I will add those to the PRs as soon as I'm back in town.

> ...I would guestimate that both the word "blinds" and the word "shutters" are more commonly used in the context of home automation than the word "shades" when referring to motorized roller blinds or motorized shutters.

Not sure that's true... Smart shades are prevelent... to name a few products:
- https://www.zebrablinds.com/z-wave-smart-cellular-shades
- https://www.baliblinds.com/motorization/
- http://budgetblinds.springswindowfashions.com/motorized_treatments/

Not that SmartThings gets everything right, but it is a good comparison... They named their capabilities `Window Shade` and `Window Shade Preset` and don't even discrete capabilities for blinds and shutters.

**Comment by Gamester17** [comment]
An additional device class you might want to add here is "awning" which is quite common to motorize

https://www.somfysystems.com/residential/outdoor/awnings

And another cover class is "pergola" (as in specialized shades for pergolas)

https://www.somfysystems.com/residential/outdoor/pergolas

Somfy appears to have separate products in each of the above-mentioned cover categories.

**Comment by Gamester17** [comment]
By the way, perhaps  "damper" still belongs here as I believe that "damper" might refer to the electronic window shade technology (as in opposed to mechanically motorized shades) which is basically a thin transparent screen material that gets glued to the whole window (similar to window tint film) and LCD crystals in it then gets polarized when electricity is applied which affect the windows opacity/transparency and thus technically acting as a shade. See references:

* http://www.invisishade.com
* https://www.gotscience.org/2015/06/stay-tuned-for-low-cost-smart-windows/

Today this technology is also referred to as either "smart windows" or "digital privacy filters" as the achieved result is a built-in shade where you can tint/tone the whole window opacity/transparency depending on how much light you want to let in. Thus this is an electronic solid-state type of shade with no moving parts, other than LCD crystals.

**Comment by andrewsayre** [comment]
Let's lock this down and propose the list you came up with (less pergola).  We can always add more in the future if/and when needed.

**Comment by awarecan** [comment]
> I would argue that "shade" is not word related to cover devices in the context of home automation.

I have six HA-controllable motorized roller shade installed in my home. It definitely is one kind of window covering.

**Comment by tsvi** [comment]
If we're already on this topic. Dafang cameras use covers to allow movement of the PTZ axis.

Should this be added? It's basically a hack, as it's not really a cover, but uses the same instructions: up/down/stop/set position.

**Comment by dgomes** [comment]
@tsvi I think PTZ cameras should get their own component... (and I do have one of those cameras)

**Comment by tsvi** [comment]
Ok, so you think we need a separate PTZ component? Or should this be an optional implementation for the camera? I suppose we should open a new issue for that.

**Comment by dgomes** [comment]
Yes let's take it to a new issue

**Comment by andrewsayre** [comment]
The PRs have been updated based on the final list.  Please no more changes -- open a new issue. :)

**Comment by MartinHjelmare** [comment]
I don't know what a shade is and we can't define it as "anything".

**Comment by andrewsayre** [comment]
A `shade` is a type of window covering--which is different than a blind or shutter.  Besides the physical differences a shade reduces opacity of an opening where as blinds and shutters typically completely eliminate opacity.  Additionally, blinds and shutters can also be titled, which as shade cannot be.  For physical differences see these images:
- `shade`: A continuous plane of material (often fabric or plastic), sometimes of interconnected "cells" that can be expanded/collapsed over an opening.  Typically opens from the bottom.  [See this image](https://s7d4.scene7.com/is/image/JCPenney/DP0331201517025424M.tif?wid=350&hei=350&op_usm=.4,.8,0,0&resmode=sharp2)
- `blind`: An interconnected series of individual slats (often plastic, metal, or wood) that is expanded/collapsed over an opening.  When horizontal, are up/down an opening.  When vertical, are drawn from side to side or split in the middle, like curtains.  The gaps between the slats allow light to bleed through and can be adjusted using tilt. [See this image](https://www.blinds.com/SqlImages/8fa610dd-4e6f-e811-946d-0a986990730e.jpg?quality=90&mode=crop&anchor=middlecenter&width=680&height=535&format=jpg)
- `shutter`: An interconnected series of slats (often plastic or wood) that cover an opening.  They are opened outward (away from the window) to let light in.  The slats can often be adjusted to allow light through without having to open the blinds.  There are both internal and external blinds. [See this image](https://static.smithandnoble.com/test/gallery/bnd_10539.jpg?d=396x495)

These coverings are not exclusive to windows though that is their most predominate application.

**Comment by MartinHjelmare** [comment]
Super! Very clear! Thanks!
