### ISSUE TITLE
Add Person support to Proximity

### ISSUE THREAD

**Issue by OnFreund** [home-assistant/architecture#154]
Now that a `Person` is a first class object in HA, I think it makes sense that `Proximity` works on Person instead of/in addition to device tracker. For example, if I'm using both OwnTracks and the native app, Proximity would be able to use the latest update, regardless of which source it came from.

Note: `Proxmity` does support multiple devices trackers, but:
1. It's not entirely clear what's the relation between them. e.g. is direction of travel compared based on the previous reading from the same device tracker? The previous reading from the previous closest one? etc..
2. It would mean having the list of device trackers repeated once in Person and once in Proximity.

**Comment by OnFreund** [comment]
Would love to get some opinions on this matter.

**Comment by MartinHjelmare** [comment]
What is your suggestion of change?

**Comment by OnFreund** [comment]
I propose a change to the `Proximity` component such that it supports both device trackers and persons as input. If I understand correctly, the relevant parts of the external interfaces are identical for `device_tracker` and `person`.

**Comment by MartinHjelmare** [comment]
The proximity component already supports that. In an architecture issue we want the proposal to include both a "what?" and a "how?" or at least a detailed description of the problem. I don't see that yet here. Please clarify.

**Comment by OnFreund** [comment]
I couldn't find any mention of Person in the documentation for the component, nor any commit to change the component or its test to support Person devices (it also seems like moving the component to its own folder broke the history).
If Person is indeed supported, and no change was necessary, that is great news (though I would imagine that at the very list this line `DEPENDENCIES = ['zone', 'device_tracker']`, would need to include `person` as well).
In that case I would propose changing the documentation to reflect it, and adding the relevant tests.

**Comment by MartinHjelmare** [comment]
There's no dependency on person in the proximity component.

The proximity component uses latitude and longitude coordinates for its calculations. It can use any entity that exposes them in its state attributes. I don't think we need more tests for that.

It's apparent that there was very little research done before opening this architecture issue. Updating the docs doesn't require an architecture issue.

I suggest we close this issue. A PR to update the docs is welcome.

**Comment by OnFreund** [comment]
> It's apparent that there was very little research done before opening this architecture issue.

This is both wrong and patronizing.

Research that was done prior to opening this issue:
* Checking the proximity documentation that are all about device trackers.
* Checking the tests for proximity, which are all about device trackers.
* Checking the source code for proximity, that has a dependency on `device_tracker` but not on `person`.
* Seeing that the component also has a list of `proximity_devices`, but a Person is not a device.
* Checking commit histories for the component, its tests and its documentation, and finding nothing that will add Person support.

You believe that Person will work, and that's great, but it's clearly not supported - it's not tested, not documented, and nothing that will prevent this from easily breaking in the future.
If you think that the changes required to add Person support (in tests, source, and documentation) do not require an architecture issue, or that these changes should not be made, we can definitely talk about it, but your latest comment does not address all of these changes.

**Comment by MartinHjelmare** [comment]
When reading this issue I tested the use case. It already works. Did you test it and saw something not working? I would expect this, before saying that it doesn't work. If you did test it but forgot to mention it, I apologize. Otherwise I still think too little research was done.

Then I read the source code in the proximity component. There's nothing there that suggests that a person entity wouldn't be supported.

The proximity component is very old, has code that should be cleaned up and doesn't follow our current standards. The dependency on device tracker seems to be unnecessary.

I don't see the point of this architecture issue. There doesn't seem to be any need of architectural changes. We should just make an addition to the docs.

**Comment by balloob** [comment]
The architecture repo is not for feature requests, it's for architectural changes to the core of Home Assistant.
