### ISSUE TITLE
Adding an API to insert states of sensor (past or future)

### ISSUE THREAD

**Issue by grea09** [home-assistant/architecture#155]
Ehlo, I would like to ask if it is possible to add an API to add records in the recorder database based on external history or forecasts.

Here is the target issue: the Linky component (currently broken) uses an API that doesn’t allow real-time access to the value of the sensor. Instead all you can access is the history of the value for each half-hours as recent as the previous day. While wanting to interface with the utility meter there are only one way: do an ugly hack to present the yesterday data in function of the time. This makes impossible any correlation of data afterwards or to have correct monthly bills.

Another example of the issue: The MiFlora defices are battery powered. Each request takes a bit of energy. That is why it is adviced to have a low polling frequency. That results in poor temporal resolution in graphs and a lot of energy waste. The offical app however can access a low energy log and therefore get data with a good resolution in one request.

Last example is for weather forecast. I am aware that [this issue](https://github.com/home-assistant/architecture/issues/15) already asks for that but I am wondering if the API should be the same regardless of past or future. An example was if you get a weather API that gives you an array of the predicted weather for the next hour. It would be nice to be able to integrate an history graph that gives the projected temperatur for example.

---
The request is as follow: create a new API in the recorder/sensor components that allows a sensor to add entries in its past state.

I am willing to code it myself but I prefer to have some guidance to do that properly as well as validation of the core team before I get to work.

Thanks in advance.

**Comment by fabaff** [comment]
Did you ask Enedis if they are willing to allow access to live data?

**Comment by grea09** [comment]
> Did you ask Enedis if they are willing to allow access to live data?

I did, a couple of times. It's actually illegal for them to not give access to live data since they took in billions in tax money for that (and the site has less than 50% uptime). Lawsuits are ongoing but in the meantime we must do with what they give.

**Comment by BrunoSpy** [comment]
Hello
Any news on this subject ?

I add another example : gaz consumption is available in open data but with a delay of 2 or 3 days. The result is a totally useless graph consumption in the energy dashboard.

**Comment by balloob** [comment]
Home Assistant is not interested in allowing old data to be inserted into the state machine. Home Assistant does allow inserting legacy data into the generated statistics table.
