### ISSUE TITLE
Add ConfigEntries API operations

### ISSUE THREAD

**Issue by andrewsayre** [home-assistant/architecture#158]
This is a proposal to extend the `homeassistant.config_entries.ConfigEntries` API with the following operations to facilitate the ability to unload or reload config entries:

1. `async_unload(entry_id: str) -> bool`
    - Unwinds a loaded config entry, using the same process as `async_remove` but does not remove it from storage.
    - Returns `True` if the entry and all related platforms unload, otherwise `False`
    - Changes the entry state to `ENTRY_STATE_NOT_LOADED` if successful

1. `async_setup(entry_id: str) -> bool`
    - This must be an existing config entry in the registry that has one of the following states: `ENTRY_STATE_NOT_LOADED`, `ENTRY_STATE_SETUP_ERROR`, or `ENTRY_STATE_MIGRATION_ERROR`
    - Runs the config entry through the setup routine following the same process as `_async_finish_flow` and `homeassistant.setup`

1. `async_reload(entry_id: str) -> bool`
    - Essentially chains unload and setup.
    - If unload or setup fail, returns `False`, otherwise `True`

This functionality would be used by components that need to reload their config entries (and in effect, their devices and entities) in response to:
1. Changes in device/entries represented by the entry (due to external adds, removes, or updates) - _This is the use case I have for the SmartThings component._
2. Change of a credential or token, which may yield different access to devices.
3. Change in config entry options that affects entities or platforms under the component.

**Comment by balloob** [comment]
Aren't all these use cases solved by just reload?

**Comment by balloob** [comment]
I think it's a good idea btw.

**Comment by andrewsayre** [comment]
> Aren't all these use cases solved by just reload?

True - I can't think of many likely use cases.  It doesn't really change the implementation -- I can make them private for now, so it would be an easy change in the future.

**Comment by balloob** [comment]
Just make them public. Guess they need to be added anyway. 

That way we can add a nice "disable/enable" button to the UI too 👍

**Comment by balloob** [comment]
Working on adding these methods, doing a clean up of the config entry state logic too. This will be the new one:

![image](https://user-images.githubusercontent.com/1444314/53509208-33b8ad80-3a70-11e9-898d-da87b9cbd64b.png)

```graphviz
digraph G {
  "not loaded" -> "loaded"
  "not loaded" -> "setup error"
  "not loaded" -> "setup retry"
  "not loaded" -> "migration error"
  "loaded" -> "not loaded"
  "loaded" -> "failed unload"
  "setup retry" -> "not loaded"
  "setup error" -> "not loaded"
}
```

**Comment by andrewsayre** [comment]
Nice!  Two other thoughts:
- Add some way to know in component/platform `async_unload_config_entry` if it's just being unloaded vs. removed.  Or maybe add a `async_remove_config_entry` callback?  In SmartThings, I would use this flag to determine if I should delete the SmartApp via the API to minimize the chance of orphaned apps.
- Fix the typing of VERSION in `ConfigEntry.__init__`.  I think it was `str` should be `int` based on how we're using it from config flows.

**Comment by balloob** [comment]
I suggest we make it an extra callback `async_remove_config_entry` but won't do it in my PR to close this issue. 

PR https://github.com/home-assistant/home-assistant/pull/21502

**Comment by andrewsayre** [comment]
Nice!  I'll take a deeper look tonight (and open a separate issue for the remove callback).

**Comment by balloob** [comment]
You can open a PR instead 👍
