### ISSUE TITLE
Remove the "zigbee" component in favour of the newer "zha" component

### ISSUE THREAD

**Issue by Gamester17** [home-assistant/architecture#160]
Suggest removing the older "zigbee" component in favor of the newer "zha" component.

My main argument is that having both of these is and can confuse new users/developers. For end-users, I believe that it be confusing to have two components that do the same thing, and to bo both end-users and developers, I think it must be confusing to have one component be named "zigbee" and the other "zha" when they both are "zigbee". 

- https://www.home-assistant.io/components/zigbee/
- https://www.home-assistant.io/components/zha/

Firstly, I propose that the older "zigbee" component is now obsolete as replaced by the newer "zha" component so that older component can now be removed. "ZHA" stands for "Zigbee Home Automation" which uses the "zigpy" Zigbee Stack library with the "zigpy-xbee" radio module dependency makes the newer "ZHA" component supports the same XBee radios hardware as older "zigbee" component.

Secondly, perhaps more disruptive short-term but after the removal of the older "zigbee" component, I propose to rename the newer "zha" component to the older name of "zigbee". This because having it named "zha" is both technically incorrect and confusing.

That is, it is technically having the component remain named as "ZHA" is incorrect because "Zigbee Home Automation" is only one out of several Zigbee profiles supported by the current ZHA component, one other very common profile being "Zigbee Light Link" (which most smart lightbulbs use), and one other being "the "Zigbee Smart Energy" profile. Perhaps a more correct naming would otherwise be "Zigbee PRO" as I understand that covers all profiles (but I could be wrong about that).

- https://en.wikipedia.org/wiki/Zigbee

It would also be confusing and non-intuitive for people looking for native Zigbee solution in Home Assistant. For example, the Z-Wave component is simply named "zwave" so if there after removal of the old and there would be only one for Zigbee then why not rename that component to just "zigbee". So at least if the "ZHA" component could be renamed to "Zigbee" or "Zigbee Pro" on the frontend side it could be less confusing to end-users.

- https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/zigbee
- https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/zha
- https://github.com/zigpy/zigpy
- https://github.com/zigpy/zigpy-xbee

Tag ZHA component developers @dmulcahey @rcloran @Adminiuga @damarco 

PS: Hope this architectural change proposal is ok here even though I am not a developer myself.

**Comment by balloob** [comment]
They are not the same. One is for Zigbee DIY, the other for consumer devices.

As per the the initial contributor of ZHA component: https://github.com/home-assistant/home-assistant/pull/6263#issuecomment-282728341

Since they are not the same, removing either is not an option.

**Comment by Gamester17** [comment]
You see, very confusing. The point that the current naming of these two components is an issue is still valid.

**Comment by Adminiuga** [comment]
I understand the point of not removing/renaming the older component. IMO at very least should update the docs and add something like "See also: ZHA Component" to Zigbee component doc and vice versa

@balloob are you keeping any statistics about component usage? In other words is there any  mechanism preventing a component going stale?

**Comment by balloob** [comment]
We don't keep any statistics. All in favor of making the documentation more clear 👍
