### ISSUE TITLE
Adding Sensor and Binary Sensor support to Google Assistant

### ISSUE THREAD

**Issue by CultusMechanicus** [home-assistant/architecture#162]
The current setup of the Google Assistant component doesn't support the 'sensor' or 'binary_sensor' domains and covers are treated as lights. I suspect this is due to the Actions for Google documentation being a bit slow to update with regards to DeviceTypes and Traits.

There's a list of 'in progress' DeviceTypes and Traits at https://github.com/actions-on-google/smart-home-nodejs/issues/253 , the most obviously useful ones being:  
* [action.devices.traits.Sensor](https://storage.googleapis.com/hc-eap/SmartHome%20Sensor%20Trait%20Schema.pdf)
* [action.devices.types.SENSOR](https://storage.googleapis.com/hc-eap/SmartHome%20Sensor%20Guide.pdf)
* [action.devices.traits.OpenClose](https://storage.googleapis.com/hc-eap/SmartHome%20OpenClose%20Schema.pdf)

Those should cover temperature, humidity, lux and simple binary sensors, as well door/window contact sensors and a nicer way of handling covers. While they may not be fully finalised, SmartThings is currently using at least the three listed above to expose its attached sensors.

**Comment by balloob** [comment]
Interesting, I was not aware. It's a bit icky to implement them and then have them change on us, breaking things. However, I am not opposed to PRs implementing some of these.

**Comment by michaelarnauts** [comment]
Nice, for blinds, they seem to have device type [action.devices.types.BLINDS](https://storage.googleapis.com/hc-eap/SmartHome%20Blinds%20Guide.pdf) that uses [action.devices.traits.OpenClose](https://storage.googleapis.com/hc-eap/SmartHome%20OpenClose%20Schema.pdf).

**Comment by balloob** [comment]
A few more official ones got added too https://www.androidpolice.com/2019/02/27/google-assistant-adds-native-support-for-smart-air-fresheners-and-fireplaces/

**Comment by dshokouhi** [comment]
Looks like blinds are now officially supported: https://developers.google.com/actions/smarthome/guides/blinds

Some of the traits are now live too, seems like we can now leverage OpenClose for binary sensors :)

https://developers.google.com/actions/smarthome/traits/openclose

**Comment by balloob** [comment]
all official sensors and binary sensors are now integrated. The unofficial ones seem to not work properly.
