### ISSUE TITLE
Additional device_class signal_strength

### ISSUE THREAD

**Issue by SukramJ** [home-assistant/architecture#165]
Hi,

i think a device_class "signal_strength" (DEVICE_CLASS_SIGNAL_STRENGTH = 'signal_strength') is needed for sensor devices that deliver additional metrics for rssi (Received Signal Strength Indicator). The required unit for this is "dBm".
Possible icons are mdi:wifi (Signal) and mdi:wifi-off (No Signal).
This is e.g. useful for detecting issues with signal strength over time.

BR
Markus

**Comment by balloob** [comment]
Yeah, I think that would fit. Which integrations would be able to use this?

**Comment by SukramJ** [comment]
In my case it is homematicip_cloud.

Could you also comment [21563](https://github.com/home-assistant/home-assistant/pull/21563)
It's about adding signal strength measures to homematicip_cloud.
I think your advice is needed for this PR

**Comment by Data-Monkey** [comment]
maybe also googlehome and it's BT tracker capabilities.

**Comment by Landrash** [comment]
Also useful for esphome that has a wifi sensor

**Comment by OttoWinter** [comment]
@Landrash Yes but that has unit "dB" (not "dBm") which is slightly differently semantically.

- dB is a ratio of two values.
- dBm is a ratio of two values where one of them is 1mW (milliwatt)

So the former term includes the dBm one (and 1dB can thus also mean 1dBm). Looking at Wikipedia, the unit dB is preferred over dBm in the SI Units: https://en.m.wikipedia.org/wiki/DBm

So I'd propose that this device class also adds the more generic "dB" as a unit.

**Comment by molobrakos** [comment]
Would it be more intuitive to the user to offer automatic conversion to quality in percent?
https://stackoverflow.com/questions/15797920/how-to-convert-wifi-signal-strength-from-quality-percent-to-rssi-dbm/30585711
