### ISSUE TITLE
Support latest 2 Python versions

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#167]
Currently Home Assistant tracks Debian stable to decide on the minimum supported version of Python. This is currently Python 3.5 which was released on September 13, 2015!

Instead of focusing on missing features in Python 3.5.2 (a lot), I want instead to talk about changing our approach on this. Instead of following Debian Stable, I suggest that we support the latest 2 versions of Python. That will be 3.6 (released December 23, 2016) and 3.7 (released June 27, 2018). (Python 3.8 is not scheduled for release until the end of the year)

As discussed [earlier](https://github.com/home-assistant/architecture/issues/126#issuecomment-457819615), we're now aiming to make sure things work on Hass.io, Docker and Hassbian. So let's take a look at the impact:

The impact of this:
 - Hass.io: none (already 3.7)
 - Docker: none (already 3.7)
 - Hassbian: This is Debian based and so is, like Debian stable, currently supports Python 3.5.2 (I think!). Hassbian runs a script on first boot to install Home Assistant, and we can make this script install the latest Python instead. For upgrading existing installations, it is easy because the config lives in another directory and dependencies are installed inside the venv. All that is needed is:

```bash
# Assuming this is a dir with a venv with Home Assistant installed
rm -rf homeassistant
mkdir homeassistant
python3.7 -m venv homeassistant
cd homeassistant
source bin/activate
pip3 install homeassistant
```

## Implementation plan

- Hassbian implements installing the latest Python on first boot ([instructions](https://gist.github.com/SeppPenner/6a5a30ebc8f79936fa136c524417761d))
- For 4 releases (2 months), print a warning if users are running a soon to be deprecated Python version. 
- Drop Python 3.5.2 support

## Plan for new Python releases

- When a .0 release comes out (ie 3.8.0), start printing a warning for the release that will be dropped
- After at least 2 months and when a .1 release is out, drop support for the oldest version of Python.

CC @home-assistant/hassbian

**Comment by MartinHjelmare** [comment]
Hassbian has Python 3.5.3. That is what latest Debian stable has.

**Comment by ludeeus** [comment]
Having the startup script install this on first boot will add 1 hour to the startup time, no sane user will wait so long, that has to be added to the image.

For existing installations `hassbian-config` has a upgrade script that will upgrade python to the latest stable version and make Home Assistant use that version.

 CC @landrash

**Comment by pvizeli** [comment]
There are too many missing features on Python 3.5 <. So if 3.5.2 or 3.5.6 make no difference.

**Comment by balloob** [comment]
Ah right. Adding it to pi-gen and put it in image is the right path. The idea is that it is installed as "altinstall" and so it won't replace system python, just be made available as python3.7 on path. 

Also, doh on 3.5.3. my bad.

**Comment by balloob** [comment]
Good to know that hassbian scripts already supports an upgrade. That means we just need to see support added to pi-gen

**Comment by Landrash** [comment]
There's one big problem with installing a separate version of Python. It
negates any upstream security patches. As soon as we have a separate
version of python that's not packaged we need to track, package and patch
it our self's.

I've tested replacing the Python version shipped with Raspbian before but
there's problems with some utilities included and package dependencies. So
without rearchitecture of the base image which would break the
comparability with Raspbian that's not an option.

The next version of Debian(10) includes Python 3.7.2.
Waiting for a Raspbian based on that would be preferable but if it's not an
option I'll have a look at other options.

**Comment by balloob** [comment]
If we do the "make altinstall" it will not replace system python. If hassbian already supports upgrading python, we just need to run the altinstall as part of the pi-gen?

**Comment by pvizeli** [comment]
Our docker (Official docker image / hass.io image) use also not the distro python versions.

**Comment by awarecan** [comment]
Last time Raspbian released stretch after Debian stretch full freeze six months. So, I expect Raspbian Buster will arrive on September 12, 2019. Could we at least support python 3.5.3 till that time?

**Comment by balloob** [comment]
I prefer not to. Because then one could argue that we should allow people some time to upgrade their distro too?

I think that doing an altinstall of Python is less involved than a dist-upgrade. Especially if you can use the [Python upgrade hassbian-script](https://github.com/home-assistant/hassbian-scripts/blob/dev/package/opt/hassbian/suites/python.sh).

**Comment by OttoWinter** [comment]
Just out of curiosity: What features in particular are missing from 3.5 that 3.6 has? From a quick look at the [changelog](https://docs.python.org/3/whatsnew/3.6.html) I only see these:

- asyncio improvements (not sure what exactly?)
- pathlib
- format string literals

I don't have too much against this change, just curious what feature we desperately need and have no simple workaround for. (coming from somebody who's still stuck in py2.7 :D )

**Comment by awarecan** [comment]
For me,

* PEP 525, asynchronous generators.
* PEP 530: asynchronous comprehensions

**Comment by pvizeli** [comment]
- PEP 526 (that one is amazing)
- PEP 519 (One of my favorites)

**Comment by Landrash** [comment]
Only problem I see with this is leaving the Raspbian distribution that's the "standard" distribution for a Raspberry Pi.
It can still be installed but with a much longer installation method on a "stock" Raspbian installation.
This should be taken into account since it can quickly be considered alienating by parts of the community.

I've been looking into the changes I need to make to the Hassbian and the *upgrade-script* can be used for an upgrade. It won't work in it's current form for updating the python version after that without manual intervention. Assuming there's a security bug in Python we then leave any installation created and not manually updated potentially vulnerable. This should be mentioned before I do any changes to how the image is composed currently.

Packaging a newer version of python and keeping that updated is the only viable option I know of right now. (That currently is a bigger undertaking than I believe I have the time for currently.)

Either way we move forward there's going to be backlash and a better explanation of why than
PEP 526 / 519 is really needed for anyone who isn't a python dev.

**Comment by balloob** [comment]
The most foremost reason to limit to latest Python 2 versions is to reduce the maintenance burden, second reason is to improve the development experience. Since we are 99% run by volunteers, making life for our developers easier is important.

 - Developers don't need to check if features work under Python 3.5. Like all dictionaries are ordered in 3.6. 
 - Developers don't need to make PRs to libs to make them compatible with Python 3.5 or even end up forking them. 
 - Most of the flakey tests are under Python 3.5.
 - It will shave off at least 20 minutes from our test suite as we drop Python 3.5. Travis backlog is a big burden on developer velocity.
 - We don't let our future be dictated by the choices/release cycle of any Linux distributions.
 - IDEs/tooling better support the official type syntax for variables
 - With Python 3.6 we can start using [Black](https://pypi.org/project/black/), dropping most of our linting rules.

I agree that if we could find/create a deb package repository, users would have the easiest path forward. However, it wouldn't be difficult to create a small update script for Hassbian so that we can tell users if their Python is outdated.

**Comment by rytilahti** [comment]
The ones I have hit myself while working on libraries:

* Literal string formating aka. f-strings; using `.format()` feels very unpythonic and ackward when one is used to use `%` (PEP 498)
* Underscores in numerals (10000000 versus 10_000_000) (PEP 515)
* Async comprehensions (PEP 530): `[await do_x(x) for x in something]`
* Type annotations for variables; `my_value: MyType = None` instead of `my_value = None  # type: MyType` (PEP 526)

From the points raised by @balloob the introduction of enforced black by precommit hooks will shave off a lot of frustration and need for "fix this or that"  -- looking at PRs, it seems to be a common practice to let the hound and the travis do those checks instead using tox & others locally, maybe there is something wrong with the setup when people avoid doing it? I admit to do that myself, too..

Wrt. the situation with Debian, are there no backports being built for newer python versions if that's the only blocker to make this change? If so, would it be feasible thing to consider doing that or is that completely out of question? I think the pros of having a newer python version clearly outweigh the backporting effort.

**Comment by balloob** [comment]
We would need backports of Python 3.7 for the three different arm versions. From my Google foo, none are available right now.

**Comment by balloob** [comment]
Ah looks like there is a thing called `checkinstall`, which can do this easily.

https://help.ubuntu.com/community/CheckInstall

```
apt-get install checkinstall
```

And then instead of `make altinstall` for Python source, we use `checkinstall make altinstall`

**Comment by DubhAd** [comment]
There's `checkinstall` and another more Debian specific tool that can do that (I'll dig out the details). For Hassbian if the project had it's own PPA then it would be "easy" to provide a way of updating Python and any other packages.

**Comment by DubhAd** [comment]
`debuild` is [the thing](https://blog.packagecloud.io/debian/debuild/packaging/2015/06/08/buildling-deb-packages-with-debuild/) I was thinking of.

**Comment by rytilahti** [comment]
The backporting (never done it myself that seriously) goes somehow like this:
1. Fetch the source package from testing/unstable/experimental
2. Add patches to make it work on the target system, if necessary
3. Build packages with debuild

Here are instructions how to do that formally: https://wiki.debian.org/BuildingFormalBackports

**Comment by Adminiuga** [comment]
+1 about debian backporting. I thinks that's the way to go and not the check install. I mean we do it for some python packages, so no reason we couldn't do it for debian packages. The problem with back-ports is keeping it up-to-date with security patches.

**Comment by Kane610** [comment]
Why can't hass be run in docker on hassbian?

**Comment by Landrash** [comment]
It adds an abstraction layer that's not wanted by many.

**Comment by Kane610** [comment]
What is hassbians mission?

**Comment by Adminiuga** [comment]
BTW Debian Buster is in freeze, so backporting python to stretch until Buster is releases shouldn't be an issue.

**Comment by balloob** [comment]
@Kane610 let's stick on topic please

**Comment by balloob** [comment]
I suggest that we deprecate Python 3.5 starting the first release after June 1, 2019. This will give the Hassbian crew 2,5 months to implement a solution. After 2 months, on August 1, 2019, we adopt that Home Assistant will support the latest 2 major releases of Python.

**Comment by Landrash** [comment]
Seems like a good timeframe.

**Comment by Landrash** [comment]
Debian Buster pre-release available now.
Very early build and not that well tested yet.
https://github.com/home-assistant/pi-gen/releases/tag/v1.6
Running Python 3.7.3rc1

**Comment by awarecan** [comment]
We don't have test suite running on 3.7.3, can we use 3.7.2 until 3.7.3 release?

**Comment by Landrash** [comment]
@awarecan  3.7.3 is whats shipped in Debian Buster and what's downloaded by the update script in Hassbian since it's the latest release of Python :)

**Comment by pvizeli** [comment]
Well, all docker is on 3.7.3 without a issue

**Comment by awarecan** [comment]
Looks like 3.7.3 arrived in circle ci as well, I will update our CI env now. All for 3.7.3 now.

**Comment by awarecan** [comment]
Oh, shoot, we are using `3.7-stretch` in CircleCI. It already be 3.7.3 now.
