### ISSUE TITLE
Allow partial custom overlays

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/architecture#170]
I'd like to get some feedback from the devs on this because I'm not familiar enough with the system to fully understand the details.

From what I can tell, one of the main reasons for #141 was to prevent incompatibility issues that could arise when a component updates and changes functionality that a partial custom overlay was using. The preferred solution is to now override the entire component to minimize breakages. This doesn't come without it's own issues, but it should help in many cases.

However, a number of people are finding workarounds to try to emulate the old way of using partial overlays. There is a good summary of the alternative solutions in [this community thread](https://community.home-assistant.io/t/0-89-breaking-change-prevent-partial-custom-component-overlays/103728/47). Essentially, the idea is to either import everything from the built-in component into your custom component or make a new component with just your custom platform and use everything else from the built-in component.

What I'm unclear about is whether these alternative solutions provide any advantages over the old partial overlays or whether they have essentially all of the same problems with little to no benefits. If they are subject to the same breakages as partial custom overlays, then it's apparent that the block on them wasn't enough to prevent the types of issues it was trying to prevent, since people will still run into the same issues with these new alternatives. Also, these approaches are likely to just cause even more issues since they require extra complexity to achieve the same results.

Either way, it's apparent that there is a desire from at least some of the user base to continue using partial overlays despite the known potential breakages and maintenance requirements. I would propose unblocking the use of partial custom overlays and simply issue a warning when they're detected (no idea if this is easy to do, though) or lock the feature behind an option that needs to be enabled first. The documentation for creating custom components should provide the recommendation to override the entire component. This would hopefully be enough to dissuade most newcomers from using partial overlays but still allow advanced users to do so without having to jump through hoops to implement the alternative solutions.

**Comment by tboyce021** [comment]
Basically, I'd like a way to say "Yes, I know what I'm doing. Let me override just this platform". Even an option to enable developer/advanced features that needs to be enabled before allowing partial overlays could work as well.

**Comment by balloob** [comment]
We've taken a lot of steps recently to work towards a package format for components. Embedding the platforms, trying to consolidate all the code related to 1 integration in 1 directory. In the future we will want to standardize and extend this format with new features, including potentially decoupling integration updates from the normal release cycle. This will not be possible with partial updates.

Looking at the community thread, the one approach that I think by far is the best approach, is creating a platform under a new name. Sure, you still have the problems that partial overlays can cause, however:

 - It's the open source way. We fork, modify, distribute.
 - No need to copy any internal files over
 - Easy to spot it's a custom component when filing an issue in the Home Assistant tracker
 - A user could only use it for the things that require it, instead of routing all his MQTT switches through a custom version, potentially less will break.
 - Less fear spreading when users comment on release notes that X broke but forgot to mention it was a custom override

At the end of the day, most of us are volunteers. Volunteers are everything in this project. We did a release last Wednesday, 94 different people contributed code. Many more helped with documentation, moderation, creating videos, helping others. If I can relieve a little workload from our volunteers, if I can avoid them being targeted with misinformation/attacks/rants because things don't go as a random person on the internet wants, if I can make it even just a little more pleasant to contribute, we should. And avoiding partial overlays helps with that.

_(Note, this last paragraph was not aimed at you or this issue.)_

**Comment by tboyce021** [comment]
Thanks for the quick reply. I definitely understand the desire to reduce the workload for volunteers, especially when the issues are essentially user error.

The downside to these alternatives, though, is that they have even more issues than partial overlays and appear to provide no extra benefits. If people start using the import strategy, for example, then the situation for volunteers is actually no better than it was before but the situation for users is a bit worse.

If it's truly not possible to support partial overlays, then I guess that's just a trade off we have to accept. However, I was under the impression that there isn't currently anything preventing them from working, other than the desire to not deal with the issues they can cause. Of course that could change if/when integration updates are decoupled, but until that happens or there is a design for it (is there one yet?), it seems difficult to know if there would actually be more issues or not.

Also, FWIW, I've made contributions to the codebase and in the forums where I used partial overlays to quickly do some testing or make some changes to a platform. While I could use one of the alternatives or copy the entire component to do that, the extra effort may, in some cases, encourage people to not even bother (probably not, but it is definitely a possibility for anyone considering contributing).

I guess maybe the way to go is to just let this play out for a bit to see what direction people go with it and reconsider things in the future if it doesn't.

**Comment by balloob** [comment]
No architecture issue yet. Some ideas got mentioned in #124:

> Packaged components. If we have a single folder for a component and all it's platforms, we can make sure we have a file with metadata to specify requirements (so we can install requirements before loading the Python file and thus import stuff at the top of our python files), versioning, code owners, logo, name. Now this can be independently distributed and updated. Not just by us, but by others too, like Hass.io add-on repositories including updates etc. Just like Hass.io add-ons, it will ease maintenance as no longer the core team is the bottleneck of all PR reviews

You're right that there is currently nothing preventing them from working. But as we were already forcing people to update their custom components by changing the folder structure, it seemed appropriate to minimize the number of breaking changes and get to our final form. 

For trying out some quick code, it shouldn't be hard to create a `generate_custom_component` script that just copies the files from the built-in package into your custom components folder for quick experimentation.

**Comment by tboyce021** [comment]
I'd thought about trying to write a script or even custom component that is able to find missing pieces of other custom components and pull them in automatically or generate the proper imports to emulate it but haven't tried anything yet.

What is your opinion on recommending the alternative solutions from that thread to other users though? Personally, if I can't easily come up with a scripted solution I like, I'd probably use the import method just because it has fewer caveats. But I'm also able to debug most things myself and not bother volunteers too much with issues. However, I'd hate to go around recommending these if they're effectively the same as partial overlays since that negates the advantages from blocking them in the first place.

**Comment by tboyce021** [comment]
I guess based on your previous comment I would assume:

Import method: Not recommended since it's essentially the same as a partial overlay and is not distinguishable as a custom component

New name method: Aceeptable if you can live with the caveats since it's easily distinguishable as a custom component

**Comment by tboyce021** [comment]
Now, based on that, I came up with an alternative idea: Allow partial overlays but make them distinguishable in the configs. This would work the same way as Lovelace custom cards, e.g.

```yaml
mqtt:
- platform: custom:light
```

Voila. Now you can customize just the light platform using a partial overlay but it's still obvious from the config that it's a custom component so volunteers don't waste time on it.

Obviously, if there's an architectural reason partial overlays can't work then this is unnecessary. But if it's simply to reduce the burden then maybe this could work?

**Comment by balloob** [comment]
My preference will be to use the new name method as I describe in my first reply https://github.com/home-assistant/architecture/issues/170#issuecomment-471245179

I would not be against supporting `custom:` for platforms (it would require quotes or YAML goes crazy), however, it will only be possible for platform only integrations, of which we get less and less. More things are moving to being powered from a component and no longer have individual platform configuration. And in that case it won't be supported anymore unless all components update how they handle their configuration (which is too much)

Also note, if you can specify `"custom:mqtt"`, might as well just specify `tboyce_mqtt`

**Comment by balloob** [comment]
I'm going to close this as we should not revert this back, just to restrict it again in the future. The best approach is to get to the future faster.
