### ISSUE TITLE
Discovery process

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/architecture#172]
## Reasoning
In #121, there was this point from @balloob 

> Only do discovery when it's necessary (onboarding, visit to integrations page)

And a counterpoint from @rytilahti 

> Move from polling not to "poll only on configure integration and onboarding", but to continuous discovery

I also just created a [feature request](https://community.home-assistant.io/t/manually-run-discovery/104980) on the forums regarding this, but since it relates to #121, which seems to be a related but probably separate topic, I decided to start a new discussion here to go into more detail on those points and a few others (let me know if this is not the right place for this).

## Adding devices through discovery
I will start by saying that, personally, my primary issue with discovery is that it adds things automatically. This can cause issues in some cases and is just plain undesired in others. Maintaining a list of included/excluded domains when the list of possible domains can change with each release and requires a restart to modify is too tedious. It also can't account for cases where you may want to add one device from a domain via discovery but ignore another device from the same domain.

Therefore, discovery should only notify when devices are found but require manual interaction before actually adding anything. That could be (and already is for integrations that support it) as simple as clicking "configure" for any discovered integrations and completing any additional steps.

At most, there could be an option to enable adding things automatically when possible, but this should be turned off by default to avoid adding devices automatically before the user can disable the option. Alternatively, it could be configurable during the initial setup but should also be configurable at any point after.

## Running discovery
As useful as discovery is, it really doesn't need to run very often. When the home setup is fairly stable, adding new devices is likely to be infrequent. Running discovery continuously or periodically when nothing is added for months or years seems like a waste of resources.

For most cases, having a button at the top of the integrations page to run discovery only when needed should suffice. For other cases, exposing a service that could be called to trigger the discovery process would be beneficial.

### Onboarding
As mentioned, discovery is particularly useful during onboarding to quickly find and configure supported devices. However, not everything can be found and configured via discovery, so users would likely need to go to the integrations page to set things up. Since a new setup already directs the user to the integrations page, having a button at the top of that page to run discovery would make it a natural part of the onboarding process (initial setup -> login -> link to integrations page -> button to run discovery and/or set up integrations manually).

### Adding new devices
When a new device does get added, either the user is aware of it and wants to add it or they're not aware or don't want to add it. If they're aware and want to it add, they can go to the integrations page and run discovery or configure the device manually. If they're not aware or don't want to add it, they wouldn't expect it to be available in Home Assistant so it's not really necessary to find/configure it for them.

### After updates
Since an update could add support for new integrations or add discovery support to existing integrations, it could be useful to run discovery after each update to check for newly supported devices. This could be treated essentially the same way as adding new devices. The user can choose to run discovery after the update to check for new devices or simply do nothing if they don't care.

### Via service call
Exposing a service call to run discovery can actually be used to make most of the useful cases automatic and as a bonus it is entirely user configurable by default. The user can set up an automation to run discovery after an update, each startup, periodically every X minutes/hours/days, at specific times, or any combination of things they choose.

The one case the service call can't easily cover is the initial onboarding since no automations will be set up yet to handle it. In that case, it could be made optional as part of the initial setup, e.g. "check this box to run discovery after setup"; however, that seems mostly unnecessary if the button to run discovery is already easily found as part of onboarding process, especially if the user needs to manually accept the discovered integrations anyway. If discovery adds devices automatically, this becomes more useful.

## TODO
- [ ] Does discovery run for a set amount of time or does it require an action to start and stop (maybe both depending on the use)?

**Comment by balloob** [comment]
I plan on having onboarding look like this: https://www.figma.com/proto/hQpYcU3H4yJWT5dzcZSLmU/Home-Assistant-onboarding?node-id=291%3A6&scaling=min-zoom&redirected=1

The goal is for all discovered items to be configured via config entries. Config entries will not set up anything automatically, instead will ask user to confirm.

There is actually not that much overhead to running discovery, especially once we limit it to just mDNS & SSDP. All other discovery protocols we currently support are one-off protocols and shouldn't be part of our discovery. Users will still be able to trigger integration specific discoveries when starting a config entry flow for that integration. 

And also on the cost of mDNS discovery, we will already be running mDNS to make Home Assistant discoverable on the network for other apps to find (like iOS app). (will be part of the default config)

SSDP is a socket that we would send a broadcast packet on every 5 minutes and then listen for 5 seconds.

The actual goal is to kill completely us relying on the netdisco package. Instead, I want to just have integrations specify in their manifest file how they can be discovered.

**Comment by tboyce021** [comment]
Perfect. That takes care of my main concern.

It would still be nice to have an option to run it again only when desired, though. I don't particularly want to deal with periodic notifications or having discovery show things it found when I don't care. This is kind of already possible by changing the config to enable discovery, configuring what it finds, then changing it back to disable it again, but a button that does effectively the same without the restarts would be nice.

I suppose these points from #121 may already cover that depending on how it's implemented:

> 1.1.1 If unwanted. Either dismiss (will be shown again later) or disable (no future notifications from this device shall be shown).

> 2.1. Discovery process is done as a whole, discovering all (even the disabled) devices and providing the opportunity to configure them.

**Comment by tboyce021** [comment]
I guess we can leave this issue or close it and merge it into #121 as a continuation of that discussion if desired. I just wasn't clear where the separation of concerns should lie and didn't want to clutter up that thread if this wasn't entirely related.

**Comment by balloob** [comment]
> It would still be nice to have an option to run it again only when desired, though. I don't particularly want to deal with periodic notifications or having discovery show things it found when I don't care. 

We should never implement a feature to work around behavior of our own code 🤷‍♂️ because even if we fix our own code, that feature now lives forever.

**Comment by tboyce021** [comment]
Makes sense. I think I was still working under the idea that it may not be desirable to run discovery continuously/periodically for one reason or another.

Is it the idea then that adding z-wave/zigbee nodes will always remain as part of a separate workflow? I mention this because SmartThings essentially had a single "discovery" page where it would find these as well as other integrations, so it's certainly possible to consolidate them all into the same process if desired.

However, if discovery is going to be limited to only a couple lightweight protocols, it's not that big of a deal to just run continuously. I guess this part from #121 had me believe there might be some more intensive discovery methods as well, though:

> Config Entries will be able to register how they can be discovered: upnp/SSDP, mDNS/zeroconf/bonjour **or with their own custom method**.

> We also will only run discovery during onboarding and whenever the user navigates to the integration page. So during normal operation, these packages won't be loaded.

If it only runs when navigating to the integration page (aside from onboarding) then I guess **that** is essentially the same as the button that I proposed (the button to go to the integration page is the button that runs discovery). It doesn't seem like a stretch to just make it an actual button on that page instead of automatic when going to the page, but the difference is fairly small.

**Comment by balloob** [comment]
Ah I see how that sentence could be confusing. The custom method is just available when a user initiates a config flow (clicks configure) on the integrations page.

**Comment by tboyce021** [comment]
That makes more sense now. Most of this probably isn't necessary in that case. I thought it was going to support more types of discovery without clicking "configure" first. I imagined that could easily get pretty resource intensive given the number of integrations available and I'm sure people could probably come up with all kinds of crazy ways to discover various things.

Would things such as attached devices (e.g. z-wave/zigbee sticks) ever be discoverable automatically or will they always require manual configuration? Not sure it makes sense to handle those in the same way as network devices anyway though.

**Comment by balloob** [comment]
Probably. Integrations should be able to specify vendor IDs and we can use that for discovery. But now we're talking like 1000 years in the future 😉

**Comment by tboyce021** [comment]
That's fair enough.  I must have been tired when I originally read through #121 because this also sounds like the equivalent of the "button" I was proposing here:

> A user can have the option to do an "extended" discovery that will include all integrations with custom discovery

We can probably close this since it's based on a different (incorrect) idea of how the discovery would work. I think these ideas from here and #121 cover the things I was going for but still allow discovering some things automatically:

- Only lightweight discovery protocols run continuously/periodically
- Custom or intensive discovery methods only run during the config flow for that integration (and potentially a few other (TBD) cases, e.g. onboarding, after major updates, etc.)
- A user can have the option to do an "extended" discovery that will include all integrations with custom discovery
- Ability to "permanently" dismiss a notification for a discovered device but provide a method to discover it again later

There are some ideas here that could still be considered, e.g. an option to disable even running the lightweight protocols continuously, expose the "extended" discovery via a service call so people can choose to run it periodically, etc. But those probably don't change the overall architecture and can just be feature requests.

Then just throw in another feature request for discovering USB devices in the future . Especially if it was able to keep track of them when they change paths in /dev and eliminate the need to write udev rules.

Sorry for all the noise on this. But at least I think I have a better understanding of the overall goal for discovery 😁

**Comment by MartinHjelmare** [comment]
This suggestion has mostly been solved and we have finalized our approach to discovery.

Discovery flows can now be ignored via the config entry unique id feature.

https://developers.home-assistant.io/docs/config_entries_config_flow_handler#unique-ids

For the currently available built-in discovery protocols (including USB) see the manifest docs:
https://developers.home-assistant.io/docs/creating_integration_manifest
