### ISSUE TITLE
Sunset api_password and legacy_api_password auth provider

### ISSUE THREAD

**Issue by awarecan** [home-assistant/architecture#175]
As our plan`http.api_password` will be removed in 0.90 release. User must use `legacy_api_password` auth provider to opt-in this feature.

We need plan how/when we remove the `legacy_api_password` authentication proivder.

My initial plan is
- let first migration from `http.api_password` to auth provider take two releases 
- .92 and .93 print out deprecated warning when user use api_password to authenticate (we already have that warning for a long time, but in INFO level, we need to change it to WARN level and give specific deprecated release number)
- .94 remove feature (same time with the trusted networks loop hole)

**Comment by balloob** [comment]
I was thinking of keeping the auth provider around for a while. Although insecure, if the user goes through the effort to configure it, why not let them have a single password as entrance?

**Comment by delneet** [comment]
I think this impacts certain NodeRed addons/integrations.
Just an FYI.

**Comment by balloob** [comment]
The most popular Node Red integration uses oauth tokens.

**Comment by Kane610** [comment]
Zeroconf references api_password https://github.com/home-assistant/home-assistant/blob/18149dcb8c2f23d4694c65f3d3dce52f36c34e02/homeassistant/components/zeroconf/__init__.py#L34

**Comment by pvizeli** [comment]
Hass.io was migrated a long time before to new auth system (before long life token was initialized) and have his own user. Any add-ons they use the Hass.io API proxy are not affected since a long time now.

**Comment by robbiet480** [comment]
Also needs to be removed from `/api/discovery_info`. Might be worth replacing that specific spot with a flag whether authentication is required or not (it would only be `false` if all auth was disabled _or_ trusted networks was enabled).

**Comment by balloob** [comment]
We do not support HA without auth.

**Comment by balloob** [comment]
Going to close this. I don't think it's necessary to sunset this auth provider. It's dumb to use, but the user should go out of their way to enable it.
