### ISSUE TITLE
Device automations

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#178]
I think that it's time we rethink our automation component. Our current automation component is built around core pieces of HA: events, services, MQTT messages. 

This requires a lot of user knowledge to get started with them.

I want to get to a world where we have an automation component that speaks the users language: devices. This new component will power two use cases (both covered by the same backend):

- Device configuration: User knows it has a remote, so if he wants something to happen when he presses the button.
 - Device automation: User has a motion detector, when motion is detected, it wants something to happen.

It will be impossible for Home Assistant to pre-define all possible triggers, so instead, we should put this on the integrations and entity components:

 - Given a device, find all entity registrations
 - For each entity registration, resolve the integration and the entity component
 - Ask entity component for possible triggers, conditions and actions for entity.
 - Ask integration for possible triggers, conditions and actions for entity

When a user configures one of those triggers, conditions or actions, we will ask the integration to do the work too. The integration can internally use our event/state/condition helpers to do the work.

## Constraints

 - It depends on devices, so it requires integrations to have config entries
 - YAML configuration will be tricky, as both device IDs and identifiers for integration trigger/condition/action will need to be found by the user.

**Comment by MartinHjelmare** [comment]
It looks like it's only the first layer that depends on the device. The rest of the layers use the entity. So then we could possibly make the first layer (interface) optional, and allow interfacing with the second layer directly. The use case would be to be more YAML friendly.

A general point about YAML config, is that the group that likes that, probably has a great overlap with the group that likes command like tools, like home assistant CLI. That tool could help with bridging between entity and device ids.

**Comment by Kane610** [comment]
For this example of a remote device we need to be able to create a relation between a device and an event for triggering of automations

**Comment by emontnemery** [comment]
I think this is a really good idea, maybe particularly so for remote controls / buttons.

In this list:
- Ask entity component for possible triggers, conditions and actions for entity.
- Ask integration for possible triggers, conditions and actions for entity

Isn't there a third case, for example for remote controls which are not entities:
- Ask _device_ for possible triggers, conditions and actions for entity

Also, could an MVP be limited to:
- Ask device for possible triggers

I'm imaging MQTT as a suitable candidate for an MVP..

**Comment by balloob** [comment]
If each integration that offers a remote control registers a device, we could have integrations add the following methods:

```
async def async_get_device_automation_triggers(hass, device):

async def async_get_device_automation_conditions(hass, device):

async def async_get_device_automation_actions(hass, device):
```

For MVP, I would suggest we start with just triggers, and have it call existing scripts.

**Comment by Jc2k** [comment]
Could we have some built in triggers for entities with well defined states like light, climate, etc. This could be quite handy for devices with their own physical controls (thermostats, window openers, etc) and for sensors/binary sensors? A lot of entities could get support for this without any changes. More advanced integrations like MQTT etc could define custom triggers.

For actions, would quite like to be able to reuse the more-info ui widgetry to set target states for entities inline - kind of like inline scenes - more than a UI for calling functions (services). With option to run a script if you need to do something a bit more advanced.

**Comment by balloob** [comment]
For people interested in this, @emontnemery has been hacking at an MVP for this: https://github.com/home-assistant/home-assistant/pull/24044

**Comment by balloob** [comment]
This has been released.
