### ISSUE TITLE
Integration manifests

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#179]
Glossary of terms:

 - Component: entrypoint/foundation for an integration in Home Assistant. Example: "Hue" and it's stored in `components/hue/__init__.py`
 - Platform: an extension of an integration for an entity component. Example: Hue's Light Platform is stored in `components/hue/light.py`.
 - Integration: all files related to integrating a service or product family into Home Assistant
 - domain: the identifier used to identify the integrations folder and data. Example: `hue`

----

So now that the great migration is over and all files are in their own folders, I want to propose that we introduce integration manifests. I suggest that we use JSON and that we start with just the information that we already have today stored in `manifest.json`: name, domain, requirements and dependencies. These values will replace the `REQUIREMENTS` and `DEPENDENCIES` constants in the integration. This will allow us to make sure that we install a requirement or load a dependency before importing a file and can start having imports at the top of a file 👍 

For things that we don't have today, but want to add to a manifest, please open a new issue for each individual value that we want to capture (ie zeroconf discovery, upnp discovery, min_ha_version, author, version, integration quality scale, manufacturer).

```json
{
  "name": "Philips Hue",
  "domain": "hue",
  "requirements": [
    "aiohue==1.9.1"
  ],
  "dependencies": []
}
```

There are also some things that I would want to track in the future, that we can autodetect. However, I don't want to run autodetect at runtime, instead I want to run it once and cache it, as it's static for built-in components (`has_tests`, `has_config_entry`). But let's leave that out of scope for this issue.

## Manifests MVP

 - Run a script to generate these once for all integrations and commit them to the repo
 - When about to set up a component, check manifest to get dependencies and requirements, fall back to `DEPENDENCIES` and `REQUIREMENTS` if none found in manifest.
 - Write a validator for CI that checks that all integrations in our repo have a manifest specifying name, domain, requirements and dependencies.

## Manifests, part deux

The fun starts!

 - Generate requirements files based on manifests instead of `script/gen_requirements_all.py`
 - Generate a file with integrations that have config flows automatically
 - Build an integration validator in the future, to check for things like:
    - if the domain == dirname
    - if the integration imports from other integrations that are not in its dependencies (not allowed)
 - Make it the source of truth where the website gets its metadata.

**Comment by rohankapoorcom** [comment]
Why json over yaml?

**Comment by awarecan** [comment]
Prefer json over yaml for all non-user facing files

**Comment by pvizeli** [comment]
Exactly. Json is for system generated and maintained files and yaml for user config.

**Comment by pvizeli** [comment]
I think the biggest challenge to offload packages as a store is the runtime binary. Mostly it's simple Python, but sometimes it needs also library and software on the host system.

**Comment by robbiet480** [comment]
I can handle the backend infrastructure of the directory, things like searching and analytics and such.

**Comment by dgomes** [comment]
Since the purpose of the manifest is to "automate" things, lets add a couple more items:
- author GitHub handle: CODEOWNER
- link to documentation: this used to be a comment in the header pointing to our repo, if it's a custom_component this needs to exist
- HA version the integration was built for: if we are splitting integrations from core repo, this will inevitably be needed.
