### ISSUE TITLE
Invalid characters in entity id are silently accepted, breaks service calls to that entity

### ISSUE THREAD

**Issue by BioSehnsucht** [home-assistant/architecture#183]
**Home Assistant release with the issue:**
0.68 (likely older releases too)

**Last working Home Assistant release (if known):**
Unknown

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Component/platform:**
New component/platform under development for Elk M1 automation / security system panel - but issue likely would affect any entity making the same mistake I did

**Description of problem:**
If you use invalid characters for `entity_id` such as uppercase letters, HASS may silently accept it without error, but service calls to the entity will never find it. I had forgotten to `.lower()` the entity id before assigning it and couldn't figure out why service calls wouldn't work - when I looked in HASS developer tools / entity states it appeared lower, so I didn't realize I had goofed right away.

Attempting to toggle switches / lights stopped working (originally was working, but made changes to how entity ids were created which lead to the problem of accidental uppercase), and as far as I can tell due to the entity id mismatch (lowercase in the frontend but truly mixed case in the backend) those service calls never found the entity. Once I finally realized I forgot to `.lower()` that solved the problem, but it really had me scratching my head for a while. While debugging this I even commented out my `turn_on` method expecting a `NotImplementedException` but that didn't happen... because the service call wasn't hitting the entity at all, not just failing to call my methods.

I would have expected some kind of error to be thrown, either an `Exception` regarding invalid entity id or at least something logged to warn you that invalid characters were used. Obviously this is the responsibility of the developer (in this case, myself) creating the component / platform to get this right, but if we don't, it would be nice if HASS would remind us. :)

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
N/A

**Traceback (if applicable):**
None

**Additional information:**
None

**Comment by frenck** [comment]
This is no longer an issue current day. 🎉
