### ISSUE TITLE
Add as_local_time method in template util

### ISSUE THREAD

**Issue by awarecan** [home-assistant/architecture#185]
Triggered by home-assistant/home-assistant#22659

Current templating don't have function to covert UTC time to local time.
See doc: https://www.home-assistant.io/docs/configuration/templating/#time

Propose adding `as_local_time()` and `as_utc_time()` helper method to covert datetime object to either UTC or local time in template

cc @akasma74

**Comment by akasma74** [comment]
Thanks @awarecan , that would be great and better than double-converting via timestamp ;)

**Comment by balloob** [comment]
If it's just for printing purposes, why not use `timestamp_custom` ? https://www.home-assistant.io/docs/configuration/templating/#time

**Comment by akasma74** [comment]
> If it's just for printing purposes, why not use `timestamp_custom` ? https://www.home-assistant.io/docs/configuration/templating/#time

just because I used it in the code below
```
{% set current_time = now() %}
{% set delta = current_time | as_timestamp - states.sensor.time.last_changed | as_timestamp %}
{% if delta < 60 %}
  it is now {{ now() }}
  last time the sensor was changed {{ delta }} seconds ago on {{ states.sensor.time.last_changed | timestamp_custom('%H:%M:%S on %d %b %Y', true) }}
{% endif %}
```

and the output wasn't right, do you know why?

> it is now 2019-04-03 07:16:14.754577+01:00
>   last time the sensor was changed 13.743921041488647 seconds ago on 2019-04-03 06:16:01.009964+00:00

**Comment by akasma74** [comment]
This code works as expected
```
{% set current_time = now() %}
{% set delta = current_time | as_timestamp - states.sensor.time.last_changed | as_timestamp %}
{% if delta < 60 %}
  it is now {{ now() }}
  last time the sensor was changed {{ delta }} seconds ago on {{ states.sensor.time.last_changed | as_timestamp | timestamp_custom('%H:%M:%S on %d %b %Y', true) }} 
{% endif %}
```

> it is now 2019-04-03 08:25:16.408879+01:00
>   last time the sensor was changed 15.398185014724731 seconds ago on 08:25:01 on 03 Apr 2019

but it requires that extra conversion to timestamp.

**Comment by akasma74** [comment]
isn't it because there is some difference in how restored/changed state is represented in HA?
something like it's by default datetime but after HA restart it's a string?

**Comment by balloob** [comment]
That last thing was a bug and has been fixed.

**Comment by a005** [comment]
I think using a timestamp in templates is anachronism. Date&time arithmetic should be as simple as it can be (and Python allows).
Time delta should be calculated in this manner (no TZ issue):
```
{% set current_time = now() %}
{% set delta = now() - states.sensor.time.last_changed  %}
{{ delta.seconds }}
```
But for printing purpose no elegant (in one step) solutions:
```
# documented way with timestamp
{{states.sensor.time | as_timestamp | timestamp_custom("%H:%M:%S on %d %b %Y") }}
# without timestamp
{{states.sensor.time.astimezone().strftime("%H:%M:%S on %d %b %Y") }}
# with as_local filter
{{(states.sensor.time | as_local).strftime("%H:%M:%S on %d %b %Y") }}
```
Is it possible to add filter datetime_custom(format_string, local_time=True) for datetime object not timestamp? This would reduce the template code and eliminate unnecessary conversions:
`{{states.sensor.time | datetime_custom("%H:%M:%S on %d %b %Y") }}`

**Comment by MartinHjelmare** [comment]
We now have a template function / filter `as_local`.

https://www.home-assistant.io/docs/configuration/templating/#time
