### ISSUE TITLE
Split built-in MQTT server to own integration

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#186]
The MQTT component currently contains a built-in MQTT server which can be loaded via the config. We should split this out into its own integration. Or maybe its time to remove it completely?

It has some memory leaks and it is no longer actively developed.

**Comment by robbiet480** [comment]
It's also broken already according to https://github.com/home-assistant/home-assistant/issues/18228

**Comment by emontnemery** [comment]
Given the warning against using the internal broker in the documentation, it's not clear what the benefit of using it are?

**Comment by rohankapoorcom** [comment]
Another vote for removing it completely.

**Comment by balloob** [comment]
Alright, let's remove it.

**Comment by fabaff** [comment]
According to the commit log is the development of HBMQTT still going on.

**Comment by emontnemery** [comment]
> Alright, let's remove it.

So, start with a deprecation warning, then remove a few releases from now?

**Comment by awarecan** [comment]
I voted to separate component.

That "not use" warning was referring to a two years old bug, can we first confirm if it still not fixed?

**Comment by pvizeli** [comment]
I vote for removing. It's not the job of home assistant to provide an MQTT server.

**Comment by emontnemery** [comment]
@awarecan I think a strong argument against keeping the embedded broker is that the flow for setting up a Mosquitto server with Hass.io is extremely simple and user friendly with the Mosquitto add-on.

What value does it add to Hass to maintain our own MQTT broker?

Btw, this is the memory leak issue beerfactory/hbmqtt#62, no progress in 2 years.

**Comment by awarecan** [comment]
Hassio is not our only user base.

The underly websocket lib used in hbmqtt is [websocket](https://github.com/aaugustin/websockets/releases), which released several version in these two years. Should we investigate whether the memory leak still the case before we make a decision?

**Comment by emontnemery** [comment]
> Hassio is not our only user base.

Sure, but even so, what value does an embedded MQTT broker bring?
Is it an obstacle for non-Hassio user to setup Mosquitto or any other MQTT broker?

> Should we investigate whether the memory leak still the case

Maybe, but there seems to other issues related to the embedded broker that are not receiving enough / timely attention.

**Comment by pvizeli** [comment]
For a user with no knowledge, we suggest using a Home Automation Hub like Hass.io

Otherwise, they are fit to install an MQTT broker on his system. We should not solve stuff on Home Assistant they are ident to be a System problem.

So if you are busy and have no time to maintain your local system, feel free to use Hass.io. The hbmqtt is nothing they we should try to maintain by side of the wide used mosquito broker. We should focus our time more in our problems like ozw or other stuff they need real love.

**Comment by dgomes** [comment]
How about running a poll on #homeassistant discord channel ;) ?

**Comment by robbiet480** [comment]
I'd suggest that if we did want to poll, we do it on the forums, since they have a poll plugin that will automatically track results and ensure everyone only votes once.

**Comment by emontnemery** [comment]
The built-in MQTT server is marked as deprecated in Hass 0.92, can this issue be closed now or we wait for user feedback?

**Comment by balloob** [comment]
We already marked it as deprecated, I think that concludes this. I think the next step would be a PR to avoid having it set up automatically if no MQTT config is passed in.
