### ISSUE TITLE
Dependency in manifest

### ISSUE THREAD

**Issue by awarecan** [home-assistant/architecture#187]
Currently, the `dependencies` field in `manifest.json` are missing the `DEPENDENCIES` defined in the "platform" file.

For example, DEPENDENCIES in `automation/__init__.py` only has `group`. However, `automation/webhook.py` depends on `webhook` component which have not been extracted to `manifest.json`

**Solution 1**: simply add all dependencies to manifest in current format
Pros: simple
Cons: all dependencies component will be loaded, even it will only be used in a platform may not be configured by user 

**Solution 2**: change `dependencies` field define to following format
Pros: good performance, only load dependency when it is necessary
Cons: complex format

Schema 2.1:
```json
{
  "domain": "automation",
  "dependencies": {
    "_": ["group"],
    "webhook": ["webhook"]
  }
}
```
Schema 2.2:
```json
{
  "domain": "automation",
  "dependencies": [
    "group",
    {"webhook": ["webhook"]}
  ]
}
```

Any other suggestion?

**Comment by rohankapoorcom** [comment]
I share the same concerns about both approaches, but I think for performance (not loading too many unneeded components), we should use Solution 2. I like schema 2.2 better because it's more explicit.

**Comment by balloob** [comment]
This is only a problem for the automation component. I don't think that manifests should solve it. Instead, automation integration should not use platforms.

**Comment by awarecan** [comment]
When I created the issue, I thought it may affect more component, but so far, automation is the only component discovered. Some single file platforms may have same issue but changes are easy to justify. 

I already fixed html5 notify, two ffmpeg sensor (they should be merged to ffmpeg component actually), and one device tracker platform.

@balloob how do you think we correct automation component for now? Just add webhook in?

**Comment by balloob** [comment]
yeah, let's add webhook

**Comment by balloob** [comment]
There are 3 integrations with bad platforms:

https://github.com/home-assistant/home-assistant/blob/7a33dc5cec0fe864c0857c570c89cbfbb6502401/homeassistant/loader.py#L40

**Comment by awarecan** [comment]
Should I close it as we have `after_dependencies` now

**Comment by balloob** [comment]
yes
