### ISSUE TITLE
Add code_arm_required to alarm_control_panel base

### ISSUE THREAD

**Issue by JumpMaster** [home-assistant/architecture#189]
The addition of code_arm_required to the mqtt alarm allows the system to be armed without a code been entered.  There is also a feature request on the forum to add this to manual alarm and manual mqtt alarm.

The more-info-alarm_control_panel only enables the arm buttons once a single character is entered in the code field.  If a user has code_arm_required set to false the arm buttons should not be disabled.

To make code_arm_required visible to the front end it needs to be added to the state_attr within the base object.

I have made this change in PR [22641](https://github.com/home-assistant/home-assistant/pull/22641) with a default return value of true so the default behavior is retained.  Objects that inherit from alarm_control_panel can override this behavior if they implement code_arm_required.

I have also implemented this change in PR [22618](https://github.com/home-assistant/home-assistant/pull/22618) and have included the front end fix in PR [3052](https://github.com/home-assistant/home-assistant-polymer/pull/3052)

Thanks,
Kev

**Comment by balloob** [comment]
This makes sense.
