### ISSUE TITLE
Template function to expand groups

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#193]
There's currently no simple way to iterate over group members in a template.

I propose a `expand` method for the template system to do this, so the following would work:

```
{% for entity in expand('group.downstairs') %}
  {{ entity.state }}
{% endfor %}
```

as would:

```
{{ expand(entities.group.downstairs,'light.stairwell')|join(',', attribute='state') }}
```

and:

```
{{ expand(['group.downstairs',states.light
  'group.upstairs','switch.kitchen'])|join(',', attribute='state') }}
```

Also we'd fix the `closest` function so the final argument has an implicit expand over an iterable, so:

```
{{ closest(['person.penny','person.kerensa']) }}
```

would work properly (it doesn't currently, it has to be a group, string, states, or states.domain, iterables aren't accepted).

**Comment by balloob** [comment]
Seems reasonable. It will be just a wrapper using `expand_entity_ids` from the group component.

**Comment by Swamp-Ig** [comment]
Basically yep
