### ISSUE TITLE
Pass scan_interval to EntityComponent._async_setup_platform via discovery_info

### ISSUE THREAD

**Issue by pnbruckner** [home-assistant/architecture#194]
When an integration sets up one of its platforms via `homeassistant.helpers.discovery.load_platform` it would be nice to be able to pass `scan_interval` via the `discovery_info` parameter.

As things are currently implemented, at least as far as I can determine, the only way to control a platform's `scan_interval` is either via [`homeassistant.helpers.EntityComponent._async_setup_platform`](https://github.com/home-assistant/home-assistant/blob/02347df1405f74232d7b094d81d38e0123357b22/homeassistant/helpers/entity_component.py#L196-L217)'s `platform_config` parameter (which doesn't apply when using `discovery.load_platform`), or via the platform module's `SCAN_INTERVAL` attribute (which is a fixed value.)

If `EntityComponent._async_setup_platform` was enhanced it would be possible to pass `scan_interval` via `discovery_info`. E.g., if [these current lines](https://github.com/home-assistant/home-assistant/blob/02347df1405f74232d7b094d81d38e0123357b22/homeassistant/helpers/entity_component.py#L205-L207):
```python
        # Use config scan interval, fallback to platform if none set
        scan_interval = platform_config.get(
            CONF_SCAN_INTERVAL, getattr(platform, 'SCAN_INTERVAL', None))
```
where changed to the following:
```python
        # Use config or discovery_info scan interval,
        # fallback to platform if none set
        try:
            disc_scan_interval = discovery_info[CONF_SCAN_INTERVAL]
        except (TypeError, KeyError):
            disc_scan_interval = None
        scan_interval = platform_config.get(
            CONF_SCAN_INTERVAL,
            disc_scan_interval or getattr(platform, 'SCAN_INTERVAL', None))
```
then it would be possible.

An example of where this would be used is in the current `amcrest` component. It supports a `scan_interval` configuration variable, but it is effectively ignored. But with the change above, it could be passed to the call to `discovery.load_platform` for its `sensor` platform (and for its new `binary_sensor` platform which has been submitted. In fact, I'd probably want to change the configuration so that each sensor type can have its `scan_interval` set independently.)

When looking at other existing code to see how others have dealt with this issue I mostly found the use of throttling. The problem with that technique is threefold:

1. The effective polling period cannot be very precisely controlled, because it basically has to be a multiple of the platform's `SCAN_INTERVAL` attribute.
1. The throttling code is being called more often than necessary (since often it will just return without calling update.)
1. Throttling plays havoc with the new `homeassistant.update_entity` service, because there's no way for the throttling code to know (at least not that I could find) if it was called via the usual period invocation, or from a service call.

Lastly, I'm still pretty new to HA, so if there's a different way to deal with this issue that already exists, by all means, I'd love to be pointed in the right direction (and, of course, feel free to close this issue.)

Thanks!

**Comment by pnbruckner** [comment]
Should I just propose this change in a PR? (I.e., is this the wrong place to discuss this?)

**Comment by balloob** [comment]
We should not do this. That type of discovery is going away in favor of forwarding config entries. Scan interval is no longer a supported feature.
