### ISSUE TITLE
How to deal with soft dependencies

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#196]
There are some components that _might_ use an integration, but not always.

Examples are MySensors and OwnTracks, which can both rely on MQTT.

We should introduce a new "soft" dependency, where during startup we will make sure that the integration exists, and if it is being set up as part of something else, we wait for it to finish.

With https://github.com/home-assistant/home-assistant/pull/23037 I introduced our new manifest validator: `hassfest`. It will check for usage of `hass.components.X` and makes sure that the referenced integrations are mentioned in the dependencies.

Besides MQTT, there is also another use case, the make something available when loaded case. For example, shopping list registers sentences with the conversation component and adds a websocket API command. However, these two things should only be exposed when the user chooses to load websocket or conversation integration, merely registering something with it should not cause it to load.

**Comment by awarecan** [comment]
`requirements`
`dependencies`
`uses`

**Comment by balloob** [comment]
The problem with `uses` is that now it will be up to the integration that interacts with an integration to decide how to load it. That seems weird, and should be something that should be allowed by an integration? Maybe we need a `allow_use_without_setup` ? 

Current integrations that will be eligible for `use` list:
 - websocket_api (register WS commands)
 - conversation (register sentences)
 - frontend (register panels)
 - cloud (is_subscribed)

**Comment by ties** [comment]
If I read this correctly the semantics that you want are similar to the ones of [After=](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before) in systemd: 

> They configure ordering dependencies between units. If a unit foo.service
> contains a setting Before=bar.service and both units are being started,
> bar.service's start-up is delayed until foo.service has finished starting up.

Implementation is straight forward; Instead of loading components just in time when they are encountered,  with the manifests it is easy (would have been possible with regexes like hassfest does) to create the dependency tree [without loading components] and create an ordering for loading that accounts for these constraints.

**Comment by balloob** [comment]
Ah, yes, "after" is perfect. That will solve the optional MQTT dependency. Let's call it "after_dependencies".

**Comment by ties** [comment]
And the semantics of the term "after" are relatively clear – which is a bonus. The current approach is a local improvement and a good MVP.

However I realised that this could create an edge case in the following (hypothetical) situation:
  * A component with `after_dependencies` is loaded, it's dependencies are missing
  * Through discovery, a component is loaded that loads one of the `after_dependencies`.
  * result: situation is inconsistent

It feels like 'restarting' the integration is the logical solution but I'm not familiar enough with the lifecycle of integrations to be sure if they can just be re-started.

Possibly, a  similar situation could exist if an integration dependant on such a dependency is loaded after the integration that has it as an `after_dependency` is loaded.

Note that this is a hypothetical situation (which probably was obvious if you're very familiar with the code) and currently there are no (indirect) integrations depending `mqtt` that appear to be candidates for discovery. 

If wanted I have a branch that adds code that analyses the dependency graph to `hassfest` (in https://github.com/ties/home-assistant/commit/4b3be38ff434dc4b007107a4e2e267ddf49e0e7b) that that allows users to search for integrations 'indirectly or directly depending on' another integration.

**Comment by balloob** [comment]
Right. Integrations, even when specifying `after`, should still use `async_when_setup` (from `homeassistant.setup`) to make sure the integration is available, because they can also be launched without it being available.
