### ISSUE TITLE
Add device class to switch component to represent outlets

### ISSUE THREAD

**Issue by elupus** [home-assistant/architecture#197]
Google has the device type Outlet to indicate a smart outlet which is separate from a switch type. This is something home assistant have no domain for.

I don't think it make sense to add a new domain for it since they behave identically to switches in almost all regards. Only really differs in appearance and possibly spoken intents.

I propose to add device_class to the switch component to represent outlets as in: https://github.com/home-assistant/home-assistant/pull/23149

**Comment by balloob** [comment]
Sounds good 👍

**Comment by balloob** [comment]
added in https://github.com/home-assistant/home-assistant/pull/23149
