### ISSUE TITLE
Manifest.json: support zeroconf discovery

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#198]
This is a proposal to add manifest-based zeroconf discovery of integrations.

Zeroconf discovery is based around service types, example types are:

- `_esphomelib._tcp.local.`
- `_googlecast._tcp.local.`

## Manifest.json

In the manifest we define a list of zeroconf types that should trigger this integration. Example:

```json5
{
  // …
  "zeroconf": ["_googlecast._tcp.local."],
}
```

## Doing the zeroconf discovery

The zeroconf integration will have to be updated to do the discovery. It should use [`aiozeroconf`](https://github.com/frawau/aiozeroconf) to run the discovery, and when something is found on the network, load the config flow of the appropriate integration.

The discovery integration will have to be updated to ignore config entry based zeroconf discoveries.

## Gathering all the discoverable integrations

We will update `hassfest` to go through all integrations and create a file with a JSON file containing `type: domain[]`.

For beyond MVP: For custom components, on startup the zeroconf integration (responsible for discovering these integrations), will load all manifests of all custom integrations and fetch their zeroconf types.

## Integrations handling discovered info

We will use config entries for this. We already do this successfully for the discovery integration, and we can do this for this too. To deal with it, a config flow will have to add a step called `zeroconf`.

This will also make it possible for config flows to decline discovered devices when device is already set up or if it can't handle the type. The latter is especially important because there are a bunch of services/devices that are listening for `_http.local.` type 🙄 

Side note on this: right now we always set up the requirements before we load any step of the config flow. We should consider having it be up to the integration when to install requirements. Downside is that then we can't load config flow because we can't load the file. This topic will need to be discussed in a new architecture issue.

## Final note

This approach will also be used for upnp/ssdp discovery. Once both zeroconf and ssdp implemented, we will retire `discovery` and `netdisco`.

**Comment by Kane610** [comment]
I'd be happy to take on this when given time for feedback

**Comment by balloob** [comment]
There are currently 4 zeroconf integrations that all respond to `_http._tcp.local.`: https://github.com/home-assistant/netdisco/search?q=_http._tcp.local.&unscoped_q=_http._tcp.local.

They are further filtered out by the name. I don't think that we should try to capture this in the manifest, instead we should handle this inside the config flow handler of each integration.

We should pass the following data as input to the zeroconf step: https://github.com/home-assistant/netdisco/blob/da1bda146b4762bc572cb28da30cfb09b1d083aa/netdisco/discoverables/__init__.py#L115-L134

**Comment by Kane610** [comment]
For the discovered config entry would it be possible for each integration to affect naming in some way as to easier identify which integration is what; e.g. device model and host address

**Comment by Jc2k** [comment]
We just added support for `title_placeholders` so you can tell which integration is which in the "Discovered" part of the integrations panel. See [here](https://github.com/home-assistant/home-assistant-polymer/pull/3106). If the config flow knows how to pull out more detail in its `async_step_discovery` you can surface it it to the user through placeholders in your localisation strings like this:

![56458793-0529c580-6383-11e9-9640-8a9ff06fd598](https://user-images.githubusercontent.com/11544/56751678-8f589c00-677e-11e9-9307-55bfcec047a5.png)

Corresponding server side change for homekit_controller [here](https://github.com/home-assistant/home-assistant/pull/23311).

**Comment by Kane610** [comment]
That's really awesome!

**Comment by Kane610** [comment]
Ok to get started on this?

**Comment by balloob** [comment]
Yes
