### ISSUE TITLE
Hass life-cycle marker interface and implementation.

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#199]
For consideration:

It would be useful if the hass lifecycle methods were propagated to fields within an entity on registration, those being setting the `hass` reference, and the methods:

```python
class HassLifecycleField:
    def __init__(self):
        self.hass = None

    async def async_added_to_hass(self, parent:Entity, field_name:List[str]) -> None:
        """Run when entity about to be added to hass."""

    async def async_will_remove_from_hass(self) -> None:
        """Run when entity will be removed from hass."""
```

How this would work would be when `async_add_entities` was called from `setup_platform`, the code would do an iteration through though the `__dict__` of the passed entity (depth first search through subfields of marked objects, and collections too), and:
1. Call `field.hass = hass` on each one until all done.
2. Then call `async_added_to_hass` with parent as the entity, and field_name as the path to the object from the entity.

The code would also call `async_remove_from_hass` in the same order when the parent entity is removed.

### Why this is useful

Setting hass on templates. There's a whole lot of `_blah_template.hass = hass` in the code. I'm sure there's other stuff like this that just needs the hass object set.

What really motivated this for me however would be that I'd like to have an class that encapsulates all the details of tracking a template, including adding the listener for state changes that affect the template, storing the results, marking the state as needing an update, verifying results, and removing the listener when the containing entity is shut down. Without allowing entity fields to have their own hass lifecycle, you are dependent on every class doing this stuff to do it all in their own lifecycle methods, and do it correctly. This is a bit messy. 

This would save on a bunch of potentially error prone boilerplate code involved in propogating the hass object to fields in the entity.

I considered subclassing Entity to add this behaviour, but it's probably more general-purpose useful in any case. I will be subclassing anyhow, just thought it was worthy of consideration.

**Comment by balloob** [comment]
I'm personally not a fan of magic like this. It's difficult for developers reading the code to see what's going on, and the changes are low that developers writing template related code (which is not added too often) are aware of it.

**Comment by Swamp-Ig** [comment]
Yeh, I was a bit edgy about it too. I thought I'd suggest because I can see there's value outside of just templates, but will close anyhow.
