### ISSUE TITLE
Introducing the home-assistant/architecture repo

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#2]
From time to time we have architectural discussions in the chat. However, these conversations are easily lost nor are any followed up. This repo will help with organizing these discussions. Feel free to start new topics or join existing discussions.

CC @home-assistant/developers

**Comment by tinloaf** [comment]
Should discussion happen in Issues, or should we write up a short description of what we propose (e.g., as a Markdown file) and create a PR as basis for the discussion?

I think the latter would have the advantage that over time, the documentation in the files in this repo can also serve as a knowledge base for developers.

**Comment by balloob** [comment]
Any knowledge should end up on the developer website. This should just be for discussion. For bigger topics, like [UI schema](https://github.com/home-assistant/ui-schema/issues), I can create a new repo.
