### ISSUE TITLE
Use plant database to get values for plant config options

### ISSUE THREAD

**Issue by isabellaalstrom** [home-assistant/architecture#200]
Someone have recently managed to reverse engineer the api for getting plant information from the database that the official MiFlora app uses. This would greatly improve the plant sensor in hass, if we somehow could use this information to autogenerate values for the options of max and min moisture etc.

I just have no idea of how to best do this (or if it would be legal to use this?).

One thought I had was if plant sensor would have a gui based configuration (is that what's called the config flow?) and have some kind of searchable drop down list of the plants, but I don't know if that would be alright or the best way. Help and thoughts needed!

Links:
[Discussion on forums](https://community.home-assistant.io/t/miflora-sensor-plant-database/53131/17)
[Git repo for db](https://github.com/khronimo/MiFloraDB)

**Comment by iantrich** [comment]
I would start with being able to look up min/max values based on a plant id. A config flow with querying of the different plants types could be done later.

**Comment by balloob** [comment]
I would not want to add 5MB to Home Assistant just as a plant database. Preferably someone hosts it somewhere in the cloud, and data can be fetched and displayed locally.

**Comment by iantrich** [comment]
It's already in that github repo. A python lib wrapper to access that should be enough, right?

**Comment by michaelarnauts** [comment]
Why not use the API that has been found to query it there? https://community.home-assistant.io/t/miflora-sensor-plant-database/53131/13

Github isn't that keen on using their servers as storage.

**Comment by isabellaalstrom** [comment]
So @iantrich are you saying a first step would be to expose the db in a user friendly way, to be able to maybe link it in the component docs and so that the user can look up their plant there and manually add values based on that?
Any thought of the legality of "ripping" their db like this? Can it cause problems?

**Comment by isabellaalstrom** [comment]
I have also saved this data locally (as json) as to not have it disappearing if the repo gets taken down.

**Comment by iantrich** [comment]
I think @michaelarnauts has the right idea

**Comment by fabaff** [comment]
After the Swiss Federal Office for the Environment (FOEN) limited the access to the available data, a guy started to [host](https://swisshydroapi.bouni.de/) the information which we now are using for the `swiss_hydrological_data` sensor.

**Comment by raccettura** [comment]
I'd want to point out potential copyright issues here.  While "data" itself can't be copyrighted in most countries it seems a lot of this isn't really data but descriptions and suggestions for potential min/max water levels which might not really qualify as "data" but rather as advice or a suggestion. 

Keeping the sources used to compile this data tracked and  ensuring only appropriately licensed data is used will be important regardless of where it's hosted. Scraping off commercial API's might be problematic.

**Comment by balloob** [comment]
Good point.

This is out of scope for HA. If someone has an API, it can be integrated.
