### ISSUE TITLE
Manifest.json: Add config_flow key

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#201]
Proposal to add an optional `config_flow` key to `manifest.json`: true or false. This way we will be able to automatically generate the list of integrations that support config flows, in the future allowing custom integrations to provide config flows too.

Also suggestion to have the config flow be defined in a file named `config_flow.py`. Right now we have to import the component of an integration (`__init__.py`) and expect a decorated class to be defined, which adds the class to `HANDLERS` registry in `config entries`. This has the downside that we are not able to import requirements at the top of the file, unless we want to install all dependencies and requirements before. This is something that we want to move away from.

So here is proposal:

## Step 1

- Add `config_flow: boolean` to `manifest.json`
- Update `hassfest` to automatically generate a JSON file with all integrations that have a config flow
- Update handler loading in `ConfigEntries._async_create_flow` and `components.config.config.entries.ConfigManagerAvailableFlowView` to use the JSON file

## Step 2

- Move config flows to `config_flow.py`. Loading the config flow file should not load any requirements.
- Update `hassfest` to validate that if a manifest has `config_flow: true`, there is a file `config_flow.py` (and maybe also that we can import it, on CircleCI we hace no requirements installed)

## Future

- Scan custom component folder for integrations that are able to be set up

**Comment by awarecan** [comment]
You beat me. I have thought about it, just too tired to write it down.

Move to `config_flow.py` is a good idea.

**Comment by pvizeli** [comment]
I like that

**Comment by Swamp-Ig** [comment]
Just thinking: rather than just a boolean, would it be worth having a key into a localisation file that gives the name of the flow / integration?

That way no code needs to load, potentially saving on having to load dependencies, just display the (localised) name in the integrations config screen, and only load the code if it gets clicked on.

You could have a boolean flag for integrations that do discovery.

**Comment by balloob** [comment]
I guess we already have the name in the manifest that we could use for this? And for discovery, it will actually load the config flow and translations, and allow the config flow to customize the title.

**Comment by Swamp-Ig** [comment]
@balloob makes sense. 

The issues AFAICS are: 

#### I18n

The name potentially needs to get localised, or at least have potential to get localised. The manifest has a pre-localised name in English only. Should we spec the manifest file to use localisable strings for the integration name? This does have a downside however in that it makes it hard to just read the manifest file and  figure out what it's all about. One alternative is to have an optional localisable string that keys into a side file with translations in it in there as well, which has it's upsides for sure although it does mean potentially downloading another text file. Another option is to have the set of localised names in the manifest itself:

```json
{
  "domain": "acer_projector",
  "name": {
      "en": "Acer projector",
      "es": "Proyector Acer"
  },
  "documentation": "https://www.home-assistant.io/components/acer_projector",
  "requirements": [
    "pyserial==3.1.1"
  ],
  "dependencies": [],
  "codeowners": []
}
```

In the longer run you'd probably want to consider putting a description into the manifest file too, so again having multiple languages already in the file does make some sense. Then there's only one file to download from a repository, which is useful particularly when you consider the following:

#### Loading requirements

You probably don't want to download/install/load requirements for integrations that don't have a discovery process and only start their config flow process manually. Particularly as (presumably) we're going to use the same mechanism to install custom integrations when users pick them out and just download the manifest file from some repository when offering up stuff to install, before going the whole hog and installing it. Given this it's nice to know if we actually need to load any code to run discovery.

**Comment by awarecan** [comment]
Regarding localization part, the correct way to do that is
```json
// manifest.json
{
  "domain": "acer_projector",
  "name": "Acer projector",
  "description": "Bla bla Acer projector",
  "documentation": "https://www.home-assistant.io/components/acer_projector",
  "requirements": [
    "pyserial==3.1.1"
  ],
  "dependencies": [],
  "codeowners": []
}
```
```json
// manifest.es.json
{
  "name": "Proyector Acer",
  "description": "Proyector Acer bla bla"
}
```

**Comment by Swamp-Ig** [comment]
Agreed, however that has the downside of having to (potentially) download two files. It's not that big of a deal though.

**Comment by MartinHjelmare** [comment]
How many names need to support localization? Brand names should not be localized and those are the majority.

**Comment by Swamp-Ig** [comment]
Very few no doubt, but It's easier to get it right from the start than patch it up later, and so just thought it was worth considering. The example was literally the first one I came across when scanning down alphabetically, and that's one that needs translation. Descriptions would OTOH mostly all need translating. 

@awarecan is no doubt doing it right anyhow and having a separate file. Maybe plus a flag for discoverable components too so only those get installed initially while the other ones are more install on demand. 

I imagine the end result is to have a component repository, and automatically maintain an archive of all the manifests and then download them as a batch to offer up for installation (or upgrade). You could also batch up the translation files as well and only download the ones you need, in which case having them separate makes more sense.

**Comment by balloob** [comment]
I think that we should not have localization as part of the `config_flow` key. We should discuss adding localization of the name in the manifest in a new issue.

**Comment by awarecan** [comment]
I suggest tag it to 1.0 milestone

**Comment by balloob** [comment]
Done @awarecan, in that case let's do the same for my discovery proposal at #198
