### ISSUE TITLE
Add automation/script condition to check security level

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#203]
Currently when the user triggers an automation to run, say by turning on a script, the user that caused the event is used in the security context for the automation.

This means that whatever the automation does, such as make [service calls](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/script.py#L299) the user that triggered the automation to run will be passed through for any security checks.

The issue with this is that if there's potentially a security restriction on those service calls, and therefore the automation can fail to perform some of its actions but not others, and this will fail silently without any feedback to the user.

The complex way to fix this issue would be to check through the security attributes of any service calls that the automation might make before triggering it to run and either run the script atomically, or fail. This is very difficult to arrange however since services can do internal security checks at runtime, and the services themselves can be templated.

The simplest solution would be to add a security check condition to the automation. This condition can be put in at the start of the script, and if it fails then the script exits without logging errors. If a security check fails otherwise this will get logged and it's the responsibility of the script writer / admin to manage this.

Anyhow, probably not very high priority but I've logged it here for now.

**Comment by balloob** [comment]
I think that an initial step could be that we add an automation condition or a script check that verifies the user/group that triggered an automation / script.

**Comment by Swamp-Ig** [comment]
Already happens with the service call doesn't it?

**Comment by balloob** [comment]
Well I meant as a condition to stop execution. 

So I can create an automation that only triggers when I turn on a light.

**Comment by Swamp-Ig** [comment]
Yeh, that's what I was talking about basically:

```
blah_script:
  sequence:
  - condition: security
    allow_users: penny
    allow_groups:
      - admin
      - custom
    deny_groups: kids
  - service: cover.open_cover
    data:
      entity_id: cover.garage_door
```

**Comment by balloob** [comment]
Well, for scripts it won't be needed. As scripts are entities, and so they are covered by the entity policy with read, control, edit.

**Comment by Swamp-Ig** [comment]
As in you can control access to individual scripts? Then it's done for scripts.

It looks to me like what we need to do is to [put a check right here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/automation/__init__.py#L376) that the passed context is valid to call the automation's entity.

Then you don't need a condition, the automation itself can be secured directly. Does that seem right to you?

The only other issue is that you might want to run an automation (and probably scripts too) as another user, rather than the triggering user. 

Maybe something like:

```
automation:
  - id: my_automation
    run_as:  user-or-group
    trigger: ...
```

**Comment by balloob** [comment]
Automations run as root.

**Comment by Swamp-Ig** [comment]
I don't think that's true. [Here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/script.py#L299) for example, the service call is made in the context of the triggering event's context. You can follow this back through the line linked above and the automation triggers.

**Comment by balloob** [comment]
Correct, scripts run within a context and that context is always the same for all calls resulting inside a script. 

Automations will create a new context that refers to the triggering context, so that they run as root:

https://github.com/home-assistant/home-assistant/blob/407e0c58f90a4d972ed98bd608255f9f70c4da42/homeassistant/components/automation/__init__.py#L283-L285

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
