### ISSUE TITLE
Migrate zone set up from config flow to WS API

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#204]
Right now we set up zones via a config flow. That seemed like a good idea at the time but I am here now proposing moving it to having its own websocket API.

We should limit config flows to integrations that interact with services/devices. Things like a zone should be handled in it's own part of the configuration panel. During creation we can show a live display of the zone using maps etc.

**Comment by Kane610** [comment]
I agree, the config flow implementation is flawed and zones shouldn't be shoehorned into it. It was right for the time, but it needs to evolve.

**Comment by balloob** [comment]
As a guideline, I think that we should adopt: use a config flow if you need to configure an external service or device.

**Comment by Kane610** [comment]
Yes, this is a different kind of integration and shouldn't be grouped with 3rd party implementations
