### ISSUE TITLE
Template component: self_id variable

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#207]
When rendering templates for the template entities, it could be useful to be able to access the entity's ID. This would be useful for example in the icon template:

```
'icon_template': 
  "{% if is_state(self_id, 'open') %}mdi:garage_open{% endif %}"
```

This is very simple to implement, it would need documentation however.

There's obvious concerned regarding self-reference and continuous updating, however this is less of an issue because:

* Template entities only trigger state update messages when they actually change value
* If update throttling is implemented like in #206, then the value can only flip-flop periodically instead of in an quick and endless loop
* There's nothing stopping this happening already, it's just a convenience utility
* There's the potential to catch and flag this as an error if it's an actual problem

**Comment by balloob** [comment]
Sounds good. 

I guess reading your own state from the state machine feels a bit weird. However, any alternative I can think of requires the users to learn new objects, just for a faster case, in which case they will probably not end up using it.

**Comment by Swamp-Ig** [comment]
It was the easiest solution I could think of. The good thing about using the ID too is that it's stable and it doesn't change. ...unless it does in a rename, but in that situation the template will just get re-registered with the new ID anyhow so it's still all fine :grin:

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
