### ISSUE TITLE
Template component: Dynamic entity IDs in templates

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#208]
**Home Assistant release with the issue:**
0.90

### Description of problem:
Currently entities using scripts use a regexp to figure out the entities touched by the script. This approach is used in multiple locations in the template component, but also in other places. The goal of the regexp is to ensure that all templates don't need to be recalculated for every state change in the system, but only for state changes of interested entities, so basically it's a performance optimisation.

The regexp approach however is quite limited, it both over-constrains and under-constrains the entity list depending on the provided template. 

If the script generates entity IDs dynamically, then the regexp will fail and over-constrain the listening set. It won't pick up that the entity is referenced by the script, and it will fail silently. It can only extract an entity ID if it actually exists in the script, if that entity is computed rather than just specified then the regexp approach can't possibly work. The only way to know this has happened practically is to watch the output and notice that it's not changing.

If a script searches for some entities by entity_id and then only watches some of them, then the regexp approach will under-constrain the entity list. This is particularly bad when using iterators, the regexp will generate a watch list of all entities, and so the script gets regenerated for every state change in the system. While this isn't a failure, it's using resources ineffectively.

The partially implemented solution for over-constraint failures is to have a list of entity IDs specified next to the template that replaces the list produced by the regexp. The problem with this is that the entity ID list has to be kept up to date, if there's any spelling mistakes in the entity ID list the entity list approach fails, and also it's a priori impossible to produce an accurate entity list for many templates. The same side-definition of entity IDs has to happen in every place where templated attributes exist, which is in 25 or so places by my count.

The entity_id list has to cover all the templates for a particular entity too, including the templates for the icon and picture. This means potentially multiple templates will need updating if any entity that any of them observes change. This is clearly an under-constraint issue.

In summary: the regexp approach doesn't work, and it can't be improved to make it work in a general sense.

#### The improved algorithm

To solve this issue, we need to do some dynamic programming.

As the template is computed, it looks up various states to produce its result. It can be clearly seen that a template result can only change if the states that it actually reference change. So, as we're computing the template, we keep track of any states that have been referenced by the template, and add them to a list. When one of the states in the list change, we recompute the template collecting the used states again and see if its output has changed. We then re-use the new list for the next re-computation.

If any of these re-computations result in an output change, this is then handed back to the template listener.

##### Handling iterators

If the template contains an iterator, then we still need to watch any entities it touches. Additionally we also need to recalculate the template if an entity is added or removed from the system. The new code gracefully handles this situation, as long as just the entity ID is touched then the state isn't added to the state list.

#### Examples of scripts that won't work currently:

```
{{ states(states('input_select.watching')) }}
```

This template allows a user to select a state to display in an input select field. You could specify an entity_id list that matches the list available to the input select, but this would mean under-constraint because you'd have to list all entities that the watching input select had as options, rather than just the one currently selected. If you updated the list of options in the input select, you'd have to update the list associated with the template too, and if you made a spelling mistake the template wouldn't work properly.

If you were to replace the input select with an input text, then you'd have to drop-back to all entities in the system, which is a big under-constraint.

```
{{ states.switch|length }}
```

Count of all the switches in the system. The only way this template would work with the regexp is to trigger on all entity changes, the new algorithm will only trigger when a new state is added or removed from the system.

```
{{ states.sensor|selectattr('attributes.battery', 'lt', 10)|join(', ', attribute='entity_id') }}
```

This one is an interesting one, it lists the entity IDs for all sensors with a low battery. This could only be achieved previously by listing all sensors in the entity_id list. With the updated code this just works.

**Comment by amelchio** [comment]
I think this is awesome. Let me add a couple of comments that I made elsewhere:

> So the change here is that we don't try to figure out what is _going_ to be impacted. We record the fact as entities _are_ impacted.

> [...]

> This proposal:
> * is an immense improvement in usability
> * painlessly enables templates that were nigh impossible before
> * removes potential for configuration errors
> * fixes difficult bugs like https://github.com/home-assistant/home-assistant/issues/6342#issuecomment-427093742
> * limits code duplication
> * and even improves performance

The linked PRs are big changes but I have been discussing this idea a bit with @Swamp-Ig during the past few weeks and while the proposed implementation has had some issues, all of them could AFAIK be fixed elegantly. As someone who has tried to bugfix the regexp implementation, I see this as a big improvement.

**Comment by balloob** [comment]
I agree that this is a big improvement. I would propose that if we end up figuring out during set up that a template includes all, we only update it via manual render.

It would also be nice if we update our template dev tool to show this info.

**Comment by Swamp-Ig** [comment]
I handle the all case in the upstream code, basically it won't render much because it only happens with life-cycle changes on states (creation/deletion). Entities only get added to the state access list if their state or properties are accessed, and in this case we do need to trigger a render even if the list is long.

I agree with cool-down for re-render though, there's an arch issue to cover this.

**Comment by amelchio** [comment]
If I understand it right, this (untested) template will iterate all but actually only track changes to entities named with `office_`:
```
{% for state in states %}
  {% if state.entity_id | regex_match('.*\.office_') %}
    {{ state.entity_id }}={{ state.state }}
  {% endif %}
{% endfor %}
```
Forcing manual updates here would be a huge loss.

**Comment by Swamp-Ig** [comment]
That template will work as intended. The `state.state` part accesses any state touched, so you'll end up with re-rendering whenever:

* `sensor.office_door` is touched, or anything else matching that regex.
* An entity life-cycle event, so adding or removing an entity

The beauty of it is that the `.*.office_` will now dynamically add any new office entities to the watch list as they are added to the system, because the state is read (also works for attributes).

However if you had:

```
{% for state in states %}
  {% if state.entity_id | regex_match('.*\.office_') %}
    {{ state.entity_id }},
  {% endif %}
{% endfor %}
```

because there's no access to the state, we don't have to watch any states for changes because they can't affect the template result, we only watch for lifecycle events.

I actually anticipate having template groups, where you define a template that outputs a list of entity IDs that then define a group. This is going to be very useful, you can define your office entity group like:

```
{{ states | selectattr("entity_id", "match", ".*.office_") | attr("entity_id") | join(",") }}
```

then the group will automatically get re-rendered whenever a new entity is added to the system, and updated when the entity matches the regexp. The group *won't* however get re-rendered with any state change of the selected entities, because the state isn't accessed.

**Comment by Mariusthvdb** [comment]
is this still open to post some thoughts? (was correctly kicked out by Frenck [here](https://github.com/home-assistant/core/pull/39382#issuecomment-694717095), sorry for the misplaced post.)

Magic that templates now find their entities dynamically.  Thanks for that!

However, deprecating the `entity_id:` in template sensors also has a few serious downsides, which I would like to ask to be re-considered/mitigated:

- adding an entity_id (or list of) allowed us to limit the updating of the template sensor, to state changes of those entity_id's. When deprecating this, the template would be re-evaluated even if not desired so by the author of a template like this:

```
      entities_domains_counter:
#        entity_id:
#          - sensor.date
#          - sensor.count_persistent_notifications
        friendly_name: Entities per domain
        value_template: >
          {{states|count}}
        attribute_templates:
          headline: >
            {{states|count}} entities in {{states|groupby('domain')|count}} domains
          alert: >
            {{states.alert|count}}
          automation: >
            {{states.automation|count}}
          binary_sensor: >
            {{states.binary_sensor|count}}
          camera: >
            {{states.camera|count}}
          climate: >
            {{states.climate|count}}
          counter: >
            {{states.counter|count}}
# continue to list all domains
```

- secondly: the entity_id: was a global setting for the complete template sensor. deprecating that forces us to mitigate the loss of it in all individual parts of the template sensor, eg see:

```
      hour_icon:
        friendly_name: Hour icon
       # entity_id: sensor.time
        value_template: >
          {% set word = ['skipthis','one','two','three','four','five','six','seven',
                         'eight','nine','ten','eleven','twelve','one'] %}
          {%- set hour = now().strftime('%-I')|int %}
          {%- set minute = now().strftime('%-M')|int %}
          {%- set index = hour if minute <= 30 else hour + 1 %}mdi:clock-time-{{word[index]}}
            {{- '-outline' if states('sun.sun') != 'above_horizon' }}

        icon_template: >
          {% set word = ['skipthis','one','two','three','four','five','six','seven',
                         'eight','nine','ten','eleven','twelve','one'] %}
          {%- set hour = now().strftime('%-I')|int %}
          {%- set minute = now().strftime('%-M')|int %}
          {%- set index = hour if minute <= 30 else hour + 1 %}mdi:clock-time-{{word[index]}}
            {{- '-outline' if states('sun.sun') != 'above_horizon' }}

        attribute_templates:
          Hour: >
            {{now().strftime('%-I')}}
          Minutes: >
            {{now().strftime('%-M')}}
          Addition: >
            {{0 if now().strftime('%-M')|int <= 30 else 1}}
```

since the above template is built around the function now() and not an entity_id, do we need to set` {% x = states('sensor.time') %}` in all of those individual templates of 1 template sensor?

hope to add to the development of the core template sensor with this, 
thanks for considering

**Comment by frenck** [comment]
```
value_template: >
          {{states|count}}
```

I would say that is correct, as you track everything.

An automation with a helper might be more fitting here. As that provides conditions to decide.

**Comment by amelchio** [comment]
@Mariusthvdb Please have a little patience, you asked this question in three places now. I am going to reply in the forum.

As this has finally been released, I am going to close this issue. Further refinements can be discussed as separate topics but I think we will find that once we learn working with this new way, not much will need to be refined.
