### ISSUE TITLE
Reverse Proxy Compatibility

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/architecture#21]
This has been a bit of annoyance of mine (and from what I've read, many others) for a while now and it seemed like this was a good place to raise it for discussion and consideration. I imagine this is in no-way a small change which is why it hasn't happened already.

I run a few applications at home and have everything come through my NGINX reverse proxy (although this applies to any reverse proxy). It's good having a simple, single point of entry to my network and I can apply additional security at that level which is also nice. Every application I'm running has a reverse proxy allowance, in that all URLs for the service fall behind a set page; for example [IP/port]**/appName/**[UI/API/doesn't matter].

Home Assistant does not allow this, which means in my reverse proxy I have ALL traffic going to my Home Assistant instance with the exception of those that are picked up with rules that look for 'appName'. This works for me, because (so far) Home Assistant is the only app I run that doesn't support reverse proxies and requires external access, but others won't be so lucky.

It would be great to see all Home Assistant URLs sit behind an _optional_ subpage (i.e. [IP/port]**/HomeAssistant/**[API/etc].

**Comment by OttoWinter** [comment]
So what you're really asking here is the ability to change the relative URL root of the Home Assistant installation to allow urls like `192.168.178.42/homeassistant/states` instead of the "forced" `192.168.178.42/states`? I'm not sure how was that would be since Frontend would probably also need to know this at compile time.

(Btw, you can have multiple IPs point to the same computer in your network; for example have `192.168.178.2` point to Home Assistant and `192.168.178.3` to everything else)

**Comment by balloob** [comment]
A pull request to add this to the frontend is welcome. Here are some constraints:

 - It should not make current startup slower because it's doing extra requests or things like that
 - it should be backwards compatible

**Comment by michaelarnauts** [comment]
This can quite easily be fixed by using (sub)domain names that point at your home address. Ngnix can route requests to hass based on a specific  domain. Even it is a dynamic address, this is possible. This also plays nicely with https what won't work good with just an IP.

**Comment by balloob** [comment]
There you go, problem solved, case closed…

**Comment by pvizeli** [comment]
That is a problem of reverse proxy and not our software.
@balloob we should not change or make our URL schema dynamic. Otherwise it is relay hard for things like hass.io to interact with home-assistant.

**Comment by fanthos** [comment]
To make the web UI reverse proxy compatible with `appname`, we don't have to make the URL dynamic. Seems that make the front-end works with relative URL will resolve the issue. `/api/*` mapped to `/appname/api/*` for front-end page, and nginx will forward it to `/api/*`.
