### ISSUE TITLE
Support device and entity ID migration

### ISSUE THREAD

**Issue by andrewsayre** [home-assistant/architecture#215]
## Summary:
This is a proposal to add the ability to update (or migrate) the ID of a devices and entities to new IDs.  This is needed if the integration is unable to provide permanent unique IDs, but can temporarily.  

## Use case: 
HEOS issues a numeric ID to every device, but these IDs get reissued during a firmware change.  We can the use a secondary attribute to map the old ID to the new ID.  Having the ability to update a device and entity ID prevents creating orphaned devices and entities with suffixes like `media_player.office_2`.

#### `DeviceRegistry.async_migrate_device_identifiers(self, device_id, identifiers: set)`
- Find existing entry using `device_id`
- Update the entry's identifiers
- Triggers save of the registry

#### `EntityRegistry.async_migrate_entity_unique_id(self, from_unique_id, to_unique_id)`
- Find existing entity using `from_unique_id`
- Check for uniqueness of `to_unique_id` and update the entry's `unique_id`
- Trigger save of the registry

Any other considerations?

**Comment by andrewsayre** [comment]
CC @MartinHjelmare - I think you had another use case for PS4 -- does the above meet the requirements for that integration?

**Comment by MartinHjelmare** [comment]
The device registry is optional, right? How do we update unique_id of entity registry entry with this proposal? I think all entity attributes of the entry should be migratable

**Comment by andrewsayre** [comment]
I’m not understanding your question...

This proposal is to add the ability to update the device registry and entity registry.  Those are independent operations and needs.  The registers are tied together using an internal ID unrelated to device_id and unique_id.

**Comment by MartinHjelmare** [comment]
How do we migrate entity unique_id? I see how we can migrate entity entity_id.

**Comment by andrewsayre** [comment]
Oops... yes meant to make it about `unique_id`.  Updated proposal.

**Comment by balloob** [comment]
For device registry, it is possible that multiple integrations point at the same device. So if you say "Check for uniqueness if identifiers and update the entry", do you mean merge new identifiers in ? And if that's the case, why not make the old identifier part of device info, so the device registry does it's thing ? 

I have also just thought of a use case where we want to merge two device registry entries, because we auto merge new connections/identifiers, we might end up with having device A and device B. Then device A reports `A, B` and now we have two entries for B. 

For entity registry, when will this be called? In what case do we know an entity ID? Wouldn't it make more sense to do a migration based on `from_unique_id` and `to_unique_id` ?

**Comment by andrewsayre** [comment]
> For device registry, it is possible that multiple integrations point at the same device. So if you say "Check for uniqueness if identifiers and update the entry", do you mean merge new identifiers in ? And if that's the case, why not make the old identifier part of device info, so the device registry does it's thing ?
>
> I have also just thought of a use case where we want to merge two device registry entries, because we auto merge new connections/identifiers, we might end up with having device A and device B. Then device A reports `A, B` and now we have two entries for B.

The use case I'm trying to solve is simply to change the `identifiers` of a `DeviceEntry`.  Meaning I don't want the old ids associated any more and I know the new ones.  It sounds like the issue is with the check for uniqueness, which I will remove remove.

> For entity registry, when will this be called? In what case do we know an entity ID? Wouldn't it make more sense to do a migration based on from_unique_id and to_unique_id ?

That makes more sense and would save having to lookup the `entity_id` from the registry.
