### ISSUE TITLE
Entity class is converting temperatures an not other units.

### ISSUE THREAD

**Issue by vangorra** [home-assistant/architecture#217]
The Entity class is attempting to be smart by automatically converting units (metric or imperial) to unit system in the config (metric is default). The problem is the only values that are converted are temperatures. Further, this does not take into account the localization of the user. Overall, this is a complex issue and it either should implement true localization, allow the user to choose or do nothing at all. Selectively choosing one unit type is weird.

Since changing this could cause breaking changes, I've created a PR that allows developers to disable the feature on a per-entity basis. 
https://github.com/home-assistant/home-assistant/pull/23499

**Comment by awarecan** [comment]
We already have few open or closed issue around the same topic, especially #10, #48, #164. I don't see the necessary open a new discussion. I also cant find use case to support your proposal.

**Comment by vangorra** [comment]
@awarecan The discussion on #10 has some great use-cases supporting the override of this feature. I also provided some more as well. I'll close this duplicate.
