### ISSUE TITLE
Expand media player media_types

### ISSUE THREAD

**Issue by andrewsayre** [home-assistant/architecture#218]
This is a proposal to add 2 new consts to the media_types:
- `MEDIA_TYPE_FAVORITE`: Indicates a favorite or preset.  Example: [HEOS Favorites](https://denon-uk.custhelp.com/app/answers/detail/a_id/4745/~/adding-to-a-favorite-list).
- `MEDIA_TYPE_QUICK_SELECT`: Indicates a saved configuration of settings.  Example: [HEOS Quick Select function](http://manuals.denon.com/heosbar/ALL/en/FIQOSYtvjpachh.php).

Both of these would be used in the HEOS integration, specifically in the `play_media` service.  This would be in addition to supporting `playlist` and `url` as `media_type`.

Note: The `play_media` service schema does not currently validate against the constants, but the documentation indicates it must be one of the valid values.  With the exception of one media_player platform, all use the existing constants today.

**Comment by balloob** [comment]
I wonder if we should require constants to even be defined for this

**Comment by andrewsayre** [comment]
We don’t require it today in the code, but the docs indicate otherwise.  I looked at all the platforms that implement this service and only one uses custom types, all the rest use the constants.  It seems the parameters of this service are meant to refer to the same names attributes on the media player itself, which is probably why people assume it has to be one of the constants.

I’m fine not defining constants for this, then this arch issue isn’t needed.  I just didn’t want to go outside the constants in case we start enforcing validation  in the future.  :)

**Comment by balloob** [comment]
Oh right, that is true, if the media player type and current url can be passed back, that would be great. 

And media type is used in frontend to decide on how to show the cover or style the media player.

**Comment by balloob** [comment]
I feel like the overlap is slightly weird, in that when we use `favorite` or `quick_select`, the media type that is being played will turn to audio. So in that case, we should probably not have the media type be the only type of input for the play_media command.

**Comment by andrewsayre** [comment]
Sounds good. I'll close this issue and stick with strings.
