### ISSUE TITLE
Sensor continuous values without unit_of_measurement

### ISSUE THREAD

**Issue by vigonotion** [home-assistant/architecture#219]
**Problem**:
I have multiple `sensor` entites that count things:
- water bottle count
- cola bottle count

I want to have a continuous value (graph) instead of distinct values. For this, I would need to set a unit_of_measurement, but *count* has no unit.

![flaschen](https://user-images.githubusercontent.com/1506970/56884897-60d30d80-6a6b-11e9-9793-05bb3128c68a.png)
*Left: current situation / Right: desired situation*

**Ideas to solve this**:
- add device_class *count* that changes the appearance to continuous
- add attribute to set appearance (appearance: [distinct|continuous])

**Comment by dgomes** [comment]
Why don't you use `#` as the `unit_of_measurement` ?

**Comment by vigonotion** [comment]
that's not really a solution, more of a hack to make it work until fixed. The hash is rather ugly there, it's not needed, and it's not a unit.

**Comment by amelchio** [comment]
Cola bottles is a unit though.

https://github.com/home-assistant/home-assistant/blob/0.92.1/homeassistant/components/verisure/sensor.py#L145-L147

**Comment by Swamp-Ig** [comment]
The unit is 'bottles'.
