### ISSUE TITLE
Add network validation features

### ISSUE THREAD

**Issue by felipediel** [home-assistant/architecture#222]
# Background

Almost all integrations need a valid IP or MAC address to work, so I think it would be interesting to have a consistent validation method for these inputs. We already have functions for URL and port validation, but we still do not have a proper way to validate IP and MAC address entries using the voluptuous library.

I see some developers racking their brains to develop regular expressions for this exaustive task and in the end of the day they still don't have a 100% consistent function to validate and normalize the most common types of non-standard and mistyped MAC addresses. Some give up the task and simply do not validate it. And now we have 64-bit MAC addresses that also need to be validated.

The IP address is a bit more easy to validate, but in many cases it still needs to be done in the middle of the code, after the configuration entries are loaded. There's still no consistent method for validation via voluptuous.Schema().

# Proposal

My suggestion is to handle these inputs in the same way that is done with the other network inputs (port and URL), so it would be something like this:

## Example code for `some_component.py`:
```python
import voluptuous as vol

from homeassistant.const import CONF_IP_ADDRESS, CONF_MAC
import homeassistant.helpers.config_validation as cv


DEVICE_SCHEMA = vol.Schema({
    vol.Required(CONF_IP_ADDRESS): cv.ip_address,
    vol.Required(CONF_MAC): cv.mac_address
})
```

# Drawbacks
There's no drawback, since no code will be removed from Home Assistant core. Maybe some code will be removed from platforms in the future, and less code will be needed to create new platforms, since this method simplificates the process of network data validation.

# Questions
A contributor asked a good question in the pull-request: Is there a problem with our current usage?
```python
from ipaddress import ip_address


DEVICE_SCHEMA = vol.Schema({
    vol.Required(CONF_IP_ADDRESS): ip_address,
})
```
And my answer is yes. First of all, this usage doesn't distinguish IPv4 and IPv6 addresses, which is sometimes necessary. You must access the returned object to get this information, and you are not able to do it inside voluptuous.Schema.
The second problem is that ipaddress.ip_address() returns a ValueError in case of inconsistency, but voluptuous.Schema() requires a voluptuous.Invalid exception to work correctly in this case. This exception is more suitable for testing Schema-related functions and it allows the programmer to set a specific error message for the problem. This is well documented at [voluptuous documentation](https://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html). Raising ValueError does not allow delivering an error message to the user and may lead to inconsistencies. This is a test I made with pytest in which the ipaddress.ip_address() approach failed:

 ```py
import ipaddress

import pytest
import voluptuous as vol


def test_ip_address():
    """Test IP address validation."""
    test = vol.Schema(ipaddress.ip_address)
    invalid = (
        None, True, False, 123, 123.456, 123+456j,
        [], [1, 2, 3, 4], ['a', 'b', 'c', 'd'],
        {}, {'a': 1, 'b': 2, 'c': 3, 'd': 4},
        '', 'abc', '123', '!@#$%', 'abc::123::def', '...', ':::::::',
        '1.2.3', '1.2.3.4.5', 'abc1.2.3.4', '1.2.3.4abc', '.2.3.4', '1..3.4',
        '1.2.3.', '*.2.3.4', '1.*.3.4', '1.2.*.4', '1.2.3.*', 'a.2.3.4',
        '1.b.3.4', '1.2.c.4', '1.2.3.d', '256.2.3.4', '1.256.3.4', '1.2.256.4',
        '1.2.3.256', '1:2:3:4', '1-2-3-4', '1/2/3/4', '1_2_3_4', '1,2,3,4',
        '1 2 3 4', '1:2:3:4:5:6:7', '1:2:3:4:5:6:7:8:9', 'xyz1:2:3:4:5:6:7:8',
        '1:2:3:4:5:6:7:8xyz', ':2:3:4:5:6:7:8', '1:2:3:4:5:6:7:',
        '*:2:3:4:5:6:7:8', '1:2:3:*:5:6:7:8', '1:2:3:4:5:6:7:*',
        'g:2:3:4:5:6:7:8', '1:2:3:g:5:6:7:8', '1:2:3:4:5:6:7:g',
        '10000:2:3:4:5:6:7:8', '1:2:3:10000:5:6:7:8', '1:2:3:4:5:6:7:10000',
        '1.2.3.4.5.6.7.8', '1-2-3-4-5-6-7-8', '1/2/3/4/5/6/7/8',
        '1_2_3_4_5_6_7_8', '1,2,3,4,5,6,7,8', '1 2 3 4 5 6 7 8')
    valid = (
        '172.16.54.1', '192.168.0.1', '10.0.0.1', '255.255.255.1',
        '2001:db8:85a3:0:0:8a2e:370:7334', 'FE80::B3FF:FE1E:8329')
    for value in invalid:
        with pytest.raises(vol.MultipleInvalid):
            test(value)
    for value in valid:
        assert test(value)
```

This is a great function for validating IP address, but it needs a wrapper function to work correctly with voluptuous.Schema(). So I did it.

# Solution
I am proposing the complete solution here: [#23698](https://github.com/home-assistant/home-assistant/pull/23698). It's all done, all the functions have been tested locally and are working very well. Test files are available if you wish to test other entries. Documentation is done. Everything working flawlessly and awaiting your aproval.

**Comment by balloob** [comment]
Voluptuous has a `Coerce` helper that will convert ValueError to correct Invalid exception: https://github.com/alecthomas/voluptuous/blob/master/voluptuous/validators.py#L67-L71

**Comment by felipediel** [comment]
> Voluptuous has a `Coerce` helper that will convert ValueError to correct Invalid exception: https://github.com/alecthomas/voluptuous/blob/master/voluptuous/validators.py#L67-L71

Hi, Paul. This syntax also failed in pytest:
```py
import ipaddress

import pytest
import voluptuous as vol


def test_ip_address():
    """Test IP address validation."""
    test = vol.Schema(vol.Coerce(ipaddress.ip_address, "Invalid IP address."))
    invalid = (
        None, True, False, 123, 123.456, 123+456j,
        [], [1, 2, 3, 4], ['a', 'b', 'c', 'd'],
        {}, {'a': 1, 'b': 2, 'c': 3, 'd': 4},
        '', 'abc', '123', '!@#$%', 'abc::123::def', '...', ':::::::',
        '1.2.3', '1.2.3.4.5', 'abc1.2.3.4', '1.2.3.4abc', '.2.3.4', '1..3.4',
        '1.2.3.', '*.2.3.4', '1.*.3.4', '1.2.*.4', '1.2.3.*', 'a.2.3.4',
        '1.b.3.4', '1.2.c.4', '1.2.3.d', '256.2.3.4', '1.256.3.4', '1.2.256.4',
        '1.2.3.256', '1:2:3:4', '1-2-3-4', '1/2/3/4', '1_2_3_4', '1,2,3,4',
        '1 2 3 4', '1:2:3:4:5:6:7', '1:2:3:4:5:6:7:8:9', 'xyz1:2:3:4:5:6:7:8',
        '1:2:3:4:5:6:7:8xyz', ':2:3:4:5:6:7:8', '1:2:3:4:5:6:7:',
        '*:2:3:4:5:6:7:8', '1:2:3:*:5:6:7:8', '1:2:3:4:5:6:7:*',
        'g:2:3:4:5:6:7:8', '1:2:3:g:5:6:7:8', '1:2:3:4:5:6:7:g',
        '10000:2:3:4:5:6:7:8', '1:2:3:10000:5:6:7:8', '1:2:3:4:5:6:7:10000',
        '1.2.3.4.5.6.7.8', '1-2-3-4-5-6-7-8', '1/2/3/4/5/6/7/8',
        '1_2_3_4_5_6_7_8', '1,2,3,4,5,6,7,8', '1 2 3 4 5 6 7 8')
    valid = (
        '172.16.54.1', '192.168.0.1', '10.0.0.1', '255.255.255.1',
        '2001:db8:85a3:0:0:8a2e:370:7334', 'FE80::B3FF:FE1E:8329')
    for value in invalid:
        with pytest.raises(vol.MultipleInvalid):
            test(value)
    for value in valid:
        assert test(value)
```
Gives an error:
```
Failed: DID NOT RAISE <class 'voluptuous.error.MultipleInvalid'>
```
Even if it had passed the test, it does not distinguish between IPv4 and IPv6, which is necessary for some integrations. And there is also the MAC validation problem, which is very common.

Don't you think it would be nice to have these helper functions inside Home Assistant? They would be used by almost all integrations, and since they do not represent any disruption, no code prior to them would need to be modified.

They could be used even combined with other existing network validators in a very clean and organized way, for example:
## Example code for `some_component.py`:
```python
import voluptuous as vol

from homeassistant.const import CONF_IP_ADDRESS, CONF_MAC
import homeassistant.helpers.config_validation as cv

DEVICE_SCHEMA = vol.Schema({
    vol.Required(CONF_HOST): vol.Any(cv.url, cv.ip_address)
})
```
I truly believe this would help many developers in the validation process, since in the above case, most are validating a string and doing all the IP and URL validation work within the code.

Please consider this. And thanks for creating the Home Assistant, since I discovered it my home has completely changed.

**Comment by balloob** [comment]
your test is wrong, you should replace it with `pytest.raises(vol.Invalid)`

**Comment by felipediel** [comment]
It also did not work. Look, these functions would be useful for the integrations I'm developing (and I'll share soon), but it's okay if you do not want them to be a permanent part of the Home Assistant. Would you like it better if I make a separate library and include them in my integrations whenever I need?

**Comment by balloob** [comment]
I do not want this added to the core. If people want to distinguish between IPv4 and IPv6, they can use the `IPv4Address` and `IPv6Address` classes from the `ipaddress` package in Python. I am sure that the core lib did their due diligence in validating the inputs and so we should use that. Contributed integrations should also use the Python `ipaddress` package for IP address validation.
