### ISSUE TITLE
Introduce "human-friendly summary" field for the PR template

### ISSUE THREAD

**Issue by rytilahti** [home-assistant/architecture#224]
Inspired by https://github.com/home-assistant/architecture/issues/195, I want to open a discussion on adding a human-friendly changelog field to the PR template. All feedback, opinions, ideas are welcome as always, I just want to put this up here for discussion.

Until now, the release notes have contained information found important by the core developers / release managers, and the "detailed changelog" simply lists the PR titles for common changes. As this is not very end user friendly (most users are not that interested in changes related to integrations they are not using, and sometimes PR titles are unclear of implications to their setup), I'm proposing adding a new field (formatting can be decided later) called "change summary"/"human-friendly summary", which SHALL filled by all PRs and shall contain a text to be used in the changelog.

This text is targeted to end users or those being otherwise interested in the particular integration, and shall be written as such that it is understandable for someone who does not know technical intricacies or may not be interested in those. The reviewers/mergers MUST enforce filling this field on changes visible to end users. In case of simple upstream version bumps, this MAY contain information which is potentially valuable to users. 

Besides making the main changelog more readable, this information can be further be used to produce integration specific changelogs, which could use to show users only the changes relevant to their installation. If the field is not filled, the PR will not be listed in the main "changelog", but information based on PR titles will still be the accessible in the "detailed" changelog.

Implementing this would involve changing (https://github.com/home-assistant/home-assistant/blob/dev/.github/PULL_REQUEST_TEMPLATE.md) and adapting the release scripts & website generator. Later on, integration specific changelogs could be generated and later used directly by other parts (e.g. by introducing a "what's new" component showing the changes since last update that is tailored for the setup). Technical details how to implement these can be discussed later, this is just to gather some feedback whether such an idea is worth pursuing.

**Comment by balloob** [comment]
#195

**Comment by frenck** [comment]
closing this in favor of #195
