### ISSUE TITLE
Delete devices/entities when we remove config entry

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#227]
When we remove a config entry, we should clean up all entities that belonged to that config entry. After that, we remove the config entry from device entries and remove all devices that now have 0 config entries linked to them.

Initially we did not do this, in case someone was going to re-install an integration and didn't want to set up the names. However, I think that this is an edge case and we now put the cleanup burden on the user.

**Comment by Swamp-Ig** [comment]
👍 

Just be aware though, currently entities don't get deleted very often, and I have seen (and fixed some of) several places in the code where this is going to cause None reference exceptions when event listeners expect something attached to the new_state of an `EVENT_STATE_CHANGED` event. We're probably going to have to do a pretty thorough audit to shake them all out.

Also, sorry if this is a bit off topic, but if we're going to be deleting more entities, would it be worth having a `EVENT_ENTITY_LIFECYCLE` event for entity creation/rename/delete ? If nothing else it would be a good thing to show up in the log.

**Comment by Swamp-Ig** [comment]
Will sort this out. They do already happen, but nobody has noticed yet :grin:

**Comment by Swamp-Ig** [comment]
![Delete Entry](https://user-images.githubusercontent.com/6317645/57976280-d39e2b80-7a0e-11e9-874b-2323eb88f56c.png)

I've finished this, just writing some test cases.

Is there any point to even having the delete button there? It deletes the entity, but then it just gets re-created on the next reboot.

**Comment by balloob** [comment]
It's mainly for entities that are no longer linked to an existing integration, and then especially for the ones configured via configuration.yaml, since Home Assistant doesn't know when something is deleted from configuration.yaml.

**Comment by Swamp-Ig** [comment]
Done

**Comment by RyanEwen** [comment]
> It's mainly for entities that are no longer linked to an existing integration, and then especially for the ones configured via configuration.yaml, since Home Assistant doesn't know when something is deleted from configuration.yaml.

Perhaps the button could be conditionally shown just for those cases, to make it less confusing?

**Comment by Swamp-Ig** [comment]
I think the orphans are those that haven't been touched since the last reboot.

**Comment by Adminiuga** [comment]
I think we should have an optional button to keep the entities in the entity registry. For scenarios like this:
1. Configure ZHA integration
2. add devices, modify entities ID
3. need to change ZHA config entry, for example if serial port has changed
4. remove config_entry and you loose all your entities

**Comment by Swamp-Ig** [comment]
This would be better served by re-configuring the existing config entry, rather than removing a re-adding.

**Comment by Adminiuga** [comment]
Which integration allow config entry reconfiguration?

**Comment by Swamp-Ig** [comment]
You can't do this currently, that would be a long-term goal.

In terms of needing to change the zwave config entry because the serial port is changed, that's probably going to be better served by symlinking a virtual device to the actual device. There are ways to get this set up automatically in linux, but I haven't done it myself because I didn't need to.

**Comment by ties** [comment]
> In terms of needing to change the zwave config entry because the serial port is changed, that's probably going to be better served by symlinking a virtual device to the actual device. There are ways to get this set up automatically in linux, but I haven't done it myself because I didn't need to.

It is also an issue that hassio - or a docker-compose config (see below) can perfectly solve. The path of the serial port should be deterministic based on the id of the device. Documentation should/could also recommend to just use the `/dev/serial/by-id` path since these are stable as long as the serials are unique.
```yaml
# docker-compose.yml
    devices:
      - "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E1A591-if00:/dev/ttyACM0"
```

**Comment by balloob** [comment]
@Adminiuga we already support config entry options, but don't expose it yet on the UI (somewhere on the list!)
