### ISSUE TITLE
Option to run through onboarding wizards again and again

### ISSUE THREAD

**Issue by Hedda** [home-assistant/architecture#228]
Summary; Suggest adding the ability for end-users to run through onboarding wizard and its "integration" steps, starting over, again and again, however when restarting it/them it, importing current configurations/settings and allow to make changes to those existing configurations/settings before saving and exiting onboarding wizard and its "integration" steps.

This is a follow-up for the onboarding feature https://github.com/home-assistant/architecture/issues/92

As once onboarding is in place, it would be nice if both the onboarding setup-wizard as well as all onboarding setup-wizards for integration" steps did not start only run once initial-installation alone. It would be great if the same also be if the same onboarding setup-wizards steps could also be started again later, again and again, letting users make changes to their initial choices.

Re-using the onboarding "setup-wizard(s)" that way so that the user can either make changes to the config/settings that they made on initial install as well for the user to later configure components that they for whatever reason skipped when they first ran the "setup-wizard" upon initial installation.

This way the user could just restart the onboarding "setup-wizard" whenever, (again and again), to also configure new components after for example adding hardware USB/serial adapters for Z-Wave and/or Zigbee.

I think the ability to restart the onboarding "setup-wizard" will be very helpful and more comfortable to people who do not make daily changes in Home Assistant and might be inclined to forget how to make settings changes or even reconfigure standard settings that many other people might normally only set upon initial installation.

**Comment by awarecan** [comment]
After you system is up, you can goto configuration/integration page to check new discovered integration if have any. This page has exactly same code as onboarding page.

I didn't see the necessary to allow user to rerun onboarding. If you feel that onboarding page has better user experience, we may reproduce the same UX in configuration/integration page.

**Comment by balloob** [comment]
Exactly what @awarecan says 👍

**Comment by Hedda** [comment]
@awarecan Yes, my point was really that the onboarding page has a better user experience for new users.

Generally, I would advise making many configuration/setup-wizards available for new users (yet optional).
