### ISSUE TITLE
Option to group devices in 'zones' as well as grouping in 'areas'

### ISSUE THREAD

**Issue by Hedda** [home-assistant/architecture#229]
The new "area" feature was added in Home Assistant 0.87 and now I would like to request the addition of a "zone" grouping feature to be added to Home Assistant, and that 'zones' should be able to be used separately or in combination with 'areas'.

Background: Owners of Philips Hue Bridge and the Philips Hue App probably know that it for quite some time have had a "rooms" feature which is basically the equivalent to Home Assistant "area" feature, and if you been a frequent user of the Philips Hue system you might then also be aware that one of the most requested features have for them to also add grouping of devices within rooms or independent of rooms. Anyway, Philips has finally added the ability to group together in 'zones' separately from the grouping of rooms/areas (though the "zones" is still in beta stage). See:

https://www.theverge.com/circuitbreaker/2019/5/9/18563423/philips-hue-bulbs-group-together-zone-app-update-smart-home-light

https://www.youtube.com/watch?v=CC-1LDxirJg

The ability to group devices in 'zones' as well as a grouping in 'areas' is especially relevant when you have devices that feature an integrated dimmable or color-changer, such as Philips Hue lights and many (but not all) competing for smart lightbulbs do. 

For example if you have multiple Philips Hue spotlights in the ceiling of your kitchen then you would likely want to control them all as one group, but if also have other Philips Hue lights in the same kitchen, like say in the window-lights and countertop-lights then you would not want those in the same group, thus it is not enough to place them all the same "area" to be able to control the ceiling-spotlights as a separate group from the window-lights and countertop-lights which you may or may not also want to place in their own group.

 A more simple example is if you have two (2) Philips Hue lightbulbs in the same window and you also have one Philips Hue lightbulb in the ceiling of the same room it would be very nice to be able to group the two window-lightbulbs in the same group separate from the grouping that is the area as in the room.

**Comment by michaelarnauts** [comment]
I'm using the basic `group` functionality for that. Works perfect!

**Comment by Swamp-Ig** [comment]
[Groups](https://www.home-assistant.io/components/group/) already exist, they can be used for this exact purpose.

It would be nice to have some UI around putting things in groups, which is something I've considered contributing. Currently this can be done in lovelace anyhow, but without back-end groups.

Closing for now anyhow as it exists already,

**Comment by Kane610** [comment]
IIRC there is plans to add another level to areas later on. Call it zones or whatever.

**Comment by Hedda** [comment]
@Kane610 so maybe re-open this?

**Comment by Swamp-Ig** [comment]
@Hedda Groups exist, they do what you want already. There's a possibility to improve the UI, but they do basically what you want. They do need configuration in a config file, that's the only thing missing.
