### ISSUE TITLE
Add more detailed alarm triggered states

### ISSUE THREAD

**Issue by austinmroczek** [home-assistant/architecture#231]
Per initial discussion at https://github.com/home-assistant/home-assistant/pull/23709 

Also, this conversation is similar to https://github.com/home-assistant/architecture/issues/54

Right now there is only one alarm control panel state for when the alarm is "going off".  This is ``STATE_ALARM_TRIGGERED`` in homeassistant/const.py.

I would like my automation to respond differently if it's a burglar (turn on siren, announce police on the way) or fire (unlock doors, turn on lights, turn off fans) or carbon monoxide (open windows, turn on fans).

Here are the options I see to add this functionality:

a) My original request was to add new states to homeassistant/const.py

``STATE_ALARM_TRIGGERED_FIRE_SMOKE``
``STATE_ALARM_TRIGGERED_CARBON_MONOXIDE``

b) Use a state attribute to add detail to the existing state, per @andrewsayre suggestion

I assume it would be something along the lines of:

``states.alarm_control_panel.my_alarm.attributes["trigger_type"]``

Then trigger_type can be defined by specific components as needed.

Are there other possible solutions?

What are the pros/cons of each, and suggested path forward?

**Comment by balloob** [comment]
I like B but call it trigger_source.

**Comment by austinmroczek** [comment]
When you said trigger_source, I was thinking sensor name/location.  For example, I have five smoke alarms, each with a name like "Master Bedroom Smoke."

Perhaps we have two different state attributes, one for trigger_type and one for trigger_source?

**Comment by Swamp-Ig** [comment]
> When you said trigger_source, I was thinking sensor name/location

That would be entity_id if we're staying consistent with the other events.
