### ISSUE TITLE
Require automatic migration for backwards incompatible changes

### ISSUE THREAD

**Issue by emosenkis** [home-assistant/architecture#237]
## Context

Breaking changes are currently documented in the release notes but they still break many users' setups, as is evident in the comments section and the forums.

## Decision

Any change that causes breakage must, if possible, include an automatic migration of the user's configuration, automations, etc. When fully automated migration is impossible, the release notes must contain explicit directions for affected users.

This includes changes that remove a component - they must either allow Home Assistant instances with the reminded component configured to continue functioning (aide from the removed component) or automatically comment out the component's configuration.

This should be a hard requirement for Home Assistant 1.0.

## Consequences

Maintaining a Home Assistant instance and keeping it up to date will become easier because actual breaking changes should never happen unless by accident. Submitting breaking changes will become harder because of the extra work needed to implement and test an automatic migration. Some infrastructure work will probably be need to provide component authors with tools for implementing automatic migration. Downgrading a Home Assistant instance to an earlier version may require manually reversing any automatic migrations that were performed by the newer version.

**Comment by Swamp-Ig** [comment]
Would this apply to the whole of HA, or just the core? We probably need to define exactly what the core is too.

**Comment by emosenkis** [comment]
This would apply to all of HA. The goal is for updating Home Assistant to be a safe operation that never breaks a user's setup.

**Comment by timmo001** [comment]
No breaking changes are impossible. Avoiding making them as much as possible, should be followed, but sometimes there are cases where a breaking change will be made.

Once #202 is a thing though, this would be a non-issue for minor releases I guess since the core team is not responsible for third parties changes and breaking changes.

For example, companies that provide api's (especially for the 'cloud' world we live in) will change their spec. This is a known fact. Some will even remove their integration entirely, which will also 'break' a users system, as we all know we have been hit with recently. These cases are unavoidable and the release notes already give viable reasons for the changes. (Perhaps this could be added to the pr template checklist)

**Comment by SeanPM5** [comment]
Just to point out one recent example, `google tts` was renamed `google_translate` in 0.92 and although there was an automatic conversion, it only applied to users who had their config located in `configuration.yaml`. For those of us who use packages like me, it was a breaking change.

So ideally any automatic migration should work with packages too.

**Comment by Swamp-Ig** [comment]
> although there was an automatic conversion, it only applied to users who had their config located in configuration.yaml. For those of us who use packages like me, it was a breaking change.

If you're using some kind of customised process, then really that's outside the scope of something managed by an automated update process. It's implicit that if you do things not according to the "usual practice" you're on your own. 

That's not to say that modularised config is entirely "nonstandard practice", but it's getting less mainstream for sure.

**Comment by ties** [comment]
> If you're using some kind of customised process, then really that's outside the scope of something managed by an automated update process. It's implicit that if you do things not according to the "usual practice" you're on your own.

I think this example highlights the core issue with automated migration. Updating the configuration (in almost any case) is not a direct search and replace. Instead it is an operation that requires more semantics to be performed.

I see automated migration as something that should be performed, and is reasonably implementable for configuration that is stored in the storage of Home Assistant. But for explicit configuration in yaml the problem becomes immensely more difficult.

Configuration is not only syntax but also constrained by semantics, and these are loosely defined in the yaml. Creating an AST representation that includes imports, knows valid options for integrations, etc has multiple steps that are _feasible_ but are of a completely different magnitude in yaml than in configuration with more formally defined semantics.

**Comment by pvizeli** [comment]
Home Assistant core has no breaking changes and all Component they use the new schematic (Integration) have also no breaking change any more.

The problem is, that only 5% of the component support the new schema.

**Comment by balloob** [comment]
Yeah, we can indeed close this issue. All integrations that use config flows do not have any breaking changes as the code defines how config is stored and data is versioned.

We do however have a user base (not so much developer base) that loves configuration.yaml and storing things in there, and we are unable to update configuration.yaml without losing users formatting. So yeah, anything that is in configuration.yaml will forever be vulnerable to breaking changes and that is not going to change.
