### ISSUE TITLE
"loop=loop" is going away

### ISSUE THREAD

**Issue by smurfix** [home-assistant/architecture#238]
## Context

asyncio has a large number of functions that expects to receive "loop=…" arguments. However, these are redundant while the loop you're passing is executing – which is always true, these days, assuming that you're in hass's main thread, which you should be if you call async functions.

Also, the `loop` argument is already deprecated, and scheduled for removal in Python 3.10. See https://docs.python.org/3/library/asyncio-task.html .

## Decision

Start removing "loop=hass.loop" arguments now, finish sometime before 1.0 (ideally).

## Consequences

Home Assistant 1.0 will run under Python 3.9 (assuming that the asyncio people stick to that schedule) without inundating the user with a heap of deprecation warnings.

Calling functions meant to be used only in async context from sync context will raise an error if they try to interact with asyncio, as they should.

**Comment by pvizeli** [comment]
I agree but need some change on our test system.

My concern is Python 3.6 they have not such nice function to get the event loop like Python 3.7. Maybe we should go to this task with python 3.8 after we can use the feature from Python 3.7

**Comment by balloob** [comment]
I agree.

In Python 3.5.3 and later, `asyncio.get_event_loop()` will always return the current event loop. Hence, I agree that we should remove all occurrences. I don't think that it impacts our test runs, and if it does, we should be able to solve it using `asyncio.set_event_loop` before diving into async code.

**Comment by smurfix** [comment]
Long-term, asyncio is going to transition towards deprecating `run_until_complete` and `run_forever`. `asyncio.run` will be "the" way of running an async loop.
Our main loop already doesn't require those functions any more, so we might want to transition our testcases away from them, too. `@pytest.mark.asyncio` is your friend. ;-)

**Comment by balloob** [comment]
hmm , we don't currently use the decorator but our async functions are already executed in the event loop 🤔 I have to admit that when it comes to our testing, we learn as needed, instead of looking at what is available. Still also have a lot of tests using `unittest.TestCase` 🤷‍♂

**Comment by Swamp-Ig** [comment]
For non-test code at least, it should be possible to do most of the work with a regexp.

I just ran an regexp which came up with 199 results, with a quick inspection most of these will work fine after an eyeball to make sure they're sensible.

**Comment by MartinHjelmare** [comment]
`@pytest.mark.asyncio` is available from pytest-asyncio, which we don't use.

https://pypi.org/project/pytest-asyncio/

We use pytest-aiohttp. Those two libraries provide similar functionality in terms of async tests, but there some differences. You can eg configure the former to run all test coroutines in a module as async tasks with an event loop fixture. pytest-aiohttp will run test coroutines by default as async tasks with the loop fixture.

**Comment by pvizeli** [comment]
The correct function to get the event loop on 3.7 and higher is `asyncio.get_running_loop()` but `asyncio.get_event_loop()` should work as helper until we can use the new function.

**Comment by frenck** [comment]
The codebase has been adjusted for this, this architectural issue can be closed.
