### ISSUE TITLE
Add entity getter method to the hass instance

### ISSUE THREAD

**Issue by andvikt** [home-assistant/architecture#239]
It would be much easier to work with entities directly than with service calls, so we could have some method on the hass instance, that work like a mapping or a factory, that returns an actual entity instance from it’s id

**Comment by Swamp-Ig** [comment]
This isn't really going to happen. 

It's not the way the system works really, it would only be achievable with quite considerable change to the underlying architecture, and wouldn't actually gain much in terms of benefits.

If you need to pass classes or other objects between entities, then `hass.data` is the way to do it.

**Comment by balloob** [comment]
Just a note, integrations should only access `hass.data` objects that they stored themselves. You are not supposed to access other data. If you need to interact with other integrations, add methods on your integration that take `hass` as first argument, use `@bind_hass` and can be accessed via `hass.components.X.async_turn_on` etc
