### ISSUE TITLE
Pressure Sensor device_class

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/architecture#24]
Simple proposal: a `pressure` device class for sensors. From [Wikipedia](https://en.wikipedia.org/wiki/Pressure):

> **Pressure** (symbol: p or P) is the force applied perpendicular to the surface of an object per unit area over which that force is distributed.

### Potential uses

Atmospheric pressure

### Units

`hPa`, `mbar` [, `inHg` 😶]

Other units: `kPa` (move to `hPa`?), `mb` (move to `mbar`?), 

### Icon

[`mdi:gauge`](https://materialdesignicons.com/icon/gauge)

![gauge 1](https://user-images.githubusercontent.com/6833237/39630668-4a678a02-4fb0-11e8-8083-42f3b2ead232.png)

### Past uses

[WUnderground](https://www.home-assistant.io/components/sensor.wunderground/), [Dark Sky](https://www.home-assistant.io/components/weather.darksky/), [Yahoo Weather](https://www.home-assistant.io/components/sensor.yweather/), [One Wire](https://www.home-assistant.io/components/sensor.onewire/), [enviro pHAT](https://www.home-assistant.io/components/sensor.envirophat/), [Android IP Webcam Sensor](https://www.home-assistant.io/components/sensor.android_ip_webcam/), [Buienradar](https://www.home-assistant.io/components/sensor.buienradar/), [Netatmo Sensor](https://www.home-assistant.io/components/sensor.netatmo/), [Telldus Live Sensor](https://www.home-assistant.io/components/sensor.tellduslive/), [Xiaomi Aqara](https://www.home-assistant.io/components/xiaomi_aqara/), [OpenWeatherMap](https://www.home-assistant.io/components/sensor.openweathermap/), [ARWN](https://www.home-assistant.io/components/sensor.arwn/), [BME680](https://www.home-assistant.io/components/sensor.bme280/), [ZAMG](https://www.home-assistant.io/components/sensor.zamg/), [Sense HAT Sensor](https://www.home-assistant.io/components/sensor.sensehat/), [BloomSky Sensor](https://www.home-assistant.io/components/sensor.bloomsky/)

**Comment by balloob** [comment]
Sounds good to me.

**Comment by dgomes** [comment]
Should we open issues for each new device class ? or should we rename this issue and keep track of the list of classes in a single issue?

**Comment by c727** [comment]
SI is Pa or N/mm². hPa is used in combination with gases. I don't know if this should be included in the class name

**Comment by balloob** [comment]
New issue per new device class please @dgomes

**Comment by dgomes** [comment]
Most Meteo Services use hPa.

https://en.wikipedia.org/wiki/Pascal_(unit)#Hectopascal_and_millibar_units

**Comment by Pelado-Mat** [comment]
+1 also useful for water pressure sensors. I'm building a HA config for irrigation and water management, and I'm forced to use V_BARO
