### ISSUE TITLE
JSON schemas for explicit semantics

### ISSUE THREAD

**Issue by ties** [home-assistant/architecture#240]
## Context

At the moment Home Assistant uses JSON files, both in the code (manifests) as in it's configuration (`~/.homeassistant/.storage`). The validation of these files is performed using Voluptuous. This allows for validation, but does not have a native construct for versioning.

## Decision

Start using (versioned) JSON schemas for JSON

## Consequences

  * Validation of JSON files is easier. URL of schema refers to valid elements.
  * Versioning of the file format of JSON files becomes explicit.
  * Migrations are easier
    * Previous versions of file formats are still available
    * It easy to see that a file was valid before migration, and is after migration.
  * Improved tool support

The latter is an intriguing point. While JSON is not used as the human-readable file format, the tool support that comes with json schemas provides a good experience. The [Vega-Lite editor](https://vega.github.io/editor/#/examples/vega-lite/bar_grouped) is a good example for this, with autocompletion of both keys and valid values for enums.

If needed it should even be possible to generate a JSON schema from calls that instantiate the Voluptuous validator objects.

**Comment by frenck** [comment]
This architectural issue has been open for a long time without any response from others, so that would indicate this proposal isn't accepted. Therefore closing this issue.
