### ISSUE TITLE
why not use /var/lib/docker/volumes?

### ISSUE THREAD

**Issue by aristosv** [home-assistant/architecture#241]
Not really an issue, more of a question.

Any container I install, by default it gets installed in /var/lib/docker/volumes. But when I run this script:

`https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh`

home assistant and hassio are installed just fine, **but not in /var/lib/docker/volumes**.

I was wondering if there's a technical reason for this, and if I can somehow install the hassio container where all the other containers are (/var/lib/docker/volumes)

Thanks

**Comment by nickcj931** [comment]
Agree, I don't see any advantage of using volumes, are there any?

Personally I only ever use volumes where I want to isolate a test environment or something that isn't going to be running for an excessive period of time, basically anything I don't care if i lose it, kind of a throw away. 
Not sure if that is the right way but it's a heck of a lot easier managing shared folders than volumes in my environment anyway.

**Comment by pvizeli** [comment]
I close that issue or will someone work on a new integration?

**Comment by nickcj931** [comment]
I don't think there's much call for it and there is no follow up from OP

**Comment by aristosv** [comment]
I just ended up using the Home Assistant container, which work like all my other containers. I just don’t have hass.io, but I wasn’t really using it anyway. So all good.
