### ISSUE TITLE
add support_keys (or similar) to media_player

### ISSUE THREAD

**Issue by snicker** [home-assistant/architecture#242]
## Context

Many `media_player` type devices support directional input or other 'key press' type inputs. HomeAssistant currently does not have a way to communicate these types of events to the device controlled using the `media_player` component.

As an example, with the recent addition of Television support to the `Homekit` component (0.93), iOS devices may communicate these types of key presses to HomeAssistant, but HomeAssistant does not have a way to relay those messages back to the underlying `media_player` component.

Similarly, there is no UI in HA or service available for automation to communicate these kinds of key presses to `media_player` devices.

## Decision

- add a new constant for `SUPPORT_KEYS` to `media_player.const` (to be used if the media player handles "key" inputs)
- build a list of integer constants for `supported_key_<KEYNAME>` in `media_player.const` (suggested list of keys below)
- add `def press_key(self, key):` to `media_player`, where `key` is the value of the constant 
- add `def support_keys(self):` to `media_player`, return bool for whether or not the `media_player` supports key inputs
- add `def supported_keys(self):` to `media player`, returns the supported keys for that `media_player` (dicussion needed here due to some implied ambiguity of support_keys vs supported_keys)
- add service `SEND_KEY` accepting values or key names

### suggested initial keys ###

(Borrowed from the Homekit implementation) 

>
	ArrowUp
	ArrowDown
	ArrowLeft
	ArrowRight
	Select
	Back
	Exit
	Information

A possibility exists that this could expand even further to handle numeric input:

>
	NumPad1
	NumPad2
	NumPad3
	NumPad4
	NumPad5
	NumPad6
	NumPad7
	NumPad8
	NumPad9
	NumPad0

## Consequences

- Opens many more opportunities to automate Smart TV devices or other media players that accept directional or numeric input
- Necessitates a revisit to all existing media player components to see if they can take advantage of the new feature
- Creates an opportunity for a lovelace "remote control" card

**Comment by andrewsayre** [comment]
Isn't this what the existing `remote` platform is for?  I don't think combining that with `media_player` makes sense...

**Comment by snicker** [comment]
@andrewsayre yes and no:

It seems that a few existing implementations of the `remote` platform were built to address this architectural issue (AppleTV, Roku) whereas others are built for "actual" universal remotes (Harmony, Kira, Xiaomi, iTach)

The `remote` platform has the somewhat beneficial aspect of being able to define arbitrary commands, but the suggestion I am making could render the `remote` implementations for AppleTV/Roku unnecessary, keeping that platform solely for "universal remotes".

Another possible solution to the issue brought to like by Homekit is binding a `remote` to a `media_player` somehow. Either

1. the Homekit component needs to know how a `remote` and a `media_player` relate to each other via configuration, then it can send commands to the `remote` instead of the `media_player`
2. the `media_player` configuration must somehow define a `remote` that is bound to it and service calls to `media_player.send_command` (new service) would just proxy calls to that `remote`

However, given that most media players have a fairly "standard" set of button inputs, implementing it directly into `media_player` makes more sense to me.

Borrowed from @OverloadUT in Discord: "A smart TV is a media player, and you should be able to control it with service calls to that media player. Requiring some (but not all!) of the commands to go to a different entity is super confusing"

**Comment by snicker** [comment]
Additionally, media player platforms like `android_tv` currently have zero implementation of this kind of functionality.

**Comment by adrum** [comment]
Back when I was planning out the Television accessory implementation, my plan was to add the ability to link a remote to a media player, just like the recently implemented `linked_battery_sensor` entity config option. 

There are opportunities all around the HomeKit component to extend functionality by linking multiple entities in one HomeKit accessory. I was going to wait for that architectural topic to be finished before moving onto linking a `remote` to a `media_player`. 

See https://github.com/home-assistant/home-assistant/pull/23553 for another example.

**Comment by yuriglushko** [comment]
Any updates on this? Homekit remote looks kinda pointless now, only able to play/pause and change volume and all other buttons doing nothing

**Comment by MartinHjelmare** [comment]
We use the remote integration for this purpose.

https://developers.home-assistant.io/docs/core/entity/remote
