### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/architecture#243]
## Context

We have now `homeassistant/home-assistant` as amd64 image based on Debian Linux with a size of 761 (compressed). On the other side, we have `homeassistant/...-homeassistant` with support 5 architectures based on Alpine Linux with a size of 376 (compressed). This image is also used by Hass.io and the Dockerfiles are checked by hadolint and mostly best praxis. Hass.io support more components out of the box. We build in the background a wheels repository for Alpine and want to extend that support in the future. It's true that the image supports more components but TF and chrome are currently not supported out of the box.

## Decision

We are currently fragmented with 2 Docker images and build system. Our Docker team and resource are very limited and we should focus all our resource to one Project/image system. Otherwise, we need to solve every problem twice. Also, can the regular Docker installation improved by coming Hass.io feature with modular component installation and smaller images.

I want that we have one build system and `homeassistant/home-assistant` going to be a meta repository that points to the correct architecture of `homeassistant/...-homeassistant`.

## Consequences

We need to extend the azure builds to support the tagging system `dev`, `beta` and `stable`.  We need also move forward with the wheels repository and the Home Assistant core pip installation for Docker environment.

**Comment by balloob** [comment]
Yeah, I agree that this is a good direction. It makes indeed no sense to maintain two Docker images for the same architecture. 

For the tagging system, it will be `dev`, `rc` and `latest` (instead of stable).

**Comment by pvizeli** [comment]
Use `latest` for tagging is very bad praxis because any mistake of automation or process ends up automatic to mess up the latest tag. All lint programs warn if you pin to this tag and every user guide and best praxis to the same.

I'm okay with every tag name for the stable release, but latest is the worse one that we can use for a stable one.

**Comment by OttoWinter** [comment]
So this of course also means that we would need to decide between debian and alpine as the base image for docker (right?). Changing the main `homeassistant/home-assistant` to the alpine build system could be a big breaking change (pretty much anybody that extends the docker image).

I'm not saying I'm against switchting the build system, just that we should be aware that this could be a big breaking change.

**Comment by pvizeli** [comment]
Well, the choice if, if we want to use one Docker backend/build. Hass.io can't switch to Debian because they don't support all our Architectures.

**Comment by balloob** [comment]
Since the Hass.io Home Assistant images are also compatible with x86, can't we just decide to stop making new builds of the `homeassistant/home-assistant` image and redirect people to the other image? 

Granted, it will need the tags dev, rc and stable set up as Pascal mentioned.

**Comment by ties** [comment]
> Since the Hass.io Home Assistant images are also compatible with x86, can't we just decide to stop making new builds of the `homeassistant/home-assistant` image and redirect people to the other image?

Could you share telemetry on how often each image gets installed? If possible split out across `uses custom_components {yes, no}`? Purely going off the number of downloads the debian based image seems to have a relatively large following and as @OttoWinter mentions switching to Alpine _will_ break things.

I don't see an easy way to detect custom (derived) docker images, but this likely to give a solid upper boundary.

Besides not breaking stuff, the 'good' part of the current image is that most of the size of the Debian based image is shared with other python 3.7 images, and that it is really transparent to inspect the build: With the hassio image, determining how it is built is convoluted.

**Comment by balloob** [comment]
Docker Hub gives no data, but I also think that it doesn't really matter. 

We already remove all build tools form all our Docker images, so it would only matter if people are extending our images and building stuff. I am not aware of any public image that extends from ours, so it is mostly for personal use, hence there are not many.

**Comment by OttoWinter** [comment]
> We already remove all build tools form all our Docker images, so it would only matter if people are extending our images and building stuff. I am not aware of any public image that extends from ours, so it is mostly for personal use, hence there are not many.

I tend to agree that this is for advanced users only - but the big places where I've seen that happen is: When creating a custom component with some dependency or more often: shell commands. For example git is not installed in the base image and has to be added as an additional layer.

That's also why the docker image is also so often getting PRs to add some package to it - I think we can use that as a metric for how many image extensions there are out there.  And I tend to think it's more than you'd think - and the thing I fear is that those people are also the most vocal when it comes to a breaking change (and moving from debian to alpine in docker is not always so nice; some packages don't exist on the other platform).

If there's no other option with the supported packages, sure we should choose alpine. But I don't really see a problem with the existing setup so much. Yes image size is a problem, but I think 60% of that is from the python base image, which many users probably already have downloaded somewhere.

**Comment by ties** [comment]
> We already remove all build tools form all our Docker images, so it would only matter if people are extending our images and building stuff.

Since the image is based off `python:3.7` it is indirectly [based off](https://hub.docker.com/_/python) ` `buildpack-deps` which contains dependencies to make "a majority of arbitrary gem install / npm install / pip install [should be] successful without additional header/development packages."

The ubuntu based image _does_ currently contain `make/gcc/g++/...`. In contrast, the hassio image does not.
```bash
$ docker run -it --rm homeassistant/amd64-homeassistant /bin/bash -c 'which gcc; which make; which g++'
starting version 3.2.7

$ docker run -it --rm homeassistant/home-assistant /bin/bash -c 'which gcc; which make; which g++'
/usr/bin/gcc
/usr/bin/make
/usr/bin/g++
```

> I am not aware of any public image that extends from ours, so it is mostly for personal use, hence there are not many.

That argument works the other way around. These images being for personal use causes there to be many derived images. And all of these would need to migrate from apt to `apk` and new package names, while being a very vocal part of the community.

> (and moving from debian to alpine in docker is not always so nice; some packages don't exist on the other platform).

Some packages do not even build (at all) or run with the same performance when built using musl libc. There are good reasons why the [python docker image](https://hub.docker.com/_/python) offers tags with different flavours (which they explain well).

**Comment by balloob** [comment]
All good arguments for the existence of a Debian based Home Assistant image, but none are good arguments for having that image be maintained by the Home Assistant organization, which is what this issue is about.

**Comment by ties** [comment]
The builds on docker hub appear to be triggered by an automated trigger (for dev and tags) and the Dockerfile was last modified two months ago.

I agree that is inconvenient to update the latest and rc tags manually, and see that the build framework for hass.io has become a major project on its own. I agree that extending that to support the Debian based build is an inefficient use of resources. In addition I respect the _choice_ to deprecate the Debian based images and switch to hass.io image as the main image (c.f. it being an architecture discussion).

For me personally, the wheels based builds - while needed for fast cross-platform builds - go against the transparency of "being able to see what code you run" that comes with open source software, as well as a first step towards making non-hass.io a second class citizen.

I want to make sure that this choice is made with the inconvenience to expert users in mind, and [while I will not personally start one] the chance of this causing multiple unofficial docker images (with additional 'batteries' like `custom_updater` included) causing support requests in consideration.

Proposal: Switch to hass.io base images and meta-repository layout for `{ latest, dev, rc}` image at 1.0 and set-up the docker-hub auto build to continue building `-squeeze` and/or `-buster` images for expert users that need most `pip installs` to work in the container.

**Comment by balloob** [comment]
Most Python packages on PIP are pure Python and so will work on any operating system. I feel like this thread is actively looking for problems that I don't think many people experience. 

There are very few people involved in the packaging and distribution of Home Assistant, if us shutting down one image can cause other people to step up, that might actually result in a win.

**Comment by raccettura** [comment]
Well there are some things that AFAIK don't work in Alpine.  Anyone doing anything with PhantomJS for example:
https://www.home-assistant.io/components/usps/

IIRC there's also some complexity with headless chrome, but that might be old info.

**Comment by balloob** [comment]
USPS was also IP blocking users of the USPS integration: https://community.home-assistant.io/t/do-not-use-usps-component/49357?u=armdan

Webscraping is bad practice and super fragile.

**Comment by pvizeli** [comment]
> Since the Hass.io Home Assistant images are also compatible with x86, can't we just decide to stop making new builds of the homeassistant/home-assistant image and redirect people to the other image?

That is what we do with meta tags. They redirected to correct architecture image. But yeah, we can remove the meta tagging and user needs self known what they need as architecture without that docker does that automatic select. Anyway, there are also some machine-based images like for RaspberryPi because they have some different configs and library.

> against the transparency of "being able to see what code you run" that comes with open source software, as well as a first step towards making non-hass.io a second class citizen.

Hmm, all are open source and open for everyone. I will create a project they allow custom components to register PIP modules they are hosted by us.

> Well there are some things that AFAIK don't work in Alpine. Anyone doing anything with PhantomJS for 

Yes, I wrote that on the inial post. Chrome or PhantomJS don't work. But it's like for tellstick, they should run an additional container they manage the daemon.

That are not Hass.io only images, that are normal Dockerfiles. I will focus to solve the problem once instead to complicate tings.

**Comment by ZetaPhoenix** [comment]
Just my 2c:

I believe `:latest` should be used instead of `stable` as by default if a user does not add a tag docker will pull `:latest`. This would prevent users from accidentally getting the wrong image and also follows what most other projects use.

Also sounds like this will resolve https://github.com/home-assistant/home-assistant/issues/22690

**Comment by balloob** [comment]
Today the dockerfile based on Debian broke because the base image got bumped to Buster and all the scripts to install dependencies were no longer correct. I have pinned the version to Stretch in https://github.com/home-assistant/home-assistant/pull/25206

We are going to alias that image to the Hass.io Home Assistant version before the Home Assistant 1.0 release as it is actively maintained.
