### ISSUE TITLE
Deprecate discovery and configurator integrations

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#247]
## Context

 - Discovery integration used the netdisco package to scan the network and discover which integrations a user could set up.
 - Netdisco contained a wide range of network discovery protocols and was able to discover a lot of different things. This proofed to be a congestion point, as it was a central point of configuration.
 - Discovery integration would map these discovered services to integrations and load them either using discovery events or via the special "discovery" step in the config flow.
 - For integrations loaded via discovery events, they set themselves up directly without user interaction, causing frustration with users as this was unpredictable behavior that could only be disabled by either configuring the discovery integration or by removing it from the config. A few integrations behaved a little better and used the `configurator` integration to ask some user input before setting themselves up.
 - The previously mentioned behavior was standardized with config entries, making it sure that we always asked approval from a user before setting something up, and remembering discoveries so we can set up the integration without relying on the discovery integration being loaded.
 - The config entries were still hooked into the discovery integration for discovery, allowing the discovery integration to launch the special "discovery" step on the config flows.
 - We have now introduced an alternative for the discovery integration, that is having a better approach to this: a SSDP (#245) and a Zeroconf (#198) integration that will provide discovery functionality, but only work with config entries. These integrations, instead of knowing about everything, rely on files generated by aggregating discovery info from the integrations manifests.

## Decision

- Deprecate the discovery and configurator integrations. We won't remove them but no longer accept any contributions that use this.
 - Remove discovery from the default config
 - Deprecate Netdisco

## Consequences

When all integrations have been updated to use the new discovery methods, discovery will be predictable and manageable (because config entries are manageable).

Certain integrations with custom discovery protocols will no longer be discoverable. They can still run discovery when their config flow is launched from the integrations screen. Impacted services are ~~Plex~~, Logitech Media Server, Daikin, WebOS, Tellstick and X-Box Smart Glass.

**Comment by jjlawren** [comment]
This was removed from Plex in https://github.com/home-assistant/core/pull/32510.

**Comment by MartinHjelmare** [comment]
The tasks in the decision suggestion have been accomplished and we're not accepting new integrations that use legacy discovery or configurator.

Let's close here.
