### ISSUE TITLE
Add HomeKit discovery support to manifests

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#248]
## Context
Just a small definition. We have two integrations, `homekit` and `homekit_controller`. `homekit` is to **expose** Home Assistant over HomeKit. `homekit_controller` is about controlling other HomeKit devices on the network. This issue about the controller.

HomeKit discovery is a protocol that is built on top of zeroconf discovery. In our current approach, we route all homekit discoveries to the `homekit_controller` integration, which ignores some (per a hardcoded list) and offers the user a config flow to control them otherwise.

However, for some integrations, our native integration is better, or as good, as the HomeKit one. For example, LIFX. 

The current approach we are experimenting with is to have LIFX listen to the HomeKit discovery type on zeroconf, and then inside the LIFX config flow we see if the HK discovery was for LIFX. This has the downside that we install the LIFX package even if we discover a non-LIFX device. In the future, it's not going to be just LIFX that supports HK discovery, but many more, for which all the packages will be installed.

On top of that, the `homekit_controller` integration will have to maintain a list of native integrations that handle their own integration. Double bookkeeping.

CC @Jc2k @Kane610 

## Proposal

We add a new `homekit` entry to the manifest. We will start with just a list of supported models. If the model name **starts with** any of the models in the manifest, the discovery is routed to that integration. Fallback is to route it to the `homekit_controller` integration.

```json5
{
  "homekit": {
    "models": [
      "LIFX"
    ]
  }
}
```

Homekit discoveries will be routed to the config flow step `homekit`

## Consequences

 - Easy way for integrations to make themselves discoverable via HomeKit
 - Single place of bookkeeping of integrations that want to offer control of their devices

**Comment by rohankapoorcom** [comment]
Should we write an ADR file for this?

**Comment by balloob** [comment]
🤷‍♂ 

Since it was kinda a slam dunk proposal, I don't know if writing an ADR is worth it?
