### ISSUE TITLE
Use Black for Code Formatting

### ISSUE THREAD

**Issue by bachya** [home-assistant/architecture#249]
## Context

A long time ago, code formatting via `yapf` was discussed here: https://github.com/home-assistant/home-assistant/issues/9793. I couldn't find such a discussion in this repo, so resurfacing it as a holistic architectural issue for discussion.

**EDIT:** @balloob kindly reminded me that it was discussed here, as well: https://github.com/home-assistant/home-assistant/issues/16634

## Proposal

I propose that we make [Black](https://github.com/python/black) the code style and formatter of choice for the HASS back-end. After using `autopep8` and `yapf`, I like that Black handles a lot by itself:

>Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
>
>Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.
>
>Black makes code review faster by producing the smallest diffs possible.

In the 206 PRs I've merged into the HASS back-end, I would estimate that 70-80% had styling issues that either (a) failed a PR check or (b) invited additional PR commentary that, although valid, is a waste of the reviewer's and my time. This has forced me to spend countless hours fiddling with linters (and altering zillions of options), tweaking editor configs, plodding through fixes, and otherwise not spending time adding meaningful functionality to HASS.

I recently updated all of my PyPi libraries to use Black and love how it takes formatting control out of my hands, produces beautiful-looking code, and frees my mind up to focus on functionality. I've even paired it with [`pre-commit`](https://pre-commit.com/) so that any PRs submitted to those libraries are automatically styled by Black upon commit.

I have to believe that the proper application of Black would greatly reduce the amount of time we spend on reviewing style/formatting.

## Consequences

Of all the Python formatters, Black provides the fewest configuration options (requiring that control over "sane formatting" be ceded to it), which may run contrary to some people's preferences. Additionally, it is technically a beta product; although the group assures the community that it will focus primarily on bug fixes, there is no guarantee future updates won't hurt something.

Although it's possible that running Black on the entire codebase at once will produce proper results, it's likely safer to stage such an effort; thus, there is a "consequence" of this taking decent time to implement.

**Comment by balloob** [comment]
You missed this one ;-) https://github.com/home-assistant/home-assistant/issues/16634

Thanks for opening it as an architecture issue.

Previously, the main blocker for introducing Black was that it only ran under Python 3.6 and so we would have a different minimal requirement between development and running Home Assistant. Home Assistant is going to drop Python 3.5 support on August 1.

- I am all in favor of using black.
- I am in favor of not changing ANY options on black. 
- I am also in favor of doing a whole code base at once commit and putting linters in place to make sure it's black.
- We can also activate [the black_out bot](https://github.com/Mariatta/black_out) to help people black their PRs.

**Comment by bachya** [comment]
I love the idea of using default options. FWIW, thus far, I've seen two challenges involving `pylint` and `flake8`:

1. Black likes to format longer method signatures like this:

```
def run(
    arg1,
    arg2,
    kwarg1=None,
    kwarg2=None,
    kwarg3=None,
    kwarg4=None,
):
    """Run."""
    # ...
```

`pylint` will report `Wrong hanging indentation before block (add 4 spaces).` [Black has established that this is a pylint issue](https://github.com/python/black/issues/48) ([and `pylint` is at least aware of it](https://github.com/PyCQA/pylint/issues/289)). The unfortunate "fix" is to disable `bad-continuation` in `pylintrc`:

```
[MESSAGES CONTROL]
# Reasons disabled:
# bad-continuation - Invalid attack on black
disable=
  bad-continuation
```

2. Black likes longer line lengths:

>You probably noticed the peculiar default line length. _Black_ defaults to 88 characters per line, which happens to be 10% over 80. This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, 90-ish seems like the wise choice.

However, by default, this will panic `flake8`: `line too long (80 > 79 characters)`. Black's suggestion (which I've implemented) is to add a `.flake8` that looks like this:

```
[flake8]
max-line-length = 80
...
select = C,E,F,W,B,B950
ignore = E501
```

> You'll find _Black_'s own .flake8 config file is configured like this. If you're curious about the reasoning behind B950, [Bugbear's documentation](https://github.com/PyCQA/flake8-bugbear#opinionated-warnings) explains it. The tl;dr is "it's like highway speed limits, we won't bother you if you overdo it by a few km/h".

**Comment by Swamp-Ig** [comment]
This might be a slightly ignorant question, however: why use flake8 at all if black deals with code formatting?

**Comment by bachya** [comment]
@Swamp-Ig `flake8` has some useful functionality outside of formatting, like detecting unused imports.

**Comment by frenck** [comment]
IMHO we should disable all style checks on `pylint` in that case:

```
disable=
    # handled by black
    format
```

**Comment by pvizeli** [comment]
We should create an ADR.

> Previously, the main blocker for introducing Black was that it only ran under Python 3.6 and so we would have a different minimal requirement between development and running Home Assistant. Home Assistant is going to drop Python 3.5 support on August 1.

Well, they can develop with python 3.5 and if you want (I don't like that) add bot they format the code, I see no issue to block this. We speak about a code formatter and not a code functionality. They can read how the code should formatted and write it in this format or let the the bot do his job.

**Comment by Swamp-Ig** [comment]
Creating a bot to do the formatting so that someone can develop in 3.5 seems like a waste of work IMHO. Just use 3.6, a check-in filter that formats the code, and be done with it.

**Comment by balloob** [comment]
Such a bot already exists and was linked in my first comment 👍 It listens to comments and will then add a commit that formats the code.

**Comment by pvizeli** [comment]
In that case, it's no python 3.5 killer

**Comment by rytilahti** [comment]
I'm all for this :+1: Just a related side-note regarding to import sorting. It looks like that the author of isort is going to release an extension to isort to integrate it better with black (https://github.com/python/black/issues/333#issuecomment-490245892). Should we open an ADR also for using that when the time comes, as it seems to be that sorting is not going to be implemented any time soon in black?

**Comment by ties** [comment]
In the discussion after a change to the PR was made, @frenck proposed to remove the proposal to add pre-commit hook and directed me to discuss this here.

Enforced coding standards are already a part of the project. Both through CircleCI and the recommendation to set-up flake8 pre-commit hooks in the development and testing instructions. I see adding removing flake8 rules and adding black without pre-commit as a regression compared to the status quo.

I feel that the recommended usage is to run black locally. Iteratively fixing issues after CircleCI runs fails or issue comments is noisy and imo is an anti-pattern. Bots that add commits (if they exist) break some branching models but have value – however, I feel that many contributors will have issues rebasing if a commit was added, so I would stay away from that here.

**Comment by Jc2k** [comment]
We absolutely always have to have these things enforced by CI checks or a bot because contributors will make mistakes.

We should encourage people to blacken every commit and to flake8 and pylint every commit before they push, but it should be up to the dev to figure out how to integrate that into their own  workflow.

I run pylint and flake before I run the tests or do any manual integration testing. If I was “forced” to have a commit hook it would at best be something I ignored (apparently I already am) and at worse make contributing actively irritating.

Sometimes I push known broken things that’s are WIP, sometimes even with SyntaxErrors, to my own private branches because I’m switching machines after getting back from a trip. I always rebase and squash my commits to make it cleaner and easier to review. Hooks for me suck.

**Comment by MartinHjelmare** [comment]
I agree with not enforcing pre-commit hook, but I don't think that was the intention either. The discussion was about adding it as a suggestion, I think. Am I wrong?

**Comment by ties** [comment]
> I agree with not enforcing pre-commit hook, but I don't think that was the intention either. The discussion was about adding it as a suggestion, I think. Am I wrong?

Indeed. The intention was to make it suggestion, you could even call it a social norm. You can ignore or `git commit -n` it when you are aware of the downsides, but it shifts the responsibility.

I think there is value in every commit in the repo being valid according to linters and (especially) formatting tools. What happens in private forks is... private 🙂

What I have seen in other projects is that if you add them later (bot/final commit) you end up with merge/rebase issues if you branch before that commit. This situation is (very) confusing to less experienced developers.

**Comment by Jc2k** [comment]
Ah i must have misread, then yes, this sounds much better than e.g. a bot adding fixes to my PR for me. 👍

**Comment by balloob** [comment]
We use a pre-commit hook for the Home Assistant frontend repository ([source](https://github.com/home-assistant/home-assistant-polymer/blob/dev/package.json#L180-L195)), and it works great. Never get any complaints.

**Comment by presslab-us** [comment]
I just ran into this problem, and couldn't figure out what this "Black" thing was that I was failing.  Eventually I figured it out, but I didn't see anything in the developer documentation about needing to run this locally.  Did I miss something?

**Comment by scop** [comment]
That's covered by the development environment set up docs (`script/setup` takes care of it): https://developers.home-assistant.io/docs/en/development_environment.html

**Comment by AlecRust** [comment]
@presslab-us in [the dev blog announcement post](https://developers.home-assistant.io/blog/2019/07/31/black.html) it says:

> If you have an existing developer installation, please run inside your virtual environment:

For all new setups, this will be installed as part of the setup script.

Where else do you think this should be documented? Got a link?
