### ISSUE TITLE
RFC: Battery Charging attribute

### ISSUE THREAD

**Issue by schmittx** [home-assistant/architecture#25]
I'm working on an addition for HomeKit component to add battery tracking (home-assistant/home-assistant#14288). The HomeKit framework accommodates charging status in addition to battery level, therefore I'd like to propose a unified charging attribute.

My image is that attribute would be a boolean, and if charging is not supported for the entity then the attribute would not be generated.

I believe that we'd need to update at least one component to use this new attribute before it can be added, correct?

Any advice on how to proceed would be appreciated.
```
ATTR_BATTERY_CHARGING = 'battery_charging'
```

**Comment by balloob** [comment]
So this brings up another interesting issue, as for one, we don't have a list of official attributes. Note that the list [here](https://developers.home-assistant.io/docs/en/entity_index.html#generic-properties) are properties. Things that one can define on an entity and that will be stored in the state attributes.

So if this is a proposal for a property, I would say no, there is not a common enough use case.

However, if this is just a proposal for an attribute which we define in `homeassistant/const.py`, I would say: why not. However, in that case we would also introduce a new page in our dev docs to talk about such attributes and what value it should hold.

**Comment by schmittx** [comment]
You nailed it, I think a list of official attributes would be very helpful and ensure consistency.

My image for charging status specifically would be an addition to `homeassistant/const.py` as you mentioned. I'm just not sure if a boolean value is robust enough or if it should be more granular (i.e. `charging`, `not_charging`, `full`, `not_supported`, `unplugged`, etc.).

**Comment by schmittx** [comment]
Is there anyone that can help with updating the dev docs to create a section describing attributes? I'm not so good with HTML stuff, but can help with content once a structure/format is established...

**Comment by balloob** [comment]
You don't need any HTML knowledge, it's all markdown (same syntax as the comments you're typing here).

Entity page is here: https://developers.home-assistant.io/docs/en/entity_index.html

**Comment by schmittx** [comment]
Gotcha, I don't know what I was looking at initially...lots of late nights lately...

I created an initial [PR](https://github.com/home-assistant/developers.home-assistant/pull/23), any feedback is much appreciated.

**Comment by schmittx** [comment]
[PR](https://github.com/home-assistant/developers.home-assistant/pull/25) for battery charging has been created, thanks for the feedback and help so far!
