### ISSUE TITLE
Playing Spotify playlist starting with random music

### ISSUE THREAD

**Issue by lealoureiro** [home-assistant/architecture#251]
## Context

Spotify is `media_player` kind of component that is able to play a playlist media time. 
I have some automations to use this service` play_media` but is a bit annoying or repetitive arriving home and always play the same music... 

## Proposal

I would like to propose to introduce a way to be able to achieve that from one of the options below: 

1.  Extend `play_media` service
2.  Create a specific service for Spotify component

Probably the 2nd is better that does not affect the core. 

I already did some solution using the 1st option but i guess should be easy to migrate or adapt to achieve using the 2nd option.

https://github.com/home-assistant/home-assistant/pull/24604

Let me know what you think.

**Comment by andrewsayre** [comment]
So this seems fairly specific to the Spotify platform, so I think #2 makes sense.

Alternatively, we could expand the play_media schema to accept extra keys which would cover this use case and others w/out introducing integration specific concepts.  I could be open to this.

**Comment by lealoureiro** [comment]
Do you have examples where in some components where we can see that?

**Comment by andrewsayre** [comment]
Example of what?

**Comment by lealoureiro** [comment]
> we could expand the play_media schema to accept extra keys

This strategy

**Comment by lealoureiro** [comment]
How can i add a custom service to spotify component so i can call something like this:

`- service: media_player.play_random_playlist_music
`

**Comment by uSpike** [comment]
home-assistant/core#24991 was reverted, but the core `spotify` integration now supports [media_player.shuffle_set](https://www.home-assistant.io/integrations/media_player/#service-media_playershuffle_set) which I think is the intention of this issue.

**Comment by frenck** [comment]
Yes, we can close this architecture issue actually.
The shuffle can be set before starting playing something, as per official Spotify API documentation.
