### ISSUE TITLE
Removal of some Z-Wave node attributes from entities

### ISSUE THREAD

**Issue by cgarwood** [home-assistant/architecture#254]
## Context
Z-Wave includes a lot of attributes on its entities that I don't believe have any value in automations or living in the state machine. 

Currently every Z-Wave entity (sensor, switch, light, etc) has the following attributes (example from one of my sensors):
```
node_id: 32
value_index: 1
value_instance: 1
value_id: 72057594580844561
```

None of these attributes ever seem to change from what I can tell, and I don't see how any of them are valuable for running automations off of.

## Proposal
I propose removing the following attributes from Z-Wave `sensor`, `binary_sensor`, etc. entities:
```
value_index
value_instance
value_id
```

I believe some stuff still uses `node_id` to map entities to nodes, so I propose leaving it initially.

## Consequences

**Any automations based on those attributes would no longer function.**
This helps further clean up what is stored in the state machine.
Less unnecessary data in the state machine means smaller `recorder` database sizes

**Comment by kaijk** [comment]
I don't care about the latter two, but definitely need to keep node_id:  That is used for neighbor mapping, at least, and drives third party zwave topology visualization tools in HA.  The unconnected devices in the picture have lost their "neighbors" attribute and need to be "Refreshed" to recover  them.  I haven't figured out why this happens.  
![neighbors](https://user-images.githubusercontent.com/49624034/60682825-a46e3d00-9e49-11e9-8c60-f9b3531d8c32.png)

**Comment by DubhAd** [comment]
Leaving `node_id` is important I think. If nothing else it allows us to easily identify, in the dev-states menu, the related entities. The `value_X` ones don't seem to add anything useful for sensors.

**Comment by Swamp-Ig** [comment]
Right now `value_id` is needed to change the name of a value with the `rename_value` service call, although I will be putting in a PR in the near future to put this into the UI. 

I don't think the `value_id` is actually displayed anywhere else, so if this would need to be visible somewhere (probably the zwave panel, maybe in the Node Values tab?). If that gets done then I'm all for it.

Can we do this after we've updated the UI?

**Comment by cgarwood** [comment]
@kaijk Do those map tools actually use the `node_id` attribute of each individual entity? I would assume they go by the `zwave.abc123` entities instead of all the sensor, binary_sensor, etc entities.

@Swamp-lg Can definitely wait for UI updates. Though your specific example brings up another point I was considering making an architecture issue for. Should `rename_value` (among others) actually be service calls, or should they just be websocket API functions?

Long-term goal is to get the Z-Wave component cleaned up. There's a lot of legacy stuff floating around from the days before the entity registry, before the websocket API, etc.

**Comment by kaijk** [comment]
@cgarwood The graph code uses the zwave.abc entities and their attributes, not the light, switch, etc. entities on which the value_* attributes are found.  I'd still like to see the node_id on the entities, however for the reason @DubhAd mentioned, dev-states.

**Comment by OnFreund** [comment]
I personally find them useful for debugging and naming the entities of a node (and comparing with the XML).
For example, let's say you have a double switch with power/energy metering - using `value_instance` you can know which power/energy sensor is related to which load.

**Comment by happyleavesaoc** [comment]
Yes, if you need to make changes to the zwave XML, you need to know the node ID.

**Comment by OnFreund** [comment]
@happyleavesaoc not just the node ID, other values, such as `value_instance` are also very useful.
I agree that it might not be useful for automations, but it is very valuable information, so unless we have a different place to store it that is easily accessible, I propose keeping it as attributes.

**Comment by Fishwaldo** [comment]
Instance is to help identify the which values map to a multichannel device (say a 4 gang switch will generally have 4 instances of switches. 

Index may be useful more for device config Params (index maps to the param number). The other thing is that index’s are static, meaning that a Switch Index will alway have the same index value across devices etc. it can help to identify what Value does what (and not use the label as I have said many times).  

ValueID is really a internal OZW thing. I make no promises that a ValueID will remain the same between versions etc.

**Comment by decairn** [comment]
> I don't care about the latter two, but definitely need to keep node_id: That is used for neighbor mapping, at least, and drives third party zwave topology visualization tools in HA. The unconnected devices in the picture have lost their "neighbors" attribute and need to be "Refreshed" to recover them. I haven't figured out why this happens.

That broke for me with 0.91 (there was a change to do with not refreshing in background) and has not worked since without manual refresh of each node.  It is not affecting everyone though.

**Comment by OnFreund** [comment]
Can we close this? It seems like of the values proposed for removal, at least 2 of the 3 are needed.

**Comment by cgarwood** [comment]
Closing this now that the new ozw component is available and is close to feature parity with the old zwave component.
