### ISSUE TITLE
Add attribute or supported feature flag to identify cast enabled media players

### ISSUE THREAD

**Issue by fondberg** [home-assistant/architecture#255]
## Context

Add support cast player to indicate the device supports chromecast.
Intention is to be able a way to tell if a media player supports chromecast.

A real use case is to deprecate pychromecast direct usage in the custom component https://github.com/fondberg/spotcast (component strives to be made redundant as fast as possible after casting spotify to idle chromecast devices is made possible by home-assistant cloud (discussion with @balloob in discord a few months back)). The spotify-card lovelace card lists the idle chromecast devices using the sensor in the above CC to list idle chromecast devices which the user can initiate playback of Spotify on.

This can also be used for any other integration which requires the knowledge that the underlying device is a chromecast compatible
## Proposal

Either my quickly closed PR:
https://github.com/home-assistant/home-assistant/pull/24983
or an attribute for the entity.
## Consequences
As there currently is no way to tell if a media player entity is as cast entity components that want to build functionality for these will have to discover cast devices themselves using more resources and double work on the system.

**Comment by balloob** [comment]
I am not sure if this proposal makes sense. If a media player is cast-capable, it should already be exposed as a Cast entity. So in that case, all that is necessary would be to look at the entity registry and see which entities belong to the Cast integration. Those are the cast entities.

**Comment by fondberg** [comment]
Is this available for the frontend? I can't find anything which differentiates cast media players from other media players which makes it impossible to do extra automatons on only the cast enabled players such as start spotify.

**Comment by balloob** [comment]
Entities from the Cast integration have a unique ID, so they are all available in the entity registry. 

Code to fetch entity registry:

https://github.com/home-assistant/home-assistant-polymer/blob/60c2bcc4831f481c31df1180fc9b6be699df5b19/src/data/entity_registry.ts#L51-L54

Returned type is defined above it:

https://github.com/home-assistant/home-assistant-polymer/blob/60c2bcc4831f481c31df1180fc9b6be699df5b19/src/data/entity_registry.ts#L6-L13

Look for the entries with `entry.platform === cast`

If you're using this in a frontend card, best to use `subscribeEntityRegistry` defined at the bottom, as it will make sure that your data is always up to date.

**Comment by fondberg** [comment]
Great, this does indeed work, at least the list. As the card is a custom lovelace card I can't seem to find a way to get subscribeEntityRegistry to work.  Does the object  sent in with `set hass(hass)` contain this?

**Comment by balloob** [comment]
Copy paste the subscribe code into your own code, then pass in `hass.connection`.

Closing this issue as no change to arch necessary 👍
