### ISSUE TITLE
Climate 1.0: Add CURRENT_HVAC_FAN

### ISSUE THREAD

**Issue by andrewsayre** [home-assistant/architecture#259]
## Context

In climate 1.0, `hvac_mode` has a distinct operating mode for `HVAC_MODE_FAN_ONLY` but does not have a way to represent the fan running through `hvac_action`.  This means that when in fan mode, there is no way to report whether the fan is actually running or not.

## Proposal

Add a new constant `CURRENT_HVAC_FAN` to represent that the device is running the fan only.

## Consequences
- Climate devices can report action of the running fan through`hvac_action` consistently with other running actions on the device.

**Comment by andrewsayre** [comment]
This is a distinct proposal from introducing a `fan_action` -- which would describe the granular state of the fan, such as it's speed or other characteristics.

**Comment by pvizeli** [comment]
For me is that fine. No of my platform, they I had migrated, was needed this state, so I didn't add this. But if you have a platform, you can add it. I see no issue there or a needed architecture issue.

**Comment by andrewsayre** [comment]
> For me is that fine. No of my platform, they I had migrated, was needed this state, so I didn't add this. But if you have a platform, you can add it. I see no issue there or a needed architecture issue.

Sounds good.  The ST climate types have this option.  @balloob wanted to go the arch issue route to distinguish from `fan_action`.

**Comment by pvizeli** [comment]
okay, let do it 👍 it makes sense but I didn't add it because there was no need directly visible.

**Comment by balloob** [comment]
Alright, new hvac_action it is 👍
