### ISSUE TITLE
RFC: Device manufacturer / model reporting

### ISSUE THREAD

**Issue by ubnt-marc-khouri** [home-assistant/architecture#26]
### Goal

Report device manufacturer and model in a standardized way, accessible to other components and the frontend. For example, allow showing whether a Sonos player is a `Play:1` vs `Playbar`. Many components/platforms already have this info, but either report it in state_attributes, or not at all. 

### Proposal

1. [homeassistant/helpers/entity.py](https://github.com/home-assistant/home-assistant/blob/0.69.1/homeassistant/helpers/entity.py#L95): Extend `Entity` to include a `manufacturer_name` and `model_name` property (similar to `unique_id`)
2. [homeassistant/helpers/entity_platform.py](https://github.com/home-assistant/home-assistant/blob/0.69.1/homeassistant/helpers/entity_platform.py#L263): Pass the manufacturer/model information to the Entity Registry
3. entity registry: Store the mfg / model info, so that other components may access it
4. Platforms are extended to expose this information, for example in Hue:

```diff
# HueLight class
# https://github.com/home-assistant/home-assistant/blob/0.69.1/homeassistant/components/light/hue.py#L201
+    @property
+    def manufacturer_name(self):
+        """Return the manufacturer of the Hue light."""
+        return self.light.manufacturername
+
+    @property
+    def model_name(self):
+        """Return the model of the Hue light."""
+        return self.light.productname
```

**Comment by dgomes** [comment]
I also like the idea, actually some components such as camera already have model property:

https://github.com/home-assistant/home-assistant/blob/de50d5d9c1c0375c5e46042f3168d356c73f6aa1/homeassistant/components/camera/__init__.py#L254

**Comment by balloob** [comment]
We should make sure to align those. Note that this property will only be used for entities with a unique id.

**Comment by ubnt-marc-khouri** [comment]
As pointed out by @dgomes , the current Camera Entity class uses [`brand` and `model`](https://github.com/home-assistant/home-assistant/blob/de50d5d9c1c0375c5e46042f3168d356c73f6aa1/homeassistant/components/camera/__init__.py#L245), whereas my proposal is `manufacturer_name` and `model_name`. 

Any strong opinions on naming? I slightly prefer `manufacturer_name` over `brand`, but I don't feel strongly about it

**Comment by Kane610** [comment]
I prefer it as Zigbee does it; uses modelid and manufacturer

**Comment by balloob** [comment]
The downside of model id is that we can't just show it in the frontend.

**Comment by Kane610** [comment]
@balloob I see them as the same thing

**Comment by balloob** [comment]
Interesting. I would expect `id` to reference an identifier, `name` to reference a name.

I think that we should have the names contain the source + the attribute. So I wouldn't like `manufacturer`, I would prefer `manufacturer_name`. I think for model, initially I would be interested in the `model_name`, not the `model_id`. I would want to show a list of devices in Home Assistant.

**Comment by MartinHjelmare** [comment]
@balloob we can close this I think. It was solved with the device registry.

See https://github.com/home-assistant/architecture/issues/36.
