### ISSUE TITLE
Additional weather platform icons

### ISSUE THREAD

**Issue by MatthewFlamm** [home-assistant/architecture#263]
## Context

There are currently only a limited set of conditions they are supported with icons, but there are other relevant icons available for weather platforms.

## Proposal

I propose adding:

* ff55mdi-weather-tornado for tornado
* f897 mdi-weather-hurricane for hurricanes, tropical storms, etc.
* fe63 mdi-thermometer-chevron-up for hot
* fe62 mdi-thermometer-chevron-down for cold

Alternatively:
* fe61mdi-thermometer-alert for both hot and cold since temperature is also presumably displayed.

## Consequences

I don't think this breaks functionality for any existing platform, but only adds usable information for platforms that have these conditions.

There are still a few conditions that would be uncovered like dusty/hazy and other very specific conditions like volcanic activity, but the requested ones are fully supported in mdi and are common enough in my opinion.

**Comment by fabaff** [comment]
The available conditions are limited to a dozen different conditions because those are provided by the most used integrations. From my point of view it doesn't make sense to differentiate between a tornado or a hurricane. Both are storms and most likely covered by `exceptional`.

If you feel that we should expand the available conditions and move conditions out of `exceptional`, make a proposal please.

**Comment by MatthewFlamm** [comment]
I didn't see any documentation on `exceptional`, does it also have icon support?  During my digging, I also noticed that `hail` has an icon in the frontend, but is not documented either.

I'm okay with the current state given the existence of `exceptional`, although I do think `tropical-cyclone`, with corresponding icon would be a good addition.  There is a strong northern latitude bias in terms of weather platforms.

**Comment by MatthewFlamm** [comment]
I've found that exceptional is not supported.  It is just blank on the frontend.  Right now my forecasts for Florida show nothing for the days of predicted tropical storm or hurricane weather.
