### ISSUE TITLE
Climate: Add ATTR_TARGET_HUMIDITY_HIGH, ATTR_TARGET_HUMIDITY_LOW, ATTR_TARGET_HUMIDITY_STEP,  SUPPORT_TARGET_HUMIDITY_RANGE

### ISSUE THREAD

**Issue by stkang** [home-assistant/architecture#268]
## Context

Climate is a wide range of component.
(heat, cool, dry and fan)

The climate is the main function of Temperature control.

I think dehumidification is also very important. (dry)

However, climate can not use dry(humidity) alone.
ex) dehumidifier
I tried to develop it as a fan component, but I do not think it is appropriate to put the desired humidity control UI.

So I share the modified climate. 

https://github.com/stkang/home-assistant/commit/2e114302e84ca1fd584edd916406b8fc2e010e2a

Please review and let me know.

Thanks.

## Proposal

Add climate attribute and some modify code?
(ATTR_TARGET_HUMIDITY_HIGH, ATTR_TARGET_HUMIDITY_LOW, ATTR_TARGET_HUMIDITY_STEP,  SUPPORT_TARGET_HUMIDITY_RANGE)

**Comment by balloob** [comment]
We should not add `SUPPORT_TARGET_HIMIDITY_RANGE` as we're in the process of removing that flag for temperature too: #264.

**Comment by stkang** [comment]
@balloob 
Ok, no need :)
Can I pull request it?
Do you agree to modify the climate?

I know I need to get the architecture's consent to correct this.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
