### ISSUE TITLE
Add new device info attribute: default_device_info

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#277]
## Context

With device tracker integrations joining in with config entries, we now start getting multiple integrations describing the same devices. Device trackers can provide some information, like the manufacturer based on the Mac oui. However, this information should be considered as placeholders/defaults. It should not override the info in the device registry provided by the real integration.

## Proposal

Add a new field to `device_info` named `default_device_info`. This info will not override existing device info but only be used if certain information is not available.

## Consequences

It will become easier to show information about devices, which should make it easier for users to identify which product it is.

**Comment by MartinHjelmare** [comment]
I'm not really following. What is the real integration?

**Comment by Kane610** [comment]
If unifi registers a hue bridge to device registry it can't give as good details as the hue integration. With this it can add a bit more information about the device without worrying about it overriding higher quality information

**Comment by MartinHjelmare** [comment]
Will the id info of the device entry be the same even though the registering integrations are different?

**Comment by Kane610** [comment]
the id is just a random hex created by the first integration to register the device

**Comment by MartinHjelmare** [comment]
I was thinking of the connections and identifiers parameters that are used when fetching an entry from the registry.

https://github.com/home-assistant/home-assistant/blob/eba6caf8a17d7c3f6f5a725c459f7ea9252a1919/homeassistant/components/hue/__init__.py#L127-L128

https://github.com/home-assistant/home-assistant/blob/eba6caf8a17d7c3f6f5a725c459f7ea9252a1919/homeassistant/components/unifi/device_tracker.py#L265

https://github.com/home-assistant/home-assistant/blob/eba6caf8a17d7c3f6f5a725c459f7ea9252a1919/homeassistant/helpers/device_registry.py#L87-L96

So to answer my own question: It's enough that a connection info matches, even if no identifier info matches, to get a match when retrieving an entry. So when searching by mac address, part of connection info, both the hue and unifi entries will be retrieved.

Is that the problem we're addressing here?

**Comment by Kane610** [comment]
Exactly 👍

**Comment by balloob** [comment]
Correct, devices are not integration specific. See also the graphic at https://developers.home-assistant.io/docs/en/device_registry_index.html

**Comment by MartinHjelmare** [comment]
We have implemented default manufacturer, default model and default name in the device info.

https://developers.home-assistant.io/docs/device_registry_index#defining-devices
