### ISSUE TITLE
Add cooling_down and warming_up states to Media Player for projectors

### ISSUE THREAD

**Issue by IcyPalm** [home-assistant/architecture#279]
## Context

Recently I was setting up some automations for controlling a projector on the ceiling via PJLink in my local makerspace. I ran into the issue that the current PJLink component is not very fault tolerant and gives no real information back about the projector.

Examples include:
 - When the projector is on(Lamp is on) but no input is given the projector is shown as off (this is a wrong handling of error states) instead of Idle.
 - When cooling down or warming up (what can take quite a while) the status is shown as: off

The current state of the PJLink component is quite underwhelming, giving only two states.

## Proposal

The Idle state could be quite easily implemented without a core change to Home assistant but for the cooling and warming state there need to be added two more possible states to the Home assistant core. I kind of already created this([in this PR](https://github.com/home-assistant/home-assistant/pull/26155)) but was told to start an architecture discussion about this.

Possible options I see now:
 
 - Implement it the way done in my current PR: just add two more states to the Media Player component
 - Create a new entity type: Projector and move other projector components to there as well
 - Not implement the cooling/warming states and choose to ignore that(it is a choice, not sure if desired though)

## Consequences

As far as I can tell there are no real consequences to this. Maybe on the front-end side of things since more states(besides off/on/idle) need to be handled in the Media_player component

**Comment by elupus** [comment]
Would be nicer with more general, stopping starting.

**Comment by IcyPalm** [comment]
> 
> 
> Would be nicer with more general, stopping starting.

Good idea, I hadn't thought about that. That way it can be used way more general

**Comment by andrewsayre** [comment]
I like option 2, creating a `projector` entity type.  Media player always felt like a stretch to me for projectors because most of the features aren't applicable.

**Comment by pvizeli** [comment]
I agree with @andrewsayre a projector component and a media player. The media player for control the media type of projector and the projector component to control the projector specific stuff.

**Comment by dgomes** [comment]
I also support option 2. Too many things currently fit into media player (stream services, TV, STB, speakers)

**Comment by balloob** [comment]
I also say let's create a new type.

**Comment by IcyPalm** [comment]
Alright, I will start working on implementing a new type 👍 (if it turns out to something different I at least have the experience)

Could you elaborate your idea @pvizeli I don't quite understand how that should be implemented then.

**Comment by balloob** [comment]
Will close this to indicate it's resolved.

**Comment by elupus** [comment]
Aren't we a bit to specific? Why is a large TV any different from a projector? Considering it a "Renderer" would allow TVs as well.
