### ISSUE TITLE
Hook points into the UI

### ISSUE THREAD

**Issue by andrey-git** [home-assistant/architecture#28]
Hook points into the UI can allow advanced customization. Those hook points could be marked "unsafe" and changed - this would still be better that hooking in without hooks.

Below is the example of hooks cutomUI uses:
* The official `custom_ui_state_card` attribute
* Find un update group names via `partial-cards ha-cards[view-visible] .main ha-entities-card .name`
* When the user is on `/config` path, find `ha-config-navigation` element and inject a new config page into it.
* Change `LOGIC_STATE_ATTRIBUTES` to allow the user to hide additional attributes in 'more-info' and customize customUI attributes via the general UI customize editor.
* Change `partialCards.mqls` to allow redefinition of column width and number.
* Change `partialCards._defaultViewFilter` to allow hiding entities from view.
* Change `haStateLabelBadge.stateChanged` to allow theming top-of-the-page badges.
* Change `stateBadge.updateIconAppearance` to allow specifying `icon_color`.
* Change `localize` of `state-card-scene` and `state-card-script` to allow overriding the text on the button.

And one ring to rule them all:
* Change `homeAssistant._updateHass` to pre-process state update and change entity values according to user-supplied JS templates.

**Comment by balloob** [comment]
haha oh man, I knew you were doing crazy stuff, didn't realize you were going that deep.

I think that a lot of these things will be solved by moving to a hardcoded UI (#14):
 - We can add a hook to define your own column width
 - You can define your own custom components to render things such that:
  - You can update group names on the fly
  - You can color icons
  - You can update text on buttons

And you don't have to create your own complete components either. Instead, just extend it. We can add some protected methods such that it's easier to customize things.

```js
import HaStateLabelBadge from 'home-assistant-polymer/src/components/ha-state-label-badge.js';

class CustomStateLabelBadge extends HaStateLabelBadge {
  stateChanged() {
    super.stateChanged();
    // your custom logic
  }
}
```

**Comment by MartinHjelmare** [comment]
Is this still relevant after lovelace?

**Comment by balloob** [comment]
Nope. Rich customization is supported by Lovelace.
