### ISSUE TITLE
Add particulate matter 1.0 µm to air_quality platform

### ISSUE THREAD

**Issue by bieniu** [home-assistant/architecture#281]
## Context

At this time Home Assistant supports particulate matters 0.1 µm, 2.5 µm and 10 µm in `air_quality` platform. 1.0 µm which is provided by some services, for example, [airly.eu](https://airly.eu) (I'm developing component for this service) is not supported.

## Proposal

Add particulate matter 1.0 µm. I prepared PR https://github.com/home-assistant/home-assistant/pull/26483 

## Consequences

It seems to me that this change has no negative consequences.

**Comment by fabaff** [comment]
What services support PM 1.0? Usually only measurments should be added to the component which are available by most existing platforms.

**Comment by bieniu** [comment]
Examples of services that support PM1:
- [airly.eu](https://airly.eu)
- [looko2.com](https://looko2.com)
- [blebox.eu](https://blebox.eu)
- DIY sensors (PMS7003, PMS3003, PM2010)

**Comment by fabaff** [comment]
> PM2.5 and PM10 are definitely more popular but why should the platform not be able to provide additional data to user?

There is nothing against providing additional details. But additional details should be handled by a sensor to make it easier for user to create Lovelace cards. The `air_quality` was made when the primary way to display values on the frontend were built-in cards (like we have for the `weather` platforms).  

> PM0.1 is also not supported by most services, but is included in the platform.

The measurements were discussed before the implementation [was done](https://github.com/home-assistant/architecture/issues/109) and PM 0.1 was on that list. It's true that nowadays only one integration supports PM 0.1. Thus, with PM 1.0 we will end up in the same spot.

**Comment by bieniu** [comment]
I didn't know that the matter was already discussed. In that case, I close this issue.
