### ISSUE TITLE
Adding an Alarm Device Class for Binary Sensors

### ISSUE THREAD

**Issue by gcorgnet** [home-assistant/architecture#284]
## Context
The `binary_sensor` component offers various device classes which can each represent a particular use case for a `binary_sensor` (eg: a light can be on 'on' or 'off', a lock can be 'locked' or 'unlocked', etc..)
I recently installed a Konnected Interface into my Alarm Panel, which, amonst other things can create a `binary_sensor` that represents whether the alarm is 'armed' or 'disarmed'. I picked the closest `device_class` I could find, which in my case was `safety` but that is quite confusing in the UI.

## Proposal
I am suggesting a small addition to the list of `device_class`:

**alarm**: `On` means armed, `Off` means disarmed

## Consequences

This would let users present a `binary_sensor` to the UI that represents the armed state of an alarm, without rolling out their own custom sensor and writing unecessary code.
Very little risk as this is a small addition.

**Comment by gcorgnet** [comment]
PR for home-assistant.io: https://github.com/home-assistant/home-assistant.io/pull/10306
PR for home-assistant: https://github.com/home-assistant/home-assistant/pull/26508
I will create a PR in home-assistant-polymer if this goes through.

**Comment by MartinHjelmare** [comment]
Usually alarm panel devices are integrated as `alarm_control_panel` platforms and not `binary_sensor` platforms. Do we still need this device class?

**Comment by gcorgnet** [comment]
I realise this but as descrived above, the Konnected component exposes its inputs as a `binary_sensor`. One of these inputs can be set to reflect the armed/disarmed state. In my setup, I am also using manual `alarm_control_panel` which idicates what the state should be but there is a chance that they both get out of sync.

**Comment by balloob** [comment]
I don't think that there is a chance that they get out of sync because manual alarm control panel observes state changes and always adopts the latest state.

**Comment by gcorgnet** [comment]
> I don't think that there is a chance that they get out of sync because manual alarm control panel observes state changes and always adopts the latest state.

Not sure I was clear before. the `konnected` component generates a `binary_switch` entity which represents the actual armed state of the Alarm Panel. (as given by a programmed output on the alarm panel). The `konnected` component does not generate an `alarm_control_panel` entity and this must be rolled out separately, with no way to hook them up together, short of setting up automations that will update one when the other changes. Now, these automation may fail for one reason or another and I'd rather trust the `binary_sensor` being exposed by the `konnected` component rather than the manual `alarm_control_panel`.
I hope that makes sense...

**Comment by MartinHjelmare** [comment]
If `konnected` would implement an alarm_control_panel entity, would it solve the problem?

**Comment by gcorgnet** [comment]
> If `konnected` would implement an alarm_control_panel entity, would it solve the problem?

 I guess it would and I have been thinking I could give that crack as well but it's obviously more effort and would take me a while to get this together.
In the meatime, I thought adding thie `device_class` would at least let me display the status properly.

**Comment by balloob** [comment]
I don't think that we should add a device class as a temporary solution until an integration is creating the right entities.

**Comment by gcorgnet** [comment]
I think you might have misunderstood my comments above. The Konnected component will always be exposing `binary_sensor` entities and some of them can be programmed to represent the armed state of an alarm. To me, that is reason enough to include "Alarm" in the list pf possilble values for `device_class`

**Comment by gcorgnet** [comment]
Common guys, anyone nice enough to review this and try to understand my point of view?

**Comment by balloob** [comment]
Why would konnected still expose a binary sensor representing of it being armed if the alarm control panel exists to represent this ? I don't think your argument holds. Once konnected is fixed, the binary sensor will be gone.

**Comment by gcorgnet** [comment]
@balloob if we forget Konnected for a second. Can you honestly they it is inconceivable to have a binary_sensor entity that represents the Armed State of some sort of Alarm system?
Surely that should be useful beyond just Konnected...

**Comment by andriej** [comment]
Usually alarm units (or even the simple ones) have non-potential switch that they either connect or disconnect for armed/disarmed state. People tend to use it (when not using home automation) to automatically shut off water, so no flood risk.

**Comment by gcorgnet** [comment]
Hey guys, any progress on this?

**Comment by bubez81** [comment]
would be perfect to me! I'm in your exactly situation

**Comment by gcorgnet** [comment]
Thanks @bubez81 ! Come on guys, let's makes this happen!

**Comment by frenck** [comment]
Reading up, I don't understand the reasoning to add such a binary sensor. IMHO it pollutes the state engine, as the state is already present as part of the alarm panel (which should be used for alarms).

The current reasoning for adding this device class is based on a transitional reason, for a specific integration that should have implemented an alarm control panel in the first place.

Looking at the responses above, it seem that it does not get support from the core team. Therefore I think we should close and deny this request.

**Comment by okridgway** [comment]
Why not allow people to change the name of the on/off state of binary sensors to custom text? Perhaps making a "custom_class" and allowing the individual to specify what icon should be used when on, off, text of the true/false state, etc.

**Comment by LxFx** [comment]
I have a Jablotron alarm from with I receive the binary state of detectors and magnes and the alarm in general. I cannot arm the alarm using this way, only read out the state. Implementing the alarm control panel makes no sense for me, but I still want to show the alarm status (armed, not armed) in my HA interface. The request by OP is exactly what I expected to exist already, but apparently this is at odds with the complete alarm panel implementation. I think there are clearly use cases for both.

**Comment by LxFx** [comment]
A customizable binary sensor like @okridgway would be the ultimate solution to adding more and more hard coded device classes. It is also exactly what exists in other systems, for instance Loxone.

**Comment by okridgway** [comment]
@gcorgnet, @LxFx I made a new issue (#747)
