### ISSUE TITLE
climate: support for humidification devices

### ISSUE THREAD

**Issue by Shulyaka** [home-assistant/architecture#288]
## Context

A the documentation says, the `climate` integration is built for the controlling and monitoring of HVAC (heating, ventilating, and air conditioning) and thermostat devices. But the devices controlling the air properties are not limited to HVACs and thermostats. There is at least one more important class of devices that would fit naturally into the `climate` domain: Humidifiers.
We need the `climate` domain to be a more general domain for all devices controlling the air properties. However the current state of the component is inconsistent when it comes to humidification, which is only partly supported.

Humidity is in a way similar to temperature: we may have devices that raise and lower them, also both properties can be changed with ventilation to some ambient level, however in home assistant we do not have the feature parity between the two:

* We have HVAC_MODE_DRY, but we do not have HVAC_MODE_HUMIDIFY, so we support dehumidification but do not support the opposite yet
* There is a generic thermostat component, but there is no generic hygrostat component. This feature has been requested several times in the forum but didn't get enough attention so far. There are number of devices that don't have a native integration and could benefit from it.

The above issues are of course can be solved with some advanced automations, but that is not near as convenient as a `climate` device.

## Proposal

1. Introduce HVAC_MODE_HUMIDIFY and CURRENT_HVAC_HUMIDIFY constants to climate component. Probably there are other missing things that I couldn't find yet, e.g. frontend
2. Copy generic_thermostat component to a generic_hygrostat component and replace temperature references with humidity references to allow it control humidity (i.e. `max_temp` becomes `max_humidity`)
3. Optionally, to reduce code duplication, instead of generic_hygrostat create a more general template_climate component that would eventually deprecate generic_thermostat platform. The temperature references are replaced with some property-agnostic references (i.e. `max_temp` becomes `max_value`). The `ac_mode` parameter will be renamed and enhanced to allow humidity control. More changes might be needed to define the services supported based on the above parameter.

## Consequences

* More consistent features
* Allows to integrate a number of devices in a more natural way
* Opens up the possibility to create a platform in the future that combines a group of several climate devices into a single meta-device that automatically manages all aspects of the air and makes sure a humidifier and a dehumidifier (and a heater with a cooler) are not active at the same time in any room

**Comment by balloob** [comment]
I suggest that humidifiers become their own standalone integration. Just like switch and light, although both very similar feature wise, are different integrations.

**Comment by pvizeli** [comment]
I agree @balloob

**Comment by Shulyaka** [comment]
Apparently, HA developers want humidifiers to be a separate integration home-assistant/architecture#288

**Comment by jwillemsen** [comment]
I found out that some of the Daikin AC units do have a separate humidify operation mode in addition to dry and the other hvac modes. In order to support these it would really help if this discussion can be opened again, add a HVAC mode humidify, see #1077
