### ISSUE TITLE
Should services raise exceptions?

### ISSUE THREAD

**Issue by Adminiuga** [home-assistant/architecture#291]
## Context
This one is stemming from https://github.com/home-assistant/home-assistant/pull/26046#discussion_r326694985
Per current guidance "services" normally just log the error and return. We try to avoid leaking errors out of the integration. 
However, if the service raises an error, then user gets immediate feedback about service call failure, without need for user to sip through the logs. eg:
![image](https://user-images.githubusercontent.com/5826160/65352139-dc1e9280-dbb7-11e9-975f-20fe9ede3453.png)

## Proposal

Allow services to raise exceptions to inform users about failed service call. Let integration to decide whether the exceptions should be suppressed.

## Consequences

User will get an immediate feedback through a notification when a service call fails, supposedly with a helpful message explaining the nature of failure vs current behavior when user is in the dark about whether the service call was successful or not (unless the effects of the service call are visible immediately).

On a flip side, if a single "UI Action" triggers multiple service calls, then user would be flooded with the notifications.

**Comment by balloob** [comment]
All exceptions are bubbling up if a service is called with `blocking=True`. Feel free to throw things. The websocket handler will already deal with it for example: https://github.com/home-assistant/home-assistant/blob/5cf9ba51dff7e46c34d2a4dcc02cfabc6d45c2a5/homeassistant/components/websocket_api/commands.py#L146-L155

**Comment by Adminiuga** [comment]
Splendid!

**Comment by balloob** [comment]
I would even say that if there is a place where we call services and don't properly log it, that would be a bug 👍
