### ISSUE TITLE
Move quality scale and iot class to manifest

### ISSUE THREAD

**Issue by isabellaalstrom** [home-assistant/architecture#294]
## Context

The iot class and quality scale of an integration is shown in the documentation and is prone to be out of sync with the actual integration. It is also hard to determine these factors from a documentation perspective.

## Proposal

Move quality scale and iot class to the manifest for each integration.

## Consequences

This will allow for the documentation to sync this information in the future, and also keeping the information in one place, close to the actual code, makes it easier to update when an integration updates. While allowing the frontend to show it on the integration as well.

**Comment by balloob** [comment]
I like this 👍  Single source of truth. I think that @frenck was already experimenting with making the code the source of truth for a bunch of data in the docs.

**Comment by isabellaalstrom** [comment]
Yes, this suggestion was made after a discussion with @frenck. I don't know how to proceed :)

**Comment by frenck** [comment]
In the meantime, the quality scale has been moved into the manifest, the IoT class has not.
The IoT class is part of the configuration flow, however, that doesn't cover all.
Furthermore, it cannot really be used to sync to the documentation either.

**Comment by MartinHjelmare** [comment]
Both the quality scale and iot class are now part of the manifest.json.
