### ISSUE TITLE
Add new capability_attributes property to entities

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#297]
## Context

Our state objects contain various types of information:

 - information about the current state
 - display information (name, icon, entity_picture)
 - information about the capabilities (supported features, min/max mireds for light etc)

If an entity is not available, we will still include display information and the standardized information about capabilities (supportd features, device_class). However, we will not include other information about capabilities like the min/max mireds for a light.

Because of this lacking information, Google is unable to sync unavailable entities over.

## Proposal

Add a new property `capability_attributes` that returns a dictionary that will always be included in state attributes, even if the entity is unavailable. This new property will only be implemented by the entity integration base classes (Light, Switch etc). It should not be overridden by integrations.

Example implementation for light:

```python
    @property
    def capability_attributes(self):
        """Return attributes that describe device capabilities."""
        data = {}
        supported_features = self.supported_features

        if supported_features & SUPPORT_COLOR_TEMP:
            data[ATTR_MIN_MIREDS] = self.min_mireds
            data[ATTR_MAX_MIREDS] = self.max_mireds

        return data
```

These attributes currently live inside `state_attributes` and so will be moved.

## Consequences

It will be easier for external systems to understand the capabilities of unavailable lights.

**Comment by balloob** [comment]
CC @elupus

**Comment by elupus** [comment]
Is there any real point in adding a separate property for this? We already special case device_class, supported_features, ... in for example ToggleEntity::_async_write_ha_state. Can't we just extend that list with such capabilities?

**Comment by elupus** [comment]
I suppose that would expose child attributes at parent levels. Lika a reverse dependency, that would be a bit ugly. So yea i think this sounds like very nice idea.

**Comment by balloob** [comment]
Yeah, the challenge is that the entity class does not know what is relevant. The implemenetations do.

**Comment by Adminiuga** [comment]
>  It should not be overridden by integrations.

just to make sure I'm on the same page, in your example `self.min_mireds` and `self.max_mireds` are still provided by the integration, correct? If that's the case, is integration responsible for caching those values between restarts when the device is unavailable?

**Comment by balloob** [comment]
I was thinking the entity registry would be a good place to store this.

**Comment by balloob** [comment]
Here is an example implementation plus implementing it for lights. Storing it inside entity registry is not part of MVP. https://github.com/home-assistant/home-assistant/pull/29306
