### ISSUE TITLE
Proposal: Allow changing names through UI for MQTT Discovery

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/architecture#30]
## Proposal
Allow for a method to change names of entities through the UI just like with `unique_id` for MQTT Discovery component

## Use Case
There is development for a drop in replacement of `xiaomi_aqara` using `CC2531` stick to save some round trips and avoid the proprietary gateway. Currently there is https://github.com/Koenkk/zigbee2mqtt for the actual functionality using Home Assistant discovery setup, coupled with https://github.com/danielwelch/hassio-zigbee2mqtt hassio addon. 

## Current state
- Installation of addon is done through UI
- Pairing of devices can be done through MQTT or with some settings UI (input_boolean + automations)

Configuration of devices names can be done either:
- Manually if you avoid MQTT discovery in Home Assistant configuration yaml
- Manually inside zigbee2mqtt configuration yaml

As `xiaomi_aqara` already has Discovery through the gateway and `unique_id` is allowed, would be nice to have the same for `zigbee2mqtt`.

**Comment by balloob** [comment]
I think that this can easily be solved by allowing MQTT devices to specify a unique ID. That way they will end up in the Entity Registry and you can use the [normal frontend flow for renaming entities](https://d33wubrfki0l68.cloudfront.net/58cdda8d77bbea7be237f7e9b86a44eeb9d727f7/a73e7/images/blog/2018-03-0.65/entity-registry-name.gif).

The zigbee2mqtt project will be able to use Zigbee device serial numbers for unique IDs.

(this won't solve the services etc that @dgomes mentioned, but I think that is out of scope of the current discussion (and its own platform is probably best solution))

**Comment by ciotlosm** [comment]
Thanks @dgomes, @OttoWinter and @balloob.
