### ISSUE TITLE
Add ability to install add-ons at deployment

### ISSUE THREAD

**Issue by marksie1988** [home-assistant/architecture#303]
## Context

I am currently trying to automate the deployment of Hassio I have managed to deploy Hassio however there is no way to install add-ons through cli which makes it difficult with Ansible to automate deployment. 

Currently, Ansible deploys the Hassio docker installs, then it will add a webhook that will download all my ha config from github, however without the add-ons it won't work unless I go in and manually install them. 

## Proposal

Add a cli option for installing add-ons e.g. python3 -m hassaddon -install <add-on name> -config myconf.yaml

## Consequences

This would make it possible to fully automate the deployment of a Hassio server.

**Comment by balloob** [comment]
Seems to me like something for the hassio cli.

**Comment by marksie1988** [comment]
Is that available when not using hassos though? 

I use the advanced install and use the system on my existing docker platform. So I don't have the Hassio cli, unless I can access it somehow from the supervisor?

**Comment by frenck** [comment]
The Hass.io CLI can be used remotely, as documented in the hassio-cli repository.
Furthermore, Hassio has an API available, which you can use to install add-ons as well (which is used by the hassio-cli).
The API of Hassio is documented in the hassio repository.

**Comment by balloob** [comment]
I'm going to close this issue as this is for architecture issues and not for feature requests
