### ISSUE TITLE
switch show attribute

### ISSUE THREAD

**Issue by jie** [home-assistant/architecture#305]
## Context

The issue motivating this decision, and any context that influences or constrains the decision.

## Proposal

The change that you're proposing.

## Consequences

What becomes easier or more difficult to do and any risks introduced by the change that will need to be mitigated.

**Comment by MartinHjelmare** [comment]
You should only file an issue if you're proposing an architecture change and can describe *what?*, *why?* and *how?*, and is willing to do the work of implementing the change.

Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!
