### ISSUE TITLE
Add regex matching to zeroconf service names

### ISSUE THREAD

**Issue by jcalbert** [home-assistant/architecture#306]
**Home Assistant release with the issue:** 0.101.0.dev0

**Last working Home Assistant release (if known):** N/A

**Operating environment (Hass.io/Docker/Windows/etc.):** N/A

**Description of problem:**
Per https://github.com/home-assistant/home-assistant/issues/27371#issuecomment-540221641, https://github.com/home-assistant/home-assistant/issues/27371#issuecomment-544768878, https://github.com/home-assistant/home-assistant/issues/27371#issuecomment-545261330
Add regex matching for devices with specimen-unique zeroconf service names.

example:
Rainforest Automation's device's zeroconf have the form
`eagle-012abc._http._tcp`
so the associated zerconf entry in `manifest.json` would be
`  "zeroconf": ["eagle-[0-9a-f]{6}._http._tcp.local."], `

**Additional information:**

**Comment by frenck** [comment]
This has been implemented, not with regular expression, but we have wildcard support (`*`), which has been proven sufficient for our use case.
