### ISSUE TITLE
Avoid device tracker integrations having to add all devices to device registry to be able to disable them

### ISSUE THREAD

**Issue by THATDONFC** [home-assistant/architecture#307]
**Home Assistant release with the issue:**
0.100.2

**Last working Home Assistant release (if known):**
0.100.2

**Operating environment (Hass.io/Docker/Windows/etc.):**
hass.io

**Integration:**
unifi device tracker

**Description of problem:**
I think it would be nice to add the ability to select which devices we want to track BEFORE importing them as entities. I enabled this integration and all 30 of my network connected devices are showing as entities. I know it is possible to not track wired clients and unifi devices. But disabling the entities that are added is not enough. 

Example:
Integration installed -> Menu to select devices to add (or menu to select devices to exclude)
Integration installed -> Ability to delete entities from Unifi integrations page
Setup config file with IP/MAC list of devices to add -> install integration

Those are just a few ideas on how I think it could be done. 

**Additional information:**

Pinging @Kane610

**Comment by Kane610** [comment]
Thanks for this suggestion!

This is a very generic request that fits well with all device trackers, Im moving this to architecture

**Comment by MatsNl** [comment]
Related to this, should device tracker integrations also have config flow configuration instead of yaml? I'm referring specifically to router integrations like `ddwrt` or `tomato`

**Comment by MartinHjelmare** [comment]
Yes they should. I don't see how that's related.

**Comment by BlackRapsbeere** [comment]
Has this seen any updates?
`known_devices.yaml` was the way to go, but as I have heard the new architecture wants integrations to add all devices on startup and then have to user to disable them by hand.
This suggestion sees a renissaince now. I will add another suggestion to enable disabling devices in a list-mode rather than disabling every unwanted device by hand later.

**Comment by chemelli74** [comment]
I think there are 2 options to achive a clean and wide shared approach:

- add a dialog to select witch entities to track and not add any other to keep the device/entities list clean;
- add all entities like it's now and create a cleanup service for both stale and not enabled (aka disabled) entities.

It's a often raised topic, so we should device which way to go and move forward.

Just my 2 cents,

Simone

**Comment by Flop2006** [comment]
Is there anything new on this matter yet? I wanted to switch to the new FritzBox tools after updating my system, but unfortunately they are not usable like this.

I would prefer @chemelli74 approach "add a dialog to select witch entities to track and not add any other to keep the device/entities list clean;"!
Especially since apparently all tracker devices are entered as active in FritzBox Tools.

**Comment by chemelli74** [comment]
We need to be very careful with the decision.

One use case is to track new devices appearing on the network; for security purposes.

Eventually there should be a way to add/remove tracked devices later, if a user changes his mind.

All in all, I don't think that selecting devices at the begin makes much sense (BTW, I don't remember it was my proposal); much better to add all and then disable unneeded.

Simone

**Comment by balloob** [comment]
This is fixed in the next release.

**Comment by kongo09** [comment]
This has been closed as fixed. Can someone please help me find the fix?

Using FritzboxTools, I have disabled the option to enable newly added entities as I have a large number of devices on my network that I never want to see in HA.

However, I now switched one tracked mobile phone and would like to enable this, but there is no place to select it or enter its MAC / IP. I can't find the fix.
