### ISSUE TITLE
Configure core components using UI (config flow)

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/architecture#308]
## Context

Since config flow is the way forward for configuring integrations, the same should applied for core components (like input_select, input_boolean, maunal alarm panel, template entities...)

## Proposal

The config flow options and system_options dialogs will have to be modified to accept the different types of inputs required for configuring these entities. The current options dialog is very simple and will not allow configuring complex components (a very good example is the manual alarm panel).

I would like to have all components support config flow for configuring through the UI. What is the current plan for this approach. Will the core components be configured through the UI at the end?

**Comment by pvizeli** [comment]
Please no feature requests

**Comment by engrbm87** [comment]
Hello @pvizeli ,
I am not suggesting any feature request. I would like to help in moving all components configuration to UI and wanted to discuss the core components. What is the plan for them?
