### ISSUE TITLE
Proposal: Automation store

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/architecture#31]
# Proposal
Implement some sort of Automation Store in a git repo. This would allow users to pick up automations easier. 

# Current state
Users visit various sources for automation:
- Examples on git from other users 
- Examples in the webpages of various components on home-assistant.io documentation
- Examples in community forums 

All of the above are manual tasks and also are not versioned to match the current Home Assistant version.

# User journey
A user would be able to use the Automation Store to:
- Find automations that would be usable with available components in Home Assistant
- Find new automations published - Maybe allow "installed X times" types of meta to get popular automations on top
- Make sure they have tested automations for basic things

Integration with the current Automation Editor to allow changing of entities to match user's. 

# Benefits
- Easier for users to start with automation through the UI
- Better automation categories - Maybe find a way to link automations to components as examples on the website
- Surface easier popular automations

**Comment by fabaff** [comment]
The "current store" is the [Cookbook](https://www.home-assistant.io/cookbook/). There was not much interest/activity in sharing automation rules in the past. I can only guess but I think one reason is the editor and another that most automation rules are so simple that everybody can wrap their head around it. If it's get tricky then the samples will end-up often in the forum.

My problem is that I don't really see the benefit for an "Automation Store" that we need to maintain and will consume manpower. If mqtt is the trigger or a state then it doesn't matter but would result in 6 or so  different sample for a notification automation rule. Nowadays you just choose a different one in the editor and chain stuff together when you want more. In the long run should we improve the documentation to enable the users to create simple and complex rules on their own with the editor.

Well, the idea should definitely be discussed.

**Comment by ciotlosm** [comment]
@fabaff the way I saw it was, that automations in the store would be created by contributors just like hassio addons (easy to install / add from a git link). The automations than would simplify groups of automations that work together or more complex automations by autofilling most event chains in an enhanced automation editor, maybe even with decoration like hints on how to put in fields. 

I hope this makes more sense :-)

**Comment by balloob** [comment]
Most things for this are already in place in Home Assistant:

 - Automations are shared as components (ie [device sun light trigger](https://www.home-assistant.io/components/device_sun_light_trigger/)) and the configuration is just entity ids to match against
 - Components can be configured using a UI via config entries
 - Versioned is done because they are bundled with Home Assistant.
