### ISSUE TITLE
[FR] Flow-based visual editor for automations included by default

### ISSUE THREAD

**Issue by Gamester17** [home-assistant/architecture#312]
I have an architectural feature request so the hope here is the right place for an open discussion(?).

To make the programming of automations easier and more accessible to new users I would like to suggest that a simple and easy to use drag-and-drop flow-based visual editor for automations (and scripts) was included by default in Home Assistant's web-GUI, as an official 'first-party' visual editor of automations and scripts in Home Assistant.

Simple web-based editor for visual drag-and-drop coding (using so-called graphical programming blocks) automation flows via the web-GUI would make it much easier for people who are new to scripting automations, both to get started and get a visual overview of their automations and scripts from inside in Home Assistant's web-GUI.

I want to highlight that my main point here is to express that a stong wish that some type of simple drag-and-drop flow-based visual editor for automations (and scripts) was included not just an option that can be installed but that an official first-party one was always included by default with Home Assistant and that it preferable was even pre-installed by default in Hass.io

As you probably already know, there are several editor frameworks and libraries that could be used to achieve this; Node-RED perhaps being the most popular today, though I personally prefer the interlocking-blocks style of "Blockly" and "Scratch Blocks" which makes coding look simple, and an example of an open-source home automation software that specifically uses Blockly to simply programming of automations and scripting via drag-and-drop in its web-GUI is Domoticz (see https://www.domoticz.com/wiki/Blockly and https://www.domoticz.com/wiki/Automation#Blockly )

![Blockymonday](https://user-images.githubusercontent.com/28428427/69235924-cc5d0380-0b92-11ea-9b75-2ce2787e67ec.PNG)

Blockly (Blockly technology) upstream code is maintained by Google:

https://developers.google.com/blockly

Scratch Blocks builds on Google’s Blockly technology mentioned above and simply it even more

https://scratch.mit.edu/developers

**Comment by frenck** [comment]
So is this a feature request? Or are you willing to implement it?

**Comment by balloob** [comment]
This repository is only for low level architecture of Home Assistant.
