### ISSUE TITLE
Add new optional parameters `limit_entity_domain` and `limit_entity_integration` to services.yaml service object

### ISSUE THREAD

**Issue by raman325** [home-assistant/architecture#313]
## Context

As part of home-assistant/home-assistant#27289, multiple components were identified that have empty `services.yaml` because even though they have custom services that aren't available by default in a given parent `domain` like `device_tracker` or `switch`, the service has to be a part of that `domain` so that the right entity can be picked in the Entity list when making Developer Tools service calls. This has multiple consequences:

1. Service descriptions are living under the parent `domain` and not under the component they belong to:
    1. Service descriptions are loaded that will never be used because a user does not use the component that actually owns that service.
    2. With a goal of eventually delivering an app store like experience for components where components and their related metadata can be "installed" on demand, it seems logical that all information specific to a component should live within the component folder, including service descriptions.
2. Custom services belong to the `domain` of a parent device type: 
    1. It's not clear from the full `domain.service` name that the service only works for a particular component.
    2. Entity filtering doesn't actually work properly because all entities from the `domain` are listed, and the service call will fail for any entity whose `platform` is one other than the component that registered the service.

One solution to this problem would be to update the entity filtering logic to be able to also search for entities by `platform` instead of just by `domain`, which would allow parent `domain` entities to show up when making child component `domain` service calls, but that would also be confusing for integrations that have multiple parent `domains` since all of the entities that match that `platform` would be listed even though the service call will only work when the entity has the right parent `domain`.

## Proposal

1. Add a new optional parameter to the schema of the service object in `services.yaml`. I propose `device_type` since I thought `domain` might be confusing albeit accurate.
2. Add logic to the Developer Tools entity filter such that if the parameter `device_type` (or whatever it is deemed to be called) exists for a given service, filter on entities where `entity[domain]` = `service[device_type]` and `entity[platform]` = `service[domain]`
3. More of an optional if there's a concern about how much of a breaking change it would be to change the domain of existing custom services, but add fallback logic such that if, when a service call is made with an included `entity_id`, if `domain.service` isn't registered but `domain` exists, try a call to `entity[platform].service` before failing.
4. Migrate all custom services living under a parent `domain` to the component's `domain`.
5. Migrate all `services.yaml` service descriptions for these custom services from the parent components to the component's `services.yaml`

## Consequences

The net benefit is that:
- Custom services that are specific to a particular component will live under that component's `domain`, thus making the association more clear.
- Entity filtering in the UI still works as expected, and actually works better because today with custom services in a parent `domain`, all entities in that `domain` are listed including ones that the service call won't work for.
- All component custom service descriptions can be moved to the component's `services.yaml`, thus isolating all component data and metadata in one place

Since this is an optional parameter, this change will have no immediate impact to existing components. As part of home-assistant/home-assistant#27289, and a general migration, services could be migrated over from parent `domains` to the component's own `domain`.

The migration itself could be a breaking change for any automations/scripts/etc that call these services if step 3 in the proposal isn't implemented, but the risk of implementing step 3 is that it introduces hidden complexity that could create problems down the line, e.g. if the name of a custom service gets promoted and standardized to be available `domain` wide for a base device type but a component has a custom service with the same name for that device type that does something different. By the way, that example also suggests that this proposed change will make it easier for new services to get standardized for base device types and easier for components to migrate over on their own time. 

I should note that I have the ability to help with steps 4 and 5 but I am at a loss at how to actually implement 1, 2, and 3. Just throwing this out there to see if it sticks.

**Comment by balloob** [comment]
I think it would be nice to be able to add constraints to the entity_id field so we can make it easier to use in the UI. I would want to stick to `domain` as that's how we refer to domains, device_type is ambiguous as we have devices and device classes, both different things that wouldn't be used. 

Having an option to limit to entities that are related to an integration under the same domain could work too. They should probably be two options.

**Comment by raman325** [comment]
Do you see that option as being something configured in `services.yaml`? Not sure what to call that one, but for the new property I proposed, `domain` will work instead of `device_type` 👍

**Comment by raman325** [comment]
Not sure I understand what the difference between the options is. If `domain` is not provided in a service definition, then the default behavior can be to show all entities related to that integration. If `domain` is provided, then the behavior can be to show all entities related to that integration under the specified `domain`

**Comment by balloob** [comment]
Some services have other requirements. You can't default to limit entities related to that integration. For example the stream camera service takes a media player as a target.

**Comment by raman325** [comment]
Ah I see your point. So we could have three extra parameters at the field definition level in the name of maximizing flexibility:
`entity_field` -> Boolean that indicates that a field should have an entity picker (default is True if field name is `entity_id` or `entity_ids`, False otherwise)
`domains` -> List that optionally filters entity list by domain name (default is `None` and no filtering occurs)
`platforms` ->List that  Optionally filters entity list by platform name (default is `None` and no filtering occurs)

This should support most if not all scenarios and has the added benefit of making it easier for the UI to figure out when to provide an entity picker

**Comment by balloob** [comment]
domains and platforms is very ambigious. As you define a platform by specifying a domain. Variable names should explain how it's used, not what it contains.

**Comment by balloob** [comment]
- `limit_entity_domain` to limit entities to be from specific domains. (list)
- `limit_entity_integration` to limit entities to only be originating from a specific integration. (str)

**Comment by raman325** [comment]
OK so following the recorder pattern where there's a top level `include` and `exclude` how about:
`is_entity_field` -> Boolean that indicates that a field should have an entity picker (default is True if field name is entity_id or entity_ids, False otherwise)
`entity_include[domains]` -> List that Optionally filters entity list by domain name (default is None and no filtering occurs)
`entity_include[platforms]` -> List that Optionally filters entity list by platform name (default is None and no filtering occurs)

Alternatively the include parameters can be separate top level entries, and in the future a corresponding exclude parameter could be created if there's a use case that makes sense

**Comment by raman325** [comment]
I would be fine with either approach

**Comment by balloob** [comment]
> List that Optionally filters entity list by platform name

What does this even mean? 

I dont want to add very complicated substructures to `services.yaml`. It should remain simple.

**Comment by raman325** [comment]
I was attempting to maximize flexibility by allowing the entity list to be configured to come from multiple `integration`s (e.g. `domains`=[`device_tracker`] and `integrations` = [`unifi_direct`, `unifi`)], but if there is no valid use case that would require it then it does not need to be a list. I definitely agree with keeping the schema simple, I am just not aware of all of the existing use cases of `entity id` use in services

**Comment by balloob** [comment]
a service is either offered by an integration for its own entities or it targets domains. integrations should not be aware of other integrations so it cant be a list

**Comment by raman325** [comment]
OK makes sense, then lets stick with what you had originally proposed here: https://github.com/home-assistant/architecture/issues/313#issuecomment-558763612

**Comment by bramkragten** [comment]
I would like to propose to take this a step further and make the `service.yaml` a machine readable schema for all fields the service supports. This could then be used for both the frontend to create a UI and for automated generated documentation. This would give us a single source of truth.

Created a new issue https://github.com/home-assistant/architecture/issues/319

**Comment by raman325** [comment]
@bramkragten missed your proposal before I started submitting PRs. I think I should close them for now and we can revisit them as part of the larger effort for #319
