### ISSUE TITLE
Versioned "extra_html_url"

### ISSUE THREAD

**Issue by andrey-git** [home-assistant/architecture#32]
Currently custom UI loaded via `extra_html_url` has caching problem when a new versions is released.

Bellow I propose a few approaches how to solve that:

1) Make HA detect "local" files, fingerprint them on each call and inject url like `my-element-<hash>.html` instead of `my-element.html`. This will slow the page load.

2) Like (1), but fingerprint in the background and use the result next time. Latency now not affected, but still spends CPU and requires 2nd reload to get the updated file.

On Linux pynotify can be used to only FP if there were changes.

3) Allow refreshing the `extra_html_url` value from yaml via a service call. So when a new version of custom UI is released it should be uniquely named, the user should edit the config and call "refresh" service.

4) (1) + (3) fingerprint upon service call. Now user needs to call "refresh", but author doesn't need to name files uniquely and no config edit is required.

5) No fingerprinting, but maintain a random number added to the url: `my-element-random.html`. This number is changed upon service call, so a user can initiate a cache miss regardless of whether the file actually changed.

**Comment by andrey-git** [comment]
Yes, but currently it requires backend restart.

**Comment by andrey-git** [comment]
Given that I would like to avoid backend restarts and config edits I think either (2) or (4) is the best approach. (Also possible to combine those, so either a refresh or a service call will cause fp update)

**Comment by balloob** [comment]
I guess we can use a stat and append last modified time to the url. It's not slowing it down as retrieving the file already has to fetch it from disk.

**Comment by frenck** [comment]
`extra_html_url` has been deprecated and pending removal as of Home Assistant Core 0.115.
Hence, I'm closing this issue.
