### ISSUE TITLE
Add support for partlycloudy-night in weather component

### ISSUE THREAD

**Issue by MatthewFlamm** [home-assistant/architecture#322]
## Context

Currently the weather component only supports `partlycloudy`.  The icon `mdi:weather-partly-cloudy` displays a sun covered partially with clouds whether it is day or night.  

`clear-night` and `sunny` already distinguish a similar weather condition between day and night.  `sunny` is clearly incorrect at night, while `partlycloudy` condition itself is still accurate.  However, the icon support at night is incorrect, showing a sun.

None of the other conditions involve a sun or moon besides `partlycloudy`, `sunny`, and `clear-night`.

## Proposal

I propose adding `partlycloudy-night` as a supported condition with associated icon `mdi:weather-night-partly-cloudy`.  I suggest `partlycloudy-night` over `night-partlycloudy` to align with `clear-night`.  This would allow for icon support for nighttime for partly cloudy conditions.

I have not checked all integrations with weather platforms yet, and some have unclear weather code mappings without documentation.   By my interpretation, at least darksky, nws, envrionment canada, and meteo_france could utilize the new condition.

## Consequences

* Current integrations with weather platforms that support a day/night distinction will need to include `partlycloudy-night` support.  However, this is not required immediately, as it will continue to work with the current state.

* Some platforms may not support a day/night distinction, and the icon will continue to be incorrect at night.  This is no difference to the current state but may create confusion if some platforms support and some do not.  This confusion can already exist with platforms that do not support `clear-night` and only use `sunny`, e.g. metoffice.

* See also #321 for renaming `partlycloudy`.  If that is accepted, then this proposal would change to using `partly-cloudy-night`.  If it is preferred to follow the mdi naming according to #321, this proposal would change to `night-partly-cloudy`.

**Comment by balloob** [comment]
This proposal to change the backend seems to be driven by a wrong icon in the frontend?

**Comment by bramkragten** [comment]
I would suggest to change `sunny` to `clear` and let the frontend arrange it, maybe with the help of the sun integration?

**Comment by MatthewFlamm** [comment]
@balloob  The only available icons have a sun or moon.  How do you represent partly cloudy without one?  Thus it inherently needs some mechanism to distinguish.  This currently happens for clear conditions.

@bramkragten I assume you are suggesting that we use the appropriate icons on the frontend depending on sun.sun.  The problem I see is that we also use icons for forecasts in the future over several days, which I think cannot use the current state of sun.sun.

**Comment by bramkragten** [comment]
The forecast can always use day aI think?

**Comment by MatthewFlamm** [comment]
@bramkragten this could work for daily forecasts, but not for hourly forecasts.

**Comment by MatthewFlamm** [comment]
Also, what happens if I don't have sun.sun enabled in my config?

**Comment by bramkragten** [comment]
It would default to day if sun is not available.

**Comment by balloob** [comment]
I would always use day. The Home Assistant frontend is not set up to resolve icons based on other states, not should we complicate things by adding that.

**Comment by MatthewFlamm** [comment]
As an idea in this line of thinking, although I personally don't like it, could we use sun.sun in the backend?

All forecasts have a datetime associated with them and the current observation is now. The only question would be how to handle datetimes in future days where sun.sun doesn't help.  You could use todays sun events to resolve those.  

Or everything is day in forecasts.  I think you now need separate state logic for the observation and the forecast in each integration in the backend.

These both seem more complicated than adding two lines to the front end and one line per supporting integration in the backend for my proposal.

**Comment by balloob** [comment]
I am going to close this proposal as it is driven by a UI issue, which is not a reason to change our backend.

**Comment by MatthewFlamm** [comment]
Would you propose getting rid of `clear-night` to get consistent with this decision?

**Comment by balloob** [comment]
I think that would make sense.

**Comment by MatthewFlamm** [comment]
Can we collapse the states into `clear` and `partlycloudy` but add a second attribute for daytime/nighttime for observations and hourly forecasts?  Then integrations that can support it can supply this attribute otherwise the frontend uses day.

**Comment by da-anda** [comment]
> Can we collapse the states into `clear` and `partlycloudy` but add a complementary attribute for daytime/nighttime for observations and hourly forecasts? Then integrations that can support it can supply this attribute otherwise the frontend uses day.

this sounds like a good approach to me. I also see the logic to pic the correct icon in the frontend tbh, but with a state that explicitly says `sunny` that's kinda hard. So backend should report generic states and frontend can decide which icon to choose.

**Comment by Perlnx** [comment]
Is this problem resolved?
I using lasted Home Assistant Supervised 0.113.1 on Raspberry Pi OS and still saw the sun icon on partly cloudy after sunset.

**Comment by MatthewFlamm** [comment]
Read the decision above

**Comment by stth1998** [comment]
I found this issue while having to re-implement an automation after an API change in weather API and would just drop my workaround for the sun in partlycloudy at night. Maybe it is found here by someone with similar issues. it picks every third (weather) condition from an hourly forecast and joins it with ',' adding '-night' to partlycloudy between (exclusive) sun set and sun rise.

@MatthewFlamm 
... after going through that pain of debugging that write-only code, i also want to show the implication of this decision. Btw: I'd also had decided to remove `clear-night` rather than introduching `partlycloudy-night`. But it would have made this template expression even worse.

> I am going to close this proposal as it is driven by a UI issue, which is not a reason to change our backend.

`
  - action: weather.get_forecasts
    metadata: {}
    data:
      type: hourly
    target:
      entity_id: weather.home
    response_variable: hourly
  - action: input_text.set_value
    metadata: {}
    data:
      value: >
        {% set r =
        as_timestamp(as_timestamp(states("sensor.sun_next_rising"))|timestamp_local)
        | timestamp_custom("%H") | int %}{% set s =
        as_timestamp(as_timestamp(states("sensor.sun_next_setting"))|timestamp_local)
        | timestamp_custom("%H") | int %}{% set n = as_timestamp(now()) |
        timestamp_custom("%H") | int %}{% for i in hourly['weather.home'].forecast
        %}{%- if loop.index % 3 == 0 %}{% set i_n = ((n + loop.index) % 24) %}{%- if
        (i.condition == 'partlycloudy') and ((i_n < r) or (i_n > s)) %}{{
        i.condition}}-night{% else %}{{ i.condition }}{% endif -%}{%- if not
        loop.last %},{% endif -%}{% endif -%}{% endfor %}
    target:
      entity_id: input_text.hourly_condition
`
btw. `clear-night` is still there.
