### ISSUE TITLE
Ensure all registered entities are in the state machine

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#325]
## Context

The entity registry knows about entities, but not enough to be really useful. 

If an entity is registered, we also don't always represent it in the state machine.

Thanks to @elupus for the inspiration.

## Proposal

- Store `name`, `device_class`, `capability_attributes`, `supported_features` and `last_added` in the entity registry (WIP @ https://github.com/home-assistant/home-assistant/pull/30094)
- When event `home_assistant_start` is fired, write an unavailable state for all registered entities to the state machine that have no state yet and are not disabled. This state will include the extra attributes stored in the entity registry like device class and supported features.

## UI Proposal

If we are going to write a bunch of unavailable states to the state machine, we need some proper tools to clean this up fast, too.

Here is my proposal: pimp the more info dialog. Add tabs:
 - Controls (current more info)
 - Info (integration, extra attributes, device info, links to other entities in device)
 - Settings (entity registry, device registry, delete entity (state + entity registry entry))

Do not discuss the UI proposal. We will discuss it in the Polymer repo if we're moving forward with this.

## Consequences

- It will no longer be required that all devices are online and part of Home Assistant before syncing with Google/Alexa
- No more yellow boxes in the frontend that an entity doesn't exist. These entities now have a state that is unavailable.
- Integrations need to clean up the entity registry if an entity is no longer available. Example: User de-registers a LIFX bulb in the LIFX app, it should now be removed from the entity registry. This is something that can be gradually added. We'll need to add this to the quality level requirements.
- More states written to the state machine.

**Comment by Adminiuga** [comment]
Are these attributes going to be updated upon entity is added  or upon changes? Some integrations (ZHA 🙄 ) determine `device_class` in `async_added_to_hass()` i.e. after the entity was added. Would be great if those attrs were updated after `async_added_to_hass()` was executed or maybe allow entities to update `device_class` in the registry?

**Comment by amelchio** [comment]
> Example: User de-registers a LIFX bulb in the LIFX app, it should now be removed from the entity registry.

This is not possible, LIFX has no hub and no inventory. An undiscovered bulb might simply be turned off at the wall switch.

Sonos is the same, some people turn off e.g. outside players when they are not in use which I guess could be for weeks or maybe an entire winter.

**Comment by balloob** [comment]
Let's scrap LIFX as an example and instead use Hue, which has a hub and their own registry. 

@Adminiuga we could allow updating it in entity registry via the existing update method. Entity registry should not keep track of states in the state machine to keep itself up to date, that is too expensive.

**Comment by elupus** [comment]
An extension to this could be to deregister integrations if they become unavailable. It might end up cleaner than the integrations themself retrying connections. I say might here 😀.

But I think that is a separate discussion from this arch.

**Comment by MartinHjelmare** [comment]
> An extension to this could be to deregister integrations if they become unavailable.

What's an unavailable integration?

**Comment by elupus** [comment]
Chromecast disconnected from network for example.

**Comment by balloob** [comment]
I think that you're mixing up your definitions. Integration is what provides entities. 

Removing things from entity registry should be done with caution, as it means you're also removing the users customized name and entity ID. So only remove if you're 100% sure it's gone.

**Comment by Adminiuga** [comment]
+1, integration shouldn't remove entities from the `entity_registry` on its own. in other words an entity/device being unavailable does not qualifies for automatic `entity_registry` clean up. User should do it explicitly. 
IMO even when deleting an integration, we should have a checkbox "keep the entities", but that's a topic for another discussion.

**Comment by balloob** [comment]
Want to open an issue for that? (I have some opinions on that too)

**Comment by Adminiuga** [comment]
@balloob #326 Feel free to edit the description, as I probably bungled the explanation :)

**Comment by balloob** [comment]
I have updated https://github.com/home-assistant/home-assistant/pull/30094 to match the discussion in this issue.

**Comment by amelchio** [comment]
> Let's scrap LIFX as an example and instead use Hue, which has a hub which contains their own registry.

All right, I just wanted to point out the inherent inability because you said "need to". Wouldn't be the first thing to be generalized from Hue ;-)

**Comment by Jc2k** [comment]
If the `homekit` integration were driven by the entity registry and these new fields then does that mean we'd be able to get rid of the need for the "delayed start" hack? (I guess it's similar to the Google/Alexa case).

**Comment by balloob** [comment]
The `homekit` integration wouldn't need to do anything, as it will be able to read all entities from the state machine, as they will be restored at startup.
