### ISSUE TITLE
Using `input_number` for zha AnalogOutput cluster

### ISSUE THREAD

**Issue by Shulyaka** [home-assistant/architecture#328]
## Context

Hi,

I'm working on ZCL AnalogOutput cluster support for zha integration.
My current approach is to use `input_number` integration, that creates a nice slider, and when the user moves the slider we update the cluster attribute.
You can check the code on my draft PR here: home-assistant/home-assistant#30211

However there is one issue with this approach:

The `input_number` integration defines a `CONFIG_SCHEMA` which is verified during the component setup. If the user has at least one `input_number` entity defined in his `configuration.yaml` (unrelated to `zha`), then the `CONFIG_SCHEMA` check passes successfully. However when there is no other `input_number`s, and the `input_number` component is initializes within `zha`, then this check fails with the below error:

```
DEBUG:homeassistant.core:Bus:Handling <Event device_registry_updated[L]: action=create, device_id=528442ce8c094346a07588e7b7a9e09d>
DEBUG:homeassistant.components.zha.core.device:[47004](FakeModel): started initialization
DEBUG:homeassistant.components.zha.core.channels:[47004:ZDO](FakeModel): entry loaded from storage: ZhaDeviceEntry(name='FakeManufacturer FakeModel', ieee='00:0d:6f:00:0a:90:69:e7', last_seen=1577276935.3215)
DEBUG:homeassistant.components.zha.core.channels:[47004:ZDO](FakeModel): channel: 'async_initialize' stage succeeded
DEBUG:homeassistant.components.zha.core.channels:[0xb79c:1:0x000d]: initializing channel: from_cache: True
DEBUG:homeassistant.components.zha.core.channels:[0xb79c:1:0x000d]: channel: 'async_initialize' stage succeeded
DEBUG:homeassistant.components.zha.core.channels:[0xb79c:1:0x0000]: initializing channel: from_cache: True
DEBUG:homeassistant.components.zha.core.channels:[0xb79c:1:0x0000]: channel: 'async_initialize' stage succeeded
DEBUG:homeassistant.components.zha.core.device:[47004](FakeModel): power source: Battery or Unknown
DEBUG:homeassistant.components.zha.core.device:[47004](FakeModel): completed initialization
INFO:homeassistant.loader:Loaded input_number from homeassistant.components.input_number
ERROR:homeassistant.config:Invalid config for [input_number]: required key not provided @ data['input_number']. Got None. (See ?, line ?). Please check the docs at https://www.home-assistant.io/integrations/input_number
ERROR:homeassistant.setup:Setup failed for input_number: Invalid config.
```

## Proposal

I can see different solutions to this problem, but none are without downsides. They are either dirty hacks that reduce maintainability, or major code duplication (that reduces maintainability as well), or introduce breaking changes.

So I seek for your advice on this here.

## Consequences

Ability to control devices that feature AnalogOutput cluster. An example of such device is an XBee3 module which has PWM capability.

**Comment by MartinHjelmare** [comment]
The input_number integration is not meant to provide platform support for other integrations.

**Comment by Shulyaka** [comment]
Yes, but what would be a suggested approach here?
Enhance it to be able to provide that support?
Ignore and make a dirty hack that injects some missing parts into config?
Make a copy of the `input_number` and all its features (including nice lovelace support for it) just for zha?
Create a new parent integration and make current `input_number` belong to that platform?
Abandon the idea of supporting AnalogOutput devices and never ever try again?

**Comment by Adminiuga** [comment]
I think the correct question here: are there any objections of making `input_number` to provide platform support for other integrations?

**Comment by MartinHjelmare** [comment]
What is the problem that we want to solve? It's not clear from the description.

**Comment by Shulyaka** [comment]
> What is the problem that we want to solve? It's not clear from the description.

I will try to make it as clear as possible. 
I want to add support for devices that can output certain analog value. The user selects a value from the user interface or via an automation. The best way to do that seems to utilize the `input_number` integration. However as you mentioned it is currently not meant to provide platform support for other integrations. I am looking for a suitable approach to overcome this.

**Comment by frenck** [comment]
Currently, the only way to support that is by creating services that a user can use.

**Comment by Shulyaka** [comment]
Currently, yes. We can ask the user to manually configure an `input_number` entity, then manually create an automation that triggers on the value change and issues a zha cluster request command.
That's what I would like to improve with this issue, to provide a plug-and-play user experience, and probably to let other future integrations benefit from a slider UI control.

**Comment by balloob** [comment]
This issue is conflating the concern that you want a slider in the UI with the fact that the `input_number` integration is rendered as a slider. Input number should not be used by integrations to add sliders to the UI.

For ZHA we have a whole control panel, you can add as many sliders as you need there?

**Comment by Shulyaka** [comment]
Yes, you are right, I need an integration that is rendered as a slider in the UI. May be the `input_number` integration is not currently the integration that one can use to add the sliders. But I raised this architecture issue in a believe that such an integration could be done (as one of the solutions to the described problem).
I also believe other integrations could make use of it as well.

What is the ZHA control panel and how can I add sliders there?

**Comment by Adminiuga** [comment]
@Shulyaka can you provide specific real world example of what are you using Analog OutputCluster for?

@balloob is configuration panel expected to be used for "configuring" the aspects of Zigbee network and/or Zigbee devices? In other words we're not expecting to use config panel to configure the brightness of a Zigbee light?

I feel the AnalogOutputCluster falls into the same category is "light brightness"  it is a device where you control the output value in the same way you control the brightness of a light. If I had to choose I'd pick input_number integration to represent those devices as well.

**Comment by Shulyaka** [comment]
> @Shulyaka can you provide specific real world example of what are you using Analog OutputCluster for?

Well, I can provide my own use case. I am building a nozzle humidifier for my home. Its core is an electric water pump, and its speed can be controlled with a potentiometer. I have replaced the potentiometer with an XBee3 module which can generate a PWM signal. I would like to be able to control that speed from UI as well as from automations. So yes, it is more or less like "light brightness", except it is not about the light.

**Comment by balloob** [comment]
@Adminiuga oh I see now, didn't realize it was a feature of a device that is being controlled. 

input_number should still not be used, it's a pure user facing integration. We need to stay strict with that. We allowed scene to have both and it's a mess, especially with config reloading etc.

**Comment by Shulyaka** [comment]
What about creating a new integration and converting `input_number` into platform of that integration? The downside is that would be a breaking change for `input number`.

**Comment by balloob** [comment]
That's exactly what scene has and it's messy.

**Comment by pvizeli** [comment]
> The issue motivating this decision, and any context that influences or constrains the decision. Your motivation cannot include that the frontend is not representing the data correctly, as that is a frontend issue.

**Comment by Shulyaka** [comment]
My motivation is not the frontend not being able to represent something.

The issue is that we are currently missing a basic entity that other integrations could use for value input from user.
We have `binary_sensor` for binary output, `sensor` for value output, `switch` for binary input, and none for value input.
I filed this architecture issue in an intent to close this gap (or get an alternative approach).
Such integration should:
- have frontend support for user input
- expose services to change its state by automations
- be able to save and restore state
- provide a standardized way to set other properties such as unit and icon
The existing `input_number` integration meets those requirements almost perfectly, except it is not meant to be used by other integrations.

**Comment by Shulyaka** [comment]
> That's exactly what scene has and it's messy.

That's a different question why it is messy. I am sure it could be done correctly without any mess.

**Comment by Shulyaka** [comment]
I made `input_number` support other platforms!
Basically, you need 3 major changes:
- Set `required=False` in `CONFIG_SCHEMA` to allow integration setup with empty config related to the platform. Also allow empty integration config in `_async_process_config` function
- Save the EntityComponent into `hass.data["input_number"]` in `async_setup` function
- Add `async_setup_entry` and `async_unload_entry` functions.

That's it! No mess at all!

**Comment by Adminiuga** [comment]
what happens when you call `input_number.reload` service?

**Comment by Shulyaka** [comment]
Configured `input_number` entities reloaded. Entities added by ZHA stay as they were.

I also got an exception in the logs, but it seems unrelated. One of my configured `input_number` entities has a state change automation trigger. It triggered during the reload with object set to None. But I'm pretty sure it is a different issue.

```2019-12-30 21:42:44 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.67723456] Received {'type': 'call_service', 'domain': 'input_number', 'service': 'reload', 'service_data': {}, 'id':
 31}
2019-12-30 21:42:44 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=input_number, service=reload, service_data=>
2019-12-30 21:42:45 DEBUG (MainThread) [homeassistant.components.hue.sensor_base] Finished sensor request in 0.035 seconds
2019-12-30 21:42:45 DEBUG (SyncWorker_3) [homeassistant.util.yaml.loader] Secret google_assistant retrieved from secrets.yaml in folder /srv/hass
2019-12-30 21:42:45 DEBUG (SyncWorker_3) [homeassistant.util.yaml.loader] Secret web_push retrieved from secrets.yaml in folder /srv/hass
2019-12-30 21:42:45 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=input_number.pump_strength, old_state=<state input_number.pump_strength=263.0; initial=None, min=0.0, max=1023.0, step=1.0, mode=slider, friendly_name=HHumidifier Pump Strength @ 2019-12-30T21:42:17.923679+03:00>, new_state=None>
2019-12-30 21:42:45 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=input_number.tosr0x_temp, old_state=<state input_number.tosr0x_temp=5.0; initial=None, min=-55.0, max=125.0, step=0.125, mode=box, unit_of_measurement=°C, friendly_name=TOSR0X-T Temperature State, icon=mdi:temperature-celsius, hidden=True @ 2019-12-30T21:42:17.919444+03:00>, new_state=None>
2019-12-30 21:42:45 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...ew_state=None>) at /home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/homeassistant/helpers/event.py:82
Traceback (most recent call last):
  File "/events.py", line 145, in _run
  File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/homeassistant/helpers/event.py", line 104, in state_change_listener
    event.data.get("new_state"),
  File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/homeassistant/core.py", line 370, in async_run_job
    target(*args)
  File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/homeassistant/components/automation/state.py", line 93, in state_automation_listener
    call_action()
  File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/homeassistant/components/automation/state.py", line 79, in call_action
    context=to_s.context,
AttributeError: 'NoneType' object has no attribute 'context'
```

**Comment by balloob** [comment]
did you look at `homeassistant/scene.py` ?

If it can be done without being messy, proof it and open a PR 😆

**Comment by Shulyaka** [comment]
Well, I can raise a separate architecture issue if you want, and we can discuss how scene.py could be improved.
In the meantime I kindly ask you to review home-assistant/home-assistant#30211

**Comment by Shulyaka** [comment]
> what happens when you call `input_number.reload` service?

You know, I just tried it again and this time the zha input_number entities got removed. I will need to investigate it.

**Comment by Shulyaka** [comment]
My main question is how it should be done correctly.

**Comment by Shulyaka** [comment]
Seriously, I would be happy to fix things if someone tells me the correct way.
If the way to go is to start with the `scene`, then I can create a separate architecture issue to discuss what's broken about it and how it should be fixed. I believe in Home Assistant and I am ready to invest some of my time into it.

**Comment by antonverburg** [comment]
Hi all. Currently I am trying to create a 'slow-pwm' device, it should be a virtual number, (for example from 0 to 100%), that depending on it's value switches a slow-PWM output (for example to control a floor-heating device, switching it for 15 minutes on and 45 minutes off in case value is 25%). But there is no input_number platform like we have for the switch. Same applies to the PWM-controlled pumps that I use. Currently they work via the RPI-PWM outputs. Currenly I abuse the component rpi_gpio_pwm for it, as it gives me a control to output a simple PWM signal, but this should also be a kind-of simple input_number slider that can be used to do something external that is a little more analog than a binary switch. I think a platform for analog output would be nice (or do I miss something and does this already exist?)

**Comment by Shulyaka** [comment]
You are not missing. There is currently no integration that can provide platform support for other components. Light and climate have their own sliders integrated, but such slider integration could be useful for other cases such as:
* Media player volume control
* Smart kettle temperature settings
* Camera brightness
* Setting of cover level
* rpi_gpio and arduino PWM output
* Bayesian sensor probability adjustments
* coinmarketcap events on configurable threshold
* Transmission or rtorrent download speed control
* Modbus register write

**Comment by antonverburg** [comment]
Wouldn't it be better to leave input_number as it is right now, and add an 'analog_switch' platform? At bottom line, input_number is not a platform, and making it both seems to me also a bad, confusing idea.

**Comment by Shulyaka** [comment]
I think the best option is to create a new general integration domain (say, `slider`, but probably it is not the best name, I will think about names), then convert `input_number` into platform of that integration. But that would introduce a breaking change. I plan to implement it and submit for a review, if it would be acceptable or not.

**Comment by pvizeli** [comment]
@Shulyaka you did not read the important rule here:
> Your motivation cannot include that the frontend is not representing the data correctly, as that is a frontend issue.

This is clearly motivated by a UI concern. You can really save your time. Input_* stuff will be like it is now because there come upcoming changes they not merge with this. Like @antonverburg said, the best solution is an `analog_switch` component.

**Comment by Shulyaka** [comment]
> you did not read the important rule here

I already responded to that. It's not just UI.

> there come upcoming changes they not streamlining with this

Could you point me to those plans if they are public?

> Like @antonverburg said, the best solution is an analog_switch component.

Yes, thank you, I will consider that. Just one question: shouldn't `input_number` be a platform for this new `analog_switch` component?

**Comment by balloob** [comment]
Really? We mentioned it so many times now. No input_number stays itself. Stop asking the same questions.

**Comment by Shulyaka** [comment]
I am really sorry for the misunderstanding I caused. I am new to the project and it takes me some time to get the goals and values of the community with respect to the technical design. Thank you.
