### ISSUE TITLE
Make notification services more consistent

### ISSUE THREAD

**Issue by ioangogo** [home-assistant/architecture#329]
## Context

Currently notification data is not very consistent, while this is mainly due to variations between the differences between notification providers, I feel like certain things like notification images and icons could be consistent and implemented as part of a notification integration. For example taking APNS and HTML5 push notifications(firebase), APNS calls an icon a badge where as firebase calls it a icon. This could be kept consistent and the API differences here are dealt with inside the integration.

Another reason this has been brought up is how messy the android notifications are with the new companion app
```yaml
data:
  data:
    android:
      notification:
        image: "https://www.yourimage.com/test.jpg"
```

this variation in notification service interfaces leads to messy automations an means in some cases one service call cant be used to issue notification on multiple devices that use different notification integrations

## Proposal

Having a consistent interface to common aspects of a notification service, this could either be achieved by forcing notification integrations to process api differences in the data section, but this may lead to breaking changes. Another consideration could be to move common features such as `icons`, `images` and `actions` out of the sub data section of service data and into the main data alongside `message` and `title` and have a consistent implementation for them.

## Consequences

depending on the path taken breaking changes could occur on a large scale. keeping data as is and adding common features that should be consistent alongside message and title will massively reduce breakage while still maintaining advance usages in the data section.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
