### ISSUE TITLE
Buttons as binary_sensors problem

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/architecture#33]
## Background

Currently buttons like Xiaomi that don't have anything physical to control directly are discovered as binary_sensors (either xiaomi_aqara platform or mqtt). This is fine, as you'd want to link all your automation into one unit.

## Problem

Because these are buttons ideally you'd want the button to send key press and key release so you can take actions based on those states, however there are multiple types of buttons:
1. Some send key press / key release
1. Some send click and type (single, double)
1. There are some that have even more states (like the cube)

The problems appear in case 2. where if you press a button multiple times, the binary_sensor state doesn't change as you always get "single" so writing automations based on this is impossible. For MQTT you can do workarounds by registering directly to the topic.

xiaomi_aqara  seem to use some sort of manual "bus fire": https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/xiaomi_aqara.py#L337 to get around this

## Suggestion
Adjust sensor to allow automation based on updates received not on to/from or create a completely new type of entity "controller"/"button"

**Comment by MartinHjelmare** [comment]
We usually implement buttons that are stateless as events and not entities. That solves the problem I think. Events can have whatever event data that is needed, ie button press characteristics.

**Comment by cgarwood** [comment]
The only problem with events is then you can’t trll how long a button is held down. I’m using a Lutron Caseta custom component that uses sensors for the pico remotes and if I press and hold a button the sensor stays active until I release it, so I could theoretically do something different for a long press. The actual remotes themselves don’t report special long press events, just key down and key up events

**Comment by ciotlosm** [comment]
@MartinHjelmare does it matter if a button has support for state or not? Very few button types are going to have a "pressed" state for long (there are a few red emergency buttons that stay locked once pressed). 

Also how would "events" be implemented in an "auto-discovery" component like mqtt?

@cgarwood as long as you receive both events, you can get around it with automations and timers but that would again be workarounds for something that is basic to some buttons. 

If we would have a new type of entity based on a sensor that has knowledge of key up/ key down and always publishes events for automation, would make life easier for a lot of things.

**Comment by balloob** [comment]
You can have an automation listen to messages on an MQTT topic, that would solve that?

**Comment by ciotlosm** [comment]
That beats the purpose of auto-discovery of entities, and you can't reuse that entity in multiple automations, you would have to reuse the topic manually

**Comment by balloob** [comment]
You can write an automation that

 - listens to a wildcard topic on MQTT
 - fires an event with that message

That will work like auto-discovery and you can build automations on top of that event. Also, you can just listen multiple times to the same wildcard topic in automations.

**Comment by MartinHjelmare** [comment]
I think we should close this.

- Stateless buttons should be implemented as events.
- MQTT now writes the state change immediately to the state machine, so has less risk of loosing quick state changes.
- Integrations that use MQTT as transport should implement new components, that depend on the mqtt component, that supports buttons as events. The new components can handle discovery as they need.
- We don't need to support auto discovery of every type of device in the general mqtt component.
