### ISSUE TITLE
Add supported_features flags for optional Air Quality Sensor values

### ISSUE THREAD

**Issue by Jc2k** [home-assistant/architecture#330]
## Context

In https://github.com/home-assistant/home-assistant/pull/30383 the new air quality sensor relies on getting the current entity state to work out which types of sensor data to expose via HomeKit to a users iDevice. E.g. it will only be able to expose a carbon_dioxide attribute if when HomeKit starts up it seens a carbon_dioxide reading in `hass.states`.

After https://github.com/home-assistant/home-assistant/pull/30094 that means that if an air quality entity is restored from the entity registry it will appear in hass.states with an unknown state and homekit won't be able to correctly configure it.

## Proposal

For every optional attribute in the [air quality entity](https://developers.home-assistant.io/docs/en/entity_air_quality.html) there should be a feature flag that can be stored in the entity registry (via the https://github.com/home-assistant/home-assistant/pull/30094 mechanism). This will allow homekit (and presumably other integrations like Alexa or Google Assistant) to setup this data type even if it's not correctly plugged in and turned on.

## Consequences

It becomes possible for us to know what attributes an air quality sensor supports even if it's unavailable, which also allows the best user experience for homekit/alexa/google type integrations.

But it means adding 10 feature flags.

There are 10 air quality implementations that would need updating.

**Comment by elupus** [comment]
What about persisting sensor unit?

**Comment by elupus** [comment]
I realize that won't work since we expose multiple sensor values in a single entity.

**Comment by balloob** [comment]
Can we somehow use `capabilities_attributes` here ? Those will also be persisted/restored by the entity registry.

**Comment by Jc2k** [comment]
I'm not sure what that would look like.

 * We could have a field in `capability_attributes` that was a bitmask and worked exactly like `supported_features`?

 * We could have a `List[str]` of supported attributes in `capability_attributes`?

But the effect would be the same so happy with whatever you feel is most idiomatic.

**Comment by elupus** [comment]
As an aside. Media player modes suffer similar fate. We need modes/sources to be available on sync to google assistant. We may need to be a bit more dynamic on when we do syncs.

**Comment by ahayworth** [comment]
Removing the `air_quality` entity entirely and instead creating multiple `sensor` entities for a logical [device](https://developers.home-assistant.io/docs/device_registry_index) side-steps the issue of needing supported_features flags - see #362.

**Comment by Jc2k** [comment]
Better approach in #362, and implemented for homekit_controller in https://github.com/home-assistant/core/pull/54673 so closing this.
