### ISSUE TITLE
Addition of "open" or "ajar" and "failed" or "error" states for the lock entity model

### ISSUE THREAD

**Issue by NateRobinsonS** [home-assistant/architecture#332]
## Context

I'm looking into extending the (currently custom_component) implementation of Yale's Doorman Locks, accessed via the Yale Smart Hub.  The lock itself can report several states.  In addition to "locked" and "unlocked", it can report errors and that the door is "open" (and therefore the device cannot go to a locked state).

I have not researched this thoroughly, but it appears that other brands of locks can report similar states.

## Proposal

The addition of "dooropen" (or "ajar") and "failure" (or "error") as possible states in the lock entity model.

## Consequences

This change would allow the lock to indicate (to HA) that the door is open/ajar or in an error/failure state.

There is a small risk of confusion between the lock entity and the cover entity (which has a device class for doors and can be open or closed).  However, I believe that the contrast between the lock (which prevents opening of a door) and a "cover" (which would actually open or close the door) is sufficient to motivate keeping the entities separated.

**Comment by balloob** [comment]
Yeah, I think that those make sense to add. How would we have this impact the main state? Would we add `error` and `ajar`, and in the attributes specify the error if there is one ?

**Comment by NateRobinsonS** [comment]
Sounds like a good solution.  Using an attribute to specify the error would allow the various manufacturers to offer differing levels of detail regarding the source of the problem (depending on how sophisticated the hardware is).  The important features are:
1. a clear indication that the door is ajar (meaning that locking isn't possible), and
2. a clear indication (that can trigger an event) indicating that the lock failed to perform an action (e.g. to lock).

I don't think simply being "ajar" should put the lock into an "error" state.  However, I think a request to lock (secure) the door when the hardware is unable to comply (because the door is ajar) should put the lock in an "error" state.

**Comment by balloob** [comment]
Home Assistant represents the state as presented by the API. So it is up to the API to decide how to handle sending a lock request to an ajar lock.

**Comment by NateRobinsonS** [comment]
Understood and agreed.  I just wanted to clarify why I think that there should be two separate states (`error` and `ajar`).

**Comment by bdraco** [comment]
Homekit reports a state of "Jammed" so it would be nice to have a state to map to this.
```
      "ValidValues": {
         "Jammed": 1,
         "NotJammed": 0
      }
```

Do you know if there is an error state that isn't jammed besides "unknown error" that platforms regularly report?

**Comment by NateRobinsonS** [comment]
Does "jammed" translate to "unable to lock"? (I'm not an Apple user.)

**Comment by bdraco** [comment]
> Does "jammed" translate to "unable to lock"? (I'm not an Apple user.)

It indicates that the lock state is in between locked and unlocked and the device does not know if its locked far enough to restrict the door

**Comment by JOHLC** [comment]
jammed, locking, and unlocking would be good states to have 

Scenario with August smart lock: https://github.com/home-assistant/core/issues/51276#issuecomment-851051345

**Comment by bdraco** [comment]
I think it makes sense to add

`is_locking`, `is_unlocking` and `is_jammed`

Adding something about the door state is about the door and likely doesn't belong in the lock entity.

I'll put together a proposal when I have some free cycles in the next few weeks

**Comment by NateRobinsonS** [comment]
I reassert that the "state of the door", which determines whether the lock
can operate properly, belongs to the lock entity, particularly when the
lock is the source of the information.

**Comment by janiversen** [comment]
But the name “state of the door” signals lock can only be in a door. A lock should be useable for other items, like window, safe…

**Comment by NateRobinsonS** [comment]
True.  However, all locks hold "something" closed.  The problem then is the term "door".  I can't find a word that describes "cover", "door", "window", and other possibilities.

Is there harm in defining an "ajar" state for the lock?  It would be important to specify in the documentation that it is the item being locked, not the lock itself, that is "ajar".

**Comment by KapJI** [comment]
I personally think "ajar" is very ambiguous term which shouldn't be used as a state. "Slightly open" means "open", otherwise it's "jammed" or "error".

**Comment by NateRobinsonS** [comment]
Sure, but "open" and "unlocked" would, in most cases, be synonyms.  Giving a lock an attribute or state as "open" would therefore be confusing.  Do you have another suggestion for an attribute value that is less ambiguous?

**Comment by janiversen** [comment]
I think we need to think strictly in the states a lock can have, and not the things it work on. The lock itself can have unlocked/locked/jammed, while the door (if measured with a sensor) can have “closed/closing/open/opening”.

**Comment by bdraco** [comment]
The states should be mutually exclusive of each other. 

With error the lock could be locked but also in an error state.  

With ajar the lock could be unlocked and also ajar.

**Comment by NateRobinsonS** [comment]
> I think we need to think strictly in the states a lock can have, and not the things it work on. The lock itself can have unlocked/locked/jammed, while the door (if measured with a sensor) can have “closed/closing/open/opening”.

In the case of a Yale Doorman, the lock is the sensor, and detects that the door is ajar (and therefore cannot be locked).

**Comment by bdraco** [comment]
>
> 
> In the case of a Yale Doorman, the lock is the sensor, and detects that the door is ajar (and therefore cannot be locked).

We have a binary sensor class for this https://developers.home-assistant.io/docs/core/entity/binary-sensor/#available-device-classes

**Comment by KapJI** [comment]
> Sure, but "open" and "unlocked" would, in most cases, be synonyms. Giving a lock an attribute or state as "open" would therefore be confusing. Do you have another suggestion for an attribute value that is less ambiguous?

Ultimately this means that door or lock are still "open". For such extra functionality you can add state attribute `can_close: false`.

**Comment by NateRobinsonS** [comment]
> > In the case of a Yale Doorman, the lock is the sensor, and detects that the door is ajar (and therefore cannot be locked).
> 
> We have a binary sensor class for this https://developers.home-assistant.io/docs/core/entity/binary-sensor/#available-device-classes

Creating a binary sensor makes sense and allows the user to define the "opening" (door, window, cover, etc.) as appropriate.  I personally favor adding the "state" of the opening (opened, closed, or unknown) as an attribute to the lock entity, since that's where the information is coming from.  The binary sensor can be created from this attribute using a template sensor.

**Comment by Jc2k** [comment]
For what it's worth, AIUI HA is heading in the other direction than your preference and has been for some time. For example, the preferred way to model a battery that has a charging/not charging state is 2 entities, one of which is a binary sensor to indicate charging/not charging, one is a charge percentage sensor. They are then linked together via the device registry.

**Comment by bdraco** [comment]
Looks like alexa supports jammed as well https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-lockcontroller.html

**Comment by bdraco** [comment]
These will need to change to support it

Demo: https://github.com/home-assistant/core/blob/dev/homeassistant/components/demo/lock.py
Alexa: https://github.com/home-assistant/core/blob/dev/homeassistant/components/alexa/capabilities.py#L449 (small change)
Google Assistant: https://github.com/home-assistant/core/blob/dev/homeassistant/components/google_assistant/trait.py#L1103 (may not need any changes)
HomeKit: https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/type_locks.py#L18 (medium change)
HomeKit Controller: https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit_controller/lock.py#L11 (medium change)

**Comment by bdraco** [comment]
Google also supports is jammed

https://developers.google.com/assistant/smarthome/traits/lockunlock

**Comment by JOHLC** [comment]
Thank you!

**Comment by MartinHjelmare** [comment]
Implemented in https://github.com/home-assistant/core/pull/51455.
