### ISSUE TITLE
Climate support by ZHA component for Zigbee Thermostat control?

### ISSUE THREAD

**Issue by Hedda** [home-assistant/architecture#336]
Tracking any news on Climate support by ZHA integration component for Zigbee Thermostat control?

Posting this to hopefully track follow-up discussions for https://github.com/home-assistant/home-assistant/pull/24549 for discussions in regards to adding "Climate" control integrations support by the ZHA component that is needed for controlling Zigbee based Thermostats and HVAC systems which has now been made possible since #23899 has been merged by @pvizeli which in turn comes from the architectural review of Home Assistant climate entity in https://github.com/home-assistant/architecture/issues/22

https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html

Can see that both @presslab-us and @Adminiuga has been working solutions for this in dev branches

https://github.com/presslab-us/home-assistant/tree/zha-thermostat

https://github.com/Adminiuga/home-assistant/tree/ac/new-zha-climate-1.0

PS: Any tips about which models of Zigbee based Thermostat hardware is recommended for this?

**Comment by balloob** [comment]
Please fill in the template for new architecture issues.
