### ISSUE TITLE
Allow for a more dynamic supported_features

### ISSUE THREAD

**Issue by frenck** [home-assistant/architecture#338]
## Context

This is a revamp of a an earlier proposal: #1

I'd like to bring up that, closed/denied, proposal again, because I feel this would actually improve the system and provides means to enhance the user experience.

### Origin

I'm re-implementing the Spotify integration at this moment: home-assistant/home-assistant#30717

Which is the root cause of me opening up this discussion again.

More specifically, this review comment/discussion:

https://github.com/home-assistant/home-assistant/pull/30717#pullrequestreview-344423484

### What is `supported_features`

Entities have, depending on the entity component used, one or more `supported_features` assigned. This allows several parts of the system to know what features a device or service are supported by that entity.

This is a really nice feature, as it drives the capabilities of such an entity and is used to adjust the display of an entity in the frontend. It is also used for service calls, to only send specific calls to entities that support the used feature in that issued service call.

We also have other integrations that rely on the `supported_features` set of other entities. HomeKit, Alexa & Google Assistant are good examples of this. They use the same feature set to put up a device correctly to their respective platforms.

`supported_features` is implemented at the root [`Entity`](https://github.com/home-assistant/home-assistant/blob/d63ea198f2a9d65e2be4160f33688534744605df/homeassistant/helpers/entity.py#L227) class.

### Problem description

With the implementation of services (but not limited to services), it may occur that the supported set of features change during the lifetime of the Entity.

Good examples that may cause these are:
- Changes into the subscription status of the connected account.
- Changes to the devices connected to the cloud service.

Another nice common case, which was raised in #1, are Media Players. Our media player platform entity-component supports multiple sources of output. This can be the HDMI channel on a TV, audio output on a receiver or, in the case of Spotify, the Spotify Connect-enabled device handling the playback.

The problem for media players is that the media player entity-component only supports a single fixed `supported_features`-set, that does not have to reflect the feature set of the selected source.

The above results in an incorrect reflection of the capabilities of an entity, e.g., the frontend of Home Assistant. Adding a bad user experience. Some things that might occur right now are:

- Displayed buttons, that don't respond or work.
- Possible error's thrown by service calls
- Calls to entities that currently do not support the feature, while they did before, or could have supported in case ___ (fill in the bank).

### Doesn't it work already?

Yes! By the looks of it, it does.

Changing a set of supported features will cause the frontend to adapt and service calls actively query the property, so they are able to adapt to the changes instantly.

### The problem with non-static `supported_features`

Currently, we do not allow the `supported_features` to dynamically change during the lifetime of an Entity.

The main reason for this is because of other integrations that rely on this. For example, during startup, Alexa/HomeKit/Google Assistant, really need to know the capabilities of the Entity when exposing those to their respective cloud platforms.

Changing these during the lifetime of an Entity would be really hard to do? (Impossible even?)

### Earlier verdict

The earlier verdict in architectural proposal #1, seemed to be ended by the main following comments:

@amelchio 
> This seems like much ado about (almost) nothing. Can we just remove the dynamic features?
> It is crazy to have each individual platform add/remove a bunch of SUPPORT_PLAY-like bits based on their current playing state. That will give a lot of corner cases with inconsistencies and bugs.
> For now, though, I propose that we just ignore the issue and have a visible no-op Previous control in that situation. My DVD remote control always worked like that.

@balloob
> 👍 for making supported_features static across Home Assistant. It follows very much the "backend should not care nor try to solve frontend issues".

However, I do not agree, considering the context sketched in the above chapters, and I most certainly do not agree on having no-op buttons acceptable as user experience, because my DVD player does.

Also, it is not a frontend problem, since well, without correct information, the frontend would never be able to adjust.

I will try to make my point clear in this proposal.

### Active problem

Considering the previous chapter, we already have a problem. We do have quite a few integrations that already have dynamic `supported_features`, even if they don't at first glance.

A quick search through our codebase learns that quite a few integrations that implement the `supported_features` dynamically. One good example would be ESPHome. A user can change the capabilities of the device on the fly by flashing new firmware into it.

Please note, ESPHome is not the only one, there are a few more implementation that suffers from this.

Other examples of integration that has this same issue are:

- Fibaro
- WLED (change the RGB LED strip for an RGBW one)
- MQTT (autodiscovery?)

There are many more.

## Proposal

My proposal is basically the same as in #1, however, I wanted to put it on a higher level.

**Separate the set of possible `supported_features` of an Entity from the currently available feature set of an Entity.**

Basically creating a difference in:

- What an entity __could__ support, based on the implementation in the integration.
- What an entity is __currently__ supporting, based on the state of the environment inside the integration (e.g., state of a subscription).

This would allow for the dynamic use of those features and solve the problems described above.

The name of this has to be determined, but `active_features`, `active_supported_features`, `current_supported_features` are some things that crossed my mind quickly.

As a result, other parts of the system can decide on which of those sets it can and will use. For example, our frontend and service call helpers would probably use the active set, while HomeKit could rely on the possible features set.

### Example implementation

Small quick draft of how it would look like in our core:

```py
    # homeassistant/helpers/entity.py
    @property
    def supported_features(self) -> Optional[int]:
        """Flag supported features."""
        return None

    @property
    def active_supported_features(self) -> Optional[int]:
        """Flag currently active supported features."""
        return self.supported_features

```

```py
# homeassistant/helpers/service.py
async def _handle_service_platform_call(
    func, data, entities, context, required_features
):
    """Handle a function call."""
    tasks = []

    for entity in entities:
        if not entity.available:
            continue

        # Skip entities that don't have the required feature.
        if active_supported_features is not None and not any(
            entity.active_supported_features & feature_set for feature_set in required_features
        ):
            continue
```

### Not a solution

This proposal is not a solution to all of these problems. In the case of ESPHome, you don't want to expose all supported features all the time.

Accepting this proposal would mean it could be applied selectively, but we also have to accept some implementations not to implement it dynamically for a reason as mentioned above.

## Consequences

The above-provided example minimizes the consequences dramatically since the change is fully backward-compatible. However, it adds additional logic to the system.

A lot of tiny changes in a lot of places, e.g., the frontend.

## The alternative

There is an alternative: Allow for dynamic change of the current `supported_features` property we already have.

The consequence of this only effects integrations that rely on those during startup (like HomeKit/Alexa/Google).

This also doesn't require any further changes.

## Additional note

Even though I took ESPHome as an example for in this proposal, it is actually a bad example. Even this proposal would not solve the problem for ESPHome in this case specifically.

However, I used it as an example to make the point more clear and I would consider it being a "special" case.

## References occurrences of the issue

- [Rewrite of Spotify integration](https://github.com/home-assistant/home-assistant/pull/30717#pullrequestreview-344423484)
- [Add Tuya fan support](https://github.com/home-assistant/home-assistant/pull/15525#pullrequestreview-138610469)
- [Adding enigma2 media player](https://github.com/home-assistant/home-assistant/pull/15799#pullrequestreview-145463940)
- [Disable volume control for Onkyo when unavailable](https://github.com/home-assistant/home-assistant/pull/14863#pullrequestreview-127041733)
- [Add media_player.dlna_dmr component](https://github.com/home-assistant/home-assistant/pull/14749#pullrequestreview-126682102)
- [Add SmartThings Light platform](https://github.com/home-assistant/home-assistant/pull/20652#pullrequestreview-199008475)
- [Change HEOS component library and add basic config flow](https://github.com/home-assistant/home-assistant/pull/22517#pullrequestreview-220362354)

**Comment by pvizeli** [comment]
It's a pretty complex topic — more as it looks like on the first view.

I would suggest a middle way. Let's `supported_features` as it is and how it works now. But add a new `activeted_features`; they include only features they are needed to render it correct on UI.

**Comment by Jc2k** [comment]
I have a concrete example of this myself in homekit_controller.

A thermostat in homekit can have 4 modes. `off', `heat`, `cool` and `heat_cool`. `heat` and `cool` take a single target temperature. `heat_cool` takes a target range. How do I map this onto the HA climate type?

 * Does this mean sometimes `supported_features` should have `SUPPORT_TARGET_TEMPERATURE` and sometimes `SUPPORT_TARGET_TEMPERATURE_RANGE`.

 * Should `off` have neither? If not then which should it have?

I have tested this out in a branch and like you say, if `supported_features` does change the UI seems to cope. But if thats not actually supported then what is the right way to model this situation?

AIUI I think this meshes quite well with the idea of `active_features` or `active_supported_features`.

**Comment by balloob** [comment]
@Jc2k Architecture issue #264 should fix this.

Supported features should describe device capabilities. Not if these capabilities are currently available. 

The examples of ESPHome, WLED, MQTT etc changing supported features is not a problem. This is basically a hardware or firmware change, so yeah, those features change. That should be fine. These integrations are very flexible by nature and so this is ok. 

This issue at hand seems to be based on work on a media player integration. The media player was the first integration that added supported features, before it became an official thing in Home Assistant. And the current implementation is bad. It is bad because it conflates concerns of fundamental device features (ie control volume, source, sound mode) with current possibilities because of the media being played. The word "feature" is ambiguous and if I could do it all over I would name it differently. 

I don't think that we should have an `active_supported_features` that shares features/values of `supported_features`. 

I am in favour of splitting media player supported features. Have the ones that truly describe device features (ie set volume, select source, select sound mode) and create a new `player_options` which describe the current player options like can prev, can next, can play, can pause, can stop etc.  We could even move away from a bitmask and instead have options like: `yes`, `no`, `not available`. In case of prev track being "no", we could show a disabled button, a value of `not available` means the player would never be able to support this, regardless of the media so we don't bother even showing the button in the UI.

**Comment by iantrich** [comment]
+1 for moving away from bitmask. Better to be clear IMO

**Comment by frenck** [comment]
I like that @balloob, which would give more fine-grained control over media players and allows for handling the capabilities of media player sources as well. This requires some re-implementation at many locations, but that is manageable I guess.

**Comment by amelchio** [comment]
As I was quoted, let me just elaborate that I did not say that a no-op button is the best possible user experience. The comparison with a DVD remote was just to show that it is actually not that bad and users can (learn to) handle a no-op button.

When I wrote the original comment, I had bug reports about the Sonos integration hiding the Previous/Next buttons when it should not. Missing a button is IMO much worse than having a no-op button. I was unable to reproduce/fix the issue since it depended on music services that I did not subscribe to. Adding yes/no/NA will introduce similar corner case bugs. Also, we could be inherently unable to decide the playlist position with some music services. Or, for polling integrations, the information could just be stale.

If you can make it work, more power to you! However, against such inconsistent and buggy behavior, the user experience of a no-op button does not look so bad to me.

**Comment by frenck** [comment]
Thanks for your response @amelchio, I appreciate that.

It was not an attack 😉 I like how you clarified the DVD remote part. IMO, it doesn't matter, missing or no-op buttons are both experiencing similar things: Something should have worked from the user experience, but doesn't work as expected. One being missing buttons, the other not working buttons.

I agree that this provided/suggested solution will not be the solution for everything or every integration since we cannot incorporate unexpected behavior or bugs from a integration in our design. 

Hence, I believe that it is up to the integration to implement or use it correctly, or if that is not possible. It is up to the integration with path to take.

**My point with this was**: Right now, there is no choice. Even if integration is capable of handling it correctly, it is now forced into leaving it with no-op buttons for the user.


That said, I agree with balloob as well, the main case right now for my issue is the media player, which we should indeed maybe handle differently as suggested. That is quite a change, which is something completely different from this proposal.

Furthermore, some integration are dynamic by nature, and we could indeed accept the supported features go out of sync with our current run-time.

Considering the responses and suggestions, I'll go ahead and close up!

Thanks for the responses! 👍
