### ISSUE TITLE
Introduce a "link_quality" device class

### ISSUE THREAD

**Issue by pedrolamas** [home-assistant/architecture#342]
## Context

The current list of device classes is limited (I assume there are specific reasons for that) but there is a particular one that I find lacking: link quality.

At the moment, there is a device class for `signal_strength` but that is for "dB/dBm" values (documented [here](https://www.home-assistant.io/integrations/sensor/#device-class)), while link quality (provided by most Zigbee/Z-wave devices) is normally a value ranging from 0 to 127 or 255 and represented with "lqi" unit.

## Proposal

Add a new `link_quality` device class to the sensor.

## Consequences

Consistent styling and units for one, as provided by a specific device class.

**Comment by balloob** [comment]
These values really don't add much in the state machine. I feel like this is info that we want to show in a ZHA/Z-Wave panel but we shouldn't keep pushing this into the state machine to begin with. Who would automate on it ?

**Comment by PedroLamas** [comment]
Honestly, I thought the device class was for classification purposes only, which in turn allows us to set default metadata such as icon and unit (and this was my main end with this proposal).

**Comment by balloob** [comment]
Default metadata + how it behaves when synced to Google/Alexa etc. Just because we can put all the data in the world in the state machine, doesn't mean we have to. It's totally fine to just have it show up on the device info page.
