### ISSUE TITLE
Automation Inputs & Templates

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#344]
## Context

People like to share automations. However, sharing an automation is annoying if you need to look through the automation to find where certain entities or times are referenced. It also means that updating an automation means diving into the code.

This has been solved in programming languages for a long time by defining constants at the top of your code which are then consumed in your code. 

## Proposal

Add static values to an automation that can be referenced in actions, triggers and conditions. This will allow us to:

 - Quickly tune automations to your needs
 - Offer advanced automations in standard mode by only exposing the inputs
 - Make sharing of automations super easy

Static values will need a name, type, description and optionally a filter to limit the input type. Example inputs:
 - Binary Sensor device (to be used to trigger on)
 - Duration (can be used for how long a light should be on)
 - Light Devices (to be turned on)

We should build inputs in a way that we can make a UI for it to help users pick inputs. 

An automation with static inputs defined will be an Automation Template.

An automation with the inputs filled in is an instance. You can have multiple instances so you can also write 1 motion detection automation and reuse it in multiple places. 

Bonus, but maybe for v4000: input types can be defined as input_boolean etc so creating a new instance of an automation template will also ensure the right input_X things are made. 

## Consequences

Sharing automations becomes super nice.

**Comment by akasma74** [comment]
@balloob would it (indirectly) solve the long standing [issue](https://community.home-assistant.io/t/make-secrets-available-in-templating-engine/10507) with secrets not available in templates?
Like, I want to have a) `input_select` with some constant values and b) a template binary sensor that is `on` when `input_select`'s value is 'something' (one of its values).
Currently I can use secrets  to define `input_select`'s options but not in `value_template` of template sensor so I have to create another template sensor with `value_template`: `!secret something` and use its state in comparison in my original template.
Apart from creating that extra sensor, another downside is that this sensor is not readily available on HA start (unlike !secret's value) and one needs to check for `unknown` etc.
The resulting construction is cumbersome and fragile and it would be **absolutely amazing** to have a cleaner standard solution.

**Comment by balloob** [comment]
Secrets will never be available in templates. They are secret. Your reply is also off topic

**Comment by akasma74** [comment]
@balloob I mean is this feature something that would allow us using constants across various config files?
It's not a secret that people use constants declared in `secret.yaml` for that because they simply don't have alternatives (well, apart from custom `variables` components).
So hope it's not off topic .

**Comment by Misiu** [comment]
This would be super useful for thermostat automation. Imagine you have 5 thermostats and you want to control all of them. That's a lot of code. With templates, you could define logic only in one place and then create instances.
@balloob so if I edit my template all my instances will update?

**Comment by dlashua** [comment]
I think this is resolved with `variables` and `blueprints`.
