### ISSUE TITLE
Removal of timer.remaining attribute

### ISSUE THREAD

**Issue by akasma74** [home-assistant/architecture#345]
## Context

As far as I understand this attribute was never updated when timers were active and weren't paused (more details [here](https://github.com/home-assistant/home-assistant/pull/30198)), which caused issues like [this](https://github.com/home-assistant/home-assistant/issues/30062).
It is a useful attribute to determine when timer would finish as soon as it is updated every second **but** it then should be stored in state machine, which may seriously contribute to wear of sd cards, for example.

## Proposal
The goal is a) to avoid constant changes to the attribute and b) to give users information to determine when timer was recently started/restarted.

It is unlikely to achieve the first goal without giving up the idea of updating the attribute every second (and that makes the attribute pretty useless), which leads us to the proposal to remove the `remainig` attribute as incompatible with the current architecture.

The second goal could be achieved by adding an atribute like `expires`, which would hold a timestamp, for example.
The algorithm would be something like:
1. When timer is started/restarted, store utcnow()+duration into `expires`.
2. When timer is paused/finished/cancelled, we could do nothing (and leave it up to a user as `expires` makes sense only for a running timer) or set it to `None`/0. 

That way we can always tell when a running (i.e not finished/paused/cancelled) timed started (as it is useful information but one cannot rely upon `last_changed` attribute in case of restarted timer, for example) and when it would finish, which is what is often required.

The whole change is pretty easy and should solve a few issues.
The change would also include fixing the way [UI displays](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/common/entity/timer_time_remaining.ts) timers but it's also trivial.

## Consequences

Formally it's a breaking change as we remove an existing attribute.
On the other hand, it was never working properly anyway so it's hard to imagine users who rely upon such a broken functionality and therefore the impact would most likely be no damage but benefit (because they'll be able to fix their automations the right way).

**Comment by balloob** [comment]
The frontend uses `remaining` and it is working exactly as intended: it's time time remaining since the timer changed the state between running/paused/stopped.  

https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/common/entity/timer_time_remaining.ts

Relative times are not allowed in the state machine. Only timestamps and fixed durations.

**Comment by akasma74** [comment]
> The frontend uses `remaining` and it is working exactly as intended: it's time time remaining since the timer changed the state between running/paused/stopped.

in this case it just repeats `duration`, isn't it? I can see them always equal on active timers.

And is there currently a way to find out when an active timer was restarted for the last time?

**Comment by balloob** [comment]
The code I linked shows how to use remaining to calculate the current remaining time. 

Restarted is equal to last_changed of the state. Unless you want to differentiate between started and resumed, which is not possible.

**Comment by akasma74** [comment]
> Restarted is equal to last_changed of the state

you mean it equals to the time between when it was started and now?
The trouble is if you start and then restart a timer before it finishes, `last_changed` remains the same. It's logical **but** won't let us to find out when the timer was restarted for the last time (I need it sometimes, here's my [use case](https://github.com/home-assistant/home-assistant/issues/30062#issuecomment-583006855)).
Here's the junja code I pasted to Template editor
```yaml
{{ states.timer.sensor_pilight_ground_floor_kitchen_readings_expired.last_changed }}
{{ states.timer.sensor_pilight_ground_floor_kitchen_readings_expired.attributes.duration }}
{{ states.timer.sensor_pilight_ground_floor_kitchen_readings_expired.attributes.remaining }}
{{ utcnow() }}
```
and here's its output

> 2020-02-08 08:35:30.598860+00:00
> 0:04:00
> 0:04:00
> 2020-02-08 08:42:04.339370+00:00

I keep restarting my timer (as my sensor sends its readings within user-defined readings latency) but I can see no change in `last_changed` as it remains `active`, right?

So the bottom line is the code you linked relies on `last_changed` but won't work correctly for restarted timers so it needs to be addressed. One of the options is the proposed `expires` timestamp but I'm happy to accept any solution that would fix the currently malfunctioning component.

**Comment by Adminiuga** [comment]
> The frontend uses remaining and it is working exactly as intended: it's time time remaining since the timer changed the state between running/paused/stopped.

When you put it like this I have to agree it works as intended. But I have to admit, when I was using timers for the 1st time, I totally expected the `remaining` to indicate how much time is left on the timer from `now`  until expiration, not from when it was started/re-started.

and I think there's a subtle difference in treating `last_changed` as in state change or as a `timer` change. The problem is masked in Lovelace because you cannot start an already running  timer, **but** calling `timer.start` with the same `duration`  more than once within the `duration` period does not update the `last_changed` as in `state`, thus causing the FrontEnd to display wrong information.  A minor annoyance if you ask me. And it probably throws off @akasma74 calculations too.

What if we could have something like `target_expiration_timestamp` while the timer is running and `remaining` state attribute only when timer is paused? Thus re-starting an already running timer with the same "duration" would cause state to change (as it should) and Front End still can properly display the count down?

**Comment by Adminiuga** [comment]
Or an easy fix to use a "forced update" during restarts???

**Comment by Adminiuga** [comment]
@akasma74 
add to `Timer` entity class:
```

    @property
    def force_update(self) -> bool:
        """Return True if state updates should be forced.

        If True, a state change will be triggered anytime the state property is
        updated, not just when the value changes.
        """
        return True
```

And try again using the `last_changed`

**Comment by akasma74** [comment]
> I have to admit, when I was using timers for the 1st time, I totally expected the `remaining` to indicate how much time is left on the timer from `now` until expiration, not from when it was started/re-started.

that's a valid guess and it works **unless* your timer is restarted as I explained above.
my interest in when it was started/restarted is a bit different thing, but it is directly related to `last_changed` and `remaining` - that's why I'm here ;)

> and I think there's a subtle difference in treating `last_changed` as in state change or as a `timer` change.

I think the issue here is authors of the integration tried using the existing attribute `last_changed` but it's not always possible because we can restart timers (unlike entities that only change states when state string changes). Looks like a desigh flaw.





> calling `timer.start` with the same `duration` more than once within the `duration` period does not update the `last_changed` as in `state`

I think it does not update it regardless of `duration`. Are you sure specifying same duration is different than specifying a new one?



> What if we could have something like `target_expiration_timestamp` while the timer is running and `remaining` state attribute only when timer is paused?

I'm talking about the issue when timer is running and we call `timer.start`. No pausing here. No state change, it's still `active`. I thought I explained it in details above.

Not sure about `force_update`. I'm pretty sure the issue here is in the approach where the state concept is applied to an object that does not behave as an ordinary entity, namely:
ordinary entity has its state, that's basically all it has (let alone attributes) and when the state changes, we can see it and it's reflected by `last_chaged`. timers represent a delay of `duration` seconds so their `state` is when they are running or idle **but** there are also sub-states - `paused`, and it can be restarted as well. When we restart an active timer, it a) doesn't change its state- still `active` **but** its overall duration changes that leads to a different finish time - all without any change in `state`. More complex object, shouldn't be used alongside with simpler concept of `state`.

I can't test how would work a modified `Timer` class with `force_update` but if it would solve the with restarted timers, I'd be more than happy to accept it.

**Comment by Adminiuga** [comment]
> hen we restart an active timer, it a) doesn't change its state

Correct, because for the state machine the state has not changed. All state attributes and state itself are exactly the same. 
`force_update` should solve your issue without any requiring any other changes.

**Comment by Adminiuga** [comment]
Here's log with the change in place
```
2020-02-08 14:28:37 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=timer, service=start, service_data=entity_id=timer.fan_off_timer, duration=10>
2020-02-08 14:28:37 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event timer.started[L]: entity_id=timer.fan_off_timer>
2020-02-08 14:28:37 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=timer.fan_off_timer, old_state=<state timer.fan_off_timer=idle; duration=0:00:10, editable=False, remaining=0:00:00 @ 2020-02-08T14:15:11.002660-05:00>, new_state=<state timer.fan_off_timer=active; duration=0:00:10, editable=False, remaining=0:00:10 @ 2020-02-08T14:28:37.857450-05:00>>
2020-02-08 14:28:40 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=timer, service=start, service_data=entity_id=timer.fan_off_timer, duration=10>
2020-02-08 14:28:40 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event timer.restarted[L]: entity_id=timer.fan_off_timer>
2020-02-08 14:28:40 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=timer.fan_off_timer, old_state=<state timer.fan_off_timer=active; duration=0:00:10, editable=False, remaining=0:00:10 @ 2020-02-08T14:28:37.857450-05:00>, new_state=<state timer.fan_off_timer=active; duration=0:00:10, editable=False, remaining=0:00:10 @ 2020-02-08T14:28:40.913205-05:00>>
2020-02-08 14:28:43 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=timer, service=start, service_data=entity_id=timer.fan_off_timer, duration=10>
2020-02-08 14:28:43 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event timer.restarted[L]: entity_id=timer.fan_off_timer>
2020-02-08 14:28:43 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=timer.fan_off_timer, old_state=<state timer.fan_off_timer=active; duration=0:00:10, editable=False, remaining=0:00:10 @ 2020-02-08T14:28:40.913205-05:00>, new_state=<state timer.fan_off_timer=active; duration=0:00:10, editable=False, remaining=0:00:10 @ 2020-02-08T14:28:43.937019-05:00>>
2020-02-08 14:28:46 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=timer, service=start, service_data=entity_id=timer.fan_off_timer, duration=10>
2020-02-08 14:28:46 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event timer.restarted[L]: entity_id=timer.fan_off_timer>
2020-02-08 14:28:46 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=timer.fan_off_timer, old_state=<state timer.fan_off_timer=active; duration=0:00:10, editable=False, remaining=0:00:10 @ 2020-02-08T14:28:43.937019-05:00>, new_state=<state timer.fan_off_timer=active; duration=0:00:10, editable=False, remaining=0:00:10 @ 2020-02-08T14:28:46.457028-05:00>>
```

**Comment by akasma74** [comment]
@Adminiuga thanks for doing that. looks like it does the job as `last_changed` is updated on every restart.

Looks like there is no need in any architctural decisions provided the `force_updated` method is added to the `Timer` integration.

@balloob should I go ahead and close this issue and create a PR to the `Timer` referencing this discussion?

**Comment by balloob** [comment]
Yes, that would be perfect.

I also think that adding a target timestamp would be a nice touch, would make it a lot easier to also survive restarts if we ever get to add restore state. But we could leave that for a 2nd PR.

**Comment by akasma74** [comment]
> Yes, that would be perfect.

Ok, will do that soon.

> I also think that adding a target timestamp would be a nice touch, would make it a lot easier to also survive restarts if we ever get to add restore state.

Exactly. When I store the last restart time in input_datetime, it survives restarts and makes automations simple and more reliable.
That means adding a new attribute, correct? If yes, any preferences/suggestions in terms of its name?
I think it should be a separate PR (with reference to this discussion as well, just to clarify how we got there).

**Comment by balloob** [comment]
maybe `finish_timestamp` or `finish` ? And then I agree with @Adminiuga to remove `remaining` unless paused (and unfinished?).

**Comment by akasma74** [comment]
> maybe `finish_timestamp` or `finish` ?

how about `finishes_at`?

> And then I agree with @Adminiuga to remove `remaining` unless paused (and unfinished?).

that would be a 3rd PR I think. not sure I'm fully understand the complexity of it to tackle. @Adminiuga could you help?

**Comment by Adminiuga** [comment]
I'll do it.

**Comment by akasma74** [comment]
that's fab! cheers

**Comment by akasma74** [comment]
> The frontend uses `remaining` and it is working exactly as intended: it's time time remaining since the timer changed the state between running/paused/stopped.

a user [reports](https://community.home-assistant.io/t/timer-duration-limit/179048) that if he sets duration for more than a day the frontend does not update timer's countdown (but the timer itself is active) - can it be an indication that something is not quite right with the current implementation?
Just guessing, haven't checked further..

**Comment by akasma74** [comment]
Adios field marshall
