### ISSUE TITLE
Add translation guidelines for specific languages

### ISSUE THREAD

**Issue by vigonotion** [home-assistant/architecture#346]
## Context
In German, there are two main ways of addressing people: using the informal "du" or the formal "sie". Currently, the translations have both forms but should only have one.

## Proposal
Add language specific guidelines to the developer documentation and set up some guidelines like the formal/informal addressing in German.

## Consequences
The translations will be more consistent throughout Home Assistant Core.

**Comment by balloob** [comment]
I'm not opposed, but who reads documentation? It would be great if we could add language specific instructions in Lokalise.

**Comment by vigonotion** [comment]
That would be even better, though in the Lokalise documentation I cannot find something like this. They have webhooks when creating/updating keys, but no way of intercepting them (e. g. blocking translations containing a "formal" version).

**Comment by dgomes** [comment]
Well sometimes translators get stalemates with other translators on the proper way to handle the translation. A guideline such as the proper use of formal language or technical words from foreign language is appropriate.

**Comment by balloob** [comment]
Feel free to add language specific guidelines to the bottom of [this page](https://developers.home-assistant.io/docs/en/internationalization_translation.html). At least we can refer people to something.
