### ISSUE TITLE
Add moist mode for climate entities

### ISSUE THREAD

**Issue by avdeevsv91** [home-assistant/architecture#350]
## Context
In the current version, there is a drying mode, but there is no moisting mode for climate devices. Need to fix this (like the heat/cool example).

## Proposal

Pull request [#32173](https://github.com/home-assistant/home-assistant/pull/32173)

## Consequences

Simpler and logically correct implementation of climate control devices for air humidity.

**Comment by balloob** [comment]
This feature is not common enough based on our research. What devices do you know that have this?

**Comment by avdeevsv91** [comment]
All air humidifiers - several models from Xiaomi, Emoi, Electrolux, REDMOND, ZDK, Crane... There are a lot of them in the markets. Even an ordinary (non-smart) humidifier can be connected via a smart outlet and used as a climate device in HA.
The current DRY mode is suitable for draining air (this is logical), but not for moisting it. Translations also indicate this.

**Comment by balloob** [comment]
Air humidifiers should be their own type.

**Comment by pvizeli** [comment]
I agree with Paulus. The Fan support on climate is just for the fan on the heating/cooling to push the air into house. A humidifiers is not a climate. However I'm open to change my mind

**Comment by Adminiuga** [comment]
> Air humidifiers should be their own type.

Well, on that note, thermostats and "air handlers" should be their own type too and `climate` should be a meta entity comprising thermostat, air handlers, humidifiers, dehumidifiers, fans

**Comment by avdeevsv91** [comment]
> A humidifiers is not a climate. However I'm open to change my mind
I thought the climate was a device for controlling temperature and humidity. At the very least, the term "climate" (in the context of nature) includes the meaning of these parameters over a certain period of time. In addition, in climatic conditions, there is a HVAC_MODE_DRY, in the description of which it is written that this controls humidity (but on the contrary dries up).
> Well, on that note, thermostats and "air handlers" should be their own type too and climate should be a meta entity comprising thermostat, air handlers, humidifiers, dehumidifiers, fans
This looks more logical.

**Comment by MartinHjelmare** [comment]
There's an open PR to add a humidifier entity integration.

https://github.com/home-assistant/home-assistant/pull/28693

This was decided in this architecture issue:
https://github.com/home-assistant/architecture/issues/288

**Comment by avdeevsv91** [comment]
Thx, closed.
