### ISSUE TITLE
Hue: battery on 3 Hue sensors / threshold on Binary?

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/architecture#355]
## Context

The issue motivating this decision, and any context that influences or constrains the decision. Your motivation cannot include that the frontend is not representing the data correctly, as that is a frontend issue.

## Proposal

The change that you're proposing.

simplify the Hue sensors.
Seems that including battery_level on all 3 sensors is a bit much. Why not only have the motion_sensor carry this attribute. Wouldn't that offer some extra relieve?

secondly, since the binary_sensors hold the sensitivity on which they act or not, wouldn't it be more logical to add the threshold attributes to that sensor also. These now are on the light_level sensors. While the thresholds are about light_level, these sensors merely state the level. The Binary_sensor is the one acting upon the threshold.

Combining these into the Binary would offer a more logical set of state and attributes imho.

<img width="768" alt="Schermafbeelding 2020-03-07 om 12 14 24" src="https://user-images.githubusercontent.com/33354141/76142361-46939400-606d-11ea-8966-756c71146747.png">

## Consequences

What becomes easier or more difficult to do and any risks introduced by the change that will need to be mitigated.

Hope to make the integration lighter on the system, and more logical for the user.

**Comment by Kane610** [comment]
I think the current guidelines is to separate the battery sensor to its own entity

**Comment by Jc2k** [comment]
Indeed - thats what homekit_controller does. Then you use a device object to relate them to one another. E.g. I use my hue via homekit_controller (on dev it supports events which i need to test) and it looks like this in the device view:

![Screenshot 2020-03-07 at 11 29 38](https://user-images.githubusercontent.com/11544/76142601-1cd76e80-6067-11ea-9448-b5c5da055795.png)

And this in the device list:

![Screenshot 2020-03-07 at 11 31 17](https://user-images.githubusercontent.com/11544/76142608-337dc580-6067-11ea-8ab7-3689515ec1cd.png)

**Comment by Mariusthvdb** [comment]
Do you have a dedicated Hue battery sensor?
Of course I have created my own sensors:
```
    attic_motion_sensor_battery:
      friendly_name: 'Attic battery'
      unit_of_measurement: '%'
      value_template: >
        {{state_attr('binary_sensor.attic_sensor_motion','battery_level')}}
      device_class: battery
```
but the Hue integration doesn't create these as far as I can see. Would be even better, and all the more reason the streamline this?

**Comment by Jc2k** [comment]
I think we are saying that if this is going to change maybe Hue should create a dedicated battery sensor instead of having it on any of the sensors?

I posted a screenshot to show what it looks like in HA when you have a battery sensor that is linked to the motion entity via the [device registry](https://developers.home-assistant.io/docs/device_registry_index/). It's not a template sensor, it's created by `homekit_controller`. This creates a 'device' object for each accessory on a homekit bridge, and all the related entities can then be grouped by the device they are part of.

Sorry if i caused confusion with the screenshot also saying Hue. I happen to be testing `homekit_controller` with a Hue bridge at the moment because i'm testing out homekit push events with my Hue motion sensors.

**Comment by Mariusthvdb** [comment]
Agree on the dedicated battery_level sensor, shouldn't be too complicated?

what would you feel about taking it out off the other sensors then? Quite redundant to have the same value in 3, maybe even 4 sensors available.

**Comment by Kane610** [comment]
> Agree on the dedicated battery_level sensor, shouldn't be too complicated?
> 
> what would you feel about taking it out off the other sensors then? Quite redundant to have the same value in 3, maybe even 4 sensors available.

If the battery gets its own entity, absolutely

**Comment by Jc2k** [comment]
I totally agree too.

**Comment by Mariusthvdb** [comment]
cool, now lets hope one of the Hue dev's joins here ;-)

**Comment by Kane610** [comment]
That would be @balloob. Or you can create a PR to create battery sensors :)

**Comment by frenck** [comment]
I'll go ahead on close this architectural issue. The battery sensor should be separate.
This is not specific to the battery sensor, we want to avoid putting states into attributes in general 👍

**Comment by Mariusthvdb** [comment]
Ok Frenck, but is anyone 'assigned' to do this then? Seems 11 months without action is a bit overdue..
Or would you advice to create a new issue in the core repo referring to this

**Comment by frenck** [comment]
@Mariusthvdb You opened the architectural proposal to change something? This is not a feature request forum, this is a place to ask for architectural change one wants to implement.

Meaning you haven't been able to get to it the past 11 months?

**Comment by Mariusthvdb** [comment]
This must be a misunderstanding on my part. I have been waiting for some response here from the dev's side, what a final desired solution would be. Since only some have responded, but as far was I can see none of the core dev team, I guess we've all been awaiting that in vain.

So, sorry if that's the case. 
Guess, if no one is interested, we'll retain the core HA sensors with a lot of redundant info going forward.
thx.

**Comment by frenck** [comment]
All responders in this issue are core members.

Yes, we have legacy patterns, which is not a problem. Helping cleaning things up or migrate things to never patterns is appreciated.
