### ISSUE TITLE
Add a device class for gates

### ISSUE THREAD

**Issue by bdraco** [home-assistant/architecture#357]
## Context

Existing integration inconstantly classify gates as DEVICE_CLASS_GARAGE or DEVICE_CLASS_DOOR.  The current development docs state "Control of a door or gate that provides access to an area." for DEVICE_CLASS_DOOR.  The reality is that DEVICE_CLASS_GARAGE seems to get used for gates.   I am working on cleaning up myq, and plan on ismartgate next (if I can ever get them to agree to give updated api docs) and would like to have a consistent way to represent a gate.

## Proposal

Alter DEVICE_CLASS_DOOR description and add DEVICE_CLASS_GATE.  
https://github.com/home-assistant/developers.home-assistant/pull/444

DEVICE_CLASS_DOOR -> Control of a door that provides access to an area which is typically part of a structure.

DEVICE_CLASS_GATE -> Control of a gate that provides access to a driveway or other area. Gates are found outside of a structure and are typically part of a fence.

## Consequences

Integrations that support both gates and garage doors can now differentiate between them.  The downside is integrations that were classing gates as DEVICE_CLASS_DOOR or DEVICE_CLASS_GARAGE would need to be updated.  Additionally there would be the overhead of maintaining another device class.

**Comment by balloob** [comment]
Makes sense :+1:

**Comment by frenck** [comment]
Yeah, I agree on this one 👍
