### ISSUE TITLE
Recorder purge schedule

### ISSUE THREAD

**Issue by amelchio** [home-assistant/architecture#358]
## Context

The recorder purge schedule is hard to understand and barely documented, leading to confusion and bad configurations.

I think the `purge_interval` setting does not make sense. The only reason to raise it would be because purging impacts the normal running of Home Assistant. However, increasing it will only make the impact bigger when it does happen, due to larger transactions. Also, there should be less need to postpone the purging these days because the impact should be a lot less than it used to be. This is because we do not compact by default and because a huge join for state restoration has been removed.

Automatic purging happens at an arbitrary time that is related to the time Home Assistant was first started. For minimal impact, I think it would be better to run at a set time with assumed low activity.

## Proposal

I propose to remove the `recorder` configuration value `purge_interval`. I also propose to remove the logic that syncs purging to the oldest data in the recorder. Instead, do an automatic purge every night at 4AM.

I propose the addition of a `recorder` Boolean configuraton value `automatic_purge`. This defaults to true but can be disabled to enable custom purge schedules with automations.

As an alternative to the Boolean, a new setting `purge_time` could be considered, having the default `4:00` but with valid values including any time of day as well as `none`.

## Consequences

It becomes easier to document and understand the purge schedule.

Any stalls from purging will happen at a known time with less impact to most users. These situations will be easier to identify because the purge schedule is well known.

The default configuration will imply that daily purging is good. It will require more effort to do bad configurations with long purge intervals.

**Comment by balloob** [comment]
I agree. Maybe do 4:12 because of other things that might schedule themselves at the whole hour

**Comment by amelchio** [comment]
All right. I can work on this (albeit slowly).

After giving it some thought, I prefer to go with the Boolean configuration for enable/disable. Adding a time of day configuration is like starting a small automation system and we already have a big one.

**Comment by pvizeli** [comment]
I think we should set the auto purge to 3 days because people should see default (standard mode) the latest 3 days. The time is fine, all other can use an automation to solve his use case.

We should try to solve 80% of use case with default config.

**Comment by amelchio** [comment]
So you propose to also remove `purge_keep_days`? I don't mind that, a little friction before setting it to a year is probably good (at least while our database performance is so poor).

I originally [proposed to keep data for a week](https://github.com/home-assistant/core/pull/11903#issuecomment-360264581) but after a little back-and-forth @balloob wanted 10 days so he should probably chime in on changing the default duration.

**Comment by balloob** [comment]
The reason I wanted 10 days is that we can have a full week of data with some buffer, so we can do some basic learning.

I think that we should keep the number of days as a config option and a boolean for automatic purging sounds fine.

**Comment by pvizeli** [comment]
Sounds good

**Comment by dmak** [comment]
I think it is quite late for me to jump into discussion as `purge_interval` is already marked as deprecated. First: when @amelchio says
> However, increasing it will only make the impact bigger when it does happen, due to larger transactions.

what database backend he means? SQLLite? Was it checked for MySQL backend (which is currently implemented on MyISAM backend so does not support transactions)?
Second: I personally don't like the duality of the way how automatic purging configuration is implemented. If I am OK with every day purging, then it I should configure it with `auto_purge` + `purge_keep_days`. If I would like to setup purging say, every 5 days, then I need to setup `recorder.purge` service. Hot handy at all. Why `purge_interval` was causing any problems? Having a fixed time (or configurable fixed time) is fine, but making `purge_interval` deprecated is just blowing my mind.

**Comment by amelchio** [comment]
We _need_ automatic purge or disks will fill up, a poor default. The duality then follows because we can never make configuration options for all possible purge schedules that somebody wants.

> If I would like to setup purging say, every 5 days

If you want to shoot yourself in the foot, I don't mind hiding the gun a little.

> Why `purge_interval` was causing any problems? 

It was causing the problem that it was wasting people's time because it was widely misunderstood. For instance, when does the 5 days start?

The real question is: does a purge every night cause any problems? The answer is quite likely "no".

**Comment by dmak** [comment]
> For instance, when does the 5 days start?
In the same manner, when does "1 day" start? It is fine it is scheduled at fixed time 04:12 each day, why cannot it be scheduled 04:12 each 5 days?
> We need automatic purge or disks will fill up, a poor default.
Great. I solely support that.
> The duality then follows because we can never make configuration options for all possible purge schedules that somebody wants.
Still if it is possible to cover most of usecases (and I suppose that schedule for each N days is a popular usecase) within one piece of configuration, I would opt for that. I believe that other cases are more exotic.
> The real question is: does a purge every night cause any problems?
No, it does not cause any problems. But flexibility to have the number of days configurable without implementing the service is for me a plus. Simply because it is (was) one line in proper place of configuration file.
