### ISSUE TITLE
Ability to add and modify templates from the web UI

### ISSUE THREAD

**Issue by jrester** [home-assistant/architecture#365]
## Context

Currently to add an entity one still has to edit the yaml files, but it would be great if the same thing could be done from the UI. You can already write the templates in the web UI but the template must still be manually copied to the yaml files.

## Proposal

Add the ability to add and modify entities and templates directly from the web UI. So you can write the templates in the web browser, test them and directly apply them. 

## Consequences

This would help administrating a Home Assistant setup because you no longer need to leave the web UI. It also helps non-techie users to more easily use Home Assistant

**Comment by pvizeli** [comment]
That is not the place for future requests, do you want implement this feature? Yes, let this open otherwise close the issue.

**Comment by jrester** [comment]
Yea, I would like to implement this

**Comment by pvizeli** [comment]
You can look at `input_*`. It needs an API for the new panel + implements the hybrid helper like `input_*`.

**Comment by jrester** [comment]
I guess the simplest implementation would be to a config_flow to the template integration and couple that with an `input_template` Component that acts as a hybrid. But I am unsure if this implementation is very intuitive for the user because you don't expect to add a new entity from the integration panel but rather directly from the entities tab. Not sure if it is good idea to use config_flow for this.
Another way could be to construct the data and pass it to the config as it would be from reading a config file. Then setup the platform as it would normally be done. 

What do you think? Am I missing something?

**Comment by balloob** [comment]
It needs to be like input_*, based on collections.
