### ISSUE TITLE
Import of integrations and co to help users to convert their configuration from yaml to UI-based

### ISSUE THREAD

**Issue by edenhaus** [home-assistant/architecture#367]
## Context

The motivation is, that with [ADR010](https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md) the most integration's will be configured in the future over the UI. I don't want to talk about this decision here.
But we should think about the users, which must convert their yaml based configuration into the UI-based one. Converting them by hand is time consuming and also error prone.

## Proposal

My proposal would be to create an importer, which will converts automatically an existing yaml configuration into a UI-based one.

## Consequences

For the users it becomes easier to change their yaml-based configuration to a UI-based one.
I don't know how much it is to write an importer and we also need to discuss, what we do with integration's, which cannot be converted. Probably skip them and inform the user at the end.

**Comment by Kane610** [comment]
This is usually already the process when adding config flow support to existing integrations

**Comment by balloob** [comment]
That is correct. Every integration that has been migrated is converting YAML to UI. 

ADR-10 doesn't mean that our main focus is going to be converting integrations either. We just made sure new device/service integrations are using UI.
