### ISSUE TITLE
Add "key" mediatype for media_player entities

### ISSUE THREAD

**Issue by jjlawren** [home-assistant/architecture#369]
## Context

In context of https://github.com/home-assistant/core/pull/34412, I'd like to add a new possible mediatype that isn't available in https://developers.home-assistant.io/docs/entity_media_player/#mediatype. The Plex integration has the ability to uniquely identify a specific piece of media with an integer and the downstream library can also initiate playback without being provided context of what the media represents.

## Proposal

Allow `media_player.play_media` to accept a mediatype value of `MEDIA_TYPE_KEY` which represents a unique media identifier for the given integration. The "media" could be a discrete item (movie, episode, track) or a logical grouping of media (TV show, album), depending on the integration's capabilities.

## Consequences

Immediately, it would allow https://github.com/home-assistant/core/pull/34412 to be considered which would help troubleshoot playback issues with users on the Plex integration.

Longer term, this would go hand-in-hand with #331 which provides a lookup function for media. This lookup result identifier could be passed back as-is to the `play_media` service.

**Comment by bdraco** [comment]
Can you make the media type optional 
https://www.home-assistant.io/integrations/media_player/#service-media_playerplay_media

....and specify the unique id as the id?
https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by jjlawren** [comment]
Looks like `heos` has a similar use-case already to request playback by an identifier: https://github.com/home-assistant/core/blob/867138ebb8e3add49b8acba51aa126be5ba18374/homeassistant/components/heos/media_player.py#L168-L182.

It also appears that besides in the `play_media` service call, the `media_content_type` is used exclusively for handling images/thumbnails. If we can assume those two are decoupled and that the player will report back the proper `media_content_type` for the media it is playing _once_ it is playing, I see little harm in adding a unique (but context-less) identifier to request playback.

**Comment by jjlawren** [comment]
> Can you make the media type optional

Good question. Is it better to make it optional for when the `media_content_id` isn't known/defined, or is it better to be explicit and add a new `media_content_type`?

**Comment by balloob** [comment]
I think optional is fine.

**Comment by jjlawren** [comment]
After some [further discussions](https://github.com/home-assistant/core/pull/34550#issuecomment-618040897) we decided to allow integration-specific `media_content_type` values: https://github.com/home-assistant/developers.home-assistant/pull/470.
