### ISSUE TITLE
Add async_add_executor_job function to improve performance and avoid cpython bug 

### ISSUE THREAD

**Issue by awarecan** [home-assistant/architecture#37]
## Proposed Changes

```diff
--- a/homeassistant/core.py
+++ b/homeassistant/core.py
@@ -205,7 +205,7 @@ class HomeAssistant(object):
     def async_add_job(
             self,
             target: Callable[..., Any],
-            *args: Any) -> Optional[asyncio.tasks.Task]:
+            *args: Any, run_in_executor=False) -> Optional[asyncio.tasks.Task]:
         """Add a job from within the eventloop.
 
         This method must be run in the event loop.
@@ -215,7 +215,9 @@ class HomeAssistant(object):
         """
         task = None
 
-        if asyncio.iscoroutine(target):
+        if run_in_executor:
+            task = self.loop.run_in_executor(None, target, *args)
+        elif asyncio.iscoroutine(target):
             task = self.loop.create_task(target)
         elif is_callback(target):
             self.loop.call_soon(target, *args)
```

### 1. Performance
When we pass in a "sync" function to `async_add_job`, it has to pass three type check to get conclusion it is not an "async" function, has to put it into an executor. So if we know it is a "sync" function, as developer we should know, we can pass in a parameter to help short cut the decision tree. That should improve performance a little bit.

### 2. CPython bug
In a corner case, `asyncio.iscoroutinefunction` will throw exception instead return false, if you have time, you can read more detail information [here](https://bugs.python.org/issue33261). So by provide a parameter to bypass `iscoroutine` check will be a not-bad workaround in my opinion.

By the way, it is real world scenario, my code just hit this bug. Here is stack trace
```
  File "/home/jason/ha/home-assistant/homeassistant/core.py", line 223, in async_add_job
    elif asyncio.iscoroutinefunction(target):
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 258, in iscoroutinefunction
    _inspect_iscoroutinefunction(func))
  File "/usr/lib/python3.6/inspect.py", line 186, in iscoroutinefunction
    object.__code__.co_flags & CO_COROUTINE)
AttributeError: 'ProxyMethod' object has no attribute '__code__'
```

I have to write my own version of [_async_add_job](https://github.com/awarecan/home-assistant/blob/72b45169eb03003bd4d90bcb9036322b6e0ae2ed/homeassistant/components/binary_sensor/systemd.py#L68-L84) to avoid that.

## Approved Solution

Add `hass.async_add_executor_job` function.

**Comment by balloob** [comment]
We can't add a parameter to the function to make it choose something.. what you're proposing is a new function.

We were talking about that the other day with @andrey-git. I'm on my phone so don't know the pr anymore but we had list to split it up

**Comment by balloob** [comment]
Found the comment. https://github.com/home-assistant/home-assistant/pull/14429#discussion_r188084991

As initial plans were already laid out in that comment, I don't mind if we add a new function `async_add_executor_job` that behaves similar to `async_add_job` for threaded functions.

**Comment by pvizeli** [comment]
My problem with split the code is, that's never possible to cleanup the old code. At the end we mess the code base with a new function for maybe 400ms per 1milion requests.

I think we shold focus for a clean code base (core) they work as simple as possible. For Typing. We use python and that give this project the magic while we can do stuff that are not possible in other language. For runtime, typing make no change in python and that mean it's not usable.

**Comment by balloob** [comment]
So I just added a PR that introduces `hass.async_add_executor_job`. This function could probably replace like 80% of all calls to async_add_job. One thing that I like about this is that it will make it clear where we are using the executor.

**Comment by pvizeli** [comment]
Yeah I'm fine with this function but I say only that it's never been possible to cleanup the code base and we need maintain this two function with same functionality until the end of home-assistant asyncio usage :)
