### ISSUE TITLE
Add generic_water_heater entity similar to generic_thermostat

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/architecture#383]
## Context
Following the same concept as the generic_thermostat where a switch and a sensor is used I propose to have a generic_water_heater that also uses a sensor and a switch to control it.

## Proposal
A generic water heater will use a temperature sensor to read the current temperature. A switch will be used to turn on the water heater until the target temperature is reached.
for a simple water heater the concept will be as follows:
- the user sets the target temperature.
- the user sets the mode to ON.
- the switch turns ON until the target temperature is reached and then it turns OFF.

We can have an option to turn back on the switch if the temperature goes below the target temperature (similar to the how the climate entity works) but for me I don't want this to happen as I don't want the water heater to keep turning back on if the temperature goes down.

## Consequences

Since this isn't a smart device we won't have modes (like eco). In my case I have a water heater (boiler) with 2 electric coils. I have connected each one to a relay so that I can either have full power or half power. So if possible we can have these two modes and specify 2 switches so that in full power mode both switches turn on.

**Comment by mrand** [comment]
Would it make sense to just improve the generic_thermostat rather than having a new entity?

**Comment by engrbm87** [comment]
Since water_heater entity already exists we should also separate a generic water heater from a generic thermostat.
This also allows us to consider adding water heater type entities to the Google assistant smart devices. https://developers.google.com/assistant/smarthome/guides/waterheater

**Comment by antonverburg** [comment]
If the PID regulator based uppon this idea: https://github.com/home-assistant/architecture/issues/347 has been implemented (I'm currently working on that), you will automatically have a generic regulator, that also can be used as a regulator for a water heater. Wouldn't that be better? A generic regulator can be used for much more different purposes, and will require less effort in code maintenance.

**Comment by dgomes** [comment]
https://github.com/home-assistant/core/pull/44605

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
