### ISSUE TITLE
Metadata for person

### ISSUE THREAD

**Issue by ocalvo** [home-assistant/architecture#384]
## Context

There are multiple scenarios in hass where the system needs access to "personal identifiable data" (PID). 
- When doing integrations like SMS integration (to receive and send messages to a particular person)
- When doing external authetication via Facebook or Google, and email must be attached to the person/user that is trying to login.

## Proposal

Add PID data fields to person like (but not limited to):
  - Mobile Number
  - Work Email address
  - Personal Email address
  - Physical address

## Consequences

It will be easier and more secure to:
1. Specify a destination for a SMS message (as the phone number is now private in the PID repository and not in config).
2. Implement third party authentication that require a SMS number or Email address.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
