### ISSUE TITLE
Add precipitation probability to weather forcast

### ISSUE THREAD

**Issue by marawan31** [home-assistant/architecture#385]
## Context

There is currently no support for precipitation probability for weather cards and this is a very useful feature.

## Proposal

Add a percipitation probability attribute to enable weather integration to add that feature.
So basically this would add:
`ATTR_FORECAST_PRECIPITATION_PROBABILITY = "precipitation_probability"
`
in `core/homeassistant/components/weather/__init__.py`
## Consequences

Can't think of any major consequences.

**Comment by dgomes** [comment]
I support this!

Weather component IPMA could also provide this information

**Comment by fabaff** [comment]
Is this something that is supported by, let's say, 3/4 of the available platform? If not then we should not add it as the the weather integrations should be inter-changeable.

A discussion about the future of the "meta-integrations" takes place in https://github.com/home-assistant/architecture/issues/362.

**Comment by marawan31** [comment]
I see your point but given that it's an optional value it should be handled correctly. So far I've only checked env_canada but I would be choked if other platforms don't support it.

**Comment by TomBrien** [comment]
UK met office api gives it too. For me this is a fairly important value

**Comment by BradleyFord** [comment]
BOM Australia provides this data.

**Comment by MatthewFlamm** [comment]
NWS has it here
https://github.com/home-assistant/core/blob/e6065569ae1e3817b6e539c4a72be71acc92380b/homeassistant/components/nws/const.py#L9

**Comment by MatthewFlamm** [comment]
I would sightly prefer "precipitation_probability" as "prob" isn't a very common abbreviation.

**Comment by marawan31** [comment]
I agree, will update it

**Comment by marawan31** [comment]
@fabaff any updates on this?

**Comment by fabaff** [comment]
As we have a couple of integration which support this, let's add it.
