### ISSUE TITLE
Add device_classes for gas and valve, define const units for Light

### ISSUE THREAD

**Issue by CoMPaTech** [home-assistant/architecture#388]
## Context

For our climate and domestic Plugwise sensors we would like to introduce the device classes gas and valve. This allows us to classify the appropriate sensors (e.g. domestic gas measuring from a DSMR and valve for both open/close (binary_sensor) and open-% (sensor) measures.

While writing this for one of our PRs - there is a device class illuminance, but no defined unit for `lx` or `lm`.

## Proposal

Introduce 'GAS or volume (in m3)' (as in used gas for DSMR) and 'VALVE (in %)' while adding light level

 - Sensor DEVICE_CLASS_VOLUME declaring `type: volume` measured in (existing) unit VOLUME_CUBIC_METERS where users can use `mdi:gas-cylinder` or likewise indication
 - From the comments, a DEVICE_CLASS_FLOW might be a good suggestion as wel (in volume per second)
 - Sensor (and/or binary sensor) DEVICE_CLASS_VALVE declaring `type: valve` - measured in (existing) UNIT_PERCENTAGE where users can use `mdi:valve` or likewise indication (i.e. mdi:valve-open/mdi:valve-closed)
 - Introduce new Light level units LIGHT_LUX in `lx` and LIGHT_LUMEN in `lm`?

## Consequences

The units for VOLUME and FLOW should also include non DSMR standards like VOLUME_LITERS and VOLUME_GALLONS?

**Comment by BradleyFord** [comment]
Gas does not seem like a Device, I feel it should be flowmeter.
Then it can be used for multiple purposes such as liquid, gas, etc.

**Comment by CoMPaTech** [comment]
Valid comment, flow(meter) seems more in line too

**Comment by BradleyFord** [comment]
Yeah something along those lines should be good, I would probably use the
device class for other purposes.

**Comment by CoMPaTech** [comment]
Water-meters (ie DSMR-like if they exist), but also my city-heater volume/flow and probably people measuring guardenhose-systems or pond-fillers might benefit from DEVICE_CLASS_FLOW (in L/m3/whatnot)

**Comment by CoMPaTech** [comment]
Updated the issue, FLOW is definitely a good suggestion, but naturally would be a volume per time. For the original idea (DSMR-based metering) it should be a more generically VOLUME.

**Comment by shbatm** [comment]
What about VOLUMETRIC_FLOW and LIQUID_FLOW?

**Comment by MartinHjelmare** [comment]
I'm going to close this issue as it contains multiple suggestions that should be split into separate discussions and the gas sensor device class has already been implemented.

**Comment by CoMPaTech** [comment]
Apologies Martin, didn't realise it was still open
