### ISSUE TITLE
Need a name for sensor device class to show relative time

### ISSUE THREAD

**Issue by c727** [home-assistant/architecture#39]
Background is this PR: https://github.com/home-assistant/home-assistant/pull/14983 about the HA uptime sensor. Currently it's updating its state every 30 sec and flooding the state machine.

The state of the new sensor class will be an ISO formatted datetime (that you set once) and on the frontend we will show it as relative time like `3 days ago` and keep it updated there. (balloobs's idea)

Class name suggestions:
- period

**Comment by OttoWinter** [comment]
I mean it might be appear as a period in the frontend, but in the back end it's just a *timestamp*, right?

If we were to call it "time period" I'm sure that could cause some confusion trying to show a static time period, like travel time to work.

So I would say "timestamp" would be more appropriate.

**Comment by c727** [comment]
Hmmm... `Uptime: 3 hours ago` is a bit strange. So I will also change the default name to something like `Restarted` or we create 2 new classes: one will show `3 hours` and the other will show `3 hours ago`

**Comment by balloob** [comment]
I guess if we keep device classes to the content, timestamp is in this case the most appropriate. I guess the frontend will need to be updated to render it then both by showing the timestamp and showing how long it was ago. Depending on the data, one could be more important than the other.

**Comment by c727** [comment]
And do you think we should support both: `uptime: 3 hours` and `restart: 3 hours _ago_` or is one enough?

**Comment by c727** [comment]
Otto, I think for the static example we don't need a class as the state would not be updated every interval

**Comment by c727** [comment]
^it will effect this one device_class

**Comment by awarecan** [comment]
I also need one to display timestamp in future. For example, ETA: `in 5 minutes`

**Comment by balloob** [comment]
I think just making it device class `timestamp` is the way to go . If timestamp is in the future, we add "in X", else it's "X ago", depending on locale.

With experimental UI, people can choose if they want to see the relative time or the timestamp.
