### ISSUE TITLE
Prometheus plans & code ownership

### ISSUE THREAD

**Issue by knyar** [home-assistant/architecture#391]
@MartinHjelmare suggested discussing plans and ownership for Prometheus integration in https://github.com/home-assistant/core/pull/31945, so I just wanted to kick off a discussion here.

I have started [a short Google doc](https://docs.google.com/document/d/1qkKObZXbZPVVVc6E4qHRpD5WNWcN0FrOeZFtL3HD7NE/edit#) for us to discuss plans, but if folks would prefer to keep everything here, I can move its content into this issue.

I personally don't have a lot of features in mind, but a few questions related to metric naming came up when @mweinelt reviewed my PR linked above, so I've seeded the doc with some specific naming related improvements.

FWIW, I am also happy to be a 'codeowner' for Prometheus integration and review corresponding PRs.

CC a few other authors and reviewers of recent (2019 & 2020) Prometheus PRs, in alphabetic order: @balloob, @growse, @joegross, @mitchellrj, @nbarrientos, @perosb, @robbiet480, @springstan, @tcastberg, @treydock

**Comment by balloob** [comment]
Documenting the guidelines is a big 👍 

I don't think that a lot of new features are necessary, we just care about exporting it and that's that. Having rules on how we export should also be documented I think.

**Comment by balloob** [comment]
btw we don't have currently specific `README.md` in integration folders, but I'm in favor of that to document developer guidelines for the integration

**Comment by mweinelt** [comment]
What should be the way forward with regards to attributes? I recently add https://github.com/home-assistant/core/pull/35216 to expose those, but I heard they were on the way out. Where is the discussion on that?

**Comment by balloob** [comment]
Like Martin stated in that PR, attributes are on their way out. That's not going to be changed.

If you want to bulk export, use `helpers/debounce.py` to send data every 5 seconds.

**Comment by mweinelt** [comment]
Another kink with the current prometheus integration I have is that no namespace is set by default. This makes it quite a lot harder to find hass metrics and unnecessary pollutes the metric search feature of prometheus.

I think we should default that to `hass`.

**Comment by knyar** [comment]
> Another kink with the current prometheus integration I have is that no namespace is set by default. 

Setting up a non-empty namespace as the default will break metric continuity for most users, which will be very disruptive. 
What I would like to propose instead is a documentation change encouraging users to configure a namespace: https://github.com/home-assistant/home-assistant.io/pull/17722

**Comment by frenck** [comment]
@knyar There is no architectural issue needed for discussing the contents of a documentation parent PR.

Considering the other content of this architectural discussion has been conclusive and no longer needed, I'll go ahead and close this one up.
