### ISSUE TITLE
Add a slider entity, like a switch but analog

### ISSUE THREAD

**Issue by CJNE** [home-assistant/architecture#398]
## Context

We have the switch entity to display and control binary values but in case of values that are analog there is no simple entity that can be used to represent and control them. 
A slider entity could be a useful building block for integrations that want to offer control over such non-binary states. 

## Proposal

Add a new entity called slider.
It would work exactly like the switch entity but with the important difference that instead of "is_on" it would instead have a "state" property. Like a sensor but writeable.
The state change should also be accessible as a service.
Other properties would be min value, max value and step.

The UI part would be represented as a slider, when clicked it would display historic values just like a sensor would.

## Consequences

It would hopefully make things easier for integrations that deals with non-binary values and serve as a convenient way to control and show them both in UI and automations.

**Comment by CJNE** [comment]
This is similar to #347 but with inclusion of the state as well as the output.

**Comment by frenck** [comment]
This has been added: the `number` entity component.

**Comment by CJNE** [comment]
Thank you, just what i needed :)
