### ISSUE TITLE
Image Blackboard (was Image Processing refactoring)

### ISSUE THREAD

**Issue by dgomes** [home-assistant/architecture#41]
[Image Processing](https://www.home-assistant.io/components/image_processing/) component allows the processing of images supplied by the camera component.

Basically it snapshots an image from a given camera, processes the image to extract information (eg. license plate, face) and triggers an event that most commonly is used in an automation (eg. send a notification)

In this process the image that was processed gets lost. Even if an automation triggers a new snapshot from the camera, the image will not be the same one captured before.

As image_processing components evolve, some will take longer time to process (using CV/ML/DL techniques) and eventually, whatever they detect in the image, will get lost in the "numbers" produced and without an option to use the image.

So what can be done?

- Make the image_processing component behave like a camera (we can even recycle the camera UI) and therefore expose the image as an attribute of the component.
- Have the image_processing component send the image together with the event (might be resource wasteful ?) and make possible for other entities to process such image or display (thinking about extending generic_camera to receive an image, or creating image_processing pipelines)

I would like your comments/thoughts on this matter.

**Comment by dgomes** [comment]
Would a PR to add SINK to image_processing be accepted ?

SINK would be a camera (would also issue a PR for a sink_camera that can receive images)

**Comment by dgomes** [comment]
My previous proposal would create a circular dependency between _image_processing_ and _camera_.

Image Processing should be a proper service, without any dependency on camera component. **Ideally** you would have a queue to receive images, and a queue with processed images.

But I also see a second opportunity: 

Notifications that include images, have the images passed around through the filesystem (very bad when you are running on an RPi3). It would be interesting to also share images with Notification System.

Passing images through the event bus will just through hundreds of kbytes through the bus (requiring conversion of binary images to base64 for json serialization).

To tackle all these issues, my proposal would be for the development of a [blackboard](https://en.wikipedia.org/wiki/Blackboard_(design_pattern)) for images. The blackboard could live in **hass.data**. 

I have no problem diving into coding this solution, just would like some feedback beforehand.

**Comment by Kane610** [comment]
Do you really need to pass along the image? Can't you extend camera component to keep its own queue instead? And image processing would consume event and use image? Possibly with a lock to not clean image during processing

**Comment by dgomes** [comment]
@Kane610 your first proposal would still create a dependency between components (instead of moving to a decoupled solution)

"other place" is my proposal :)

**Comment by Kane610** [comment]
Allright, maybe I misunderstood :)
