### ISSUE TITLE
Calendar component refresh / Add a new CalendarEntity

### ISSUE THREAD

**Issue by wernerhp** [home-assistant/architecture#411]
## Context

The existing `CalendarEventDevice` is pretty outdated.
The state is shown as `on` and `off` instead of a more relevant `free` and `busy`.
It only shows a single upcoming event in its `state_attributes`, which means if there are multiple events happening at the same time, that only one is shown.
If there is an all day event, no other events are shown.
`CalendarEventView` does an API call every time it's called, which is slow.
It's a `Device`

## Proposal

Deprecate the current `CalendarEventDevice`
Add a new `CalendarEntity`.

https://github.com/wernerhp/core/commit/22578df32c3fdb988b270cb1ab9f134c2a91bf59

## Consequences

A new `CalendarEntity` that
- caches multiple events in `state_attributes` (like `weather.forecast`)
- has views that return data from cache.
- has a `CalendarEventView` that returns events for a `day`, `week`, `month` or `schedule` view
- supports multiple concurrent events.
- has a `CalendarEvent(ABC)` that makes it easy to create and extend calendar events.
- better automations and templates

The old calendar integration will be used when configuring the component via `configuration.yaml`.
The new calendar integration will be used when configuring the component via `ConfigFlow`.

This serves as a primer to a new Google calendar platform integration, which will include a `ConfigFlow` with Google OAuth2.  This calendar integration will support Google Calendar API and Google People API (for a contact events calendar supporting Birthdays, Anniversaries and other custom events).

Downside...there will be two different calendar components for a while.

**Comment by MartinHjelmare** [comment]
See https://github.com/home-assistant/architecture/issues/38 for the existing suggestion.

**Comment by wernerhp** [comment]
Thanks @MartinHjelmare I saw that one, but it seemed very old and there was a PR for it, so I thought it was completed.

**Comment by MartinHjelmare** [comment]
It's not completed. I did some clean up as a start of that plan.
