### ISSUE TITLE
Get device details in templates

### ISSUE THREAD

**Issue by dwradcliffe** [home-assistant/architecture#416]
## Context

As more components use the device registry, more device data is moved away from entities and on to devices, as was designed. This means that the current methods of getting attributes on entities is no longer sufficient within templates.

Example:
With the new ozw component, there is a real device for each zwave node, and we no longer have the `zwave.*` entities. Information about the node, such as device model and manufacturer is on the device and not on any entity. There is no way to get the model of, for example, a switch from a template.

Here is an example script that no longer works: https://github.com/kschlichter/Home-Assistant-Inovelli-Red-Dimmer-Switch/blob/master/inovelli_red_dimmer_switch

## Proposal

I propose we add one or more template extensions/helpers to fetch information from the device registry for a given entity.

Something like this:

```jinja
{% if 'LZW31' in device_name(entity_id) %}
```

## Consequences

This will give people more ways to use the proper device/entity architecture. I'm not sure if there's any negative consequences.

cc @frenck @cgarwood

**Comment by balloob** [comment]
I wouldn't want to return just the device name. Probably something like `device(entity_id)` returning a [device registry entry](https://developers.home-assistant.io/docs/device_registry_index#device-properties)

**Comment by dwradcliffe** [comment]
That sounds good. 👍 I can try to get a PR started when I have a chance this week unless someone beats me to it.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
