### ISSUE TITLE
getting config entry data in the frontend

### ISSUE THREAD

**Issue by ziv1234** [home-assistant/architecture#421]
## Context

The issue motivating this decision, and any context that influences or constrains the decision. Your motivation cannot include that the frontend is not representing the data correctly, as that is a frontend issue.
i am trying to build a panel for dynalite configuration using the mqtt panel as an example. I can get the config entry id from the search params and get the config entry. however, it doesn't have the "data" attribute. Any way to request this from the system?
## Proposal

The change that you're proposing.

## Consequences

What becomes easier or more difficult to do and any risks introduced by the change that will need to be mitigated.

**Comment by balloob** [comment]
This will not be possible. Config entry data contains sensitive information like auth tokens. Instead add a websocket API to your integration that provides the relevant data.

**Comment by ziv1234** [comment]
thanks. will go down the websocket path
