### ISSUE TITLE
You are running an unsupported installation

### ISSUE THREAD

**Issue by jesuslg123** [home-assistant/architecture#423]
## Context

I'm running home assistant (234) on Docker 19.03 and my instance is informing me that my installations is unsupported.

[According the documentation](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions) Docker CE 19.03 is supported.

Any idea why is this happening? 

Thank you.

**Comment by ludeeus** [comment]
Your supervisor logs will have more details on why your installation is unsupported.
This is our architecture repository.

If you need help looking at the logs, please reach out on the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e)
