### ISSUE TITLE
Supported Operating System, System dependencies and versions: NetworkManager >= 1.18.0 ?

### ISSUE THREAD

**Issue by danielbrunt57** [home-assistant/architecture#427]
network-manager in Debian 10 buster (stable) is 1.14.6.  
network-manager 1.18.0 is listed as experimental (net): 1.18.0-1 [debports]: powerpcspe. 
Should I be using 1.18.0-1 for a supported supervised installation on Debian 10?

**Comment by danielbrunt57** [comment]
I updated docker to use journald instead of the default json-file as the logging driver and now Supervisor no longer warns me that I'm using an unsupported platform so network-manager 1.14.6 must be okay.

**Comment by carstencodes** [comment]
For me, the workaround mentioned by @danielbrunt57 has not worked. Searching for [network-manager on debian stable](https://packages.debian.org/search?suite=all&searchon=names&keywords=network-manager) resolves 1.14.6-2. Therefore debian testing (1.26.2-1) or debian unstable (same version) must be used, which conflicts with debian stable (buster). Can you please clarify this issue?

**Comment by danielbrunt57** [comment]
> 
> 
> For me, the workaround mentioned by @danielbrunt57 has not worked. Searching for [network-manager on debian stable](https://packages.debian.org/search?suite=all&searchon=names&keywords=network-manager) resolves 1.14.6-2. Therefore debian testing (1.26.2-1) or debian unstable (same version) must be used, which conflicts with debian stable (buster). Can you please clarify this issue?

Your supervisor warns you about an unsupported platform despite using Network Manager 1.14.6-2 and journald for docker logging?  Any errors or warnings in your supervisor log?

**Comment by carstencodes** [comment]
Ok, I see.

20-08-25 19:02:39 ERROR (MainThread) [supervisor.core] Detected unsupported OS: Raspbian GNU/Linux 10 (buster)
20-08-25 19:02:40 INFO (MainThread) [__main__] Run Supervisor
20-08-25 19:02:40 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-08-25 19:02:40 CRITICAL (MainThread) [supervisor.core] System running in a unsupported environment!

Do I really need to install Debian/arm 10 to make the supervisor happy?

**Comment by danielbrunt57** [comment]
You may need Debian/arm64 (debian-10.5.0-arm64-netinst.iso) but I could be wrong and it must be Pi3 as I don't think Debian has added support for Pi4 (see [.](https://wiki.debian.org/RaspberryPi)  I only started HA in June so all of this is quite new to me...

**Comment by carstencodes** [comment]
Thanks for clarification. It's really a Pi3. Maybe I'll setup a new revision during my next holiday.
