### ISSUE TITLE
Adding platform to root integration

### ISSUE THREAD

**Issue by dgomes** [home-assistant/architecture#434]
## Context

This issue comes https://github.com/home-assistant/core/pull/40028 where a PR was made to add the "Notify" platform to the TTS integration.

The proposed contribution is generic (it works with all existing and future tts platforms) and was therefore created under the tts integration.

## Proposal

I'm proposing that root integrations can implement other existing platforms. This makes sense not only for the case that triggered this, but also for e.g. : cameras and image_processing

## Consequences

No foreseen consequences, it simply has never been done before, but its based on existing required services, so there is guarantee of support by all inherited integrations.

**Comment by balloob** [comment]
It has been done before with Switch having a Light platform. Or Group having a light and cover platform. This is fine.
