### ISSUE TITLE
Allow nesting light groups

### ISSUE THREAD

**Issue by ryanjohnsontv** [home-assistant/architecture#437]
## Context

Currently when grouping light entities into a group, I am unable to reference that group as an entity for another light group.

## Proposal

Allow nesting light group entities into other light groups. For instance light group "Living Room Fan Lights" has entities `light.living_room_fan_light_1` & `light.living_room_fan_light_2`, but for convenience I also have a light group, "Living Room Down Lights", for my additional recessed lights in my living room. Currently, I am unable to create a parent light group, "Living Room Lights", that includes just the two light entities generated from those two light groups. 

## Consequences

This will make organizing a large collections of lights much easier, as individual light entities will not need to be repeated in YAML.

**Comment by frenck** [comment]
So this makes light groups that have dependencies on other light groups when creating them.

What is your implementation suggestion for this @ryanjohnsontv?

**Comment by balloob** [comment]
Why is this not possible today? You can just put a `light.living_room_fan` in your other group ?

**Comment by ryanjohnsontv** [comment]
> Why is this not possible today? You can just put a `light.living_room_fan` in your other group ?

In its current state when I add an existing light group in another light group, the new group appears as unavailable.
![image](https://user-images.githubusercontent.com/43426700/94444041-820dc100-016b-11eb-925b-ef97c25a9433.png)
![image](https://user-images.githubusercontent.com/43426700/94444157-a23d8000-016b-11eb-8e4f-abed8ed49a50.png)

**Comment by KevinCathcart** [comment]
This sounds more like an implementation issue/bug/limitation than an architectural issue.

Except in the obviously bad scenario of group A including Group B, which includes Group A, I don't immediately see anything in the code that should cause this not to work.

I do however see a [recent bugfix](https://github.com/home-assistant/core/commit/3880ac0b0daacf8b47c2bf94fb0231d9e2de1bda) that seems like it could be related.

**Comment by balloob** [comment]
Yeah, this is a bug. Closing this. Re-test if it still occurs in 0.116 beta (releasing today) and fiel a bug if it does.
