### ISSUE TITLE
Home Assistant's naming has become confusing, an official naming timeline/chart is needed.

### ISSUE THREAD

**Issue by techdragon** [home-assistant/architecture#439]
## Context

I spent _FAR_ too long trying to work out just what I was running (more than a few minutes when I followed the website instructions is too long), and on top of far too long trying to work out that this is the correct name that matches what older documentation in third party plugins, and older forum posts. I should not have had to find this document https://github.com/home-assistant/architecture/blob/master/adr/0015-home-assistant-os.md in order to work out just what I installed on my raspberry pi. Which also means I spent far too long working out what I am running, _and got it wrong_. Notice how nothing on the install page explains which install method relates to which "named configuration" you have https://www.home-assistant.io/hassio/installation/ ... also that's another place using "hassio" for yet another potential source of confusion regarding the name of what you are installing/running.

## Proposal

A genealogy style timeline of all the various names for the methods of running / installing home assistant is needed. There are currently 4 distinct names for how you might be running home assistant and a plethora of older names. "Home Assistant Container", "Home Assistant Supervised", "Home Assistant OS", and "Home Assistant Core"... the legacy of "Hass.io" and older names needs to be clearly documented by the timeline/chart. 

## Consequences

Anything to do with older documentation, screenshots, etc ... and/or third party resources that may get updated less frequently will be easier for users to work with.

**Comment by balloob** [comment]
This is not an architecture issue but a documentation issue. We accept contributions to the docs.
