### ISSUE TITLE
Adopting IndieAuth extension

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#44]
While developing the auth system, it always felt weird that we would have users create client IDs and then authenticate before being able to use their instance with third party apps. It should be able to just redirect user, authenticate and it should work. 

Using client id as extra layer for security was also not realistic because the frontend would expose their client id. Hence, an attacker could just scrape the index to get a client ID to use.

All these things I kind of ignored while working on the meat of the problem: users itself. Then last night I read this article on HackerNews about the IndieAuth extension for the OAuth2 spec: https://aaronparecki.com/2018/07/07/7/oauth-for-the-open-web

It's perfect suited for our decentralized setup. Instead of client ID and redirect URI being preconfigured, it will be based on urls and a set of rules. No creation of clients necessary.

Cc @awarecan

**Comment by balloob** [comment]
It's not giving any extra security.

The Client ID of the Home Assistant frontend will always be accessible. If a hacker wants to try out your logins, it can just try to login to your normal frontend.

**Comment by awarecan** [comment]
Yes, so I say I *feel* safe. I can imagine that may users will make similar feature request after this change released.

**Comment by awarecan** [comment]
OK, I have a scenario for it.

Let's say I am very worry my security, I don't want anyone access my frontend though Internet, but I have to open API access for some webhook, so I just open 443 port, and only allow https://mydomain.com/api/some_endpoint be access from Internet. 

In that case, hacker need only discovery "some_endpoint" before he can play attack. He doesn't need to know client_id. If I white list client_id, my security level back to normal setup of OAuth2, he need to first guess my client_id now.

**Comment by pvizeli** [comment]
This use case is more for a proxy. We should make our UI safe as possible but we should not go into competition to a full featured webserver/proxy.

**Comment by balloob** [comment]
Given that they know your instance url, they already could because the frontend contains a client id.
