### ISSUE TITLE
New platform proposal: Kitchen Appliance (cooking/heating/cooling)

### ISSUE THREAD

**Issue by blakadder** [home-assistant/architecture#443]
## Context

I have a couple of MQTT based kitchen appliances such as water kettle and air fryers that have specific features that are difficult to emulate in other components and require configuring a lot of sensors, switches, input_numbers and input_selects and accompanying automations and scripts which makes integration for average users quite an ordeal.

Since Tuya announced a big lineup of kitchen appliances and cooperation with european kitchen appliance manufacturers there will be an influx of new devices in the market which would require such a specific integration.

see links for possible use cases and current HA integrations:
- https://templates.blakadder.com/proficook_PC-WKS_1167.html
- https://templates.blakadder.com/blitzwolf_BW-AF1.html
- https://github.com/fineemb/Xiaomi-Smart-Multipurpose-Kettle

## Proposal

Creation of a new platform, `cooking_appliance` or `kitchen_appliance or something more elegant tbd because it could include cooling and/or heating appliances. 

Required features (from my experiences):

- Power on/off
- start/pause/stop cooking/heating
- Time remaining
- Current (internal/cooking) temperature
- Set target (cooking) time/timer
- Set target (cooking) temperature
- Mode select (in this case it would be internally programmed modes)
- Report status:
   (examples):
   - idle
   - heating
   - keep warm
   - cooking complete/reached target temp
- error notification (example: tray/kettle inserted/removed, overheated, etc)
and many more...

## Consequences

A lot easier integration of a growing segment of connected kitchen appliances.

**Comment by yuvalabou** [comment]
I would agree, Just like the "Plant" entity

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
