### ISSUE TITLE
FR: Allow camera scan_interval to be user configurable

### ISSUE THREAD

**Issue by JesseWebDotCom** [home-assistant/architecture#45]
Camera previews before and after Lovelace are updated at a hard coded default of every 10 seconds.  Please provide a user configurable setting (ex. scan_interval: 2) for each individual camera and or all cameras collectively

Thanks

**Comment by MartinHjelmare** [comment]
Architecture proposals should answer *what*, *why* and *how*. This only describes the first of those, so it sounds more as a feature request.

Feature requests should be directed to our corresponding forum section.

Will this proposal be complemented with further info?

**Comment by balloob** [comment]
The frontend is not meant to show a live stream. Users only want to make it configurable because they want to have a live stream.

**Comment by MartinHjelmare** [comment]
I think we should close this. It's a feature request and we also have the new hls stream component now.
