### ISSUE TITLE
Add Attributes for Calendar Integration

### ISSUE THREAD

**Issue by tkdrob** [home-assistant/architecture#457]
## Context

Current integration does not provide tentative or cancelled (deleted) event status. The time an event was created and last updated can be useful for automations. Transparency can tell the user if they are marked as busy during the event. Visibility shows whether the event is private or publicly visible. 

## Proposal

I am looking to have the above mentioned attributes normalized. These attributes are supported in google calendar.

## Consequences

A possible risk is lack of support for proposed features from other integrations that use the calendar. I am not personally aware of any because I use google. The created and updated times provided by google have to be converted to match the start and end time format. 

My proposed PR: https://github.com/home-assistant/core/pull/41180

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
