### ISSUE TITLE
Configuration directory

### ISSUE THREAD

**Issue by gwww** [home-assistant/architecture#46]
This is a two-part issue.

The simpler to describe, and possibly solve part, is that many programs now use `~/.config` to store their configuration files. In particular in OSX and Linux/Unix this is the trend. Google XDG_CONFIG_HOME environment variable for more.

The more complex piece of this discussion is that the configuration directory (`.homeassistant`) contains a mix of different purposed "stuff". For example a quick scan of my config dir show:
* Edited YAML files that are part of my configuration
* Generated YAML files (e.g.: Harmony)
* `www` directory that contains code (Lovelace monster card in my case)
* `custom_components` that contains code (ElkM1 in my case)
* Log file(s)
* `deps` directory, which looks like a virtualenv setup, not sure of its purpose (I actual run `hass` in my own virtualenv while developing)
* `tts` directory, not sure of its purpose

I have two proposals.

1. On appropriate OSs use the `~/.config` for configuration. ~/.config is the default with fallback to .homeassistant; Use XDG_CONFIG_HOME as appropriate.
2. For more discussion but general goal is editable configuration exists alone in a directory (tree). Code, logs, generated configuration is not mixed in with edited configuration. 

A starting proposal for directory structure:
```
.config/home-assistant
├── config
│   ├── automations.yaml
│   ├── configuration.yaml
│   ├── secrets.yaml
│   └── ui-lovelace.yaml
├── custom-components
│   └── elkm1
│       ├── alarm_control_panel
│       │   └── elkm1.py
│       ├── climate
│       │   └── elkm1.py
│       ├── elkm1.py
│       ├── light
│       │   └── elkm1.py
│       ├── sensor
│       │   └── elkm1.py
│       └── switch
│           └── elkm1.py
├── logs
└── www
    └── monster-card.js
```

**Comment by rytilahti** [comment]
Generally speaking I like the idea of using standardized locations for files. OSX has its own structure for storing these files, see https://github.com/ActiveState/appdirs for a library to obtain the proper directory for a specific data type on all common platforms.

So on a generic linux the data locations would be something like this:
- ~/.config/home-assistant/ for configuration
- ~/.cache/home-assistant/log/ for logs
- ~/.cache/home-assistant/deps/ for cached dependencies
- ~/.local/share/home-assistant/ for data files (www, custom_components should belong here I think)

The question I have is that converting it all backwards compatible to this format would require some work, and "reseting" ones installation will be more complicated than "please remove ~/.homeassistant/", is it still worth the effort and what pros & cons there are for doing this?

**Comment by dgomes** [comment]
HomeAssistant runs as a daemon, why keep everything in a home dir ?

IMHO it should be moved to the POSIX `etc` dir. 

Since many people run HA inside a container, splitting the configuration throughout several subtrees is also a less then optimal idea.

BTW: I find this issue of very low priority.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
