### ISSUE TITLE
Add Barometric Pressure to HA Weather Forecast Model

### ISSUE THREAD

**Issue by bchastain** [home-assistant/architecture#467]
## Context

Several weather data providers give access to hourly or daily barometric pressure forecasts as a part of their API. I know that OpenWeatherMap and WeatherUnderground do this and there are likely others as well.

## Proposal

We add a ATTR_FORECAST_PRESSURE entry to the HA Weather Forecast Model so that HA will be able to work with this readily-available pressure forecast data.

## Consequences

The only issue I see is that perhaps not all weather APIs provide a forecast for pressure, so this value would be missing for those integrations.

**Comment by MartinHjelmare** [comment]
It will be easier to get approval here if we can see a summary of all our current weather platforms how many of them provides the pressure forecast.

**Comment by bchastain** [comment]
OK I can work on that, but out of curiosity, what's the downside to adding this to the model even if some platforms don't provide it?

**Comment by MartinHjelmare** [comment]
We only add features that are supported by a larger part of current and potential integrations.

**Comment by bchastain** [comment]
OK I dug through them all, and here's my summary:

<table border="1">
<tr><th>Platform</th><th>Any Forecast</th><th>Current Pressure</th><th>Pressure Forecast</th></tr>
<tr><td>Accuweather</td><td>Y</td><td>Y</td><td>N</td></tr>
<tr><td>Ambient Weather Station</td><td>N</td><td>Y</td><td>N</td></tr>
<tr><td>Buienradar</td><td>Y</td><td>Y</td><td>N</td></tr>
<tr><td>DarkSky</td><td>Y</td><td>Y</td><td>Y</td></tr>
<tr><td>DWD</td><td>N**</td><td>N</td><td>N</td></tr>
<tr><td>Environment Canada</td><td>N***</td><td>Y</td><td>N</td></tr>
<tr><td>IPMA</td><td>Y</td><td>Y</td><td>N</td></tr>
<tr><td>Met Office</td><td>Y</td><td>Y</td><td>Y</td></tr>
<tr><td>Météo-France</td><td>Y</td><td>N</td><td>N</td></tr>
<tr><td>Met.no</td><td>Y</td><td>Y</td><td>Y</td></tr>
<tr><td>NWS</td><td>Y</td><td>Y</td><td>N</td></tr>
<tr><td>OWM</td><td>Y</td><td>Y</td><td>Y</td></tr>
<tr><td>SMHI</td><td>Y</td><td>Y</td><td>Y</td></tr>
<tr><td>Taps Aff</td><td>N</td><td>N</td><td>N</td></tr>
<tr><td>Trafikverket</td><td>N</td><td>Y</td><td>N</td></tr>
<tr><td>Wunderground</td><td>Y</td><td>Y</td><td>Y</td></tr>
<tr><td>ZAMG</td><td>N</td><td>Y</td><td>N</td></tr>
</table>

** Only provides forecasts of warnings
*** Only provides textual forecasts

So if you only look at providers that actually provide forecasts and any barometric pressure data at all, that makes 6 of those remaining 10 that provide pressure forecasts. That seems like a large part of the platforms to me.

**Comment by MartinHjelmare** [comment]
Good! Thanks for the summary.

I'm positive about adding this feature. 👍

We should get some more opinions from other members before moving on.

**Comment by fabaff** [comment]
I'm OK with adding it as according to the table the popular integrations supports it.

**Comment by frenck** [comment]
Yeah, looks good! Makes sense.

**Comment by helto4real** [comment]
I am positive to add it to SMHI pypi lib and fix integration if this is going to happen.

**Comment by MartinHjelmare** [comment]
@bramkragten will this work for the frontend card?

**Comment by helto4real** [comment]
Now when looking into my pypi lib I realized it is allready implemented so it should be very easy to add it to Home Assistant if barometric pressure is added. I will follow this issue and implement if needed for SMHI.

**Comment by bramkragten** [comment]
> @bramkragten will this work for the frontend card?
Yes, I see no problems there

**Comment by MartinHjelmare** [comment]
Ok, then I think we can go ahead here and consider this suggestion approved. :+1:
