### ISSUE TITLE
Add temperature offset for thermostats

### ISSUE THREAD

**Issue by jeinwag** [home-assistant/architecture#468]
## Context

Some thermostats, like the FRITZ!DECT 301, allow the user to specify a temperature offset, which is used to adjust for the difference between the temperature measured at the thermostat/heater and the actual room temperature.
A quick research showed that Tado and Homematic thermostats also support this feature.

## Proposal

I propose adding the temperature offset as a property to ClimateEntity.

## Consequences

This change would enable Home Assistant to change the temperature offset, so you could use any external temperature sensor (which is HA compatible, of course) to automatically adjust the offset while still using the automatic control of the thermostate

I'd be willing to help with a PR.

**Comment by tristan-k** [comment]
Has this been implemented?

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
