### ISSUE TITLE
Correct power factor range (and unit)

### ISSUE THREAD

**Issue by Cougar** [home-assistant/architecture#469]
## Context

Power factor is a [ratio of real power to apparent power](https://en.wikipedia.org/wiki/Power_factor#Definition_and_calculation). The value is in range **-1.0 to 1.0**. Right now the HA describes it with a percent (percent from what?).

The current range and unit idea came from discussion in #397. There was an issue that numbers need a unit (to display graphs correct way).

I have looked a lot of [public](https://github.com/search?q=%22homeassistant%3A%22+filename%3Aconfiguration.yaml) [configurations](https://github.com/search?l=&q=%22+power_factor%22+extension%3A.yaml+language%3AYAML&type=code) and wrote that in [forum](https://community.home-assistant.io/t/power-factor-change-suggestion-from-100-100-to-1-0-1-0/234246).

I have found from feedback and from configurations that there are very few users who care about power factor and they usually use correct range between -1.0 and 1.0. The workaround for a "percent" unit is to replace it with invented units like "cos(φ)" but the common one is to use a space as a unit (empty unit) and then it looks correct in Lovelace graphs too.

There are only two integrations in core where power factor is used: [Shelly](https://github.com/home-assistant/core/blob/dev/homeassistant/components/shelly/sensor.py#L74) and [Keba](https://github.com/home-assistant/core/blob/dev/homeassistant/components/keba/sensor.py#L126). Power factor values from Keba sensor are already in correct range.

## Proposal

* Change power factor range from -100…100 to -1…1.
* Use " " (space) as a unit (as long as unit is required for Lovelace graphs).

## Consequences

This will be a **breaking change**. Users who has been used with percent, need to multiply the new value with 100. Users who like to see correct numbers and divided the value with 100 before (most likely only in case of Shelly), have to remove this division.

Shelly is the only integration that gives power factor in range -100…100 (or is it 0…100?) and needs to be changed in core code. I have a PR ready for that and for documentation change.

All other sensors that I have searched (like [Tasmota](https://github.com/arendst/Tasmota/blob/development/tasmota/xdrv_03_energy.ino#L963), some [Z-wave power sensors](https://github.com/codersaur/SmartThings/blob/master/devices/greenwave-powernode-single/greenwave-powernode-single.groovy#L620), Keba, [OpenEnergyMonitor](https://github.com/openenergymonitor/EmonLibCM/blob/master/emonLibCM.cpp#L628) based projects) return correct power factor.

Only few exceptions are systems which don't support floating numbers in their wire protocols and then the user library or application to divide the number with 100 or [1000](https://github.com/dannerph/keba-kecontact/blob/3753b4d81e2c460206765e187c4fef253435146f/keba_kecontact/keba_protocol.py#L113) (depending on the resolution).

Based on my research, it is very unlikely that anyone run any automation based on power factor.

**Comment by dgomes** [comment]
φ (cos-phi) ?

**Comment by dannerph** [comment]
From electrical point of view, I fully agree. I can live with "p.f." as unit if a unit is required. Empty unit (space) is also fine but probably not consistent with all other measures.

**Comment by Cougar** [comment]
My understanding is that in the HA the unit is even not bound with device class. For instance, if I create sensor like this:

```yaml
  - platform: mqtt
    name: "POW voltage"
    state_topic: "DVES_A0352E/tele/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    device_class: voltage
```

Then it will give a number without a unit and Lovelace shows state changes instead of graph.

It looks like that the unit needs to be configured in any case. In case of YAML, every user can (and must) choose their unit. In case of using web UI (config flow), the integration sets up device and its sensors with proper units. Only two of such sensors exist in the core right now.

If anyone really likes to see a range 0…100, it can be still easily achieved with [template](https://www.home-assistant.io/integrations/template/). In some cases power factor can be also negative but negative percentage is totally misleading IMHO.

@dgomes yes, "φ" is Greek letter phi and it denotes an angle. [Wikipedia](https://en.wikipedia.org/wiki/Power_factor#Definition_and_calculation) has good illustrations and describes what this angle means (there is no angle in electricity, this is for pure math for vector calculations).

@dannerph As long nothing breaks in HA, I would still propose to use " " as a unit to be correct. This can be easily modified with [customizations](https://www.home-assistant.io/docs/configuration/customizing-devices/#unit_of_measurement) anyway. I removed this unit (and changed the value to the right range) some times ago and don't see any problem with that.

Can we correct this before 1.0 or is it too late? The change itself is a really small (three lines ([1](https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/__init__.py#L48), [2](https://github.com/home-assistant/core/blob/dev/homeassistant/components/shelly/sensor.py#L74), [3](https://github.com/home-assistant/core/blob/dev/tests/testing_config/custom_components/test/sensor.py#L25)) in core and one place in [documentation](https://www.home-assistant.io/integrations/sensor/#device-class)).

**Comment by Cougar** [comment]
I understand that percent was proposed to [pass test](https://github.com/home-assistant/core/pull/36800#issuecomment-670529397) instead of fixing it… :)

**Comment by dannerph** [comment]
@Cougar: How does the influxdb component behave if there is no unit or a unit of " "? In my keba integration the power factor is an attribute of the charging power sensor thus not a problem.

![grafik](https://user-images.githubusercontent.com/11915163/101609840-bde4c280-3a07-11eb-9231-f4b3667e79ff.png)

**Comment by Cougar** [comment]
When unit is defined as space, it is also in InfluxDB with such name but when unit is empty then it I don't see it in InfluxDB any more. This is also why I suggest to use "space" as a unit.

**Comment by fsaris** [comment]
If a proper solution for https://github.com/home-assistant/architecture/discussions/503 is found I think we can use the power factor without unit.

**Comment by frenck** [comment]
As this issue is otherwise resolved, I'll go ahead and close it.
