### ISSUE TITLE
After Update to docker-ce 20.10 homeassistant won't strat and clean all addon image

### ISSUE THREAD

**Issue by wes1993** [home-assistant/architecture#470]
## Context

After update the docker-ce to 20.10 and reboot the machine homeassistant won't start automatically and clean all my addon image, included the homeassistant container and image...
This are the packages that i have updated:

Preparativi per estrarre .../0-libssl1.1_1.1.1d-0+deb10u4_amd64.deb...
Estrazione di libssl1.1:amd64 (1.1.1d-0+deb10u4) su (1.1.1d-0+deb10u3)...
Preparativi per estrarre .../1-containerd.io_1.4.3-1_amd64.deb...
Estrazione di containerd.io (1.4.3-1) su (1.3.9-1)...
Preparativi per estrarre .../2-docker-ce-cli_5%3a20.10.0~3-0~debian-buster_amd64.deb...
Estrazione di docker-ce-cli (5:20.10.0~3-0~debian-buster) su (5:19.03.14~3-0~debian-buster)...
Preparativi per estrarre .../3-docker-ce_5%3a20.10.0~3-0~debian-buster_amd64.deb...
Estrazione di docker-ce (5:20.10.0~3-0~debian-buster) su (5:19.03.14~3-0~debian-buster)...
Selezionato il pacchetto docker-ce-rootless-extras non precedentemente selezionato.
Preparativi per estrarre .../4-docker-ce-rootless-extras_5%3a20.10.0~3-0~debian-buster_amd64.deb...
Estrazione di docker-ce-rootless-extras (5:20.10.0~3-0~debian-buster)...
Preparativi per estrarre .../5-openssl_1.1.1d-0+deb10u4_amd64.deb...
Estrazione di openssl (1.1.1d-0+deb10u4) su (1.1.1d-0+deb10u3)...

## Proposal

Fix the issue

**Comment by frenck** [comment]
This is the repository to discuss architectural issues with the Home Assistant Core. Please check https://www.home-assistant.io/help on how to report an issue.

Thanks 👍

**Comment by wes1993** [comment]
Thanks,
Sorry for my error
