### ISSUE TITLE
Support external RDBMS or NoSQL DB for the use case of .storage

### ISSUE THREAD

**Issue by gsdevme** [home-assistant/architecture#472]
## Context

When deploying HA in containerised environment this would further ease a high availability deployment strategy for Home Assistant by keeping  the container volume immutable. Furthermore it would mean running two or more or even a beta version locally would be easier. 

The recorder already supports some RDBMS options so there is certainly users who have this already ready to go without any extra deployments required. Further keeps parity with its featureset also as the recorder has been able to do this for a while.

Few more points

- A Raspberry Pi deployment having both the recorder & .storage external really would help reduce the problems you run into I/O wise on the SD Card. 
- Existing industry standard database tools could be utilised including for backup.
- Running beta versions on another host or locally is very simple without manually interacting with a filesystem of an undocumented nature (from a user point of view).
- I/O read/write on the host needs to be catered for.
- Mixture of 'secrets/configuration' might be easier to restructure outside of a big folder with files re: https://github.com/home-assistant/architecture/issues/370
- Very often its confusing from a user prospective what we even need to do with .storage (see https://community.home-assistant.io/t/config-storage-ha-hassio/103878 https://community.home-assistant.io/t/new-storage-folder-should-it-be-backed-up/67349 https://old.reddit.com/r/homeassistant/comments/f6ctmu/storage_backup_recommendations/ https://old.reddit.com/r/homeassistant/comments/jdyi95/version_control_yaml_vs_storage/ https://old.reddit.com/r/homeassistant/comments/f6ctmu/storage_backup_recommendations/)
- Automated deployments via Kubenetes, ansible, docker etc are all trivial as you don't need to worry about the .storage folder. 
- Migration when upgrading could utilize advanced RDBMS features to provide rollbacks if the configuration check was to fail (i.e. abort an upgrade and prevent mutating the database)

## Proposal

Support external RDBMS or NoSQL for the use case of .storage as a more advanced configuration.

## Consequences

Not exactly sure here, Id imagine the implementation might be difficult depending how pesudo style flat file database is implemented. 

## Work Arounds

My current workaround is to run a NFS share that can be access from multiple nodes. It's not as stable as a native database though as its subject to other pitfails.

I'm also trying to use the CLI to do certain tasks as a "init" step before my container boots but there is limited support for things although sometimes the non-secret things can be put into VCS but its abit of guess work to know those.

**Comment by BradleyFord** [comment]
Agree, this would be awesome and allow storage for a much longer time
period.

We already have the ability to push days to InfluxDB, but this is then
totally separate to the HA implementation.

Switching to InfluxDB as a default would be very good and easy to manage
via the supervisor structure.

**Comment by gsdevme** [comment]
> Switching to InfluxDB as a default would be very good and easy to manage
via the supervisor structure.

As in switching the native recorder to Influx? yeah Id perhaps like that although this is specifically about the .storage/ rather than the recorder thats sqlite.db by default. You can already put the recorder in a RDBMS

**Comment by BradleyFord** [comment]
Ah yes you are correct, sorry for disturbing.

**Comment by shbatm** [comment]
I like this idea as well. The json structure of the /.storage/core.* files seems like it'd lend itself to move to MongoDB or other NoSQL style, which could be spun up in its own docker container under the Supervisor or extended to another server instance for advanced users.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
