### ISSUE TITLE
Climate Cleanup - state to follow HVAC mode

### ISSUE THREAD

**Issue by Stendec1** [home-assistant/architecture#474]
## Context

Interfacing with the climate domain from Node Red to set the temperature results changing the state to "heating" when passing on the mode "heat" along with the temperature. Since the state is set by the HVAC unit itself this results in alternating between states: "heating" <-> "idle".

I'm using following in combination with HASSIO:
- https://github.com/gysmo38/mitsubishi2MQTT
- https://github.com/giuseppeg88/node-red-contrib-thermostat-scheduler

## Proposal

Ability to disconnect HVAC state from HVAC mode. Maybe by means of an additional operation_mode?

## Consequences

Having the ability to disconnect HVAC state from HVAC mode with defaulting to the current way of working would enable
smart HVAC implementations such as https://github.com/gysmo38/mitsubishi2MQTT in combination with https://github.com/giuseppeg88/node-red-contrib-thermostat-scheduler

**Comment by elupus** [comment]
This don't seem to be a core arch change. It looks to be a bug in the integration. Mode and (Current) Action is already separated in core.

**Comment by Stendec1** [comment]
Strange, in the following post:
https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup/

I read:
_The state of a climate entity is now always equal to the HVAC mode._

Which is exactly what happens in my situation.

**Comment by elupus** [comment]
The state always follows the configured static setting of the device (think of it as the knob on the device that controls it's behavior). The attribute hvac_action represent what it is curently doing.

So for example state will be statically set to heat_cool, but hvac_action will alternate between heating, cooling, idle.

I hate the "mode" term. It's so ambiguous. And "state" here actually refers to the state of the knob/button on the thermostat control panel.

**Comment by Stendec1** [comment]
Ok, thanks for the clarification.
From Node Red I'm using a call service to HASS with the following:
{
    "temperature": "{{payload}}",
    "hvac_mode": "heat"
}
...which sets the "state" to "heating".
Leaving out the "hvac_mode" results in switching the HVAC to "heat_cool" "mode".

Is there a way I can send the temperature from Node red to HASS without affecting the "mode" and/or "state"?

**Comment by elupus** [comment]
When you do a service call you control the knob value of whatever the climate entity you are controlling. So it all depends on how that entity behaves. You can't control the hvac_action value. It's internal to the entity. Ie it's read back from the device you are controlling.

But now we are heading into device support which is more forum related discussion.

**Comment by MartinHjelmare** [comment]
Closing as this is not the correct forum.

Please open an issue in the core repo with info and logs about the integration you're using.

**Comment by Stendec1** [comment]
So just for my understanding. Doing a service call to only send the temperature should NOT result in "turning the knob" to "heat_cool". Now that's exactly what it does.

Nevertheless, I will post my issue on the forum. 
Thank you very much for you swift reply!

**Comment by emontnemery** [comment]
If you think it's a bug, open an issue here: https://github.com/home-assistant/core/issues , that's what Martin meant.

**Comment by Stendec1** [comment]
Hi Erik, I understood.

With the info you gave me I'm just doing some more digging and tracing on the MQTT level to collect as much information as possible before issuing it as a bug. 

Thanks again for your support.
