### ISSUE TITLE
Add genre property to media_player

### ISSUE THREAD

**Issue by postlund** [home-assistant/architecture#475]
## Context

I want to expose the genre of what's current playing in the Apple TV integration, but it seems to be missing in the entity model.

## Proposal

Introduce a new constant for genre (`ATTR_MEDIA_GENRE`) and add a `genre` property to `MediaPlayerEntity`. It should also be added to `ATTR_TO_PROPERTY`.

## Consequences

It's just an other media property like the rest, shouldn't pose any problems other than "yet another property".

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
