### ISSUE TITLE
NFC tags: Allow tag ID to be set from the tag UID

### ISSUE THREAD

**Issue by kmdm** [home-assistant/architecture#489]
## Context

Currently, when using NFC tags in Home Assistant a tag can potentially have two IDs. 

  * One ID that's written to the tag using the Home Assistant App; and
  * The tag UID that esp based solutions, such as the PN532 will emit to Home Assistant.

Thus this potentially requires duplicate configuration in Home Assistant to handle the tags across mobile phone and ESP based readers. 

This was originally requested in the android companion app issue tracker and it was suggested to raise it in the architecture repo: 

  * https://github.com/home-assistant/android/issues/1307

## Proposal

I'd like to propose that the companion apps have the option to write the tag UID to the tag as the the tag ID used by Home Assistant. This would mean the ID sent from either the ESP based readers or the Home Assistant apps would be identical. 

## Consequences

  * Reading/writing the tag UID as the ID would make it a two-step operation instead of a one-step operation to provision a tag; but
  * Not all users will require this option and any that do would probably appreciate consistent tag IDs; and 
  * Since this only changes the source of the "random" tag ID written and not how the tag data is stored consequences should be minimal/non-existent.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
