### ISSUE TITLE
Extend Context to include remote address

### ISSUE THREAD

**Issue by awarecan** [home-assistant/architecture#49]
Context is a new concept we just added into core (home-assistant/home-assistant#15674).

Now I want to extend it to include the remote address. I am going to get remote address from request.get('ha_real_ip'), which has been set by real_ip middleware. I have few design issue want get some input.

1. Naming
I really struggle on this, which one is better? `remote_address`, `real_ip`, `from`, `where`, even `location`

2. Typing
request['ha_real_ip'] is a IPAddressV4 or IPAddressV6 type, can I use `object` in the Context def, or use `str`?

```python
@attr.s(slots=True, frozen=True)
class Context:
    """The context that triggered something."""

    id = attr.ib(
        type=str,
        default=attr.Factory(lambda: uuid.uuid4().hex),
    )
    remote_address = attr.ib(
        type=str,  # type=object ?
        default=None,
    )
    user_id = attr.ib(
        type=str,
        default=None,
    )
```

**Comment by balloob** [comment]
I don't think that adding IP address is a good idea.

From what I think why, you want to add it to allow the user whitelist feature. However, adding an IP address to EVERY context ever for the sake of 1 auth provider is a hard no from me. 

The only thing I might consider is refresh token ID, as that will allow us to point at which device was used. However, we don't have a use case right now and I think that we should first make context more widespread (including recorder/ store/restore) before adding new data.

**Comment by awarecan** [comment]
My intention is to support trusted network auth provider, but I think that may help to audit log as well, so that we can tracking who did what at when from where.

Anyway, it would not be a road blocker for me, I can use other way to make trusted networks auth provider works.

**Comment by balloob** [comment]
No longer needed.
