### ISSUE TITLE
Add device classes to `sensor` for weight

### ISSUE THREAD

**Issue by nareddyt** [home-assistant/architecture#491]
## Context
Smart bathroom scales, load cells, etc. read dimensions that HA can handle only as generic. I would like to introduce a device class for weight-based sensors.

## Proposal
Add 2 new device classes for weight-related items: `force` and `mass`

The original goal was to add a device class for weight. However, I found that the term `weight` is often misused. Weight is a `force`, but most people are really referring to `mass` when they measure their weight.

After [further reading](https://en.wikipedia.org/wiki/Mass_versus_weight), the SI units clearly define the distinction:
- `mass` (kg, lbs for imperial conversion): This is what people commonly refer to as weight. Can be used for measurements by smart bathroom scales, bed occupancy sensors, etc.
- `force` (N): Can be used by any sensors that are not manufactured to take into account gravity. Anything that senses force horizontally.

So I added support for both. Users can choose between the two to refer to the correct scientific term when they want to measure `weight`. 

PRs:
- Core PR: https://github.com/home-assistant/core/pull/45508
- home-assistant.io PR: https://github.com/home-assistant/home-assistant.io/pull/16301
- developers PR: https://github.com/home-assistant/developers.home-assistant/pull/779

## Consequences
Sensors can use more specific device class for "weight" measurement.

**Comment by MartinHjelmare** [comment]
It's easier to accept changes to the entity model if we can see an overview of the current integrations and also possible devices/brands in the wild and how many would benefit from the added device classes. Can you make a table or summary of this?

**Comment by nareddyt** [comment]
Good point. Here is a summary of what I've found:

- The [ESPHome integration](https://www.home-assistant.io/integrations/esphome/) allows connecting load cells to an ESP to measure `mass` ([reference](https://esphome.io/components/sensor/hx711.html)). Other sensors can be connected to measure force and/or pressure ([example](https://learn.sparkfun.com/tutorials/force-sensitive-resistor-hookup-guide?_ga=2.144539189.1078773881.1611594214-1375515631.1608939209)). I plan to implement https://github.com/esphome/feature-requests/issues/553 so device classes can be set for non-binary sensors directly in the ESP config. Both device classes will be useful here.
- The [Fitbit integration](https://www.home-assistant.io/integrations/fitbit/) calls the Fitbit API and retrieves your weight. It is exposed as a sensor in HA. The `mass` device class will help here.
- Same for the [Smartthings integration](https://www.home-assistant.io/integrations/smartthings/), it exposes the `bodyWeightMeasurement` sensor.
- Same for [Withings](https://www.home-assistant.io/integrations/withings/). It has sensors for `fat_mass_lbs`, `bone_mass_lbs`, `muscle_mass_lbs`. Notice they all say `mass` in the name.

**Comment by blakadder** [comment]
Tasmota supports load cells.

Bluetooth scale data gathered with https://github.com/lolouk44/xiaomi_mi_scale
