### ISSUE TITLE
RFC: Templates that generate non-strings

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#5]
In #general people were talking about how to generate a list from a template. That is currently not possible because all templates generate strings.

We once had an open PR to run all templates through YAML but that's a gigantic can of worms. The PR got rejected.

Today I was thinking how we might be able to solve this anyway, and I came up with something:

If a template result starts with `json(` and ends with `)`, the template result will be parsed as JSON before being returned to the caller.

Examples:
 - Returning a list: `json([255, 0, 0])`
 - Returning a number `json(200)`
 - Returning an object `json({"hello": "world"})`

Advantages from this approach is that it is opt-in and allows for slightly more advanced things in templated service calls.

**Comment by balloob** [comment]
Note that I wouldn't want people to return objects. It's mainly for lists.

**Comment by maddox** [comment]
> Note that I wouldn't want people to return objects. It's mainly for lists.

Good luck communicating that and setting the right expectations :/

Are there any other cases this can solve other than lists? If not, why not name the wrapper something super specific like `list()` and interpret it like that? That could set better expectations.

Is simple string matching out of the question? Just checking to see if an array format is returned, and then parsing it into a list?

**Comment by OttoWinter** [comment]
> Are there any other cases this can solve other than lists?

I would say having templated attributes (useful for things like lights, universal media_player, ...) could also be done this way - if it's a thing Home Assistant wants to add support for.

**Comment by balloob** [comment]
Both lists and objects can already be created. See this example: https://github.com/home-assistant/home-assistant/pull/12469

Maybe adding this is not needed.

**Comment by OttoWinter** [comment]
Oh, that's right - good catch! We should say that it only works when the `cv.template_complex` is used:

https://github.com/home-assistant/home-assistant/blob/e4ef6b91d6552bb6f1d49b579f94a161944ce1a4/homeassistant/helpers/config_validation.py#L349-L360

Next, I want to point out that this doesn't always look super clean. I mean it's not a problem, but worth pointing out: Suppose we have a variable `rgb_color = '255,0,255'` in a script. In order to pass it into `light.turn_on`, we'd have to write:

```yaml
service: light.turn_on
data_template:
  entity_id: ...
  rgb_color:
    - "{{ rgb_color.split(',')[0]|int }}"
    - "{{ rgb_color.split(',')[1]|int }}"
    - "{{ rgb_color.split(',')[2]|int }}"
```

whereas `{{ json(rgb_color.split(',') | map('int') | list) }}` would be a bit nicer. Again, purely cosmetical and not really a problem.

**Comment by balloob** [comment]
It would be `json({{rgb_color.split(',') | map('int') | list}})` as json is not an official function but something bolted on top of the template renderer. Still looks horrible.

I've posted an example with a script with data_template to the forums and let's leave it at that for now.

**Comment by maddox** [comment]
Is it in the docs somewhere?

**Comment by balloob** [comment]
Don't think so. PR welcome 😉
