### ISSUE TITLE
Introduce a new device_class for casement windows

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/architecture#524]
## Context

In Europe we use casement windows more than up/down windows, more common on US.

Proposal is to create a new device_class for the that variant.
Name is mutuate from material design:

`mdi-window-closed-variant`
`mdi-window-open-variant`

I was also made aware of a discussion about this: [what-the-heck-is-up-with-the-window-icon](https://community.home-assistant.io/t/what-the-heck-is-up-with-the-window-icon/220029/)

## Proposal

PR for new device_class: [#46923](https://github.com/home-assistant/core/pull/46923)

## Consequences

The idea is to allow easy customization for users having a on/off icons that otherwise needs a template for each entity.

**Comment by bdraco** [comment]
HomeKit, alexa, and maybe google assistant would need to be updated to know about the new device class.

I don't think we should let MDI drive naming here. `DEVICE_CLASS_WINDOW_CASEMENT` seems like a better choice.

**Comment by chemelli74** [comment]
> HomeKit, alexa, and maybe google assistant would need to be updated to know about the new device class.

 Maybe it's time to move definitions to a dedicated `device_class.py` and import on all integrations.

> I don't think we should let MDI drive naming here. `DEVICE_CLASS_WINDOW_CASEMENT` seems like a better choice.

Good suggestion, once this is approved, I'll update the PR accordingly. Thx.

Simone

**Comment by chemelli74** [comment]
Just noticed that discussions should be preferred to issue. 
Should I close this one and move there ?

Simone
