### ISSUE TITLE
Attribution of state updates

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#53]
With the introduction of context, we are able to track what caused a state to change. However, with the current implementation the component (ie light), is responsible for passing the `context` object to `entity.async_update_ha_state` in the handling of the service call. However, this is only done if `entity.should_poll` is set to `True`. If instead, the state is pushed to Home Assistant, we won't trigger an update and instead wait for the integration to notify Home Assistant an update is ready. 

With the current approach, that context will be lost.

I suggest we allow setting a context on an entity. This context will be available for a certain period of time and state updates will be attributed to that context.

```python
class Entity:

    def async_set_context(self, context):
        self._context = context
        self._context_set = dt_util.utcnow()

    @property
    def context_recent_time(self):
        """Time that a context is considered recent."""
        return timedelta(seconds=5)

    async def async_update_ha_state(self, force_update=False):
        …

        if (self._context_set is None or
                dt_util.utcnow() - self._context_set > self.context_recent_time):
            context = None
        else:
            context = self._context

        …
```

**Comment by MartinHjelmare** [comment]
Looks good. The critical factor here is the timedelta, I think. Some entities might represent sleeping actuator nodes, that wake up on an interval, check for messages to execute, then go back to sleep. For those cases, 5 seconds could be too short.

**Comment by awarecan** [comment]
Feel like an over design. Is an empty context already meant that update was caused by integration, not a particular user (e.g., from device itself)

**Comment by balloob** [comment]
I've updated the proposal so that for specific entities/devices, it can be updated by the developer.

**Comment by balloob** [comment]
If an empty context is given, a new context will be generated inside the core.

**Comment by balloob** [comment]
Opened a PR to address this issue.
