### ISSUE TITLE
Extending type hints

### ISSUE THREAD

**Issue by scop** [home-assistant/architecture#55]
I would be willing to help out in extending type hints across the entire HA code base. But because this is a largish undertaking, I would like to gain assurance that it is desirable and such work would be accepted before doing more work on that front.

Some work is already submitted in PR home-assistant/home-assistant#15853

**Comment by andrey-git** [comment]
I think the goal is to have the core typed. Maybe also "core" components that are called from core, like persistent notifications and a few others.

**Comment by awarecan** [comment]
Dynamic is beauty of Python, I don't like use typing everywhere.

For example

```python
async def auth_manager_from_config(hass, provider_configs)
```

I am okay change it to

```python
async def auth_manager_from_config(
        hass: HomeAssistant, provider_configs: list) -> AuthManager
```

But not your version

```python
async def auth_manager_from_config(
        hass: HomeAssistant, provider_configs: List[Dict[str, Any]]) -> AuthManager
```

**Comment by armills** [comment]
The flexibility of dynamic typing is convenient for quick hacking, but I'd definitely like to see strong typing in our core and particularly our auth modules. That's something we want to be sure is done right.

Also fine deferring typing until the flurry of development is done though.

**Comment by MartinHjelmare** [comment]
I think typing is good and we should have it for the core at least. We should follow the docs about typing when doing typing. Typing a function incompletely isn't good. It's also better to do a whole module completely than doing part of a module, to be able to use the monkeytype tool.

https://developers.home-assistant.io/docs/en/development_typing.html

If possible we should keep the line length in check though, to not have the comments go far beyond our preferred max line length. Multi-line typing comments seem to be possible from a quick google. But I'm not sure.

**Comment by awarecan** [comment]
Alright, I didn't noticed this guide's exist. I will withdraw from my position.

**Comment by frenck** [comment]
I think it is safe to say, we are type hinting!
(We should do it more though...)

Nevertheless, time to close this one up. It is stale, and a considerable amount of type hints is in our codebase now.
