### ISSUE TITLE
alarm_control_panel custom STATE_ALARM_* states not supported in UI

### ISSUE THREAD

**Issue by gwww** [home-assistant/architecture#56]
When adding a custom arming mode for an alarm_control_panel the UI does not recognize the custom arming mode.

For example, the ElkM1 alarm panel supports arming in vacation (custom state `STATE_ALARM_VACATION`) mode. There is no method to access vacation mode in the UI arming dialog.

What is the method to be able to arm a custom arming mode?

**Comment by gwww** [comment]
Opened https://github.com/home-assistant/home-assistant-polymer/issues/1561.

Related issue: https://github.com/home-assistant/architecture/issues/54

**Comment by balloob** [comment]
Custom states are not supported. We can't build UIs or expose things to Alexa or Google home if we don't know what we're building for. We set the states, that's what we support.

**Comment by BioSehnsucht** [comment]
@balloob Is it enough to provide a PR adding these states to `homeassistant.const` or is there other work that would be needed to make them officially supported?

**Comment by gwww** [comment]
I've been chewing on how to respond to this all weekend. I don't have a great response. I'm curious to understand why the states are what they are and "that's what we support".

Perhaps this is a hard problem to solve. It could be, I don't know hass well enough. I've solved similar problems before in systems just as complex. It took a great team collaborating to solve them. 

Perhaps this is not a priority. I get that there's lot of things to work on in developing this platform. However, closing this issue indicates to me that this doesn't fit on any priority list.

Perhaps it's not worth solving. Maybe most of the platforms that are going to be integrated are served well enough by the system that is there. I find that hard to believe. In my instance, arming an alarm panel in vacation mode is not terribly unique.

Perhaps its me. I could be too demanding, perfectionist, curious, .... The Open Source culture may be in conflict with the way it work. I'd like to think I can get along, work in the style of the other contributors. If I can't I'd also like to know that!

Perhaps there's another reason. The problem with guessing is people will create their own narrative. Sometimes that works. Sometimes not so much.

What I do know is that I have a passion for solving complex and interesting problems with software.

I also know is that the response "We set the states, that's what we support." doesn't encourage me to want to collaborate on improving an already awesome platform.

So, I'm left wondering what do I do now and hoping that we find a way to create dialog.

**Comment by balloob** [comment]
If our abstractino for the alarm component is not matching with all alarm systems out there, this is the right place to discuss this. In fact, there is #54 that does just this. 

This is not a priority for me personally, but it's open source and there might be for others. If you want to spend the time on this, come with a proposal and implement it, go for it.
