### ISSUE TITLE
New Entity Proposal: Boiler

### ISSUE THREAD

**Issue by zxdavb** [home-assistant/architecture#59]
I am in the process of adding a new CH/HW (central heating / hot water) component.  I see that there is no `boiler` class & @balloob has previously suggested one. With thanks to ideas in another issue herein, I suggest the following as a starting point for discussion...

In my mind, a boiler can be heated by various sources (an electrical element(s), or from (say) a combi/district boiler, via a coil).  

A cylinder is a container for HW, filled with (either) cold water, which is heated used one of the two previous methods, or filled with hot water from (say) a combi/district boiler.  Cylinders may have an internal 'cylinder stat' which will stop the boilers from exceeding some maximum temperature - this may not be part of the boiler.

```
icon = "mdi:thermometer-lines"
supported_features = SUPPORT_OPERATION_MODE | SUPPORT_ON_OFF | support_temperature | support_target_temp
state: [
  STATE_OFF,  # boiler not active (not using energy), current temp is irrelevant
  STATE_ON,  # boiler will act to attain/maintain target temp
]

state_attributes: [
  'operation_mode': [manual, schedule, etc]
  'current_temperature', # reported by a temperature sensor
  'target_temperature', # the temperature to reach...
  'temperature_unit',  # TEMP_CELSIUS, or the other one...
  'min_temperature',  # lowest possible target temp
  'max_temperature',  # maximum possible target temp
  'precision',  #  1, 0.5 or 0.1 (PRECISION_WHOLE, HALVES, TENTHS)
]

Services: [  # some devices allow setting these parameters ahead of time
  'set_operation_mode':  { 'service_data': ['operation_mode'] }
  'set_temperature': { 'service_data': ['target_temperature'] }
  'turn_off',
  'turn_on': {}
]
```

**Comment by zxdavb** [comment]
Here is the latest suggested schema:
```
TBA
```

**Comment by elupus** [comment]
Curius how this turns out. I'm author of a nibe heat pump custom component. At the moment I'm pretty much spraying sensor entities, but that is quite messy.

**Comment by zxdavb** [comment]
I was thinking about state.  The boiler could be OFF (not doing anything to raise current_temp to target_temp), or ON (reading current_temp, and if below that, doing something to raise it to target_temp).

If the boiler is ON, should we have the option of saying it is ON_AND_HEATING (or just HEATING), and ON_BUT_IDLE (or just IDLE)?

**Comment by tsvi** [comment]
I think HEATING and IDLE are the correct names as ON_AND_HEATING would
imply you could have OFF_AND_HEATING???

**Comment by zxdavb** [comment]
I agree - OFF & ON, or OFF, IDLE & ON it is!

**Comment by dgomes** [comment]
I think boiler is not generic enough.

E.g. I have solar panels for water heating, with state and information much similar to the boiler use-case.

HVAC is too generic (it includes more things besides hot water), but DHW (Domestic Hot Water) is the general term used by manufactures.

**Comment by zxdavb** [comment]
Do we agree the basic use-case is for stored water to be heated by some system?  That would include all 3 means mentioned thus far: 1) electrical element (from mains, PV cells), 2) HW coil (system boiler, district HW, solar panels), and 3) gas-fired.

When you say "boiler is not generic enough", do you mean the name of the entity class?  I think DHW doesn't offer enough advantage as a name, e.g. the HW may not be domestic.  Most people would understand 'boiler', even though the water never boils (I understand 50-60C is about right, with 61-62C used to kill any resident pseudomonas bugs).

I am from the UK, and I think the term here would be 'cylinder', since most people have a (tankless) combi boiler, which produces HW on demand.

In the US, I think 'boiler' is the term, and I happen to know that some in some countries it's called a 'geyser'.

**Comment by elupus** [comment]
Do you include hot water used for floor heating and radiators in that definition?

**Comment by zxdavb** [comment]
No, I wouldn't - that will come under climate - even if the HW for the radiators, and the HW for the heat exchanger in the boiler are coming from the same source!

**Comment by dgomes** [comment]
My 'cylinder' is heated by my solar panels and by a Heat Pump as a backup (when the desired temperature is not reach due to lack of sun).

DHW is more encompassing, or just hot-water and there fore include other systems such as central heating.

My solar panels just provides states (ON/OFF - circulation pump that transfers heat from the panels to the cylinder) and temperatures (panel temperature + cylinder temperature).

**Comment by zxdavb** [comment]
@dgomes I guess the question is: is this component the _source_ of heat for the cylinder, or is it the cylinder itself?  My preference is the latter, because a cylinder can have multiple sources of heat (mine has a backup electrical heater).

I think **hot-water** is not quite right - **stored-hot-water** would be better, or **stored-dhw**?  I'd still vote for **boiler**, tho'. 

Similar to yours, my main heat source (a system boiler that provides HW to the heat exchanger in the cylinder) can track `delivered_temp`, and `return_temp` (the difference mostly being transferred to the HW in the cylinder).

We could add `heat_source` (main_heat_source, backup_heat_source, current_heat_source) as a `state_attribute`?  And something like `cutout_temp` (the temp beyond which the cylinder will send a signal back to the heat source saying to stop)?

**Comment by dgomes** [comment]
I think it would be most useful to have the combined system, even if not every system can provide all the information. 

I'm think along the lines of the `weather` platform.

Let's agree on stuff:

State:
- HEATING: heat is being transferred to the system (MANDATORY)
- IDLE: no heat is being transferred but the system controller is live (MANDATORY)
- OFF: no heat is being transferred and the system controller if off 

Attributes:
- `current_temp`: reservoir temperature (MANDATORY)
- `delivered_temp`: temperature supplied to the reservoir
- `return_temp`: temperature at the exit of the reservoir

**Comment by zxdavb** [comment]
FWIW: My 300L cylinder has two safety systems - one is configurable, the other is a hard wired absolute upper limit of: 90C (194F) and 10bar (1000kPa), its usual maximum is 85C/8bar, but usually 55-65C and 3.5bar.

It has 6kW via electrical immersion heaters (takes ~3h to heat up from room temp), and approx 3x that via the coil.

So it's a water heater, then!

**Comment by dgomes** [comment]
Mine would also be a water-heater ;)

![water-heater](https://user-images.githubusercontent.com/137684/45105290-37f4b580-b134-11e8-9560-2dba4c5bb536.png)

**Comment by zxdavb** [comment]
OK, lets go with Off/On/Heating.

**Comment by zxdavb** [comment]
Do we want to track the supply type?
`SUPPLY_SYSTEM_BOILER`, `SUPPLY_DISTRICT_BOILER`, `SUPPLY_SOLAR_PANELS`, `SUPPLY_IMMERSION_HEATER`, 
or
`SUPPLY_PRIMARY`, `SUPPLY_BACKUP`?

**Comment by dgomes** [comment]
I believe it is not relevant to the functioning of the system.

Although it could be interesting to the GUI (showing a different logo depending on the supply type)

**Comment by dgomes** [comment]
we should use `device_class` as in other platforms :)

**Comment by balloob** [comment]
water heater has been added as a component
