### ISSUE TITLE
RFC: Entity Component owners

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#6]
(for now, let's focus on entity components)

I would love for people to step up and take ownership of certain entity components (light, switch, climate, media player). Right now random PRs will make changes to the entity base classes without a grand vision keeping it sane. Which color scheme do we support in the light component? What is operation mode supposed to contain in the climate component? etc etc.

The owner of an entity component would be responsible for:
 - Defining the entity component: what is a light? What is a light supposed to do, what methods does it support and what service data would we need?
 - Final say on PRs that touch that entity component

We will still have some generic guidelines for entity components like:
 - Use `supported_features` to indicate which features are supported
 - Use `device_class` to indicate different device types within a category
 - Unique services should be added to the platform and not the base class

**Comment by lucasweb78** [comment]
I've been spending some time getting to grips with those questions with regards to the `media_player` component and am happy to keep doing so. I know that several of the `media_player` component implementations have a core contributor who may or may not want to be involved or have some strong opinions and would be happy to work with anyone else who wants to get involved in shaping the `media_player` component

**Comment by andrey-git** [comment]
@balloob if it were technically possible - would you grant component/platform owners write permissions into their specific component/platform?

**Comment by balloob** [comment]
I would not consider someone for entity component owner unless they are also member of our org. Although there is no official vetting process, I generally invite people to the org that have shown solid code quality in PRs and ability to communicate in issues/PRs/discord/1 on 1 chats.

I think that it's a security risk to give a person write access to a platform that they contributed to Home Assistant. It would hurt our code quality and probably violate a lot of async things. Although I admit that the current approach of us reviewing everything is very demanding, it guarantees a certain level of quality.
