### ISSUE TITLE
Require pass before activating alarm?

### ISSUE THREAD

**Issue by raccettura** [home-assistant/architecture#61]
I made some tweaks a few months ago to make the alarm a bit more like a typical home alarm with a keypad which does make it simpler to use, however it raises a new question:

Should you require a code to arm the alarm?  It seems to me this is unnecessary and atypical compared to a traditional alarm.  The keypad shouldn't even appear when activating, just a matter of what mode (see issue #60). Once activated the keypad/text field appears and you need a code to deactivate.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
