### ISSUE TITLE
Extend 'media_player' with a 'channel_list' attribute

### ISSUE THREAD

**Issue by stephanerosi** [home-assistant/architecture#62]
Hello, adding this attribute would allow to show a channel selection dialog in the media_player card in the frontend.

By example, this would allow TV channel selection.
See PR for a visual : https://github.com/home-assistant/home-assistant/pull/15941

**Comment by balloob** [comment]
This is not a scalable solution. Other media players have favorites, others have playlists, artists, albums etc. The state machine should only contain the data that is the state of a device.

The moment something is proposed to add to the state machine for the sake of UI, it's a red flag.

Instead we should make a generic media browser API that the frontend can access. Base it on a tree structure that can be browsed so it can also handle media players with complicated backends.

**Comment by stephanerosi** [comment]
@balloob Do you have any example of such an API for another component? (so that I can use it as an example)

**Comment by stephanerosi** [comment]
@elupus Agree with you

**Comment by balloob** [comment]
Not all media players have a source.

No example API. We havent done this before

**Comment by elupus** [comment]
Would that case be the same as a single static source?

**Comment by balloob** [comment]
If there is a single static source, the media player would just return `None` from the media browser, indicating it doesn't support it.

**Comment by stephanerosi** [comment]
Hello, sorry I was busy these last few days.

So, as per @elupus suggestion, would a 'media_list' attribute be an acceptable compromise solution?

**Comment by balloob** [comment]
No compromise possible.

**Comment by stephanerosi** [comment]
Arf... I guess I'll work on an API when someone has begun something I can use as an example...
