### ISSUE TITLE
Generic handler of device availability

### ISSUE THREAD

**Issue by PaulAnnekov** [home-assistant/architecture#64]
The reason why we need most of devices to report availability state and its implementation for one of the components is here: https://github.com/home-assistant/home-assistant/pull/11631. Today I ran into the same problem with `miflora.py` component, started to implement similar solution and then stopped myself, because it looks like we need some generic solution.

I'm not familiar with all variety of devices that HA supports, so I can't propose a clear solution. I think it should be like this:
- There should be configurable timeout variable per-entity platform, like `unavailable_interval`
- If polling device sets `STATE_UNAVAILABLE` state during `unavailable_interval` period on each update - we make `Entity.available()` to return `false`
- If pushing device doesn't call `schedule_update_ha_state` or sets state to `STATE_UNAVAILABLE` during `unavailable_interval` period on each update - we make `Entity.available()` to return `false`
- We can set `unavailable_interval` of all polling devices to `2 * scan_interval` by default
- Pushing devices won't be checked for unavailability, unless developer will set `unavailable_interval` variable

**Comment by awarecan** [comment]
What happens if `Emtotu.avialable()` is `False`? How and when it turns back to `True`?

**Comment by PaulAnnekov** [comment]
I thought about solution one more time and found it's not good. Device should not set `STATE_UNAVAILABLE` anywhere, just make `available()` to return True/False. I will think how to make it easier for developers.

**Comment by balloob** [comment]
We should not override `Entity.available` from a system level, it's a property controlled by the integrations.

It could be achieved rather simply by extending the entity class and making it an opt-in for integrations.

```python
class AvailableEntity(Entity):
    @property
    def available_interval(self):
        return timedelta(minutes=150)

    @property
    def available(self):
        return (dt_util.utcnow() - self._last_updated < self.available_interval and
                super().available)

    def update_ha_state(self, *args, **kwargs):
        self._last_updated = dt_util.utcnow()
        if self._last_update_task is not None:
            self._last_update_task.cancel()
        self._last_update_task = self.hass.loop.call_later(
            self.available_interval.total_seconds(), self.async_schedule_update_ha_state)
        super().update_ha_state(*args, **kwargs)
```

**Comment by PaulAnnekov** [comment]
@awarecan 
> What happens if Entity.available() is False?

UI icon of the entity gets "unavailable" overlay. State changes to "unavailable". You can add an automation to send you a notification when state changes to "unavailable" and back.

> How and when it turns back to True?

For polling devices - `EntityPlatform` calls `Entity.async_update_ha_state()` each `scan_interval` (30 seconds by default). This method gets `Entity.available()` property (https://github.com/PaulAnnekov/home-assistant/blob/dev/homeassistant/helpers/entity.py#L206) and we  can find device is available again. For pushing devices - I will think how to make this check.

**Comment by PaulAnnekov** [comment]
@balloob I didn't suggest to overwrite it on system level :). I said we should override it in each specific device.

> by extending the entity class
It looks like you code doesn't work for polling devices at all, because it doesn't take into account that user can change `scan_interval` for polling device, so `available_interval` should use it. Also it should call some successor method to check if device is really unavailable. But looks good as a draft.

Do you know any device for which "unavailable" state is inappropriate?

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
