### ISSUE TITLE
Break up scene component

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#65]
Right now the scene component has a `homeassistant` platform and it has platforms for various integrations offering scenes.

As I am exploring creating a UI to create sccenes, it requires extra logic that would be specific to the `homeassistant` scene platform.

To keep logic separate, I suggest we split up the scene component. We keep `scene` just for Home Assistant scenes and create a new `scene_external` component that can contain the scene platforms.

**Comment by pvizeli** [comment]
Good idea.

maybe we can rename our internal scene to `input_scene`, because we write only states back they are defined in a rule set?

I think we should named the external scene and use the fake scene as input component?

**Comment by balloob** [comment]
I don't like perse the word `states`, what about `scene_core`?

**Comment by balloob** [comment]
I realized that we should not rename our internal scene component, that would be a huge breaking change. I prefer to break the external scenes, they are mainly loaded via discovery so are not going to be breaking changes.

**Comment by Jc2k** [comment]
I was going to open a new issue about adding UI for scenes and found this. As it might mean breaking changes, is it something on the 1.0 milestone radar?

It looks like we have `homeassistant.components.homeassistant.scene.HomeAssistantScene`. Could a UI just work with that entity directly or are the changes discussed above still required?

**Comment by balloob** [comment]
I've come to realize that since the `scene` part now lives under Home Assistant, we should be able to do this without breaking up the scene integration.

**Comment by Jc2k** [comment]
Ok - should we close this ticket then or can I hijack it to discuss scene editing API/UI?

Starting with the API I want to either:

(a) Make a ConfigEditView that stores scenes in a Storage.
(b) Make a ConfigEditView for editing a scenes.yaml
(c) Make a ConfigEditView for editing a scenes directory

(a) is my first choice and what I would have chosen had I not seen that `homeassistant.components.config` is able to edit yaml files to some extent. Existing scene config would continue to work exactly as they do now. New scenes could be added and edited entirely through the front end. Using storages mean we can do migrations later if we need to. There would be validation to stop collisions being introduced via the API, and the yaml scenes would have priority when loading at start up.

Should this be added under `homeassistant.components.config` or under `homeassistant.components.homeassistant.scene`? For (b) and (c), seems clear that it belongs under `.config`, but for (a) was less sure.

**Comment by balloob** [comment]
I suggest a websocket API to CRUD scenes which are stored in storage. I have #232 open to discuss if automations/scripts UI should work with storage too.
