### ISSUE TITLE
Security issue of Molohub(a remote access component)

### ISSUE THREAD

**Issue by haoctopus** [home-assistant/architecture#66]
##### Backgroud
As far as we know, Home Assistant runs under the LAN, if you want to access the HA remotely through the WAN, the router under the network where the HA deployment environment is located must supports port mapping, and needs to be directly accessible on the public network after mapping. And generally DDNS is also needed to solve problem with IP changing. Even though DDNS is successfully setup, it's unstable and has chance to break down because of IP or port changing. But due to the network provider's The complexity of the network environment, and the complexity of the user's own internet environment, it is difficult to systematically summarize a set of general and effective methods to achieve the target. 

##### Proposal
We committed a PR (https://github.com/home-assistant/home-assistant/pull/16253) to solve this problem, and make user easier to access  HA frontend(localhost:8123) remotely.

##### Discussion
But we still have some questions about the comments on the PR, and need some discussion to determine what and how to improve:

https://github.com/home-assistant/home-assistant/pull/16253#issuecomment-416854536

For security issue that user worry about remote server owner can access their instance, we think its resolvable. User have http component logs at their local machine, if something like that happened, user will have awareness while checking the log. If you think the issue is still, we may find some other method to prevent that.

We think HA should be accessed everywhere and everytime, the MoloHub component makes it easier. Although its now incomplete, it is worth to be discuss and improve. we are happy to listen to your suggestions, and do our best to solve the problems.

**Comment by balloob** [comment]
So I agree that the problem you're trying to solve is a real problem. It would be great to make it easier for users to make a remote connection.

However, your current approach means that you route all users traffic unencrypted over your proxy. This means that if you were malicious, you could easily copy refresh tokens when a user logs in, giving you permanent access to the instance.

For us to merge a component, means we tell our users: hey, this is ok to use. Sure, integrations can break but it will never impact your privacy by leaking the data. A leak of data would be a permanent stain on our reputation.

I don't feel comfortable allowing anyone to run a proxy that could access our users data.

And another thing that is also raising a bit of alarm bells for me is that all your accounts are anonymous. Your GitHub account has been created July 17, 2018. The only contribution of it is this component. The website [molo.cn](https://www.molo.cn/), that users use to login, show no logos or affiliation with anything. 

I think it would be a good start to make this available as a custom component. That way you don't need our endorsement and people can still easily install it. However, when they do, it's on their own risk.

**Comment by bachya** [comment]
Everyone should be aware of @balloob’s commentary on this component:

> So I agree that the problem you're trying to solve is a real problem. It would be great to make it easier for users to make a remote connection.
> 
> However, your current approach means that you route all users traffic unencrypted over your proxy. This means that if you were malicious, you could easily copy refresh tokens when a user logs in, giving you permanent access to the instance.
> 
> For us to merge a component, means we tell our users: hey, this is ok to use. Sure, integrations can break but it will never impact your privacy by leaking the data. A leak of data would be a permanent stain on our reputation.
> 
> I don't feel comfortable allowing anyone to run a proxy that could access our users data.
> 
> And another thing that is also raising a bit of alarm bells for me is that all your accounts are anonymous. Your GitHub account has been created July 17, 2018. The only contribution of it is this component. The website [molo.cn](https://www.molo.cn/), that users use to login, show no logos or affiliation with anything.
> 
> I think it would be a good start to make this available as a custom component. That way you don't need our endorsement and people can still easily install it. However, when they do, it's on their own risk.

Source: https://github.com/home-assistant/architecture/issues/66
