### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#67]
I want to start the discussion about permissions. This is possible now that we have an auth system and context, which allows us to see where a service call came from.

## Goal of this proposal

Create a flexible system that allows:

  - limiting full access to sections of configuration (Hass.io, integrations, users)
  - limiting access to viewing the states of specific entities
  - limiting access to controlling the states of specific entities
  - allow future extensions

## Non-goal of this proposal

 - Add access token specific permissions
 - Limiting access to Lovelace views

## Proposal

1. Owner user will always have all permissions.
2. Giving write access implies read access
3. Permissions contains 2 categories: "config section access" and "entity access"
4. ~~We will use our existing [entity filter helper](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/entityfilter.py). This allows the user to define `include_domains`, `include_entities`, `exclude_domains` and `exclude_entities`.~~ Not doing this as it won't work with proper read/write checks.
5. Unauthorized access will generate an event to be logged in the logbook
6. The dev tools will only be accessible by the owner.

## Implementation

APIs returning states will have to filter them based on what the user can see. Impacted APIs are `/api/states` and websocket `get_states`.

Permission check to interact with an entity will be done as late as possible: in the method that executes an entity service. That will be inside the service helper [`_handle_service_platform_call`](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/service.py#L217).

Templates will need to also honor the access system. This will require updates to the [AllStates and co](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/template.py#L200) classes.

**Comment by cgarwood** [comment]
Everything sounds good in the proposal. Just one question:
How will that work with things like template sensors and groups? If you have a group of lights, will you also need permission to every individual light entity in that group, or will it inherit? Likewise for templates, I'm assuming you'll need permissions to both the template sensor, and the sensor it is templating for it to work?

**Comment by awarecan** [comment]
So, no fine-grained permission control for state_attribute and single service. If you have read access to an entity, you can read all state_attributes. If you have write access to an entity, you can call all services provided by this entity.

**Comment by balloob** [comment]
hmm that is a good point. Although it is something that I think we don't need in the first version, especially because it will require the frontend to be able to conditionally show all controls 😱

**Comment by armills** [comment]
We should be able to create resource IDs for everything that we want to secure in hass, and once we have that the ACLs should be easy enough to define. As long as we build out the system with the assumption that any node could have future children for more fine-grained control, we should have a lot of flexibility in the future.

I'd vote for a format that's _not_ JSON, since order is important for expressing rules like this.

As a quick visual example:
```
config -read
config.core.restart +write
entities.climate +read +write
entities.climate.*.services.set_temperature -write
entities.light.living_room.* +read
entities.light.living_room.state.attributes.battery_level -read
```

**Comment by dgomes** [comment]
I don't mean to disturb, but might be interesting to look at XACML standard as a reference for ideas/concepts. It is a well known standard and broadly used. Please note that I'm not advocating to use it in HA, just that people are aware of it.

https://www.oasis-open.org/committees/xacml/

**Comment by balloob** [comment]
@armills I think that having rules that depend on order are powerful but very difficult to built a UI for.

Having a scheme that one can define per domain or per entity works very well with a UI.

You are right about the unique resource IDs. Means we can't have something that is just "read", as that is both `state` + `attributes.*`

**Comment by pvizeli** [comment]
I don't think the frontend need aware about rights. The frontend only show what the backend send to frontend. If the frontend receive only switch entity, you see only switch entity.

We should have our own format, because we could not have ACL they normaly used on file objects or AAA that is normaly used to flag trafics. There are a lot access based rights system around. Some system like docker implement multible systems. Anyway, we should build our security system with stuff that make sense.

Since we now prefer frontend configurable systems, we should use our store mechanics based on json.

**Comment by fanthos** [comment]
Vote for @armills .
We need to support wildcard(or regex?) for entity name and service name.
`+write:temperature` or `+read:*` seems good expression for reading or writing permissions.

**Comment by MartinHjelmare** [comment]
> That will be inside the service helper _handle_service_platform_call.

So services refustered in platforms will not support access system?

**Comment by fanthos** [comment]
I think we should support permission for a group of entities, like that one can operate all lights in a room not another.
We can use one regex for multiple string match.

**Comment by pvizeli** [comment]
@balloob:
- Blacklist: User see all entity default and you select entity that are not visible by user
- Whitelist: User see no entity default and you select entity that are visible by user
Our entity filter can both system.

You are right, that fronted not know the rights of service level. I think for performance, we should create a list with access every time a new state coming in (new entity). To calculate the access on real time is not very performance. Maybe we can attach it like the entity register.

@fanthos I like the idea of groups or rolle based access. Not sure if that to complex to merge.

@all: the core is bases on state machine. A state can only be changed with a service call or the background updates from device itself. In that case a read&write access based to entity don't work with that effort that we want have. User have access to entity (that is all time only readable) and write access are defined with service calls that user can execute.

**Comment by balloob** [comment]
@MartinHjelmare they will have to add support for that themselves, as we don't know which entity they will interact with.

**Comment by MartinHjelmare** [comment]
Can't platforms add context?

**Comment by pvizeli** [comment]
I think we crow the entity schema like:

```
Entity:
_________________________
| Statemachine:             |
|    - State                      |
|    - Atttribute / front   |
_________________________
| Entity Register:            |
|  - Entity_id                   |
|  - Name                       |
|  - Static                        |
__________________________
| Service register:           |
|  - Available services    |
__________________________
|  Rights:                        |
|   - Visible to U/G         |
|   -  Service to U/G       |
__________________________
```

We can use the supported feature to create the service list on entity object. But we don't use it anymore on frontend.

**Comment by balloob** [comment]
I like the idea of groups too.

So then we get group policies and users are member of a group.

The root keys in the policy are the different categories. Underneath the Entity category will be either `entity_id` or "contexts" that can contain an entity. A context can be a domain to which an entity belongs, but could in the future also be a device that an entity belongs to.

```json5
// Replace anything with `true` to whitelist everything underneath.
{
  // Root level keys are permission categories
  "config_entries": {
    // Under a root level key are the items that are described
    "entries": {
      "132jhsdflkjasdlkjasd": {
        "create": true,
        "delete": true,
        "edit": true,
      }
    }
  }
  "entities": {
    "entity_id": {
      "climate.living_room": {
        // Any thing that works for a domain will also work for an entity.
        "state": true,
        "attributes": true,
      }
    }
    "domains": {
      // Give read/write access to all of switch domain.
      "switch": {
        "state": true,
        "attributes": true,
        "services": true,
      },
      // Give read access to all of light domain.
      "light": {
        "state": true,
        "attributes": true,
      },
      "climate": {
        "state": true,
        "attributes": true,
        // Future
        "services": {
          "set_temperature": true,
          "set_fan_mode": {
            "mode": {
              "allowed_values": ["normal", "max"]
            }
          }
        }
      }
    },
    "devices": {
      // Give full access to all entities related to a device (ie a light)
      // Keys are the device IDs in device registry
      "1238u123123123123": true
    }
  }
}
```

This can be gradually built out, no need to implement everything at once. For MVP we can start with the following two types:

```json5
{
  "entities": {
    "entity_id": {
      // toggle each entity on the user is allowed to see
      "climate.living_room": true
    }
  }
}
```

```json5
{
  "entities": {
    // access to all entities
    "entity_id": true,
  }
}
```

**Comment by balloob** [comment]
Going to move `state` and `attributes` under a new "view" category, that way you can just whitelist them both at the same time.

```json5
{
  "entities": {
    "entity_id": {
      "climate.living_room": {
        "view": true,
      },
      "light.kitchen": {
        "view": {
          // We will probably never support this
          "state": true,
          "attributes": false,
        }
      }
    }
}
```

**Comment by balloob** [comment]
I've started exploring an implementation here https://github.com/home-assistant/home-assistant/pull/16890
