### ISSUE TITLE
Build azure capabilities

### ISSUE THREAD

**Issue by vijayshinva** [home-assistant/architecture#68]
I am planning to integrate capabilities of Azure into HomeAssistant. To start with I have built a simple sensor platform that shows the status(Running, Starting etc...) of a Virtual Machine hosted in Azure. This can be helpful to monitor servers like VPN, Email etc which homeassistant users use.

There is a pull request https://github.com/home-assistant/home-assistant/pull/16326

I also plan to add additional sensor platforms and notifications based on Azure. There will also be services that can help start or stop a VM in Azure.

My vision of this implementation is to have a component called azure that holds the very basic common data like the azure subscription details and have sensor platforms for each of the services azure provides something like

azure:
  client_id: 96b9XXXX-XXXX-XXXX-XXXX-XXXXcef0eff8
  client_secret: SECRET-PASSWORD
  tenant_id: 7912XXXX-XXXX-XXXX-XXXX-XXXX69bbace1
  subscription_id: f231XXXX-XXXX-XXXX-XXXX-XXXXa3299dea

sensor:
  - platform: azure_vm
    name: HASSIO_TEST_VM_ONE
    resource_group: HASSIO_TEST_RESOURCE_GROUP
  - platform: azure_servicebus
    name: SERVICEBUS_NAME
  - platform: azure_vm
    name: HASSIO_TEST_VM_TWO
    resource_group: HASSIO_TEST_RESOURCE_GROUP

notify:
  - name: NOTIFIER_NAME
    platform: azure_servicebus
    queue_name: QUEUE_NAME
    connection_string: CONNECTION_STRING
  - name: NOTIFIER_NAME
    platform: azure_eventhub
    eventhub_name: EVENT_HUB_NAME
    connection_string: CONNECTION_STRING

So azure_vm and azure_servicebus will be separate platforms. This is because Azure has a lot of disparate services on offer and it is better these platforms be kept separate modules. Trying to treat azure as a single platform and use monitored conditions will complicate the implementation and maintainability in the long term.

**Comment by MartinHjelmare** [comment]
Note that sensor platforms will never register services. Sensors are read only. Services can be implemented in the azure component or, if appropriate, in an actuator platform like switch.

**Comment by pvizeli** [comment]
Yes, services should be on component. Maybe you can discovery all available VMs and use that without user need enter that in config.

**Comment by vijayshinva** [comment]
That is correct services will be on the Azure component.

**Comment by balloob** [comment]
All platforms that are related to an integration need to have the same filename. You can have different types within the same platform, for example see MQTT light. Even a platform file can be split in multiple as can also be seen with the MQTT light.

**Comment by MartinHjelmare** [comment]
I think we can close this as the questions have been answered as far as I can tell.
