### ISSUE TITLE
You are running an unsupported installation CRITICAL: 2021/12/10 21:27:44 main.go:55: Connection ":1.1920" is not allowed to own the service "io.hass.os" due to security policies in the configuration file

### ISSUE THREAD

**Issue by userosos** [home-assistant/architecture#681]
## Context

Hi! I have:
1) docker --version
Docker version 20.10.11, build dea9396
2) systemd --version
systemd 247 (247.3-6)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
3) apt info network-manager
Package: network-manager
Version: 1.30.0-2
4) dpkg -l apparmor | tee
ii  apparmor       2.13.6-10    amd64        user-space parser utility for AppArmor
5) user@nuc:~$ screenfetch
```
         _,met$$$$$gg.           user@nuc
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 11 bullseye
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 5.10.0-9-amd64
   ,$$P'              `$$$.      Uptime: 4d 7h 26m
  ',$$P       ,ggs.     `$$b:    Packages: 2105
  `d$$'     ,$P"'   .    $$$     Shell: bash
   $$P      d$'     ,    $$P     Disk: 60G / 168G (37%)
   $$:      $$.   -    ,d$$'     CPU: Intel Pentium N3700 @ 4x 2.4GHz
   $$\;      Y$b._   _,d$P'      RAM: 1464MiB / 3854MiB
   Y$$.    `.`"Y$$$$P"'
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""
```
6) user@nuc:~$ os-agent --vesrion
INFO: 2021/12/10 21:27:44 main.go:31: Start OS-Agent 1.2.2
CRITICAL: 2021/12/10 21:27:44 main.go:55: Connection ":1.1920" is not allowed to own the service "io.hass.os" due to security policies in the configuration file
**Install the software from** https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md
 
## Proposal

I want can't see You are running an unsupported installation in Supervisor/System. See the pic.

## Consequences

I can see the pic
![изображение](https://user-images.githubusercontent.com/22872748/145623976-eeb8e1cb-fff6-4157-817f-7aab78f41c3b.png)

**Comment by frenck** [comment]
This is not an architectural proposal, but an issue report. That is not what this repository is for.

**Comment by userosos** [comment]
Ok. I crated the an new bug.
https://github.com/home-assistant/supervisor/issues/3351
