### ISSUE TITLE
Translations in the backend

### ISSUE THREAD

**Issue by hobbypunk90** [home-assistant/architecture#69]
There is no possibility to get translations in the backend.
To specify my problem:
I'm working at the Hangouts component and i work with intents. 
When there is no intent matching the given input i only can answer in a not translated sentence.
I see a similar problem in the plant component, if there are problems the state switches to problem and the attributes have a list of problems all in english and not translatable.

**Comment by balloob** [comment]
Translations are currently implemented as a frontend-only concern and linked to the language preference stored per browser. We currently don't have the idea of an "instance" language.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
