### ISSUE TITLE
Add water/fluids to available device classes

### ISSUE THREAD

**Issue by jensihnow** [home-assistant/architecture#697]
## Context

With [Energy](https://www.home-assistant.io/docs/energy) management being a huge success and [gas](https://www.home-assistant.io/docs/energy/gas/) consumption already available a missing puzzle piece is water. 

## Proposal

Make water available as [device class](https://developers.home-assistant.io/docs/core/entity/sensor/) and therefore usable within sensors.

Maybe instead of implementing _water_ it is an option to implement _fluid_ as this would cover others like _oil_ as well. Interestingly, with multiple sorts of carbon_ / nitrogen_ available maybe it should be rather fluid_water and fluid_oil. 

Water or fluids should be supported similarly as Gas in regard to Energy Management, e.g. on Frontend (Water consumptuon graph) see [Lovelace Energy](https://www.home-assistant.io/lovelace/energy/).

## Consequences

Water or fluids are most likely very similar to gas, as they are measured in m³/ ft³. It needs a decision if every fluid should be implemented individually or similar like gas in a more generic way covering all gas types. 

As one m³ reflects 1,000 liters there could be use-cases where people would rather user liters instead of m³. One could argue having liters is another way of implementing fluids. Obviously this might cause complexity about m³ vs. ft³. I'm actually not sure if ft³ are stored in m³ or ft³ (... _Volume of gas, statistics will be stored in m³._ ..., see [sensor](https://developers.home-assistant.io/docs/core/entity/sensor/)).

## The alternative

Using device class gas is an alternative as it is also measured in m³. While it works, it is technically not correct.

## Additional note

* [Existing Feature Request](https://community.home-assistant.io/t/energy-water-usage/335483/21 )
* [Example for water metering](https://community.home-assistant.io/t/water-metering-using-sensus-hri-libmbus-mqtt-and-utility-meter-integration/373010) 
* [Sensor Entity reference](https://developers.home-assistant.io/docs/core/entity/sensor/)

**Comment by Hedda** [comment]
Please also see the very related feature requests with discussion threads in the forum here which shows there is a demand for this:

https://community.home-assistant.io/t/rename-the-energy-dashboard-to-utility-to-make-it-include-readings-for-all-public-utility-resources-including-electricity-gas-heating-and-water/338847

https://community.home-assistant.io/t/energy-water-usage/335483/

**Comment by Hedda** [comment]
> Water or fluids are most likely very similar to gas, as they are measured in m³/ ft³. It needs a decision if every fluid should be implemented individually or similar like gas in a more generic way covering all gas types.

Please note modern water monittoring systems for incoming water does not only measure flow, but also temperature and pressure.

Water Leak Detector and Water Usage Monitoring System uses a combination of flow and pressure to detect small leaks, and temperature is used to warn for risk of freezing (to enable freeze guard) or risk of overheating. (as especially tap-water warmer than 20° Celcius sitting still in pipes for too long can be very dangerous to health as Legionella bacteria will then multiply).

Check out for example these commercial home automation products which feature at least those three types of sensors: 

* **Phyn** - Water Leak Detector and Water Usage Monitoring System made by Uponor and Belkin
  * https://www.phyn.com
* **Flo by Moen** - Smart Home Water Security System
  * https://meetflo.com
* **GROHE Sense Guard** - Smart Water Controller
  * https://www.grohe.us/Smarthome/sense-guard
* **Flume 2** - Smart Home Water Monitor
  * https://flumewater.com

**Comment by jensihnow** [comment]
Thanks @Hedda for adding all these details.

Pressure (cbar, bar, hPa, inHg, kPa, mbar, Pa, psi) and temperature (°C, °F) are already available as device classes, therefore they could be implemented already within the integrations. 

Flow rate is something to consider, especially for fluids. I'm actually wondering if flow-rate only becomes a number at the end, due to impulse counting of the sensor. Maybe there are sensors exposing something like liters per minute?

In [this](https://community.home-assistant.io/t/using-esphome-to-build-a-water-flow-rate-meter/119380/3) example a pulse sensor is used, which h as 27 counts for 1 liter. Additionally, the example shows _unit_of_measurement: "L/hr"_  in combindation with matchin calculation,  as well as _unit_of_measurement: "L"_ being used.

If we could now make this a device class of _water_ or _fluid_ and just name it water we might have what we need to ensure it is properly recorded and displayed e.g. in a dashboard similar/same like the Energy one. 

I like the intention of renaming the Energy to Utilities and extend it.

**Comment by Hedda** [comment]
> Flow rate is something to consider, especially for fluids. I'm actually wondering if flow-rate only becomes a number at the end, due to impulse counting of the sensor.  Maybe there are sensors exposing something like liters per minute?

Yes, there are indeed, there are many types of volumetric flow meter technologies exposing liter per minute or milliliter per second. 

https://en.wikipedia.org/wiki/Flow_measurement

The impulse counting method is really only used by basic water meters that implement a turbine flow meter such as the utility companies use to measure, as such they only offer an  amount of pulses for a set of determined liters or gallons, so guess such measurements will only use for example "P1 Monitor" and "SML sensor" based integrations to help calculate water consumption. (Still, there can be big differences in resolution between different turbine-based water meter sensors.)

Ultrasonic flow meters however do not have any moving parts and instead use ultrasound to measure the velocity to calculate volume flow, thus they can have very highly accurate resolution and offer great properties for clean drinking water meter for homes as they are maintenance-free. 

https://en.wikipedia.org/wiki/Ultrasonic_flow_meter

https://realpars.com/ultrasonic-flow-meter/

I think those often output meter per second (m/s) and then you need to calculate volume based on pipe diameter ("differential transit time measured by the sensors is directly proportional to the flow velocity in the pipe"). See example:

https://www.pce-instruments.com/eu/measuring-instruments/test-meters/ultrasonic-flow-meter-kat_152137.htm

There are also magnetic flow meters (a.k.a. mag meters, or rather electromagnetic flow meters) which technology that uses Induction to determine the flow of liquid in a pipe does not either have any moving parts but I understand that such flowmeters are much less commonly used for "clean water" (i.e. drinking water / tap water) and are instead more commonly used for "dirty water" (i.e. waste water).

https://en.wikipedia.org/wiki/Magnetic_flow_meter

**Comment by PimDoos** [comment]
I'd suggest using 'volume' as a generic device class for measuring incremental meters for both gas and fluids, as we're measuring the volume (in 'L' or 'm³') of a certain substance. This generalizes the class.
When measuring a flow of that same substance, I propose the device class to be something like `flow` or `volume_flow`, measured in a volume unit _per_ time unit, ex: 'm³/s' or 'l/min'. Examples of usecases:
* Airflow in an Air Handler in m³/h
* Flow of water within hydronic heating: l/min
* Gas consumption in the last hour: m³/h

**Comment by epenet** [comment]
Sample implementation PR for a new "water" device class (for water consumption):
https://github.com/home-assistant/core/pull/80886

**Comment by jensihnow** [comment]
Love it, thanks to @epenet and @frenck and whoever else contributed to it. Looking forward to 2022.11.🤩

**Comment by jensihnow** [comment]
This is now available see https://www.home-assistant.io/docs/energy/water and release notes for [2022.11](https://www.home-assistant.io/blog/2022/11/02/release-202211/#getting-insights-into-water-usage).
