### ISSUE TITLE
Device Tracker behavior

### ISSUE THREAD

**Issue by cybe** [home-assistant/architecture#71]
Hello,

I want to clarify the [Device Tracker](https://www.home-assistant.io/components/device_tracker/) behavior based on the current implementation ([d1e1b9b](https://github.com/home-assistant/home-assistant/blob/d1e1b9b38a06b82f6b609e68cbb99c15b934ffb3/homeassistant/components/device_tracker/__init__.py)).

This is my assumption on how device tracking should behave: A tracked device needs to be seen in a particular zone at least once within the  `consider_home` time frame to be within that zone. If not, that location information becomes stale. As we now don't have any location information, the devices location should be set to `STATE_NOT_HOME`.

However, the implementation suggests that this is not the case. There are various states where it is impossible for a device to become stale and remain "stuck" in the last known location:
* If `device.location_name` is set ([Source](https://github.com/home-assistant/home-assistant/blob/d1e1b9b38a06b82f6b609e68cbb99c15b934ffb3/homeassistant/components/device_tracker/__init__.py#L539-L540))
* If `device.gps` is set and `device.source_type` is `SOURCE_TYPE_GPS` ([Source](https://github.com/home-assistant/home-assistant/blob/d1e1b9b38a06b82f6b609e68cbb99c15b934ffb3/homeassistant/components/device_tracker/__init__.py#L541-L549))
* If `device.last_seen` is not set (i.e. Home Assistant restart) ([Source](https://github.com/home-assistant/home-assistant/blob/d1e1b9b38a06b82f6b609e68cbb99c15b934ffb3/homeassistant/components/device_tracker/__init__.py#L528)).

Furthermore, only devices in `STATE_HOME` are generally considered to become stale ([Source](https://github.com/home-assistant/home-assistant/blob/d1e1b9b38a06b82f6b609e68cbb99c15b934ffb3/homeassistant/components/device_tracker/__init__.py#L369))

From this it follows, that only devices that
1. were already seen,
2. have the current location set to `STATE_HOME` and where
3. `device.source_type != SOURCE_TYPE_GPS`

can potentially become stale and set to `STATE_NOT_HOME`.

You can also find various examples in the issue tracker [#11867](https://github.com/home-assistant/home-assistant/issues/11867) [#13723](https://github.com/home-assistant/home-assistant/issues/13723) [#10231](https://github.com/home-assistant/home-assistant/issues/10231) and the [forums](https://community.home-assistant.io/search?q=Always%20home) where devices became stuck in the home zone.

## Proposal
If my assumption and implementation analysis is correct (and I might be totally wrong here or missing something), I propose the following change in behavior:
* Any device regardless of `source_type`, `_state`, `last_seen`, `device.gps` and `location_name` should generally be considered to become stale
* `STATE_NOT_HOME` is never stale (as this is the default state)
* If `device.last_seen` is not set, the devices state is automatically stale
* `last_update_home` will be obsolete
* The actions taken for stale devices remain the same ([Source](https://github.com/home-assistant/home-assistant/blob/d1e1b9b38a06b82f6b609e68cbb99c15b934ffb3/homeassistant/components/device_tracker/__init__.py#L551-L552))

I would be willing to prepare a PR if I get some positive feedback on this.

Also pinging @balloob as the main author of this component.

**Comment by balloob** [comment]
So the device tracker component is a real mess, that's mainly because it's one of our oldest integrations.

Right now there are different source types. Only source type ROUTER will be handling stale. If the location name is set or GPS coordinates are provided, we do not automatically set a device to away. This is because when you're home, your GPS tracker won't report new locations but you're still at home, shouldn't be marked as away.

The real future of the device tracker is to untangle it all. The device tracker should **not** merge different sources into one (as it does now). Instead, each source should be independently tracked and then merged by a new integration that can take multiple sources and represent it as one.  That integration doesn't even have to live in the device tracker component, as it would be cool as it would also tie into the new user system:

1 user can have multiple devices that are being tracked and represent the location of the user.

**Comment by hhaim** [comment]
I agree with @cybe.
We need to separate the “real future” proposal from the current simple aging solution. Any device should provide (even in the future) a simple property: home or not_home. Today device can stuck at home forever (it is not hard to get into this).   Any device that wasn’t called by “seen” for more than consider_home  should be considered stale and should move to state=not_home.

**Comment by akloeckner** [comment]
In case the bigger picture is adressed (which might already be the case given the not-so-new-anymore `person` integration), please consider to augment device scanners with a `zone` setting, as proposed in #463. Just thought, the link might be helpful.

**Comment by MartinHjelmare** [comment]
The device tracker integration has been redone after this suggestion was written. If there's still a problem a new discussion should be made based on the current state.
