### ISSUE TITLE
New device type for cover

### ISSUE THREAD

**Issue by Kane610** [home-assistant/architecture#73]
My plan is to add more specific controls for (to begin with) [Keen Zigbee vents](https://keenhome.io/products/smart-vent) through deCONZ. Most special device types are today exposed as lights (power plugs, sirens, vents, curtains) and I want to make this more neatly integrated with Home assistant with the proper platform.

This device has got on/off plus brightness which would be same features as
```
SUPPORT_OPEN = 1
SUPPORT_CLOSE = 2
SUPPORT_SET_POSITION = 4
```

Suggested device type would be **damper** or something similar.

**Comment by balloob** [comment]
what do you mean with device got brightness?

**Comment by Kane610** [comment]
It is exposed as a ZHALight, so it has got brightness range which would be translated over to set_position for a cover

**Comment by balloob** [comment]
I think cover is the right place for it.
