### ISSUE TITLE
Add cloudiness property to weather component

### ISSUE THREAD

**Issue by helto4real** [home-assistant/architecture#77]
I propose to add **cloudiness** as attribute to weather components. Cloudiness represent percent of sky that has clouds. I want to implement suppprt for the Swedish weather insititure that has this information. I know yr.no has it too. Level of cloudiness can be used to for example turn on lights before normal sunset since it is probably darker. I personally use yr.no sensor for this. I think it would make sense to add to the general weather component too.

Se PR 
https://github.com/home-assistant/home-assistant/pull/16717 for more information. If this get approved I will make separate PR for this suggestion as suggested  by @martinhjelmare

**Comment by fabaff** [comment]
I agree.

**Comment by balloob** [comment]
How many other weather platforms offer this data?

**Comment by helto4real** [comment]
I am pretty sure Norwegian service yr. No does sinse the sensor has it. I can try to find out if yahoo/darksky has it in api or at least makes it possible to calculate it some other way

**Comment by stickystyle** [comment]
The dark sky sensor has an attribute called "cloud_cover" which seems to be exactly what is being proposed. I use it in my automations to turn on the porch lights in the middle of the day if it gets cloudy.

**Comment by helto4real** [comment]
Does not seem like yahoo weather has it.

**Comment by MartinHjelmare** [comment]
There are currently 13 weather integrations:
- [ ] bom
- [ ] buienradar
- [ ] darksky
- [ ] ecobee
- [ ] homematicip_cloud
- [ ] ipma
- [ ] met
- [ ] meteo_france
- [ ] metoffice
- [ ] openweathermap
- [ ] smhi
- [ ] yweather
- [ ] zamg

How many of those need to support cloudiness to let us implement this proposal?

**Comment by dgomes** [comment]
IPMA can support

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
