### ISSUE TITLE
Not hard code config_flow 

### ISSUE THREAD

**Issue by helto4real** [home-assistant/architecture#78]
I suggest config_flow are auto discovered and enable config_flow to be supported in custom components as well. It will also be great to use config_flow for simpler components like sensors that does not have hubs. Like  adding config flow handlers in the sensor/[my_sensor].py file or as an alternative allow to make components in a directory sensor/my_sensor/[files].

**Comment by balloob** [comment]
Auto discovering config flows means that we have to open every file and see if they contain a config flow. That would result in a lot of memory bloat as all these files are parsed and kept in memory. We're not going to do that.

If you can figure out a way that will cleanly allow support for platforms to have config flows, please do tell. 

And no, we can't define components as sensor/my_sensor because that's what a platform is…

**Comment by helto4real** [comment]
Yea that seems reasonable. What about allowing for config flow support in the custom components? That should be allt less to process? If that’s a problem have a specific folder to add flow handlers  or a text file pointing out the flow handler like in “built-in” components?

**Comment by balloob** [comment]
I don't want to commit to it yet because the API might not be fully stable yet. If we want to make a change, we should be able to get all flows that are using it updated.

**Comment by helto4real** [comment]
Ahh ok. Yea when it is released to "non-contributors" it should be pretty stable, I agree that is a fair statement.

**Comment by MartinHjelmare** [comment]
Should we close this until there's a proposal on how to make the non hard coded approach work?

**Comment by OttoWinter** [comment]
How about python entrypoints? (used by many python plugin systems like django).

See pkg_resources.iter_entrypoints

**Comment by rytilahti** [comment]
Did we not discuss this already elsewhere, with a conclusion that a fair way would be to move towards using some sort of meta data file (whether that is setup.py & entrypoints, or something else) to completely avoid the requirement to load up the component/platform just for the meta data purposes. That would obviously should not be limited only to the config_flow entrypoints, though.

And while requiring a proper packaging is a bit more involved from a developer's point of view, it is not that bad when considering that that's the proper way to do it while getting the benefits of them being first class packages (authorship & licensing information, dependency management, sane versioning and updates, ..).

**Comment by balloob** [comment]
Yeah, component metadata is probably the way to go. And we can have Home Assistant scan custom component for extra metadata based on a button in the UI (Refresh custom components).

**Comment by MartinHjelmare** [comment]
Can we close this now that custom components can have config flow? Supporting config flow for just a platform isn't relevant in my opinion.

**Comment by balloob** [comment]
Yeah, it can be closed.
