### ISSUE TITLE
I propose a rewrite of the Tuya component so it works locally instead of relying on the cloud (solution enclosed)

### ISSUE THREAD

**Issue by caffeinatedMike** [home-assistant/architecture#79]
Right now the current implementation of the Tuya HA component is completely reliant on their Cloud API. Since this goes against HA's whole point of complete local, secure control I propose that the current Tuya component be rewritten using the methodology implemented in @codetheweb's tuyaapi repo. 

Also, in doing so it will be possible to add Tuya door/window sensors. Please read [my discussion](https://github.com/codetheweb/tuyapi/issues/5#issuecomment-423748064) with  @codetheweb & @NorthernMan54 to find code for working with the door/window sensors. And all the code for working with the Tuya product locally can be found within @codetheweb's tuyaapi repo. However, it will need to be ported over from nodeJS to Python and possibly _slightly_ tailored to work correctly with the Home Assistant ecosystem (so HA can recognize the state changes and allow users to react/trigger actions when the state does change). I'm not too good at porting, so I hope someone else will be willing to take this on. I think it's better that it be done now while the Tuya component is still in it's infancy, rather than wait until down the road when other devices have inevitably been added to it.

**Comment by balloob** [comment]
Our Tuya integration has been contributed by Tuya. I've been in contact with their team and they told me that there is no local API. 

I think that this is not so much worth an architecture issue, we will always prefer local over remote API. So a contribution is welcome!

CC @huangyupeng

**Comment by deddc23efb** [comment]
Is there any reason for this to be closed.  There is clearly a local API and it is being worked on by various people.
