### ISSUE TITLE
Optional health check

### ISSUE THREAD

**Issue by anklimov** [home-assistant/architecture#826]
## Context

Hassio healthcheck  brings lot of limitations with system updates then Hassio used by experienced user in their own environment and user would like to take their own responsibility for interoperability software/containers on own system (for example, would like to have portainer container in docker, shared with HA supervised)

## Proposal

To made healthcheck optional (turning off this in expert mode)
Warnings level should be plenty enough to warn user in most cases

**Comment by andjones132** [comment]
Yeah. I don't get this. Is home assistant still open source? It seems it is quickly becoming more like a proprietary software that can only be run on dedicated operating system dictated by the core developers. If you want to control what software users can install, stick with our HassOS. Leave those those of us who want to run a "Supervised" environment alone.  I am beginning to think "Supervised" no longer means supervised by the user, but by the core developers.  Just my two cents.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
