### ISSUE TITLE
IQS: Silver to require a component

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#83]
Integrations usually start with a platform for an entity component like light or media player. When the integration is expanded to other platforms, it requires a breaking change when the authentication is moved to a component, causing a breaking change.

We should require having a component to manage the connection as part of the silver level. That way we can guarantee that there will not be any breaking change anymore, as the migration to config entry does not require a change.

**Comment by MartinHjelmare** [comment]
But config entry is part of gold, right? So there might still be breaking changes on silver.

**Comment by Kane610** [comment]
Not necessarily. If you import existing configuration like most config entries does. It shouldn't be a noticeable change.

**Comment by MartinHjelmare** [comment]
But I'm talking about non config entry components, which is the silver level requirement. I don't get why we should require a component on silver, cause we think it will solve breaking changes. It won't solve breaking changes on silver without config entries.

**Comment by balloob** [comment]
By requiring it as part of silver, once a component is silver, it can reach platinum without a single breaking change. So as a user, if you're just using integrations that are silver+, you can upgrade and not worry at all.

**Comment by MartinHjelmare** [comment]
That's not true. Silver level components without config entry might still introduce breaking changes. Gold+ is required to not have to worry.

**Comment by balloob** [comment]
What breaking changes might be introduced? We've managed to introduce config entries for Hue, Tradfri and MQTT without breaking changes.

**Comment by MartinHjelmare** [comment]
I'm not talking about introducing config entries. The components that don't have that might introduce breaking changes for whatever reason. Until a component has config entries, we can't guarantee no breaking changes. It's as simple as that.

**Comment by armills** [comment]
@MartinHjelmare Ensuring that integrations are using a component does eliminate one of the most common breaking changes though. Would you agree that makes it worthwhile to include in silver even if we can't completely guarantee no future breaking changes?

**Comment by MartinHjelmare** [comment]
I think it's good to include it as a requirement, but I'm thinking maybe it should be gold level. But it's ok for me to put it on silver too.

I'm mostly concerned about how we set expectations for the users, since that's what the IQS is about. I don't think we should say that we guarantee no breaking changes on silver, if we really can't do that.

**Comment by balloob** [comment]
It's already part of gold because config entries require a component.

**Comment by MartinHjelmare** [comment]
Everyone interested seem to agree to add a requirement to silver level that the component should manage the connection. If we update this [page](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html) we could close this issue.

**Comment by iantrich** [comment]
Out of curiosity, are these levels documented per-integration and I've totally missed them?

**Comment by MartinHjelmare** [comment]
Yes, see eg top left corner of this page (on desktop) https://www.home-assistant.io/components/tibber/.

**Comment by iantrich** [comment]
I must use primarily low level components ;) Thanks.

**Comment by balloob** [comment]
Created https://github.com/home-assistant/developers.home-assistant/pull/204

**Comment by MartinHjelmare** [comment]
We can close now.
