### ISSUE TITLE
Entity Icons

### ISSUE THREAD

**Issue by abmantis** [home-assistant/architecture#86]
Since the user is now able to change an entity name and id trough the UI, should he be able to also select an icon for the entity? It makes sense to have the name and icon customization in the same place.

Also, most of the current usage of the "customize" section is for setting icons (or device_class for binary_sensors). Having it selectable on the UI would remove the need to have a customize section only for that.

**Comment by cgarwood** [comment]
I think the eventual goal is to get rid of icons being saved in the state machine and have all of that set through the Lovelace config, which also means the existing Customize section ( and `customize:` portion of configuration.yaml) will be going away. It would be great to have a visual editor for building Lovelace UIs, but that's probably a long way out.

**Comment by abmantis** [comment]
But icons are used in the logbook. If they are removed from the state machine, they would have to be removed from the logbook.

**Comment by michaelarnauts** [comment]
> But icons are used in the logbook. If they are removed from the state machine, they would have to be removed from the logbook.

If lovelace will be extended to also render the logbook (what it should in my opinion), it can apply the correct icon.

**Comment by dummptyhummpty** [comment]
Should allowing the ability to change device_class be included in this? As that does affect the entity icon.

**Comment by dgomes** [comment]
What about components that change the icon dynamically ? I Just review a PR for the nissan leaf that changed the icon depending if the car is being charged or not.

**Comment by abmantis** [comment]
> What about components that change the icon dynamically ? I Just review a PR for the nissan leaf that changed the icon depending if the car is being charged or not.

Maybe the icon should still live on the state machine, and lovelace would just be an "override", like the current "customization" section is.

**Comment by rytilahti** [comment]
> What about components that change the icon dynamically ? I Just review a PR for the nissan leaf that changed the icon depending if the car is being charged or not.

That is a misuse of the icon property, IMO, as there should be a clear separation of the data and its presentation. The platform should report its state (e.g. charging, discharging, ..), and the UI should adjust the icon accordingly.

**Comment by frenck** [comment]
Users can now change icons for entities that have a unique ID (or old fashioned via customizing).
Lovelace supports overriding as well.

Hopefully, we will get an icon selector in the future. There is a separate feature request open for that in the frontend repository.

Considering the age and activity lack on this issue, I'm going to close it now.
