### ISSUE TITLE
New Device class for Reactive Energy (varh)

### ISSUE THREAD

**Issue by pfassberg** [home-assistant/architecture#877]
## Context

All electrical meters, at last in Sweden and Norway, count Reactive Energy.  There is no Device Class for Reactive Energy.

## Proposal

I propose to add a new Device Class for Reactive Energy.  I would like to use it from the MQTT integration, but Tibber, Shelly and others will also benefit from this.  There is a device class for Reactive Power since last year.

## Consequences

You can have HA to use the right unit (varh / kvarh). I see no risks by implementing it.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
