### ISSUE TITLE
Refactor/Remove DNS components

### ISSUE THREAD

**Issue by awarecan** [home-assistant/architecture#89]
There are bunch of components to keep your DNS record up-to-date. I suggest either remove them or refactor them to a common component with different platform

The list:
https://www.home-assistant.io/components/cloudflare/
https://www.home-assistant.io/components/duckdns/
https://www.home-assistant.io/components/freedns/
https://www.home-assistant.io/components/google_domains/
https://www.home-assistant.io/components/namecheapdns/
https://www.home-assistant.io/components/no_ip/
https://github.com/home-assistant/home-assistant/pull/17072

**Comment by awarecan** [comment]
IMO, those components should be removed since they are not related with home assistant's global, and they are better fit for a hass.io add-ons.

But sounds like I didn't got much support on the discussion in the route53 pull request, so another thought is we probably better design it if majority think it is good have this function provided by HA.

**Comment by balloob** [comment]
I think that users often use Dynamic DNS with Home Assistant because it allows it to be remote accessible. I think that it's fine to keep them around.

I thought about standardizing them but there really is not much to standardize, it schedules a web request.
