### ISSUE TITLE
Add parameter to specify number of seconds between press and release for remotes.

### ISSUE THREAD

**Issue by ehendrix23** [home-assistant/architecture#90]
Depending on the remote and functionality configured on the remote there might be a difference on how something is operated based on how long a button is held.

For example, I have the Harmony remotes and have them configured with my Hunter Douglas Powerrise blinds. However, the only way to get them to go up or down is by pressing and holding the button on my remote for a few seconds. (Note, Harmony is already set to send a longer signal but that is not sufficient).
For Harmony remotes, sending of a command is done by a "press" and then a "release" command. Thus to  be able to mimic this longer button press there is a delay required between press and delay.

Implementing this new optional parameter for REMOTE_SERVICE_SEND_COMMAND_SCHEMA would then allow one within the configuration to specify how much time there should be between the press and release. If not provided then the default would be 0, hence no changing current behavior.

I've submitted PR17312 (https://github.com/home-assistant/home-assistant/pull/17312)  with the proposed changes allowing anyone to look at the coding on what I propose.

**Comment by ehendrix23** [comment]
Just doing a ping on this item. Some devices require a longer press when receiving IR signals. Depending on the remote interface this can be mimicked by putting in a delay between sending the "press" signal and the "release" signal. 
When sending a command for Harmony remotes it is done by a press, followed up by a release. Thus this would introduce the option to put in a delay.

Other option would be to create a service specific for Harmony. :-)

Appreciate feedback.

**Comment by amelchio** [comment]
I think this makes sense. Some examples would improve your presentation.

**Comment by ehendrix23** [comment]
Here is a configuration example I have have one of my blinds go up:

```
left_blind_up:
  alias: "Left blind Up"
  sequence:
    - service: remote.send_command
      entity_id: remote.family_room
      data:
        command:
           - Up2
        device: Hunter Douglas Home Appliance
        hold_secs: 3
```

This will then send the press (or push) signal to the Hub for Up2; and 3 seconds later send the release signal. Similar then if I would use the remote and hold the button for 3 seconds.

**Comment by amelchio** [comment]
I feel that `hold_secs` should be per-`command` but that is probably too cumbersome?

(I realize that a workaround is to issue multiple `remote.send_command` with different `hold_secs`)

**Comment by MartinHjelmare** [comment]
https://github.com/home-assistant/home-assistant/pull/19650 was merged implementing `hold_secs` for remote `send_command` service.

If the developer docs for remote have been updated we can close this I think.

Whats the status @ehendrix23?

**Comment by MartinHjelmare** [comment]
We should update this page:
https://developers.home-assistant.io/docs/en/entity_remote.html

**Comment by ehendrix23** [comment]
Did not realize these items were in developer docs. I did update the end-user docs. :-)

I checked and there is absolutely nothing in the docs for remote entity. I'll see to update and add everything in there.

**Comment by frenck** [comment]
This architecture issue is old, stale, and possibly obsolete. Things changed a lot over the years. Additionally, we have been moving to discussions for these architectural discussions.

For that reason, I'm going to close this issue.

../Frenck
