### ISSUE TITLE
Adding curtain device class to cover component.

### ISSUE THREAD

**Issue by cnrd** [home-assistant/architecture#91]
The current cover component UI does not feel right for curtains.

This is how the UI for the Xiaomi curtain motor exposed through deCONZ currently look:
* [Open](https://i.imgur.com/B1VtSuV.png)
* [Closed](https://i.imgur.com/fpOQQSH.png)
* [Half open](https://i.imgur.com/BE5BNNQ.png)

Problems with current cover device class:
* When curtains are open the position bar is fully coloured, when they are closed it is all grey.
* The buttons for closing/opening the curtains are shown as up/down instead of left/right.

Proposal for solution:
* Add curtain device class to the cover component.
* Reverse the bar color for the curtain device class. (Such that the left most position is open and the right most position is closed).
* Replace hass:arrow-up with hass:arrow-left and hass:arrow-down with hass:arrow-right for the curtain device class.

Mockup of proposed UI:
* [Open](https://i.imgur.com/zZFq5aW.png)
* [Closed](https://i.imgur.com/WJdyAN3.png)
* [Half open](https://i.imgur.com/GDJLMlK.png)

Random thoughts / Future work:
Allow the curtain device class to support single curtain, which are either drawn left or right for opening and closing, allowing the user to define the direction and changing the direction of the position slider depending on the configured direction.

**Comment by balloob** [comment]
I think the idea of a curtain device class = :thumbsup:

Your random thoughts are a bit too wild for me :wink:, we don't make decisions on the backend just for frontend sakes. We could implement a second device class, curtain-middle-out or something (or whatever the official name is for such curtains).

**Comment by cnrd** [comment]
First of all: These two device classes would be split into two PRs.

I'm pretty sure everything in the random thoughts parts can be done with device classes, but it may require another device class.

The curtain device class would support both "normal" 2 side curtains (where you have one on each side of the window) and a curtain with it's open position on the left side of the window.

We would need a second device class for a single curtain with it's open position on the left side:
For this device class the `hass:left-arrow` would call `cover.close_cover` and the `hass:right-arrow` would call `cover.open_cover`. The position slider would follow the current `window` device class.

**Comment by balloob** [comment]
I think that a device class should explain the device, it should not be used to differ between implementation details like how the curtain is mounted.

I wonder if cover just needs a direction attribute ? Direction could be `left-to-right`, `right-to-left`, `top-to-bottom`, `bottom-to-top`, `middle-out-horizontal`, `middle-out-vertical`

**Comment by cnrd** [comment]
So would this be in place of the curtain device class?

How would such a direction attribute be implemented? It would need to be configurable, as there is no way to get that information from the actual device.

**Comment by balloob** [comment]
It would be a new attribute on cover entities that integrations would have to implement. For device class we would then just stick to "curtain"

**Comment by balloob** [comment]
We don't start updating entities with frontend PRs. It first needs to be documented in the dev docs. Adding it there will finalize it and close this issue.

**Comment by MartinHjelmare** [comment]
Should we close this?

Curtain device class has been added.

https://github.com/home-assistant/architecture/issues/153https://github.com/home-assistant/developers.home-assistant/pull/187
