### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#92]
We've been building a lot of awesome features lately, like device registry, entity registry, config entries, users and powered by all that, I want to start making it as easy as possible to get started with Home Assistant.

So I did some sketching in Figma and came up with a proposal for onboarding for which I want to like to get some feedback: https://www.figma.com/file/hQpYcU3H4yJWT5dzcZSLmU/Home-Assistant-onboarding?node-id=16%3A2

The idea is that the onboarding will guide the user to the minimal steps to get started with Home Assistant and is up and running when they finish onboarding.

Not everything will be part of onboarding, we should focus on the bare minimum. Other things thar are nice to use by the user will be moved to a new tutorial component that will create a persistent notification once a day with other tips:

 - iOS app
 - presence detection
 - Alexa/Google Assistant/Home Assistant Cloud

These tips will also include easy toggles to enable further automations related to what the user just set up. Example for presence detection step: A toggle to automatically turn on lights at night when people are home.

**Comment by iantrich** [comment]
This is excellent!

I really like the idea of wizards to setup device integrations, much like Wink. With casual users in mind, I think the integrations page should directly accessible from the main UI. A FAB to add different integrations that is on every page would be ideal, I think.

**Comment by zsarnett** [comment]
I like this a lot. I think the addition of the wizards will make it a lot easier for less technical people to use Home Assistant.

**Comment by cgarwood** [comment]
I think this would be great for getting started, as well as for pairing new devices (especially zwave and zigee devices that require you to press specific buttons on the device at a specific time)

**Comment by Hedda** [comment]
Once in place, it would be nice if any onboarding wizard(s) did not only start initially on installation but would also be if the same onboarding wizard(s) could also be started again later again and again so that user can make changes to the config/settings that can be changed or configure things that was skipped at the initial installation.

**Comment by robbiet480** [comment]
Conversation about onboarding was had on Discord [here](https://discordapp.com/channels/330944238910963714/351047592588869643/555872138746396682).

**Comment by timmo001** [comment]
Looks good! 👍 Should save a lot of time also.

One addition I would add is to perhaps add a confirm password on initial onboarding since this is the admin user.

**Comment by balloob** [comment]
That will already be part of 0.90 @timmo001  👍

**Comment by timmo001** [comment]
> That will already be part of 0.90 @timmo001 👍

Ah, I thought I saw something before mentioning it 👍
