### ISSUE TITLE
device_tracker  device with hide_if_away=true  will not be logged 

### ISSUE THREAD

**Issue by hhaim** [home-assistant/architecture#93]
I'm new to hass. 
This is the description:
"If yes/on/true then the device will be hidden if it is not at home."
my understanding the it will be hidden from the UI *not* from the database logbook.
What am I missing?

found this in the logbook source code:

            hidden = attributes.get(ATTR_HIDDEN, False)
            if hidden:
                continue

         elif event.event_type == EVENT_LOGBOOK_ENTRY:

**Comment by balloob** [comment]
okay, looks like move bot is not working. This is the wrong repo.
