### ISSUE TITLE
Areas

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#94]
Now that we have devices, it's time to go level up: areas. Areas will represent an area in the house, like a room or piece of a room (up to the user).

### Properties

- An area has a name
- An area can contain 0 or more devices
- An area can contain 0 or more [people](https://github.com/home-assistant/architecture/issues/72)

### Possibilitites

- Lovelace can be automatically configured with tabs per area during onboarding
- New lovelace card to represent an area "The temperature is X, 2 lights are on."
- Automatically configure room hint for Google Assistant
- Add extra step when configuring a new integration: ask the user where each device is located

![image](https://user-images.githubusercontent.com/1444314/47007475-9439f480-d138-11e8-9899-d7ceae9d04b1.png)

### Implementation

We should create a new Device Registry. We should follow the same architecture as for Device and Entity registry.

**Comment by Kane610** [comment]
Sounds simple enough. Simple and effective 👍

**Comment by Kane610** [comment]
I guess the devices will mostly be constant with the area? Where as people will come and go.

**Comment by balloob** [comment]
yeah this is only for devices that are static, wouldn't expect a phone to be constantly updated .

**Comment by messismore** [comment]
Would it be possible for one area to contain another area? Say, a kitchen zone within a larger room, or a reading nook, or a bed within a bedroom?

**Comment by balloob** [comment]
I don't think that's a good idea. We should keep it simple as it would complicate every interaction with areas to a point where it becomes inefficient to deal with them.

**Comment by balloob** [comment]
Thinking here, if an area can eventually have 0 or more people, we want to keep track of some state for occupied/not occupied. Besides that, an area would also be perfect to contain some aggregated stats in the attributes to help trigger automations. Does the area have lights on, what is the temperature?

I'm a bit torn. On one hand we can adhere to single source of truth, and have code that wants this info figure out their own strategy to how to fetch the states to see state of X in an area. The alternative (what I am leaning towards), is putting areas in the state machine and we have a single approach to keep track of this data. That would also allow us to control an area, like a group, with services like turn_on, turn_off.

**Comment by DubhAd** [comment]
There's also a regularly asked question about supporting multiple "homes" from a single central HA. This could potentially allow device trackers to be mapped to areas, but that would require the concept of a super-area. I do think there's merit in allowing a limited number of layering (Home -> Floor -> area), which doesn't necessarily have to be much more advanced than grouping IMO.

**Comment by Nornode** [comment]
I would love this option. 
**Use case:** Combining two smart homes into one home assistant deployment.
I recently stumbled on the issue where I'd like to make devices detected by 
device_tracker X status "home"
device_tracker Z status (e.g.) "summer-house"

**Comment by balloob** [comment]
multiple homes is out of scope for this, let's stick on topic.

I've had some more thought, I might still keep with a registry. We can make new API endpoints if we want to combine data or so.

**Comment by tsvi** [comment]
There is some merit to @DubhAd comment about layering. Mainly for multiple floors in the house.
Infinite layering can be a mess, but adding floors could definitely be interesting:
- Turn off all the lights on the second floor. (This would include all the rooms)
- Turn on the lights in the basement. (Would include the bathroom and the workroom)

**Comment by michaelarnauts** [comment]
Doesn't this fit in the current group design? Just put the areas in a group?

**Comment by abmantis** [comment]
Expanding from @messismore answer, how different will and Area be from the current Group component?

**Comment by balloob** [comment]
Compared to a group, an area will:

- not live in the state machine
- represent a physical area
- hold devices, not entities

**Comment by abmantis** [comment]
If they don't live in the state machine, are they UI only? They won't support services like turn_on?

**Comment by balloob** [comment]
They are not UI only, they will also be used for room hints for Google Assistant or in permissions for example.

I think that we could enhance services that besides `entity_id` they also take `area_id`. It's all using the extract entity logic from entity component, so it would be easy to add.

**Comment by ejosterberg** [comment]
Interesting discussion. I've created the concept of area in my automatons already.
I was looking to code up a ?component? to make managing larger systems more modular.
An area can have have one of 4 states. [ 'open', 'unknown', 'occupied', 'unoccupied']
I define all of the perimeter sensors (usually door switches) and then the interior sensors.
When all perimeter sensors close, we wait for a timer before deciding the room is unoccupied. Any activity inside the area while the perimeter is closed instantly moves the area status to occupied.
When the area is in an open state, depending on which perimeter sensors are open, the "area" becomes a part of another area. I'm afraid explaining that one can get complicated. Think along the idea that a guest room becomes a part of a common area if the door is open. I can then plan automations that target the common area to include the guest room with the open door.
I'm using this for a few purposes. One would be to close the air register of guest rooms if the door is closed for some time without any activity inside.
Another is if an area is in an unoccupied state for some defined period of time, I want an alarm/notification should an interior sensor activate. Basically this becomes an alarm per "area" by simply keeping doors closed to unused parts of the house.

Here's a really simple automation for a single area house...
[root@msphass automations]# cat area_status_msp_home.yaml
---
- id: area_status_msp_home_to_unknown
  alias: 'Area Status msp_home to Unknown'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'on'
      to: 'off'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.area_status_msp_home
      option: unknown

- id: area_status_msp_home_to_open
  alias: 'Area Status msp_home to Open'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'off'
      to: 'on'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.area_status_msp_home
      option: open

- id: area_status_msp_home_to_unoccupied
  alias: 'Area Status msp_home to Unoccupied'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.area_status_msp_home
    to: 'unknown'
    for:
      hours: 0
      minutes: 3
      seconds: 0
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.area_status_msp_home
      option: unoccupied

# Potentially theres another condition that moves from unoccupied to occupied,
# maybe an intruder...  This is not handled here, but should be considered...

- id: area_status_msp_home_to_occupied
  alias: 'Area Status msp_home to Occupied'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.basementrmmotion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.livingrmmotion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.area_status_msp_home
      state: 'unknown'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.area_status_msp_home
      option: occupied

**Comment by pbalogh77** [comment]
If a device or entity can only be in one area or in no area at all, would area be an attribute of devices and entities? Because it could be just an attribute then we could automatically filter devices and/or entities based on area and have the area functionality be very lightweight without having its own registry. What some other systems do with rooms is that you can define the default temp sensor, default motion sensor, etc, for each room. E.g. pick one from the devices and/or entities in it.

**Comment by balloob** [comment]
Even if it's an attribute, we would still need a registry to track at least the area name. However, we are making sure state machine only contains data related to the state. All information that describes an entity can and should be stored outside in the entity, device or area registry.

Another note on the implementation: we will only be able to place entities in areas if they provide a unique ID (otherwise we can't store that data in the entity registry).

**Comment by dmulcahey** [comment]
> They are not UI only, they will also be used for room hints for Google Assistant or in permissions for example.
> 
> I think that we could enhance services that besides `entity_id` they also take `area_id`. It's all using the extract entity logic from entity component, so it would be easy to add.

Does the homekit API allow the same sort of "hints" for rooms.... I would love to be able to only define this once in HA.

**Comment by Kane610** [comment]
> > They are not UI only, they will also be used for room hints for Google Assistant or in permissions for example.
> > I think that we could enhance services that besides `entity_id` they also take `area_id`. It's all using the extract entity logic from entity component, so it would be easy to add.
> 
> Does the homekit API allow the same sort of "hints" for rooms.... I would love to be able to only define this once in HA.

That would be great. Im right now naming my entities with a  prefix of the rooms name (easier when redoing it) And when placed properly the prefix is actually removed from the normal views.

**Comment by cdce8p** [comment]
> HomeKit room `hints`

@dmulcahey Unfortunately those aren't supported, yet. We'll have to wait for WWDC to see what's coming next.

**Comment by maxandersen** [comment]
@cdce8p Is that a python level homekit issue since homekit has HMRoom that can be assigned via 
https://developer.apple.com/documentation/homekit/hmhome/1620265-assignaccessory?language=objc

**Comment by cdce8p** [comment]
@maxandersen The Api you've linked is for apps running on iOS and how they can access the HomeKit data on an Apple device.
We only have access to anything that is specified in the HomeKit Accessory Protocol Specifications: 
https://developer.apple.com/homekit/specification/ and those don't include any room hints yet. Unfortunately I **don't** belive that they will be added either. Keep in mind that HomeKit is designed to handle all configurations as the primary platform. Our solution probably isn't something they though of.

**Comment by maxandersen** [comment]
@cdce8p that sucks :) 
...so here is the crazy idea - could homeassistant for ios then do the dirty deed of "sync"-ing the areas if we don't have access on the server ?

**Comment by balloob** [comment]
Closing this issue as areas have been released since 0.87.0.

**Comment by elupus** [comment]
Am i missing something or is it only planned to allow devices in areas? With KNX for example you have one device controlling lights in multiple rooms, ie entities. For custom integrations it is also  harder to create devices.

Wouldn't it make more sense to only add entities to areas. See no real point in adding devices (apart is it would make sense to inherit to entities)

**Comment by balloob** [comment]
Each light that KNX would control would have it's own device. The KNX controller would also be it's own device: https://developers.home-assistant.io/docs/en/device_registry_index.html

**Comment by cdce8p** [comment]
@maxandersen That might be possible, but I'm not sure if this is really worth it. Keep in mind that it's not just the sync which would be a problem, you would also need to handle conflicts, rooms that might not exist or have different names and so on.

**Comment by maxandersen** [comment]
@cdce8p well today homekit just seem to dump all entities into "Default Room" in homekit anyway and with 50+ thats where they are staying until Home Assistant Areas can help me put them in their right place :)

I think it could work if the ios app can assume HA knowledge of rooms is the truth and then just apply it.

**Comment by maxandersen** [comment]
btw. once https://github.com/home-assistant/home-assistant-cli/pull/152 is done you can manage Areas via hass-cli - good for those (like me) with just enough devices to make it tedious to use the current UI to assign devices.

It lets you do stuff like `hass-cli device assign Kitchen --match "Kitchen Light" eab9930f8652408882cc8cb604651c60 Cupboard` which will assign area named "Kitchen" to all devices having substring "Kitchen Light", have an id "eab9930..." or named "Cupboard".

hoping to get it tested and released in a 0.5 this weekend.

**Comment by elupus** [comment]
@balloob currently knx doesn't have unique ID, which blocks it from entity registry and if I've understand correctly also device registry.

KNX doesn't really have any unique ID for entities. The group addresses for lights/feedback are arbitrarily assigned by installer. In a sence similar to mqtt topics. There is no real way to get info on the backing device, and that is somewhat even by design.

Could we have a way for entities to automatically become devices?

**Comment by balloob** [comment]
If group addresses are unique per device, that can be used as unique ID.

I don't want to complicate our design by allowing both entities and devices to be in areas. Entities belong to a device, devices are in areas.

**Comment by elupus** [comment]
They don't have to be. They are sort of a signal id. Ie you assign a group address to an event. Then you assign what lights should react to that event. A dimmable light will for example have 4 group addresses. One for the event on/off one setting of dim level two other for feedback on current state on/off dim level.

It's perfectly valid to let multiple actuators react to same on/off command. It's perfectly possible to not have feedback. Or only one of them. 

State address could possibly be used as semi unique in a single installation. At least for lights and switches. 

Then there is thermostats, light sensors and so on. All similary configured. Given that it's sort of European industry standard would be nice to have it a first class citizen in home assistant.

**Comment by tsvi** [comment]
@balloob I hear you on not nesting areas, but we might want to add a entity to multiple areas?
We might want to have automations based on public vs. private, specific rooms, floor number, outside/inside etc.

There are a multitude of ways to define an area Even if an area can't be in another area, an area might have attributes, or else a device might be in multiple areas. Would love to hear your thoughts on the matter.

**Comment by balloob** [comment]
We need to start figuring out how devices being able to be in 1 area first. Let's see how that evolves Home Assistant first. There is no need to make it complicated from day 1 to solve some (edge?) cases.

**Comment by DaAwesomeP** [comment]
Is it possible to add a light group to an area? For example, I want to group all of my overhead lights in one switch in an area.

**Comment by frenck** [comment]
@DaAwesomeP Please do not bump closed issue. If you need support, please get on to our community forum or Discord chat. Thanks 👍
