### ISSUE TITLE
Always add listener for _update_entity_states

### ISSUE THREAD

**Issue by tadly** [home-assistant/architecture#95]
Alright, I give in as no one else is doing it...

This PR explains the the bug (and fixes it) but apparently has to be discussed here first so...
https://github.com/home-assistant/home-assistant/pull/17553

*Edit:*
As requested the description of the above PR pasted here for everyones convenience or whatever.
___
If `should_poll` for ALL `EntityComponent` is `False` at startup but
dynamically change to `True` at runtime, entities can get stuck at an
undesirable states.

## Description:
Currently, kodi shows such behavior.  
To better illustrate the issue here's how to easily reproduce it.
1. Have **one** media_player configured (kodi)
2. Start kodi
3. Start HA. [should_poll](https://github.com/home-assistant/home-assistant/blob/a71cc67efb05cf343df048885b451581b8cf0bd0/homeassistant/components/media_player/kodi.py#L502) for kodi returns `False`
4. Exit kodi
5. Start kodi
=> HA does show kodi as being offline.

**Comment by balloob** [comment]
Update your description to current behavior and what you think the behavior should change to and why. Include use cases.

**Comment by tadly** [comment]
The linked PR, the other PR linked to the first PR **and** the related issue **all** already explain the issue
but if you insist I shall copy pasta that crap over...

**Comment by balloob** [comment]
Crap? You realize that there are a lot of people involved with this project, there are a lot of PRs going around. If you want to achieve a change in core, you better be willing to drive that. You will have to gather the proposal in one place and be able to justify it. There are a 1000 things to do and so we don't want to have our time wasted.

**Comment by amelchio** [comment]
The architectural question is whether `should_poll` is allowed to be dynamic or if it should maintain the value that it has when the entity is added.

**Comment by tadly** [comment]
@balloob Read again. I insulted literally **no** one. If anything, I insulted myself as the referenced PR was made by **me**.

@amelchio That's what my initial fix (PR https://github.com/home-assistant/home-assistant/pull/17474) did where I've been told it shouldn't be merged and to create another PR (https://github.com/home-assistant/home-assistant/pull/17553)

I'm really short on time as it is and have spent way more on this already than I'm comfortable with.
I don't have to time to go even deeper in HAs architecture.

All I can say is no matter how you look at it, it's a bug and needs fixing either by not allowing should_poll to **not** be dynamic or by having the core supporting it.

**Comment by amelchio** [comment]
I think the current behavior where `should_poll` is not expected to change is okay. It allows some slight optimizations and the few entities that have a dynamic `should_poll` can simply return `True` and do the not-currently-polling test at the top of `update()`.

**Comment by balloob** [comment]
I think I would agree with @amelchio here, we would limit ourselves in future update scheduling if these things can change on the fly.

**Comment by tadly** [comment]
I've done a crude `grep` through all components to see if there are any others that might be dynamic.
Having not spent to much time reading and understanding the source of each, these might be problematic:
* `media_player/kodi.py` (This one's obvious by now)
* `sensor/imap.py`
  `_does_push` is assigned in `connect()` which is repeatedly called in `idle_loop()` (probably to re-establish the connection in case it goes done) and *could* therefore change
* `wink/__init__.py` (Not sure if `wink.pubnub_channel` can ever change after init...)

@balloob want me to reopen https://github.com/home-assistant/home-assistant/pull/17474 than?

**Comment by balloob** [comment]
Yes, I think that is the correct way to go.

**Comment by balloob** [comment]
Although, that one might still benefit from just being notified when the websocket has closed the connection?

**Comment by rytilahti** [comment]
So what is the procedure for handling disconnected websocket sockets, if not changing the `should_poll`? I have been stalling on making songpal asynchronous as I was not sure how to handle that case properly.

**Comment by balloob** [comment]
If the integration connects with a websocket, they configure a heartbeat (part of websocket protocol) or leverage a ping/pong command if available. They then will notice when a connection goes down and can try to reconnect. They can then use a backoff algorithm to delay future reconnects when current reconnect fails. If any of the reconnect attempts fail in a 401 (unauthorized), the auth is no longer valid and reconnects should stop right away and user notified. An example can be found [here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/cloud/iot.py#L45-L92). This is however not something that can be easily generalized since each system has their own implementation quirks.

**Comment by balloob** [comment]
It's fine for Kodi to just stick to automatic retry every 2^tries with a max of 5 seconds (initially you want to retry faster). Also a perfect example why we shouldn't generalize such logic :)

**Comment by tadly** [comment]
I thinks that's overkill especially when your max threshold is this low. Even with 10 seconds.

For 5 seconds you'd have:
 * Immediately retry (Probably never gonna hit that)
 * Try after 2 sec (can you even restart kodi this fast?)
 * Try after 4 sec. (this one you might hit if you simply restart kodi)
 * Try after 5 sec. repeatedly

For 10 seconds you'd have:
 * Immediately retry (Probably never gonna hit that)
 * Try after 2 sec (can you even restart kodi this fast?)
 * Try after 4 sec. (this one you might hit if you simply restart kodi)
 * Try after 8 sec. (this one you might hit if you simply restart kodi)
 * Try after 10 sec. repeatedly

Point is, using HAs polling will give us pretty much the same* with the added benefit of less code to maintain (That's a good thing).

\* The same because the component polling is external meaning you very rarely have to wait the whole 10 sec. (the default IIRC) but are more likely to hit something in-between.

**Comment by michaelarnauts** [comment]
Since the kodi integration is currently quite broken when your websockets disconnects, what's wrong with the way #17474 handles it? Maybe it's not the cleanest solution, but isn't it better then the way it is now? I might be missing something here offcourse.

Or is something else blocking this? I've read the issues and PR's about this, but I'm not really sure why it keeps on getting rejected.

**Comment by amelchio** [comment]
home-assistant/home-assistant#17474 has a review with unaddressed comments.

I think we can actually close this architecture issue as it was apparently agreed that we should not allow `should_poll()` to change during the lifetime of an entity (non-complying implementations notwithstanding).
