### ISSUE TITLE
Add 'Basic' as an IQS score

### ISSUE THREAD

**Issue by WebSpider** [home-assistant/architecture#96]
Current IQS implementation lists the following quality scores:

- silver
- gold
- platinum
- internal

This issue is to suggest adding 'Basic', instead of 'No Score'. The rationale behind this is to:

1. Make the distinction between components that have not been reviewed yet and those that have been and
2. Confirm that the component has no other status than Basic. Stating it is Basic excludes the possibility of it being anything else

**Comment by fabaff** [comment]
All integrations currently available were reviewed. Thus ["No score"](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html#no-score) says that there is nothing else.

**Comment by balloob** [comment]
I think that answers it pretty much. We should not add it.
