### ISSUE TITLE
Extend sun triggers and conditions

### ISSUE THREAD

**Issue by emontnemery** [home-assistant/architecture#98]
**Background:**
The existing sun triggers (before/after sunrise/sunset) are not ideal for automations related to dimming of lights etc.

**Proposal:**
Add some new triggers and conditions related to the sun rising and setting.
The idea is that they will be more suitable for automations which are for example controlling light brightness depending on position of the sun than the existing conditions.
A few proposed extensions below (not mutually exclusive)

## Extension 1
Cons: A bit messy with several dusk/dawn
Pros: Some more granularity; civil, nautical, astronomical dawn and dusk are well accepted terms

***For review in home-assistant/home-assistant#18146***

**Add triggers:**
- `astronomical_dawn`: sun rising above -18° solar elevation
- `nautical_dawn`: sun rising above -12° solar elevation
- `civil_dawn`: sun rising above -6°  solar elevation
- `civil_dusk`: sun setting below -6°  solar elevation
- `nautical_dusk`: sun setting below -12° solar elevation
- `astronomical_dusk`: sun setting below -18° solar elevation

**Add condition:**
- `from`: any sun trigger + `until`: any sun trigger, e.g.:
   ```
   from: 'civil_dusk'
   until: 'sunrise'
   ```

## Extension 1a
Similar to Extension 1, but add only one dusk and one dawn point
Cons: ?
Pro: Simpler

Definition of dusk and dawn can be in the sun component:
``` yaml
sun:
   dawn_solar_elevation: -8 #Set dawn to -8°  solar elevation
   dusk_solar_elevation: -8 #Set dusk to -8°  solar elevation
```

**Add triggers:**
- `dawn`: sun rising above -6°  solar elevation (can be overridden)
- `dusk`: sun setting below -6°  solar elevation (can be overridden)

**Add condition:**
- `from`: any sun trigger + `until`: any sun trigger, e.g.:
   ```
   from: 'dusk'
   until: 'sunrise'
   ```

## Extension 2
Cons: Too many options, but at the same time too limiting
Pros: `during: night` is very clear
**Add condition:**
- `during: <named_duration>`, e.g.:
   ```
   during: 'morning_twilight'
   ```

**Named durations:**
- `day`: solar elevation >0°
- `morning_civil_twilight`: -6° < solar elevation < 0° and before noon
- `evening_civil_twilight`: -6° < solar elevation < 0° and after noon
- `morning_nautical_twilight`: -12° < solar elevation < -6° and before noon
- `evening_nautical_twilight`: -12° < solar elevation < -6° and after noon
- `morning_astronomical_twilight`: -18° < solar elevation < -12° and before noon
- `evening_astronomical_twilight`: -18° < solar elevation < -12° and after noon
- `morning_twilight`: -18° < solar elevation < 0° and before noon
- `evening_twilight`: -18° < solar elevation < 0° and after noon
- `night`: solar elevation <-18°
- `day`: solar elevation >0° (alias for `up`)

## Extension 3
**Add additional triggers:**
- `start_morning_blue_hour`: sun rising above -6°  solar elevation
- `end_morning_blue_hour`: sun rising above -4°  solar elevation
- `start_evening_blue_hour`: sun setting below -4°  solar elevation
- `end_evening_blue_hour`: sun setting below -6°  solar elevation
- `start_morning_golden_hour`: sun rising above -4°  solar elevation
- `end_morning_golden_hour`: sun rising above 6°  solar elevation
- `start_evening_golden_hour`: sun setting below 6°  solar elevation
- `end_evening_golden_hour`: sun setting below -4°  solar elevation

**Add additional named durations:**
- `morning_blue_hour`: -6° < solar elevation < -4° and before noon
- `evening_blue_hour`: -6° < solar elevation < -4° and after noon
- `morning_golden_hour`: -4° < solar elevation < 6° and before noon
- `evening_golden_hour`: -4° < solar elevation < 6° and after noon

**Some nice illustrations from https://en.wikipedia.org/wiki/Twilight:**
![image](https://user-images.githubusercontent.com/14281572/47681783-b3219780-dbca-11e8-926a-e015e0b332ab.png)

![image](https://user-images.githubusercontent.com/14281572/47681690-6ccc3880-dbca-11e8-8a64-057424dc10d1.png)

![image](https://user-images.githubusercontent.com/14281572/47681774-ae5ce380-dbca-11e8-8462-4d381fe87dd3.png)

**Comment by emontnemery** [comment]
> I'd say we probably want to consider from: conditions, such as from: civil_dusk that covers when the sun is 6 degrees or below. Otherwise folks will need to stack a bunch of conditions.

OK, but then it should perhaps be mandatory to also specify the end of the range:
```
from: civil_dusk
until: sunrise
```

> Where we have a condition though, there should IMO be a matching trigger. That'd mean we'd want a trigger for golden_hour, twilight (even if that's an alias for sunset), and obviously the other twilights. 

The triggers for morning `civil_twilight` would be `civil_dawn` and `sunrise`, are you saying add also a `civil_twilight` trigger as an alias for `civil_dawn`?

**Comment by emontnemery** [comment]
By the way, instead of:
- `during: twilight`: -18° < solar elevation < 0° (??)

Maybe it should be:
- `during: morning_twilight`: -18° < solar elevation < 0°, sun is rising
- `during: evening_twilight`: -18° < solar elevation < 0°, sun is setting

**Comment by DubhAd** [comment]
> from: civil_dusk until: sunrise

I like this, it makes it *very* clear what's going on.



> are you saying add also a `civil_twilight` trigger as an alias for `civil_dawn`

I'm saying that if we trigger on "twilight" we should have a condition for "twilight"

**Comment by balloob** [comment]
Which dusk/dawn/twilight are we most likely to use? Civil? Then we should remove the `civil_` suffix

**Comment by emontnemery** [comment]
> Which dusk/dawn/twilight are we most likely to use? Civil?

Yes, I think that makes sense. According to Wikipedia:

- Civil dusk/dawn:
  > At civil dawn and at civil dusk sunlight clearly defines the horizon while the brightest stars and planets can appear. 

- Nautical dusk/dawn:
  >At nautical dawn and nautical dusk, the human eye finds it difficult, if not impossible, to discern traces of illumination near the sunset or sunrise point of the horizon ("first light” after nautical dawn but before civil dawn and "nightfall" after civil dusk but before nautical dusk).

- Astronomical dusk/dawn:
  > In the evening, even when astronomical twilight has yet to end and in the morning when astronomical twilight has already begun, most casual observers would consider the entire sky fully dark.

> we should remove the civil_ prefix

Yes, or make alias, like so:
- `astronomical_dawn`: sun rising above -18° solar elevation
- `nautical_dawn`: sun rising above -12° solar elevation
- `civil_dawn`, `dawn`: sun rising above -6°  solar elevation
- `civil_dusk`, `dusk`: sun setting below -6°  solar elevation
- `nautical_dusk`: sun setting below -12° solar elevation
- `astronomical_dusk`: sun setting below -18° solar elevation

**Comment by armills** [comment]
We should not implement this proposal in its current form. Adding lots of options that are almost the same and with similar names is a big source of confusion for new users trying to set up automations, introduces tons of extra code we now have to maintain, and doesn't even provide any functionality users couldn't set up themselves today.

We should make deliberate choices about what to include here, and not include everything possible just because we can.

**Comment by armills** [comment]
I like @OttoWinter's proposal a lot. It allows us to keep the set of options simple, and most users can keep the default angle and will never need to worry about the additional flexibility we're exposing, but it's still there for those who need it. Anyone who's doing anything really complicated is just going to be using elevation angles directly anyway, since the odds are slim their use-case aligns directly with any presets we pick.

**Comment by emontnemery** [comment]
@ottowinter do you mean it should be possible to specify the angle of dusk/dawn as a configuration of the sun platform, not for each automation? For automation trigger, just add dusk/dawn and remove the other stuff (nautical, astronomical)?

**Comment by OttoWinter** [comment]
No, for each automation (or more specifically for each trigger). For example a `sun.dawn` trigger:

By default, it will trigger on 0°. But users can optionally specify an `angle` (?) option that overrides this default to trigger on 10° for example.

This way, the default config is as simple as possible, and the navy dusk/etc can all be done manually by specifying the appropriate angle.

**Comment by emontnemery** [comment]
> By default, it will trigger on 0°. But users can optionally specify an angle

Do you mean user should be able to specify an _offset_ from the default solar elevation triggering dawn / sunrise / sunset / dusk?

So maybe something like this:
``` yaml
automation:
  trigger:
    platform: sun
    event: dawn
    angular_offset: -6 # Will trigger when sun rises above -12°
```

``` yaml
automation:
  trigger:
    platform: sun
    event: sunrise
    angular_offset: 6 # Will trigger when sun rises above 6°
```

What about in a condition:
``` yaml
# Valid entire day, from dawn until dusk
condition:
  condition: sun
  from: 'dawn'
  until: 'dusk'
```

Soemthing like this maybe:
``` yaml
# Valid entire day, from dawn -2° until dusk -2°
condition:
  condition: sun
  from: 'dawn'
  from_angular_offset: -2 # True when sun has risen above -8°
  until: 'dusk'
  until_angular_offset: -2 # True when sun has set below -8°
```

**Comment by armills** [comment]
It should not be on a per-trigger basis. If users want to define an angle for a trigger specifically they can already just use the elevation attribute.

**Comment by armills** [comment]
👍 That looks pretty good, with the small tweak that the trigger can just use the event platform, we don't need to add a custom sun trigger for this. But otherwise I can get behind this approach.

**Comment by emontnemery** [comment]
> the [added dawn and dusk] trigger can just use the event platform

Yes, but there are already custom sun triggers for sunset and sunrise in order to allow specifying a time offset. Extending those to also support dawn and dusk is very little extra code and gives consistency.
``` yaml
automation:
  trigger:
    platform: sun
    # Possible values: sunset, sunrise
    event: sunset
    # Optional time offset. This example is 45 minutes.
    offset: '-00:45:00'
```

**Comment by OttoWinter** [comment]
Personally, I don't care that much if we add this option globally as @armills suggested, or do it per-trigger. I can live with both.

On the one hand, it there is only "one" sunset angle, so a global option would make sense semantically. However, *if* we're going to add a trigger for this, I don't see why we should limit ourselves to having this global when I'm sure people can have use-cases for per-trigger angles.

One such use-case: The window blinds in my living room should open back up when the sun is at a specific angle. But my lights should turn at another angle when it starts getting darker outside. Of course, both of these can be done using  templates. In fact, this entire proposal can be done using templates and that's exactly what I'm doing right now.

This proposal is about simplifying the configuration for a common use-case after all. Also, as @emontnemery suggested, if we already have the `offset` option in the trigger, it would make little sense to me if we wouldn't also have the angle option in the trigger config.

Again, I can live with both, but I think the per-trigger option is more generic while not sacrificing maintainability/understandability.

**Comment by armills** [comment]
If people want different angles per-trigger, they can already build triggers based on the sun elevation angle. If they've already decided they need a custom angle, it will be much simpler to just write the trigger around the angles rather than trying to come up with offsets. This is already possible and no additional code is required. We do not need to add a more complicated way to implement this.

**Comment by armills** [comment]
I think we need to circle back to the basics here. You opened up this issue with this background statement:

> The existing sun triggers (before/after sunrise/sunset) are not ideal for automations related to dimming of lights etc.

So if I understand the conversation so far, the goal here is not to add any functionality that isn't already possible, but you want to make it simpler to configure. Do I understand that correctly? If that's the case, let's start with small steps here. Let's pick the use-case you think is currently the most frustrating, and give us examples of what the trigger looks like in the old system, and what it will look like with your proposed changes, so we can better understand how this change will simplify configuration for users. This is required.

**Comment by balloob** [comment]
I like the idea of improving the docs instead of making architectural changes. I'll close this then

**Comment by OnFreund** [comment]
Sorry to revive this, but I'm not sure the two options have identical behavior. Let's look at the 0 degree case, and assume it happened, and 10 minutes later HA was restarted. I believe that in this case, a trigger based on elevation would fire again (the sun is still below 0 degrees), but a sun trigger would not fire again.
If this is indeed the behavior, then a case could be made to make the sun trigger more flexible.
