### ISSUE TITLE
Releases semver support

### ISSUE THREAD

**Issue by PaulAnnekov** [home-assistant/architecture#99]
Currently beta releases are looking like `0.82.0b0`, so they go into a PATCH part of the version string. I suggest to move this beta suffix into extension part, like this: `0.82.0-beta.0` or `0.82.0-b0` or `0.82.0-b.0`.

Applying semver schema to version string will bring some benefits. E.g. I use https://gitpunch.com/ service to get email notifications with release notes on new releases. It can filter releases by major/minor/patch/all, according to semver rules. With current HA version strings it can't differentiate between `0.82.0b0` and `0.82.0`, in both cases it's a PATCH release. Of course beta release notifications are useless for me, because I don't install them and they contain no release notes, that I like to read.

**Comment by balloob** [comment]
We follow Python versioning which is what Pip supports
